### ISSUE TITLE
Window will not stay on top when clicked from taskbar

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10100]
> **9124596** created the issue

So this has been around for at least 6 months but I finally got annoyed enough to open a ticket.

If you have a bunch of other windows open (browser, program editor, etc) and cyduck is behind those windows, you must minimize all your windows to get to cyberduck. Then you can click on cyberduck and it will stay on top until you minimize it again. I usually don't see this bug with the cyberduck transfer windows. It's usually the actual ftp window when I am connected to a Server. 

I can't express how annoying this is since I have so many windows open at a time.

**Comment by Cassie205** [comment]
Tested with v8.5.10.39662:
The Cyberduck window can be moved to the top layer using the taskbar or by clicking on any visible part of the window if it's only partly behind a different one.
