### ISSUE TITLE
Interoperability with gpg-agent (YubiKey)

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10454]
> **03b55c6** created the issue

Cyberduck is great, but I cannot use it anymore, since I switched to using a YubiKey to store my SSH private key.

The reason is simply **the requirement to select a private key file** when opening a connection.
_Note_: I can connect using SSH on the command-line, using ForkLift, SourceTree, … just fine. They all just use the identity agent I have configured…

Since this blocks me from using Cyberduck, I consider this a defect…

**Comment by dkocher** [comment]
Reopening to add support for `IdentityAgent` in OpenSSH configuration.
