### ISSUE TITLE
Support versioning in NextCloud & ownCloud

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10560]
> **@dkocher** created the issue

> https://docs.nextcloud.com/server/14/developer_manual/client_apis/WebDAV/versions.html

**Comment by dkocher** [comment]
As for other protocols in #13342.

**Comment by dkocher** [comment]
Documentation for ownCloud

* [File Versions](https://doc.owncloud.com/server/next/developer_manual/webdav_api/files_versions.html)
