### ISSUE TITLE
Option to delete file on disk after completed upload

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10745]
> **a48a1f6** created the issue

hello,

i'm using cyberduck 7.0 in windows 10 x64(1903). I started using cyberduck as ftp/sftp client, but currently my main use is to backup large files to google drive (usually one-way). 

However for such purpose i find hard time doing a combined operation that 1) uploads to google drive 2) then once completed deletes original files. I guess one can just call this a move operation, but a ticket that i have taken a look at: #913 suggests move can be done via edit->cut and edit->paste , yet i couldnt get it to work for files/folders from file://localhost to mygoogle@account@www.googleapis.com. For me the paste button gets grayed out once i get to google drive location. My guess is that the 'move' suggestion may have been meant for move/copy inside same kind of location--inside same localhost maybe.

I couldnt find any mention for this kind of operation from wiki either:
https://trac.cyberduck.io/wiki/help/en/howto/transfer
https://trac.cyberduck.io/wiki/help/en/howto/upload

Unless its prohibited for some reason I can't imagine, I think supporting this operation would be really helpful. At least for me it saves simple but huge step of going back to pc to check if the upload is finished and delete local files. 

Please kindly consider this feature for future versions.

Thanks.

J

**Comment by tatze96** [comment]
duplicates #10461
