### ISSUE TITLE
High CPU usage (with the caveats)

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10773]
> **5ba5968** created the issue

```
i7-3820QM, 32Gb RAM
Windows 10 Pro 10.0.18362 Build 18362
Cyberduck v7.0.2
MountainDuck v3.1.0
```

Physical interface is dedicated to the Hyper-V switch, host OS is using virtual one via the "Internet sharing" feature:
```
> Get-NetAdapter | select Name, MediaType, MtuSize

Name                       MediaType     MtuSize
----                       ---------     -------
Physical                   802.3            1500
vEthernet (ext_switch)     802.3            1500
vEthernet (Default Switch) 802.3            1500
```

----

I have noticed that both MountainDuck and CyberDuck use excessive CPU while using protocols that impose small penalty on the traffic.<br />
For example, unencrypted FTP transfer over the 1Gbps localnet:

![external image](https://i.imgur.com/Qqb2hdq.png)

The same using MountainDuck:

![external image](https://i.imgur.com/kVvNxL1.png)

and its threads, sorted by CPU usage:

![external image](https://i.imgur.com/22S6IlX.png)

Lastly, I have noticed that MountainDuck seems to cache content at system drive.<br />Can this be disabled so application writes directly to a destination? 

![external image](https://i.imgur.com/ZnXwPwb.png)

![external image](https://i.imgur.com/ylVjorg.png)

While I am not quite familiar with NT-based systems, I am more than happy to help with the debugging of this issue.

**Comment by dkocher** [comment]
We have been unable to reproduce the problem in recent versions. Please open a [discussion](https://forum.cyberduck.io/) if you still require assistance.

**Comment by navossoc** [comment]
I am able to reproduce it.
Just limit the file transfer speed and you will see the CPU usage skyrocket!
