### ISSUE TITLE
Switching between directories in Cryptomator vault takes very long

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#10858]
> **ce6d08c** created the issue

Hi,

there's an issue with Cyberduck (and most likely Mountain Duck) that slows down switching directories when browsing through an online-only Cryptomator vault in OneDrive.

This is significantly faster when using the original Cryptomator app on iOS so it must me something with Cyberduck.

**Comment by dkocher** [comment]
I cannot seem to see any problem browsing a vault with many directories using [8.5.6](https://trac.cyberduck.io/milestone/8.5.6). I have tested with a new vault using vault format 7.
