### ISSUE TITLE
Interoperability with GPG4WIN Pageant

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11085]
> **fbb8ba7** created the issue

I am using SSH authentication through an Authentication GPG subkey stored in a smartcard. I have set up GPG4WIN with PuTTY interoperability to accomplish that. The authentication through the GPG smartcard works fine with PuTTY itself. However, CyberDuck seems to ignore it and asks me for a password or a certificate file.

Please note that I am also using a properly configured WSL-SSH-Pageant to get this kind of authentication work both in WSL (Ubuntu 20.04) and through Windows' built-in SSH client. I know that my configuration is correct since literally everything -- even a command line PHP script -- can use the key in the SmartCard. The only anomaly is CyberDuck.

**Comment by dkocher** [comment]
It would be great if you can test with version 8.5.3 and let us know if still reproducible.
