### ISSUE TITLE
Interoperabiltiy with KeePassXC

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11187]
> **89e265d** created the issue

I'm using the KeePassXC (KPXC) (https://keepassxc.org/) as my password manager. KPXC has an option to integrate into the systems SSH agent. So when I ssh into a remote machine ssh retrieves the password for the key from KPXC.

Cyber-/Mountain Duck (CD/MD) is not able to establish a connection, as long as the SSH integration in KPXC is enabled. I, either have to disable this functionality in KPXC or quit KPXC, when I want to connect to a remote machine with CD/MD.

**Comment by dkocher** [comment]
Possibly a duplicate for #13935.
