### ISSUE TITLE
PEM authentication takes 6 second for each upload and each download

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11337]
> **6e686a7** created the issue

It takes 6 long for each upload to Amazon EC2 using SFTP and a PEM file. The process hangs at the authentication step for 6 seconds. Each time I upload I have to wait that long.
This process was MUCH faster (nearly instantaneous) on a computer that I am no longer using (the computer was sold a while ago.) Is this is a settings issue? If so, what settings need to be updated to allow for faster authentication? 6 seconds is too long for each action I take. Please help.

![external image](https://matthaas.com/slow-pem.png)

**Comment by dkocher** [comment]
Recent versions have seen changes in the logic of authentication attempts for SSH connections. Reopen if still an issue.
