### ISSUE TITLE
Duplicate file default timestamp name contains unsupported cheracters

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11569]
> **930f9a0** created the issue

The feature to quickly duplicate files and get a copy with a timestap in the name is useful, but a problem that remains (there are other older requests about this) is that the default name causes problems in some cases. 

What I'd like to report in particular is the problem that it contains a colon (:) in the timestamp part. 
Like "index (2021-01-30, 15:16).php" and in macOS file systems colon is not an allowed character. Please change it to a period instead, or have an option to not include the time and just have the date.

**Comment by dkocher** [comment]
In #14437.
