### ISSUE TITLE
Transfer incomplete only when attempting to upload certain folders

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11707]
> **49f6092** created the issue

Just started using the program and its been working great so far except for this one odd issue. I'm uploading my stuff to Wasabi using their US Central server. Most of my folders will upload just fine, but there's this one folder that refuses to upload. It goes through processing all of the folders and files in question but then immediately hits Transfer Incomplete and nothing is uploaded. Inside the backup, it has my user profile so a desktop folder, documents, etc. 

I went through and cleared out all the files it said CD could not find (even though they were available on the hard drive and readable), but still can't get it to upload.
___
Attachments

* [`cyberduck.log`](https://github-cyberduck-assets.s3.amazonaws.com/11707/cyberduck.log) (9951.7 KiB)

**Comment by zemien** [comment]
I am seeing the same behaviour, but with Google Cloud Storage (Coldline):

- Can download files
- Can upload files to other folders in the same bucket

I have attached my log and have replaced any token strings with REMOVED. Null and empty tokens are left as-is.

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/7655194/cyberduck.log)

**Comment by dkocher** [comment]
Can you confirm this is resolved in version 8.3 now available.

**Comment by zemien** [comment]
Yes I can confirm it is fixed for me. Thank you!
