### ISSUE TITLE
SFTP (SSH) connection: timeout (works with SCP or ForkLift App)

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11717]
> **63f0e00** created the issue

Hello,

I have problems connecting to a server on port 22 with SFTP (SSH): timeout.
If I use the exact same connection parameter with terminal SCP or ForkLift app,
connection is working well.
I use VPN.

I already increased the timeout without effect:
"defaults write ch.sudo.cyberduck connection.timeout 30000"

How can I provide any log file?
Thank you!

**Comment by dkocher** [comment]
We have been unable to reproduce the problem in recent versions. Please open a [discussion](https://forum.cyberduck.io/) if you still require assistance.
