### ISSUE TITLE
Initial connection fails on host requiring multiple authentication

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11723]
> **36bba6c** created the issue

One of my server hosts requires BOTH ssh key AND password authentication. If I specify both in the connection dialog/Bookmark, the initial attempt fails and I am given a dialog box telling me that all methods are exhausted. This has my password in the password field but no ssh key chosen. If I select the required key from the drop-down and click the "Connect" button then the connection succeeds.

Obviously I can work around this, and I recognise that this is an edge case with the level of security being requested by the server, but it is an annoyance and there is clearly something different about the connection *after* the initial failure.

**Comment by dkocher** [comment]
Recent versions have seen changes in the logic of authentication attempts for SSH connections. Reopen if still an issue.
