### ISSUE TITLE
Failure to read attributes; does not have storage.buckets.get access

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11720]
> **f6c57ac** created the issue

Hi, 

I've raised this in the past and this still has not been fixed. 
The below error only started to happen at 7.9.1, Ive been using version 7.8.5 which works fine, but this morning it updated to 7.10.0 and I get the below message when I'm connected to my bucket

```
Does not have storage.buckets.get access to the Google Cloud Storage bucket. Domain: global. Reason: forbidden. Forbidden. Please contact your web hosting service provider for assistance.

```

Thanks, 
Renato
___
Attachments

* [`Screenshot 2021-07-02 at 11.20.57.png`](https://github-cyberduck-assets.s3.amazonaws.com/11720/Screenshot%202021-07-02%20at%2011.20.57.png) (91.0 KiB)

**Comment by dkocher** [comment]
Please reopen if reproducible with the current release.
