### ISSUE TITLE
Windows Notepad opened for .txt even when not default for either Windows or Cyberduck

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11770]
> **73b204b** created the issue

My default editor on Windows for .txt files is Notepad++. The icon displayed on cyberduck itself for the files is indeed Notepad++; but the edit button has Windows Notepad and double-clicking opens WN and not N++.

I have also set the default text editor on Cyberduck to Notepadd++ but that doesn't change anything unless I force it to open all files with it. That's suboptimal because .png and others are normally opened by a correct editor on double-click.

I only use SSH connections.
___
Attachments

* [`Screenshot 2021-08-20 123610.png`](https://github-cyberduck-assets.s3.amazonaws.com/11770/Screenshot%202021-08-20%20123610.png) (27.4 KiB)

**Comment by dkocher** [comment]
Please reopen if still an issue with version 8.4.0 or later.
