### ISSUE TITLE
Doesn't recognize subfolders in vault

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11881]
> **d93bd07** created the issue

Hi there,
I have a cryptomator vault folder named "google" on google drive.
and there were some subfolders like "/google/cctv/YYYYMM/"

first of all, duck cli CAN list and upload files in /google/cctv/ folder.
however, duck cli does not recognize /google/cctv/YYYYMM/ folders even with --vault option.

actually, it WORKED months ago. (I don't remember exact date but I'm sure that it worked)
after I updated duck cli recently, it doesn't work anymore.

Full screenshot is attached.
username and authenticating strings are masked.
vault_err.png

ps.
If I access same folder with mountain duck, the absolute path does not match with duck CLI.
I don't know why but it might be one of reason for this bug?
vault_err2.png

Thank you.

___
Attachments

* [`vault_err.png`](https://github-cyberduck-assets.s3.amazonaws.com/11881/vault_err.png) (64.7 KiB)
* [`vault_err2.png`](https://github-cyberduck-assets.s3.amazonaws.com/11881/vault_err2.png) (25.9 KiB)

**Comment by dkocher** [comment]
Reproduce with  *S3*
```
duck --vault /test-eu-west-2-cyberduck/vault --upload s3:/test-eu-west-2-cyberduck/vault/11881/ /Users/dkocher/Desktop/cryptomator_256.png --verbose
```
