### ISSUE TITLE
SFTP bookmark connection fails, same config works in FileZilla

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11893]
> **c681183** created the issue

I've been connecting to my SFTP server with no issues until yesterday, the connection is failing with one or the other of the following:

```
Server closed connection during identification exchange. The connection attempt was rejected. The server may be down, or your network may not be properly configured.
```

```
Connection reset. The connection attempt was rejected. The server may be down, or your network may not be properly configured.
```

cyberduck.log prints the following every time the connection fails, but I have no idea what the issue is:

```
ch.cyberduck.core.ProtocolFactory - List of registered protocols in ProtocolFactory{registered=[sftp], bundle=Local{path='/Applications/Cyberduck.app/Contents/Resources/Profiles'}, profiles=Local{path='/Users/semo/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Profiles'}} is empty
```

Clicking Network Diagnostics does not do anything. I'm fairly confident the issue is not caused by the server since the same configuration works fine with FileZilla. Any help is much appreciated.

___
Attachments

* [`cyberduck.log`](https://github-cyberduck-assets.s3.amazonaws.com/11893/cyberduck.log) (195.9 KiB)

**Comment by dkocher** [comment]
Recent versions have seen changes in the logic of authentication attempts for SSH connections. Reopen if still an issue.
