### ISSUE TITLE
Crashes upon clicking on "Profiles"

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11897]
> **845ca6f** created the issue

The crash report is attached. I clicked on "Profiles" followed by the immediate crash.
___
Attachments

* [`Cyberduck8-crash-report.crash`](https://github-cyberduck-assets.s3.amazonaws.com/11897/Cyberduck8-crash-report.crash) (117.1 KiB)
* [`Cyberduck_2021-11-11-144358_trac-11897.crash`](https://github-cyberduck-assets.s3.amazonaws.com/11897/Cyberduck_2021-11-11-144358_trac-11897.crash) (101.0 KiB)
* [`Cyberduck_2021-11-11-144439_trac-11897.crash`](https://github-cyberduck-assets.s3.amazonaws.com/11897/Cyberduck_2021-11-11-144439_trac-11897.crash) (99.0 KiB)

**Comment by dkocher** [comment]
```
OS Version:      Mac OS X 10.9.5 (13F34)
```
