### ISSUE TITLE
FTPS download error "502 Command REST not implemented"

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11902]
> **36ca0fe** created the issue

When I try to download files from FTPS I can download only 5-8mb. If file is bigger than 5-8mb I receive an error:

502 Command REST not implemented. Please contact your web hosting service provider for assistance.

This is reproducible in Mac and Windows. 

I can download without any problem via WinSCP.
I have an information from my colleagues. They don't have any issues with file downloading on the same ftps server with Cyberduck version 5.1.0 (20872) Mac.
___
Attachments

* [`Screenshot 2021-11-09 at 11.43.22.png`](https://github-cyberduck-assets.s3.amazonaws.com/11902/Screenshot%202021-11-09%20at%2011.43.22.png) (121.4 KiB)
* [`Screenshot 2021-11-09 at 11.45.18.png`](https://github-cyberduck-assets.s3.amazonaws.com/11902/Screenshot%202021-11-09%20at%2011.45.18.png) (69.7 KiB)
* [`Screenshot 2021-11-09 at 11.46.43.png`](https://github-cyberduck-assets.s3.amazonaws.com/11902/Screenshot%202021-11-09%20at%2011.46.43.png) (40.7 KiB)
* [`Screenshot 2021-11-09 at 12.09.22.png`](https://github-cyberduck-assets.s3.amazonaws.com/11902/Screenshot%202021-11-09%20at%2012.09.22.png) (51.3 KiB)
* [`cyberduck_v8.0.0.log`](https://github-cyberduck-assets.s3.amazonaws.com/11902/cyberduck_v8.0.0.log) (126.9 KiB)
* [`cyberduck_v8.0.2.log`](https://github-cyberduck-assets.s3.amazonaws.com/11902/cyberduck_v8.0.2.log) (698.6 KiB)

**Comment by dkocher** [comment]
Try a _Compatibility Mode_ connection profile from https://docs.cyberduck.io/protocols/ftp/#listing-directory-fails-or-shows-no-content
