### ISSUE TITLE
Transfers Window difficult to read

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11900]
> **b0ece23** created the issue

I just updated to version 8.0.0 and I can no longer read the details on the Transfers screen. The window doesn't resize to accommodate my font size choice, which is larger than average because I have a fairly large monitor and fairly poor eyesight. thus I am unable to see the transfer rate, % completed and whatever else is on that same line.
___
Attachments

* [`Screenshot 2021-11-08 125345.gif`](https://github-cyberduck-assets.s3.amazonaws.com/11900/Screenshot%202021-11-08%20125345.gif) (35.1 KiB)

**Comment by syneryder** [comment]
I have the same issue with the transfers windows layout on Windows 10, on Cyberduck 8.1.0. It's not possible to see the transfer rate details underneath the main progress bar for the transfers.

I'm running on a HiDPI (Retina-esque) laptop with text scale set to 175%, smaller than the default 200% scaling to allow more icons & windows on screen. My external 27" Dell monitor (non-HiDPI) is also set to 175% text scale.

<img width="373" alt="Cyberduck Transfers Window layout bug HiDPI" src="https://user-images.githubusercontent.com/236744/144554465-3d931667-b16a-40bf-9e7b-ffa4433b8aa9.png">

I'm running into similar scaling bugs throughout the Cyberduck 8.1.0 interface, but I can lodge different bug reports for those. I am glad to see Cyberduck finally with a crisp HiDPI interface though!

**Comment by dkocher** [comment]
Duplicate for #8961.

**Comment by dkocher** [comment]
Duplicate for #12742.
