### ISSUE TITLE
access to text version of the 'local' path to duck-mounted remote directory?

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11918]
> **c085b27** created the issue

Using CLI tools on macOS to read remote files on a mountainduck mounted (sftp) remote directory (linux) one would like to pass the local path.  

So is there simple and efficient ways to copy a text version of the path both within the macOS GUI and at the 'terminal' CLI?

Thanks for any help.

Cheers,
Chuck

**Comment by dkocher** [comment]
Just drag the folder from Finder.app to your Terminal.app window.
