### ISSUE TITLE
Files not updating after editing

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11915]
> **29dd807** created the issue

Everytime i edit a file and try to close and save it, it doesn't update in the platform at all and it also doesn't update server side

**Comment by adalseno** [comment]
I had a similar issue with dropbox (not tested on other services), but it seems to be related with Sublime Text and only if I choose to keep the files locally (in such a case I had to move the file out of the folder and then in again to have it synced).  Please note that the file, in my case, is actually updated (I can see the new content locally) but the date is not changed.  If I use textedit I get a message that the server does not support versioning when I save and it seems to work fine (wiht TexMate no message, but it's working).
On others folders (not kept locally) the edit seems to work fine but the issue with the date and Sublime text is still present (I cannot see the updated date even using ls on the terminal) even though the files is updated on Dropbox with the right date (weird). On local files (on my HD, not synced) Sublime Text has no issues with dates.
Mac Os X 10.15.7 Mountain Duck 4.8.2 (18835)

**Comment by dkocher** [comment]
Duplicate for #11729.
