### ISSUE TITLE
8.1.0 fails to connect to FTP-SSL (Explicit Auth TLS) server, 8.0.2 and Filezilla work

### ISSUE THREAD

**Issue by vlasbaard** [iterate-ch/cyberduck#12589]
<img width="309" alt="Screenshot 2021-11-30 at 09 46 55" src="https://user-images.githubusercontent.com/20222659/144014707-3fde8100-607b-4d61-b1a3-064d72c6a10a.png">

Clicking Network Diagnostics doesn't seem to do anything.

This is in 8.1.0 - the same configuration works in 8.0.2, and in Filezilla.

Regular FTP (with otherwise identical configuration) works in 8.1.0 as well.

Not sure if there is a log somewhere where I can paste things from?

OS: macOS 12.0.1 (Intel)
(Private) FTP server: PureFTPd with a Let's Encrypt certificate

**Comment by jSeird** [comment]
Same here.
Also since 8.1.0 (36410) connection to FTPS fails with the following error randomly:
<img width="303" alt="Bildschirmfoto 2021-11-30 um 12 13 22" src="https://user-images.githubusercontent.com/58764791/144037410-784ff202-2b92-4a7b-a7b1-1a67042c0537.png">

OS is also macOS 12.0.1 (Intel)
The host is proFTPd with a valid SSL. Connection via other FTP Clients or older Version of Cyberduck are working just fine.

**Comment by AliveDevil** [comment]
Debug Log output can be retrieved by opening up Cyberduck preferences, switching to the Connection-tab and enabling Debug Logging.
The log file can be revealed by clicking on Show, after reproducing the error.
If the file is not revealed, it can be found at:
* `~/Library/Logs/Cyberduck` on macOS
* `%AppData%\Cyberduck` on Windows

**Comment by AliveDevil** [comment]
There hasn't been any change [since 8.0.1](https://github.com/iterate-ch/cyberduck/commits/master/ftp).

The only difference is that macOS Java runtime has been updated from JDK 15 to JDK 17.

**Comment by vlasbaard** [comment]
Ok, got a relevant log. (Note I replaced user-/hostnames).

As far as my knowledge on the subject allows, the line where the trouble starts is after `MLSD`:

```
2021-11-30 20:30:44,829 [Thread-39] WARN  ch.cyberduck.core.ftp.FTPClient - Unable to make field private final sun.security.util.Cache sun.security.ssl.SSLSessionContextImpl.sessionHostPortCache accessible: module java.base does not "opens sun.security.ssl" to unnamed module @21507a04
```

[cyberduck-issue-12589-5-1-log.txt](https://github.com/iterate-ch/cyberduck/files/7628362/cyberduck-issue-12589-5-1-log.txt)
