### ISSUE TITLE
Infected file in jna-min-5.10.0.jar

### ISSUE THREAD

**Issue by theovanessen** [iterate-ch/cyberduck#12588]
<img width="667" alt="Screenshot 2021-11-30 at 09 40 38" src="https://user-images.githubusercontent.com/10104059/144013667-d72900b2-3e00-4079-9b64-f9fe420f906e.png">

Na het installeren van Cyberduck versie 8.1.0 (36410) gaf Bitdefender deze melding.

**Comment by dkocher** [comment]
This is a false alert. Please configure your Antivirus software accordingly.
