### ISSUE TITLE
Unlock/Lock Cryptomator Vault Option Grayed Out

### ISSUE THREAD

**Issue by fishcharlie** [iterate-ch/cyberduck#12598]
**Describe the bug**

The unlock vault option (and lock vault option) for Cryptomator is grayed out even tho it's clear the directory is a Cryptomator vault.

**To Reproduce**
1. Open a Cryptomator Vault directory
2. Click `Cancel` when prompted for vault password
3. Right click in directory and notice how `Unlock Vault` is grayed out

This also applies if you enter the vault password to unlock and try to `Lock Vault`. The option remains grayed out even tho you should be able to lock the vault.

**Expected behavior**

It to allow you to unlock (and lock) the vault after the fact.

**Screenshots**

<img width="1031" alt="Screen Shot 2021-12-01 at 10 00 35 PM" src="https://user-images.githubusercontent.com/860375/144361030-59d459ff-3f07-4182-a55c-eb1199f937e2.png">
<img width="971" alt="Screen Shot 2021-12-01 at 10 00 43 PM" src="https://user-images.githubusercontent.com/860375/144361034-c7281231-3c84-4b39-91c8-2243d75b22ec.png">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS 12.1 Beta (21C5045a)
 - Version Cyberduck Version 8.1.0 (36410)

**Additional context**

- I feel like this is a regression. I forget what version it was last working on, but even just a few months or so ago I'm pretty sure this was working properly.
- This happens across multiple types of connections and servers (S3, WebDAV, etc).

**Comment by dkocher** [comment]
I cannot seem to reproduce this on 12.0.1.

**Comment by dkocher** [comment]
The logic in 2b960eec has not changed.

**Comment by fishcharlie** [comment]
@dkocher I wonder if it's due to something Apple Silicon related??

I'm not a Java developer and I don't have any environment setup for Java dev, but maybe there is a way to temporarily add more logs to a custom build that I can run? Or maybe I can try to setup a Java environment and try to set some breakpoints?

I'd be happy to help debug further, but might need a bit of direction or guidance since I'm not a Java dev.

**Comment by dkocher** [comment]
The option is disabled if you have set _Preferences → Cryptomator → Auto detect and open vault in browser_

**Comment by dkocher** [comment]
Relates to #10798.

**Comment by fishcharlie** [comment]
@dkocher Got it. It might be useful to not have it linked to that setting. That way you can manually lock vaults after unlocking them. Currently it is impossible to do that as far as I'm aware.

This did work tho, so I thank you for your assistance.
