### ISSUE TITLE
Fail to connect to remote SFTP server on port 2224

### ISSUE THREAD

**Issue by l33tllama** [iterate-ch/cyberduck#12597]
**Describe the bug**
I am trying to connect to my own home server on port 2224 with Mountain Duck. I am the hosting provider, and I am able to connect via SSH, but not Mountain Duck.

**To Reproduce**
Add custom SFTP server with port 2224

**Expected behavior**
Should mount drive in Finder

**Screenshots**
If applicable, add 
![Screen Shot 2021-12-02 at 11 48 12 am](https://user-images.githubusercontent.com/3285878/144337511-5086c333-4131-4ef0-9499-f2e6357aac58.png)
![Screen Shot 2021-12-02 at 11 48 24 am](https://user-images.githubusercontent.com/3285878/144337517-74e53823-58aa-4a1e-b071-f566f11ace2b.png)
screenshots to help explain your problem.

**Desktop (please complete the following information):**
macOS Monterey 12.0.1
Apple MacBook Air 2020 M1

**Log Files**
I tried to upload a log file, but with extensions .log and .txt Github gives the error "is not included in the list". Here is a OneDrive link https://1drv.ms/u/s!AqiEsydnHmSd0cIWeCMSrdjTaWLp8A?e=1q3hja

**Additional context**
Just wondering if non-standard ports are an issue at the moment, for macOS?

**Comment by AliveDevil** [comment]
Just tried this with a fresh VM, changed the SSH port to 2224, just like in your sample.
Client was macOS 12 on a M1 mac Mini.

Do you know whether the connection to your server is stable? Mountain Duck applies a 10 second timeout to every request, which might be not enough for your server to answer. Can you try to increase the timeout in the preferences connection tab to something above 10 seconds?

**Comment by l33tllama** [comment]
Thanks for checking that on your machine. I don't know why, but it's working now on my machine.
I've used Mountain Duck on Windows, and I think I'll be getting it for my new Mac.
Cheers.

**Comment by AliveDevil** [comment]
Thanks for confirming, I'll close here. If it happens again feel free to comment.

Happy mounting :) 🦆
