### ISSUE TITLE
Cannot Read container configuration - S3

### ISSUE THREAD

**Issue by misilot** [iterate-ch/cyberduck#12596]
For S3 connections to bucket.s3.amazonaws.com navigating to any path results in a Cannot read container configuration.

Similar to #11896

**To Reproduce**
Add S3 bucket via bucket.s3.amazonaws.com, try and navigate to any directory, create a directory, etc...

**Expected behavior**

**Screenshots**
Config
<img width="518" alt="Config" src="https://user-images.githubusercontent.com/1446856/144258017-23e0d6f8-f25f-4153-bafa-7c1e74c357d1.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1446856/144261995-dc8381f5-20b1-4745-8c2f-45051b70878c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.0.1
 - Cyberduck version: 8.1.0

**Log Files**
https://gist.github.com/misilot/27ee4d034683fb4b6adc8dedcf9512a4

**Additional context**
This works on version 7.8.5

**Comment by dkocher** [comment]
Does it work if you set the default path to the bucket name `/ksul-…` and leave the default hostname?

**Comment by misilot** [comment]
Yes, it does work. Is the the method of connecting via bucketname.s3.amazonaws.com no longer supported?

**Comment by dkocher** [comment]
It is still supposed to work but was recently refactored in 61fb805081498a5d7775efa6ffdc33a47c9b1711.

**Comment by misilot** [comment]
Thanks @dkocher!

**Comment by dkocher** [comment]
We have not yet determined why the virtual host style syntax to connect to a single bucket does not work in this case.

**Comment by rmzelle** [comment]
I think I'm running into the same issue. For my historical S3 bookmarks, I used `Server: <bucketname>.s3.amazonaws.com` with `Path: /<bucketname>`. With recent versions of Cyberduck like 8.1.2 these now all give a "Listing directory <bucketname> failed." error when I try to connect. Changing my bookmarks to `Server: s3.amazonaws.com` solved the error.

**Comment by dkocher** [comment]
> I think I'm running into the same issue. For my historical S3 bookmarks, I used `Server: <bucketname>.s3.amazonaws.com` with `Path: /<bucketname>`. With recent versions of Cyberduck like 8.1.2 these now all give a `Listing directory <bucketname> failed.` error when I try to connect. Changing my bookmarks to `Server: s3.amazonaws.com` solved the error.

Use either the virtual host notation or specify the bucket in the _Path_ but not both.

**Comment by misilot** [comment]
@dkocher has this been fixed?

**Comment by ylangisc** [comment]
In 8.2.0 as referenced.

**Comment by misilot** [comment]
Ok, I saw it as a milestone, but didn't see it mentioned in the release notes when I went to upgrade. I hadn't gotten a chance to test on our end. 

Thanks!

**Comment by quiver** [comment]
I'm still having this error in 8.2.1.

This bug can be easily reproducible if a bucket name contains '.'.

**Comment by dkocher** [comment]
> I'm still having this error in 8.2.1.
> 
> This bug can be easily reproducible if a bucket name contains '.'.

Make sure to follow [Bucket naming rules
](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)

**Comment by quiver** [comment]
>  Make sure to follow Bucket naming rules

I know that AWS wants to [deprecate legacy naming rules](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/), but the problem is that there's little you can do to change long-working existing rules.
