### ISSUE TITLE
Connection stopped working

### ISSUE THREAD

**Issue by Robert37160** [iterate-ch/cyberduck#12607]
With latest revision a previous working connection fails.
![16_12_51_12_02](https://user-images.githubusercontent.com/26124032/144511928-85fd8894-cf04-4226-bbf3-023fbcc3e976.png)
![16_12_08_12_02](https://user-images.githubusercontent.com/26124032/144511931-1381062c-9440-4ee9-b49a-aad529fbe18f.png)
  Can I get a previous version to use till issue is resolved?

**Comment by AliveDevil** [comment]
You can get all previus versions from the [changelog](https://cyberduck.io/changelog/).
