### ISSUE TITLE
Problem with graphics

### ISSUE THREAD

**Issue by makis10** [iterate-ch/cyberduck#12603]
in latest version in windows 11 i dont see the menu with connection modes clearly
![image](https://user-images.githubusercontent.com/11842911/144433135-fe118476-8d50-4107-96dd-cfb0d8276c88.png)

**Comment by AliveDevil** [comment]
By any chance, can you disable screen scaling for Cyberduck and see if it improves the situtation (albeit being smaller or blurry).

Scaling interferes with the UI framework we are using, provided by Microsoft, which is somewhere between deprecated and life support. We do plan to improve this here, but that requires a lot of upfront work.

i.e.: Upgrading to .NET 6 with WinUI requires .NET 6 compatibility of IKVM, which we just recently got to support TLSv1.3 (#12600 ).
