### ISSUE TITLE
Hangs on "Quit" forcing a force quit

### ISSUE THREAD

**Issue by jameshale** [iterate-ch/cyberduck#12608]
I often just open Cyberduck to upload a file and once it is uploaded I quit.
Unfortunately instead of quitting I get the spinning beachball and have to do a force quit.
This doesn't happen if I just open Cyberduck, access a site, and then quit.
I am on MacOS 11.6.2 intel.

**Comment by tatze96** [comment]
I can't reproduce the described behavior within the latest Snapshot Build (8.2.4 (36898)). Do you still see the described behavior on your side?

If so: Does this issue occur in combination with a specific protocol and/or file type (file size, file extension)?

**Comment by tatze96** [comment]
I can reproduce the behavior if I have a notification window of Cyberduck open in the background at the time I quit Cyberduck.

**Comment by dkocher** [comment]
Possible duplicate of #11734.

**Comment by dkocher** [comment]
We have been unable to reproduce the problem in recent versions. Please open a [discussion](https://forum.cyberduck.io/) if you still require assistance.
