### ISSUE TITLE
Can't resize filename column 

### ISSUE THREAD

**Issue by Ethenski** [iterate-ch/cyberduck#12619]
Size, modified, kind, and the other detail panes can be resized, however the filename column cannot. 

<img width="183" alt="1" src="https://user-images.githubusercontent.com/31077919/144724416-01ca8d21-d6e4-488a-98fc-9aec0863cc79.png">

<img width="1250" alt="2" src="https://user-images.githubusercontent.com/31077919/144724418-7cf6b33a-ebc7-4b3b-a024-fe229faaf759.png">

**Comment by dkocher** [comment]
Duplicate for #11599.
