### ISSUE TITLE
S3 Cut and Pasting a folder with files causes File Not Found error after successful move

### ISSUE THREAD

**Issue by psk788** [iterate-ch/cyberduck#12617]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
When using cmd-x -> cmd-p to move a "folder" and it's content from one folder in S3 to another, it is successfully making the change but then throwing a file not found error. If there is a known AWS setting that causes this, please advise.

**To Reproduce**
1. Go to a folder that contains subfiles/folders
2. Click cmd-x/ctrl-x or click cut from the menu
3. Navigate to another directory
4. Paste the folder
5. See Error. Based on the status bar below the window, it appears to rename everything then attempt to delete the original (now renamed files)

**Expected behavior**
The file should move successfully without error.

**Screenshots**
Screen Video

https://user-images.githubusercontent.com/9382834/144618060-89157719-1de2-4688-9518-c10b34ed765e.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Big Sur 11.2.3

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

[cyberduck copy 2.log](https://github.com/iterate-ch/cyberduck/files/7650532/cyberduck.copy.2.log)

**Additional context**
Only happens on cut and not on copy.  S3 itself doesn't have folder renames so I couldn't reproduce in their console

**Comment by tatze96** [comment]
I can reproduce the described behavior.

**Comment by dkocher** [comment]
Actually old regression from 1ea4d66b67e0690314956092177b21163015eea4.
