### ISSUE TITLE
Unable to write file to Google Cloud Storage (Exception in logs)

### ISSUE THREAD

**Issue by JeremyR34** [iterate-ch/cyberduck#12623]
**Describe the bug** 
Unable to upload new file to Google Cloud Storage. Error is "Transfer incomplete".
There are some exceptions in the log.

 **To Reproduce** 
Upload a new file.

 **Expected behavior**
The file should be uploaded without error.

**Screenshots** 
![image](https://user-images.githubusercontent.com/17052863/144819183-5927b5e4-07e7-4276-9ff1-a689a51ad66e.png)

**Desktop:**
* OS: MacOS
* Version High Sierra 10.13.6
* Cyberduck 8.1.0

**Log Files** 
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/7659510/cyberduck.log)

**Additional context**
My Google Cloud connection was working great some time ago (can't tell if a particular update messed up the thing).
Navigating works fine, and overwriting an existing file works.

**Comment by dkocher** [comment]
Regression from #f19ff777.
