### ISSUE TITLE
Cannot read container configuration and other problems

### ISSUE THREAD

**Issue by AdamMacaluso** [iterate-ch/cyberduck#12631]
Started with "Cannot change permissions of " folder (and items in the folder).
So I updated CyberDuck to I think 8.1.2
Now I can't see anything in my server because it's all "Cannot read container configuration"
At some point I had "Listing directory failed" but I don't know why.

**Comment by AdamMacaluso** [comment]
I have been informed that there is an AWS issue on the east coast. So that may be my problem.

**Comment by dkocher** [comment]
Possibly duplicates #12596.

**Comment by AdamMacaluso** [comment]
This issue was fixed by Uninstalling 8.1.2 and reinstalling 7.10.2
I don't know if it's a combination of the AWS problems today, and/or the updated version, but at least my issue is fixed.
Thank you DKocher for your link.
