### ISSUE TITLE
Upload and download files - System crash

### ISSUE THREAD

**Issue by enricomz** [iterate-ch/cyberduck#12641]
Hi,
I have a problem with uploading and dowloading of files in cyberduck. I have done this activity several times in the last 4 years (with my corporate account "SIAE", server s3.amazonaws.com, path /siae-sophia-codifica) but one month ago this problem occured and now it still happens. At the moment I have no problem with autenthication, viewing and creation of folders but if I try to upload or download a file, cyberduck has a system crash. The same thing happens when I click on 'Trasferimenti'.
I have tried to uninstall e reinstall software, also newest version, but with no result. Could you help me? Thank you, kind regards.
Enrico M. Zulli

**Comment by AliveDevil** [comment]
Can you check whether clearing up `%AppData%\Cyberduck\Transfers` (macOS: `~/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/Transfers`) resolves your issue?

Please help us gather some debug information:
* Operating System (and version)
* Available physical memory
* Version of Cyberduck

**Comment by enricomz** [comment]
Hi,
doing this operation I have resolved the problem. 
Thank you for your support, kind regards.
Enrico M. Zulli
