### ISSUE TITLE
Issues with connections

### ISSUE THREAD

**Issue by Mandim1125** [iterate-ch/cyberduck#12643]
It worked fine for a day and now I can't connect to anything. It loads and then automatically disconnects me. Very frustrating considering  I paid for the full version and I need it for school...

**Comment by cultoftheplatypus** [comment]
I'm having the same issue with my FTP connection on 4.9.2.  It will continually ask for my login information, without ever allowing the download of a file.

**Comment by dkocher** [comment]
Duplicate for #12632. Please update to the latest [snapshot](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds) build.
