### ISSUE TITLE
Cyberduck doesn't work

### ISSUE THREAD

**Issue by Eelowizee** [iterate-ch/cyberduck#12640]
I can't log-in in cyberduck

**Comment by fishcharlie** [comment]
@Eelowizee You should probably provide a **lot** more detail here if you want any chance of your issue remaining open. Remember also, if the server you are trying to connect to rejects your credentials, there is nothing Cyberduck can do about that.

**Comment by AxoyTO** [comment]
Cyberduck doesn't launch since the last update(around 52mb)

**Comment by fishcharlie** [comment]
@AxoyTO Try updating to 8.1.2 (https://cyberduck.io/changelog/). Also: https://twitter.com/cyberduckapp/status/1468149579665313792?s=20.

**Comment by dkocher** [comment]
Duplicate for #12628.
