### ISSUE TITLE
No Secret Access Key 

### ISSUE THREAD

**Issue by gymcandids** [iterate-ch/cyberduck#12645]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by gymcandids** [comment]
Access key ID: Z207E0XB2CID3HZ00OP3

I believe my cyberduck server was hacked. Some of the videos are not working on my site. I need the secret access key for the ID above in order to log into cyberduck.

**Comment by dkocher** [comment]
Please delete the access keys you have published here.
