### ISSUE TITLE
Unable to log in to Cyberduck

### ISSUE THREAD

**Issue by Donald-P** [iterate-ch/cyberduck#12653]
I have been using Cyberduck for a number of years. I purchased a copy in 2019. It has been working fine for the most part. Suddenly when I went to log on yesterday to update some info on my website, it suddenly quit. It keeps asking me for my username and password but will not let me in. I get this error message "Login failed. 530 Login incorrect. Please contact your web hosting service provider for assistance" I have been in contact with my service provider and as far as I can tell nothing has changed so I am at a loss as to where the problem lies. Up until this point I have had no problems logging in, as soon as the blue address would come up, I could click on it and it would take me directly to my website so I could initiate actions. Can you help with this problem.  The username I have on file for cyberduck is donald@donaldpettit.com.My email address is don@monkey-house.ca if you could send any helpful information there or just fix the problem if you can.

**Comment by dkocher** [comment]
As the error message indicates clearly this is an error with your credentials. This is neither a bug report nor a feature request. Discuss issues you are having in the [Cyberduck Google Group](http://groups.google.com/group/cyberduck).
