### ISSUE TITLE
Toolbar Download button not downloading to default location (Windows)

### ISSUE THREAD

**Issue by alexandremarcil** [iterate-ch/cyberduck#12662]
Cannot assign a default download folder.  The UI seems incorrect...   there is no checkbox before the Download Folder option.
![cyberduck download](https://user-images.githubusercontent.com/33580707/146279966-a4a15a70-ec6b-408a-807d-c129e068df79.png)

**Comment by AliveDevil** [comment]
Why do you want to have a checkbox infront of the download folder?

You have "File->Download" (Alt-Down Arrow Key) and "File->Download To" (Alt-Shift-Down Arrow Key).
The first option downloads to the download folder, and the second to a location you choose.

**Comment by alexandremarcil** [comment]
Sorry for the confusion.  I added the download button in the menu bar and this button is equivalent to 'download to...'  (whereas on mac, this button downloads to the default folder).  It would be nice to have this on pc as well.

**Comment by AliveDevil** [comment]
Acknowledged, thanks for clarifying.
We'd need to check which behavior should be the default here, inconsistent behavior shouldn't occur.

I skimmed through the tickets and didn't find anything related to that.
