### ISSUE TITLE
timeout when trying to expand the window size

### ISSUE THREAD

**Issue by sankethsiddapur** [iterate-ch/cyberduck#12666]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.
Hi All , 
I am using Cyberduck 7.2.5(32097) version in windows.
When I try to upload larger files it is getting timed out with error : timeout when trying to expand the window size
Please help me out here

**Comment by dkocher** [comment]
Please check the logs of the SSH server with your system administrator.
