### ISSUE TITLE
Unable to open Cyberduck on macOS from the 1st click

### ISSUE THREAD

**Issue by izada** [iterate-ch/cyberduck#12683]
**Describe the bug**
Unable to open Cyberduck on macOS in 1 click

**To Reproduce**
1. Click on Cyberduck from Dock (when the app was closed)
2. Click on Cyberduck from Dock again (app already showing the active dot)
3. The app opens 

**Expected behavior**
Cyberduck app should open from first click

**Desktop**
 - OS: macOS
 - Version: 12.1

**Comment by dkocher** [comment]
I cannot reproduce this problem.

**Comment by izada** [comment]
> I cannot reproduce this problem.

Please make sure to add the app to Dock on macOS 12.1 Intel.
I attached the log also for you [cyberduck.log](https://github.com/iterate-ch/cyberduck/files/7755374/cyberduck.log)

**Comment by izada** [comment]
I'll close the issue... As the app is opening directly after double clicking the icon.
