### ISSUE TITLE
Cyberduck app is not opening

### ISSUE THREAD

**Issue by matoatti** [iterate-ch/cyberduck#12697]
Hi, I have purchased the Cyberduck app via AppStore last year (amato@t-online.hu). I wanted to use the app today and there was a question mark on the App logo. It did not open. I have tried to download via App Store and it downloads (the one with the new logo) but the app is not starting. Can you please help? Thanks, Attila

**Comment by tatze96** [comment]
Does the starting behavior still occur? If so, send us the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) if there are any. 
Also, could you let me know if there are any error messages?
