### ISSUE TITLE
Folder architecture for connections

### ISSUE THREAD

**Issue by menardavid** [iterate-ch/cyberduck#12692]
**Describe the solution you'd like**
In order to better organize the connection, it would be great to be able to create folders where you can D&D your connections

**Additional context**
Example Sequel Ace for DB connection

![image](https://user-images.githubusercontent.com/76953912/146949172-69b6f643-1e0b-44ff-a06a-c612cde8c750.png)

**Comment by dkocher** [comment]
Duplicate for #12233.
