### ISSUE TITLE
Cyberduck 8.x.x annoying small icons on windows high resolution screen

### ISSUE THREAD

**Issue by gigaplanet** [iterate-ch/cyberduck#12719]
I use dell laptod, XPS 15 with 15 inch high résolution screen 3840 x 2160 pixels.
Previous versions of cyberduck provided a nice display and icon size.
The new cyberduck version 8.x.X display very very small Icons.
I Enclose the picture of what I see.
Regards
Emmanuel.
![image](https://user-images.githubusercontent.com/55499772/147571495-b10cca12-1523-4886-9e6b-ab6454f2e526.png)

**Comment by dkocher** [comment]
Duplicate for #8961.
