### ISSUE TITLE
Unable to login to root directory of an s3 Account.

### ISSUE THREAD

**Issue by irshadelevision** [iterate-ch/cyberduck#12715]
Earlier we where able to access to root directory of a s3 account and call see all the buckets inside that root. Now I am unable to login to root directory. it is showing that the access secrete is wrong. but if you put bucket name in front of the server url it will work.

After login into a bucket we can go back to the root directory. but not directly to root directory.

My access id have full access to all the buckets and functionalities inside a bucket.

This was working fine before Christmas.

**Comment by dkocher** [comment]
Possibly duplicates #12723.

**Comment by irshadelevision** [comment]
its working if we added a bucket name after the url.
