### ISSUE TITLE
"Interoperability failure"  = more of a nuisance than a bug

### ISSUE THREAD

**Issue by anthonyrollett** [iterate-ch/cyberduck#12734]
I have used Cyberduck for many years and really appreciate it.  Lately when accessing Macs that are running the ESET security software, I almost always have to click on a popup that says "Interoperability failure" with the code 1231976033.  Click on it enough times and it eventually executes the file transfer.  Sometimes renewing the window (apple-R) seems to restore the connection.  As indicated, it's not exactly a bug but I thought I should report it.
thanks, Tony Rollett
<img width="518" alt="Screen Shot 2021-12-30 at 11 33 27 AM" src="https://user-images.githubusercontent.com/9311141/147775012-8c91490f-4639-4b0f-a0c8-1037d30f0563.png">

**Comment by dkocher** [comment]
Please reopen if you can reproduce when ESET is uninstalled.
