### ISSUE TITLE
"Bug" at double click upload

### ISSUE THREAD

**Issue by Exacaro** [iterate-ch/cyberduck#12739]
Actually is not a bug, it's misuse by the user. 
Sometimes i double click upload by mistake, the program opens 2 "open" windows and then shut down
![image](https://user-images.githubusercontent.com/97089282/148031706-b47a3cb5-e712-4ab0-853b-8e5b44dbff8c.png)
![image](https://user-images.githubusercontent.com/97089282/148032342-ea275ac9-f80a-413a-812b-9d3dcc6e2b1a.png)

I sent the report at the same time i send this

Best regards and thanks!

**Comment by AliveDevil** [comment]
Thanks for reporting, I can confirm crashes here.
