### ISSUE TITLE
SFTP Fail with Cyberduck 8.2.0

### ISSUE THREAD

**Issue by drjdg** [iterate-ch/cyberduck#12737]
After upgraded to CD 8.2.0 I ceased to be able to log onto my university's SFTP server. Even though I entered the correct password and the SSH Private Key was valid, I kept getting this error:

"Exhausted available authentication methods. Please contact your web hosting service provider for assistance."

I've solved the problem by downgrading to CD 8.1.0 (which works perfectly) ... but wanted to pass on the info.

**Comment by marcusfritze** [comment]
in my case my sftp connection is on port 21, but cyberduck changes the sftp connection back to port 22, even when I edited the port

**Comment by ylangisc** [comment]
Duplicate for #12733.
