### ISSUE TITLE
[macOS] Cyberduck drops connection after a while

### ISSUE THREAD

**Issue by Max87ZA** [iterate-ch/cyberduck#12731]
Hello,
on macos version of app(Version 8.2.0 (36680), macos 11.6.1 (20G224)) app keeps disconnecting after a while of inactivity. Common use case is, that I upload a file to ftp, wait fo some time(5-30mins) and want to upload another file/same file(replace) - I need to tap on refresh button manually to reconnect to server or try to upload a file, CB throws error, so it reconnects(try again button) and I have to upload athat file again.
is it possible to send keep-alive command every few seconds/minutes to make connection alive until I manually disconnect/close the app?
Thanks

**Comment by dkocher** [comment]
Please post the error message and the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output).

**Comment by dkocher** [comment]
Duplicate for #9075.
