### ISSUE TITLE
Cannot upload file to WebDAV if "Save Password" is disabled

### ISSUE THREAD

**Issue by mmfire118** [iterate-ch/cyberduck#12732]
If you connect to a WebDAV with "Save Password" not checked, you can browse the files on the server, but you cannot upload anything.

The only error message to show up says unauthorized (401) on the server side.

**Comment by dkocher** [comment]
This should only be reproducible if you have set _Preferences → Transfers → Use browser connection_.

**Comment by tatze96** [comment]
I can't reproduce the described behavior with disabled keychain usage and *Use browser connection* as transfer mode.

- Does this behavior persist within the latest version of Cyberduck?
- Which transfer mode is set within *Preferences → Transfers*?
- Which operating system is in use?
