### ISSUE TITLE
Some UI elements cut-off

### ISSUE THREAD

**Issue by babuskaruska** [iterate-ch/cyberduck#12742]
**Describe the bug**
Download speeds are cut-off, resolution 2560x1600 aspect ratio 16:10

**To Reproduce**
Use the same resolution and aspect ratio

**Expected behavior**
Some parts of the UI are cut

**Screenshots**
https://i.ibb.co/zhqP1Md/Screenshot-2022-01-04-230917.png

**Desktop (please complete the following information):**
Latest Windows 10 Build

**Comment by AliveDevil** [comment]
Seems like Windows 11 doesn't care, that Cyberduck isn't declaring dpi awareness, and just assumes it is.
I'm forcing Windows to just scale things up, even if the UI becomes blurry now.
