### ISSUE TITLE
Latest iMac version not connecting to some of my ec2 instances

### ISSUE THREAD

**Issue by yraghtims** [iterate-ch/cyberduck#12749]
Could not connect to some of my ec2 instances today using Cyberduck 8.2.

Downgraded to Cyberduck 8.1 and I was able to connect as usual.

I have 3 eco instances.  Two did not connect and one did.

The message I got when it did not connect was Login failed.  Exhausted available authentication methods.  Please contact your web hosting service provider for assistance.

**Comment by dkocher** [comment]
Duplicate for #12733.
