### ISSUE TITLE
Bookmarks synchronization using iCloud

### ISSUE THREAD

**Issue by ferben** [iterate-ch/cyberduck#12740]
**Is your feature request related to a problem? Please describe.**
Is difficult sync bookmarks between two or more computers (desktop and notebook)

**Describe the solution you'd like**
Bookmark synchronization using iCloud (as Safari do with web bookmarks).

**Describe alternatives you've considered**
Manual sync, but easy bookmark export/import feature missing 👎 

**Multiplatform notes**
I don't know if bookmark synchronization could be available on Windows may be using OneDrive it is possible.

**Comment by AliveDevil** [comment]
Unfortunately there is no cross-platform way of syncing bookmarks. There is Cyberduck standalone for Windows and macOS, and Cyberduck on the App Store and Microsoft Store. So using platform-dependent services is no option, as you might wwant to have them synced between Windows and macOS - iCloud and OneDrive sync are out.

Though there is an option, which won't work on the App Store version, which involves creating a symlink from the bookmarks-directory onto a cloud service, which can then be consumed on multiple machines.

Is this[^1] a viable workaround for you?

[^1]: [docs.cyberduck.io/Sharing Bookmarks between Different Computers](https://docs.cyberduck.io/cyberduck/bookmarks/#sharing-bookmarks-between-different-computers)

**Comment by ferben** [comment]
I need share bookmarks between iMac and MacBook, so not between Win<→Mac. So your workaround is good when I use iCloud folder.

I know iCloud bookmarks is feature for mac-users only but it would be really useful (at least for me :).

**Comment by ferben** [comment]
Duplicate for #7076
