### ISSUE TITLE
v8.2.1 S3 - "cannot read bucket location"

### ISSUE THREAD

**Issue by pulberg** [iterate-ch/cyberduck#12746]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
After upgrading cyberduck to v8.2.1 I am no longer able to connect to S3 bookmarks.

From the error popup, it looks like cyberduck is prepending the url with the bucket name and trying to resolve that - 

`mybucket-name.my.s3url.com` 

In my bookmarks the url is - `https://my.s3url.com:9021/mybucket-name`

Here is an excerpt from the debug logs (edited to remove org info)- 

`
2022-01-05 10:46:49,919 [Thread-41] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure BackgroundException{class=class ch.cyberduck.core.exception.ResolveFailedException, file=null, message='Cannot read bucket location.', detail='mybucket-name.my.s3url.com.', cause='java.net.UnknownHostException: mybucket-name.my.s3url.com'} running background task
`

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.1

**Comment by dkocher** [comment]
Make sure the URI with the bucket name included is not resolvable over DNS to allow us to automatically switch to path-style requests or explicitly use the connection profile _S3 (Deprecated path style requests)_ available in _Preferences → Profiles_.

**Comment by pulberg** [comment]
I think you missed the part where I said this behavior happened after I upgraded, this was all working fine in v8.2.0.  I will run the checks you suggested, but i will also revert to v8.2.0 to confirm the behavior, this should not be closed yet.

**Comment by pulberg** [comment]
I tested as you suggested, and my URI including the bucket name is *not* resolvable.  So it would appear that the "automatic" switching to path-style in cyberduck is not working.  Did something significant change from 8.2.0 to 8.2.1 regarding this ability?

**Comment by pulberg** [comment]
@dkocher I tested the s3 functionality using my existing s3 bookmarks - 

v8.0.0 - works
v8.0.2 - works
v8.1.0 - works
v8.1.1 - works
v8.2.0 - *not* working
v8.2.1 - *not* working

It appears that something changed in v8.2.x such that cyberduck no longer automatically switches to path-style requests.

**Comment by dkocher** [comment]
Most probably a regression of 7f69ba1e.
