### ISSUE TITLE
CyberDuck App Crashes During Transfer

### ISSUE THREAD

**Issue by 41SweetWorld** [iterate-ch/cyberduck#12760]
Hello,

While using the latest version 8.2 of CyberDuck, the app crashes (closes after not responding) while I upload or download image files to a company internal server while on the network via VPN.  I have tried uninstalling/reinstalling and roll back to older versions as far back as 7.10.0.  This started on 1/3/2022 after using the updated app for a few days prior.  My local machine was taking a company pushed Windows [update ](https://support.microsoft.com/en-us/topic/december-14-2021-kb5008206-os-build-18363-1977-e54dfc3e-7d16-4d88-a4a3-59efbf0633f1)in the background at the same time as the first crash, not sure if that caused the issue. 

I am using Windows 10 Enterprise and have a paid version of the app.  Looking for a solution. 

Thanks,
Chrysti

**Comment by AliveDevil** [comment]
Hi Chrysti,
can you attach the log files and crash reports per our support[^1] documentation, screenshots of error messages, and following file:
Please open up Event Viewer, expand Windows Logs, then select Application.
Start Cyberduck and let it crash during transfer.
Return to Event Viewer, a hint "New Events are available" should appear at the top, click the underlined part, select the two top most errors, where the first line states `Application: Cyberduck.exe`.
Click "Save selected as …" on the right side in the actions-panel, and attach that file.

[^1]: [docs.cyberduck.io/support](https://docs.cyberduck.io/cyberduck/support/)

**Comment by 41SweetWorld** [comment]
Hi dkocher

I have the requested documentation ready, but think I need to check with my company's privacy and security policy since I believe these contain company information.  Is there a way to share securely? 

Thanks,
Chrysti

**Comment by dkocher** [comment]
Please write to support@cyberducck.io.
