### ISSUE TITLE
Cyberduck - file copy to pCloud space

### ISSUE THREAD

**Issue by H-o-a-g-i-e** [iterate-ch/cyberduck#12761]
when trying to backup files to an encrypted vault folder on pcloud I keep getting the error as attached.

When copying folders and files to the not encrypted space I do not receive any errors. It works but with about half of the speed as when I copy files to my STRATO cloud.

When I use the pCloud drive and the cryptomator app I do not have any issues creating folders or copying files to the vault.

I was wondering if there is an issue within Cyberduck. I also wonder because the upload speed to the not encrypted part is about half of what the upload speed to my STRATO webspace is and when using pcloud drive and cryptomator app then the upload speed is quite a bit faster than when using Cyberduck.

Your help is greatly appreciated as I became to love using Cyberduck in the past years for it being easy to use and having to use cryptomator and pdrive for the uploads is definitely more inconvenient.

[Screen Shot 2022-01-06 at 21.53.44.pdf](https://github.com/iterate-ch/cyberduck/files/7824750/Screen.Shot.2022-01-06.at.21.53.44.pdf)
[Screen Shot 2022-01-06 at 21.54.21.pdf](https://github.com/iterate-ch/cyberduck/files/7824752/Screen.Shot.2022-01-06.at.21.54.21.pdf)

**Comment by dkocher** [comment]
If this cannot be reproduced with a different provider using WebDAV this is most possibly an issue with pCloud.
