### ISSUE TITLE
Google Drive Upload Fails

### ISSUE THREAD

**Issue by mvjunkie** [iterate-ch/cyberduck#12763]
Can you check whether uploading at day-time (not at 2 in the morning) makes any difference at all?

Run a constant ping-test against the DNS-server of comcast (`ping 68.87.85.102`, or on Windows: `ping -t 68.87.85.102`) and check for possible packet-loss between 2am and 4am. Hitting Ctrl+C at the end will bring up a statistic of packages sent, mean round trip time and packages lost.
To do that: Open up `cmd.exe`, type in `ping -t 68.87.85.102`, hit return and let it run a day or so, hit Ctrl+C to get the summary.

If it worked before, did the Xfinity Gateway upgrade its software automatically (I know my router from Telekom Germany does)? Eventually you can get some hints from the [my device info portal](http://mydeviceinfo.xfinity.com/) or the [equipment update page](https://customer.xfinity.com/devices/equipment-update) provided by comcast.

Another option would be to check whether an older version of Cyberduck works fine, can you remember which version worked and downgrade to that using the installer on the [changelog page](https://cyberduck.io/changelog)?

Ruling out possibilities here:
* Comcast alters connections (though they shouldn't anymore, since 2008), and resets TCP connections
* The Xfinity router did an upgrade, and is now having issues keeping up with uploads, or has some feature enabled that interferes with long running TCP connections
* Comcast does an IP refresh in the night, interrupting the connection
* A Cyberduck updated introduced the issue

While writing I got a total of 2.2 GiB transferred to Google Drive, without interruption.

Update:
Looking at [Every day at the same time, my internet dies for 1 minute. How do I investigate?](https://news.ycombinator.com/item?id=25802714), can you check your public facing IP before a disconnect, and after a disconnect?

_Originally posted by @AliveDevil in https://github.com/iterate-ch/cyberduck/issues/12744#issuecomment-1005813743_

-------------

Sorry to bring this up again, I made some hardware changes, and am trying to figure out if its hardware related or my xfinity router, i changed the dns on my main computer to googles but the xfinity router wont let me change it on their unit so xfinity capture and redirects to their dns anyway. Next is to bypass the xfinity router/settings and use personal modem. I cleared out the CD.log and attempted only 1 transfer, which failed as usual. Could you please have a look at the log and tell me what you see.

**Comment by mvjunkie** [comment]
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/7826815/cyberduck.log)

**Comment by AliveDevil** [comment]
For future reference: You can always just answer to closed tickets, them being closed doesn't mean we won't look at them ever again.

Transfer failed at around `23:56:01`, with an upload going roughly 15 Minutes (started `23:41:10`), with a constant speed of 3 MiByte/s. My test transfer I did the other day was 2 GiB and change, in something like four hours.

```
2022-01-06 23:56:01,759 [timer-1] TransferProgress{size=20037258707, transferred=2617540608, progress='2.4 GiB (2,617,540,608 bytes) of 18.7 GiB (13%, 2.9 MB/sec, 98 minutes remaining)', speed=2937.2780052628923}
2022-01-06 23:56:01,852 [nYE8t162-transfer-1] Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.ConnectionRefusedException, file=null, message='Connection failed', detail='Connection reset by peer: socket write error.', cause='java.net.SocketException: Connection reset by peer: socket write error'}
```

Though this time, different than the one you created initially, did have another error popping up:
After failing we do a Tcp reachability test, and this came up:
```
2022-01-06 23:56:01,852 [nYE8t162-transfer-1] Reachability test with url https://www.googleapis.com
2022-01-06 23:56:01,868 [nYE8t162-transfer-1] WebException thrown with status NameResolutionFailure
```
We check whether `www.googleapis.com` returns any IP, and your DNS server returns a failure immediately (within `0.01` seconds)

The first log you sent containd this entry:
```
2022-01-05 03:11:46,197 [rcVtK4gt-transfer-5] Reachability test with url https://www.googleapis.com
2022-01-05 03:11:46,280 [rcVtK4gt-transfer-5] WebException thrown with status ProtocolError
```
Meaning that it got atleast an IP and the server did in fact answer to a connection attempt.

So:

At 2021-01-05 03:11 your transfer dropped, but DNS worked fine, and a subsequent transfer started to transfer all-over again.  
Albeit with horrendously slow speeds of 80 KiByte/s, starting `03:11` up until `03:28` when it froze again after 17 Minutes.

Now your transfer dropped at `2021-01-06 23:56`, after 15 Minutes of transfer (starting `23:41`), and failing with a DNS Resolution failure (which would indicate total loss of network connectivity)
To me this looks like somewhere on the path to the Google Drive storage servers there is some device closing a TCP connection after 15 Minutes.

Do you have any other modem available, which is not the Xb7?
