### ISSUE TITLE
Cyberduck doesn't launch 

### ISSUE THREAD

**Issue by kohei-kambe** [iterate-ch/cyberduck#12762]
Hi, Cybertduck soft ware doesn't launch if I click the icon.
It happened from yesterday and I re-installed today, but still doesn't work.
How can I solve this?

https://user-images.githubusercontent.com/96526201/148482314-c470743a-218a-4d94-a4c4-d4c1c2917674.mp4

**Comment by AliveDevil** [comment]
You captured your Chrome-window only.

Regardless, please open up Event Viewer, expand Windows Logs, then select Application.
Start Cyberduck, and return to Event Viewer, a hint "New Events are available" should appear at the top, click the underlined part, select the two top most errors, where the first line states `Application: Cyberduck.exe`.
Click "Save selected as …" on the right side in the actions-panel, and attach that file.
