### ISSUE TITLE
can able to build but app can't be launch

### ISSUE THREAD

**Issue by bharatn161** [iterate-ch/cyberduck#12771]
**Describe the bug**
I have download the code and try to run it. I have add all the prerequisites as per doc.

After install all the prerequisites I got several errors like **jni.h** file not found. so I drag and drop ini.h file directly from the jdk. I also get error for sparkle framework, which is not found.

so I remove sparkle framework script and all the required references  from the code. 

as the results I can able to build successfully but app can't be launch.

If I click on app from dock directly I can see the same scenario every time.

**Error**

Error loading runtime bundle.
The application failed to launch with a unrecoverable exception.

**Comment by dkocher** [comment]
Make sure to follow [Building](https://github.com/iterate-ch/cyberduck#building).

**Comment by bharatn161** [comment]
Getting error while running mvn verify -DskipTests -DskipSign.

**Comment by dkocher** [comment]
You will need to post the build errors if you want us to assist.
