### ISSUE TITLE
duck-CLI isn't printing full transcript in debug verbose output

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#12796]
**Describe the bug**
> `duck --debug --verbose --list …`

Doesn't include rolling log output.

**To Reproduce**
```
duck --debug --verbose  --username … --list …
Opening FTP-SSL connection to …
The certificate for this server is invalid. You might be connecting to a server that is pretending to be … which could put your confidential information at risk. Would you like to connect to the server anyway? (y/n): y
Listing directory /…
> STAT /
```

This is reset with set/reset cursor position in TerminalLoggingAppender, perhaps.

**Expected behavior**
Include _all_ FTP debug output.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.2.1

**Comment by dkocher** [comment]
Possible regression from #12718.

**Comment by JoshuaBehrens** [comment]
Insane reaction time 💙
