### ISSUE TITLE
Support for Telegram APIs

### ISSUE THREAD

**Issue by ntman1** [iterate-ch/cyberduck#12790]
Provide CyberDuck/Mountain Duck with connectivity to Telegram's Storage APIs - to mirror features found with TeleDrive - https://teledriveapp.com

Similar code is here as well - https://github.com/khrj/teledrive

TechRadar - A simple trick lets you turn Telegram into a free unlimited cloud storage service  - https://www.techradar.com/news/a-simple-trick-lets-you-turn-telegram-into-a-free-unlimited-cloud-storage-service

TeleDrive: To Make Telegram Become A Free, Limitless Cloud Storage Service, Use This Simple Approach - https://www.cloudorian.com/news/teledrive-to-make-telegram-become-a-free-limitless-cloud-storage-service-use-this-simple-approach/#.YeElXf7MKMo

**Comment by dkocher** [comment]
We will not implement an API that is not advertised and supported by the owner for this usage.
