### ISSUE TITLE
FTP site can't navigate beyond root directory

### ISSUE THREAD

**Issue by jdmarlow0** [iterate-ch/cyberduck#12806]
Hi created an FTP server for myself at home and I'm able to use it just fine on FileZilla PRO. But when I login using Cyberduck or Mountain Duck the main directly loads fine, and then when I double click it to open that directory it just shows the same directory again and again and again.  Like you can't navigate past it.  I'm only seeing this in those two apps so I'm assuming it's a bug with loading FTP servers on Cyber and Mountain Duck.  Would love to get it fixed because I prefer your apps over FileZilla!

The FTP server is a plain FTP by the way.  Not SFTP or using SSL or anything fancy.

**Comment by dkocher** [comment]
Try the FTP (Compatibility Mode) connection profile available in Preferences → Profiles.

**Comment by jdmarlow0** [comment]
This works thank you!!

JD Marlow
646-456-3844
www.jdmarlow.com

**Comment by AliveDevil** [comment]
Would you mind sharing which FTP server you are connecting to?

**Comment by jdmarlow0** [comment]
I was able to get this fixed by using compatibility mode!

JD Marlow
646-456-3844
www.jdmarlow.com

**Comment by AliveDevil** [comment]
I got that, though for documentation purposes (on https://docs.cyberduck.io) it would be useful to know which server software creates these issues.

**Comment by jdmarlow0** [comment]
Ah ok.  It’s an FTP server I created using my router.  It’s the Asus RT-AX89X.  Asus uses (NAME).asuscomm.com address for FTPs such as these.

JD Marlow
646-456-3844
www.jdmarlow.com

**Comment by AliveDevil** [comment]
Thanks for confirming.

Relates: https://github.com/iterate-ch/docs/issues/140
