### ISSUE TITLE
Problem with cyberduck on PC

### ISSUE THREAD

**Issue by juper55** [iterate-ch/cyberduck#12800]
Hi,
I can't open a picture file with any other application than paint. 
How is this possible? Can you fix the problem?
Thank you!

**Comment by AliveDevil** [comment]
Thanks bringing this to our attention.
Unfortunately we currently don't have any way of invoking Microsoft Store apps directly, so you are out of luck here.
We'll get this implemented in a future update though.

I created a feature request which includes more information: https://github.com/iterate-ch/cyberduck/issues/12802
