### ISSUE TITLE
Support Store apps for Edit-capabilities

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#12802]
`SHAssocEnumHandlers`[^1] can be used to directly invoke a handler, and doesn't rely on registry hacks to find OpenWithList and `shell/open/command` to be defined.

[^1]: https://stackoverflow.com/questions/48400038/use-shassocenumhandlers-in-c-sharp

**Comment by dkocher** [comment]
Might also help to resolve #11770.

**Comment by AliveDevil** [comment]
> Might also help to resolve #11770.

This would make all implementations for finding applications currently in place in Cyberduck Windows obsolete, as I'd like to just create one implementation which is capable of opening a file with any application, through Windows Shell.

**Comment by AliveDevil** [comment]
Discussion here:
This _will_ result in preferences having to remove the Default-editor setting, as everything will be handled by underlying User preference in Windows.

New behavior for editing files:
* If none is returned in SHAssocEnumHandlers use SHOpenWithDialog[^1].
* If any is returned, use `isRecommended` property to determine first and Edit toolbar option default application
  * Any other is appended by IEnumAssocHandler[^2] order
  * Append last item "Open With …" which uses SHOpenWithDialog.

Unsure how to fit this into EditorFactory and ApplicationFinder though.
Need to extend Application class to allow for passing IAssocHandler down the line and invoked with a file path.
Cannot use ApplicationLauncher or ApplicationFinder as provided by AbstractEditor as that relies on Process.Start, which is unavailable here.

[^1]: https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenwithdialog
[^2]: https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ienumassochandlers

**Comment by AliveDevil** [comment]
CLI behavior changes to following:
`--edit` downloads file and opens default/recommended handler. If non available use SHOpenWithDialog
Adding `--edit=with` or `--edit-with` always uses SHOpenWithDialog. Opinions here?

**Comment by AliveDevil** [comment]
Currently blocked by microsoft/CsWin32#521.

**Comment by AliveDevil** [comment]
Behavior will need to address for situations where there is no editor defined for a file type, i.e.:
For .mp4 there is no editor defined on my system, but an application which is set as default viewer.
Do we want to allow fast editing (Ctrl+K) for files with no registered application capable of editing a file type?

`SHAssocEnumHandlers` will return any application with registered _open_ verb of file type, not necessarily only handlers which are _edit_ capable. There is no way of determining whether `IAssocHandler` can edit a particular file.

**Comment by AliveDevil** [comment]
https://github.com/iterate-ch/cyberduck/blob/4128201562d77b7beb7ee36700bcecfcf4a390f6/core/src/main/csharp/ch/cyberduck/core/local/ShellApplicationFinder.cs#L69

We can `ShellExecuteEx` any arbitrary ProgId with specified verbs. This will need PInvoke, as ProcessStartInfo/Process.Start cannot use `lpClass`-field for starting a ProgId.
Need to differentiate in ApplicationLauncher between ProgIdApplication and ShellApplication, which use different ways of invoking (`IAssocHandler.Invoke`/`ShellExecuteEx`).

**Comment by AliveDevil** [comment]
It's something.

https://user-images.githubusercontent.com/734738/161038833-a292969a-3e32-4b36-adcc-0488e81f8177.mp4
