### ISSUE TITLE
Windows 11, registration key apparently does not work

### ISSUE THREAD

**Issue by dwightlindsey** [iterate-ch/cyberduck#12813]
I just installed Cyberduck on my Windows 11 Microsoft Surfacebook.  I double clicked on the file but the "Get a registration key!" flag is still there, so I guess the registration key was not accepted.

**Comment by AliveDevil** [comment]
Did you get the confirmation message that the registration key has been applied successfully?
Did you then restart Cyberduck?

For further registration key troubleshooting can you send us a mail to support@cyberduck.io?
