### ISSUE TITLE
Backblaze connection doesn't work

### ISSUE THREAD

**Issue by efrancou** [iterate-ch/cyberduck#12823]
I think it's related to endpoint which is not allowed to be modified.

**Comment by dkocher** [comment]
You will need to provide more information. Refer to the [documentation](https://docs.cyberduck.io/protocols/b2/).

**Comment by efrancou** [comment]
This is so weird. I was unable to connect following the guide in your documentation (credentials error). Even I tried copying to notepad to avoid formatting. I tried about 20 times on Windows and Mac, finally when I was screen recording it worked (I was unable to Paste keys, just didn't worked Ctrl + V and manually entered)
