### ISSUE TITLE
Listing Directory / failed

### ISSUE THREAD

**Issue by Anandsoni14** [iterate-ch/cyberduck#12841]
Whenever I am trying to work from my Windows PC I am getting this issue. But it's working fine in my MacOS.
<img width="456" alt="Screenshot 2022-02-02 at 01 34 40" src="https://user-images.githubusercontent.com/9585873/152043003-c5865ca1-27e5-4cb5-a28a-313e9a3ca2b4.png">

**Comment by dkocher** [comment]
Check the date & time settings on your PC.

**Comment by Anandsoni14** [comment]
Checked, it's right -8 UTC.

**Comment by Anandsoni14** [comment]
But the issue is still there.
