### ISSUE TITLE
S3 Bug

### ISSUE THREAD

**Issue by duncanheather1** [iterate-ch/cyberduck#12849]
S3 Access Key ID is required every time I open Cyberduck  Despite ticking the Save Password box

Please could you fix it ASAP
Many Thanks

I am using Windows 11

**Comment by dkocher** [comment]
Make sure you have checked _Preferences → Connection → Use Keychain_.

**Comment by duncanheather1** [comment]
Hi David
Thank you for the quick response.   I confirm that I already had Use
Keychain ticked, but still keep losing the access key ID.

This has happened once before after an update. But not sure what you did to
fix.

Any help much appreciated
Duncan

**Comment by duncanheather1** [comment]
Dear David
Thank you.  The password issue has now been fixed in the latest update

Much appreciated




Duncan Heather

Principal

 

 <http://www.ocgd.org/> 

 

LET’S CONNECT!    <http://www.facebook.com/pages/Oxford-College-of-Garden-Design/181907238498584?sk=wall>  <https://twitter.com/#!/OCGDPrincipal>  ***@***.***?subject=OCGD%20Enquiry>  <http://www.gardendesigncourses.blogspot.com/>  <http://uk.linkedin.com/in/duncanheather>    <http://pinterest.com/gardenarchitect/> 

 

Oxford College of Garden Design

T: +44 (0)1491 628950

E:   ***@***.***> ***@***.***

W:  <http://www.ocgd.org/> www.ocgd.org
