### ISSUE TITLE
Does not recognize already known host from known_hosts file with ssh-ed25519 host key

### ISSUE THREAD

**Issue by DenisMir** [iterate-ch/cyberduck#12844]
OS: MacOS 12.2 
Cyberduck Version: Version 8.2.1 (36773)

I'm connecting to a host via SFTP that is already remembered in the `known_hosts` file in `~/.ssh` with a `ssh-ed25519` host key. Now Cyberduck presents me with an unknown host confirmation dialog and wants to add a `ED25519_CERT` host key. When I remember that one I got now two entries for the same host. 

Why does Cyberduck not recognize the already available `ssh-ed25519` host key?

**Comment by DenisMir** [comment]
Just for information the entry that is added by Cyberduck is a `HostCertificate` and is not allowed to land in the `known_hosts` file. So this is definitely a bug.

**Comment by dkocher** [comment]
I suppose it should be added to known_hosts with type {{ssh-ed25519}}.

**Comment by dkocher** [comment]
I cannot seem to reproduce the issue with the following entry being added

```
localhost ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEBwwoq1LRYZL00szyIzDBwF1MbSQAKepI9br0zcDR7A
```

**Comment by DenisMir** [comment]
@dkocher With which MacOS version have you tested it? And against which SSH version on the server side?
