### ISSUE TITLE
Update flow is frustrating

### ISSUE THREAD

**Issue by oliversalzburg** [iterate-ch/cyberduck#12848]
When you release a new update for Cyberduck, this is what users go through:

1. Open Cyberduck.
2. Receive a popup, notifying you that an update is available and that you could update. This is already getting in the way of why I originally opened Cyberduck.
3. To get this out of the way, you install the update.
4. After the update installation procedure is complete, nothing happens.
5. What was it that I orignally wanted to do...?

A few suggestions to improve this:

1. Open Cyberduck after the installation process completes.
2. Ask the user if they want to re-open Cyberduck now that the installation has completed.
3. Don't install the update when starting the application; remember the decision, then install on exit.

Cheers

**Comment by dkocher** [comment]
- On Windows, this will be resolved by migrating away from our current updater with #10857.
- On macOS, #12778 should support updates in the background.
