### ISSUE TITLE
SFTP using a keyfile not working

### ISSUE THREAD

**Issue by mgoggie** [iterate-ch/cyberduck#12857]
Getting Broken transport; encountered EOF. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

Connection works using Filezilla.

Version 8.2.3 (36880)

**Comment by jonathandhn** [comment]
I'm on the same predicament since yesterday ( Macos 12.3.1, Cyberduck  8.3.3 ), ssh keys on ~/.ssh path. None of the SFTP storage works anymore, what ever the server, selecting a key do nothing.

**Comment by ylangisc** [comment]
Might be related or a duplicate of #13442.
