### ISSUE TITLE
Missing download overwrite prompt (8.2.3)

### ISSUE THREAD

**Issue by hokutosu** [iterate-ch/cyberduck#12860]
I had just upgraded Cyberduck from v8.2.0 to v8.2.3
In 8.2.0, when downloading existing files, Cyberduck would prompt user what to do (resume, overwrite, compare, etc)
After upgrading to 8.2.3 it automatically downloaded all those files again without user prompt.

I was able to reproduce this issue on Windows 7 and Windows 10 installations.

**Comment by AliveDevil** [comment]
Checking #12878 beforehand, then I'll check for always overwriting downloads.

**Comment by AliveDevil** [comment]
Comparison: https://github.com/iterate-ch/cyberduck/compare/release-8-2-0..release-8-2-3?diff=unified

**Comment by AliveDevil** [comment]
I can confirm, this does happen on Cyberduck 8.2.3 as well.

**Comment by AliveDevil** [comment]
Regression of https://github.com/iterate-ch/cyberduck/pull/12798.
