### ISSUE TITLE
big files and cyberrduck

### ISSUE THREAD

**Issue by machampl** [iterate-ch/cyberduck#12884]
Hi,
I am using cyberduck - with smal files up to 2 Gib I don´t have any problems. If they get larger (10Gibs) they will whether end with an erroro or, today, it uploads 100% and then starts all over again!!

**Comment by tatze96** [comment]
Does this behavior occur in combination with a specific protocol?
Please attach a screenshot of the displayed error message.

**Comment by tatze96** [comment]
I can't reproduce the behavior on my side while using Cyberduck 8.2.4 (36993) in combination with WebDAV (HTTPS), FTPS, and S3. Which protocols are in use on your side?
