### ISSUE TITLE
OpenSSH ssh-agent support for windows

### ISSUE THREAD

**Issue by 8uurg** [iterate-ch/cyberduck#12880]
**Is your feature request related to a problem? Please describe.**
Managing SSH hosts, their configuration, including keys, are usually done through .ssh/config. Recent versions of Windows (10+) come with a OpenSSH installation, including the `ssh-agent`. The configuration & keys loaded by the SSH agent do not seem to work:
* CyberDuck is unable to resolve hostnames listed in the .ssh/config file.
* Based on the documentation, `ssh-agent` is only supported on Linux (and Mac?)

**Describe the solution you'd like**
Currently Cyberduck (and Mountain Duck) seem to only support PuTTY & PageAnt, OpenSSH support on Windows would be much appreciated.

**Describe alternatives you've considered**
* Falling back to using PuTTY & PageAnt, requires me to maintain multiple programs for the same task.

**Additional context**

**Comment by AliveDevil** [comment]
Technical for why it hasn't been implemented yet: https://github.com/iterate-ch/cyberduck/pull/12882#discussion_r805879434

Basically: Our agent proxy dependency is ancient (8 years old, and abandoned) with no support for the Windows OpenSSH named-pipe hackery around the Unix-domain sockets.
