### ISSUE TITLE
Cyberduck crashing nonstop on Win10 

### ISSUE THREAD

**Issue by user2393** [iterate-ch/cyberduck#12883]
I am so sick of restarting uploads for the millionth time and wasting hours because every time cyberduck freezes and my transfer is incomplete. I've done a billion reads on this external drive because of resuming every time it hangs up, and then it goes through the whole "preparing" and "checking" process before it finally starts uploading to B2 cloud, until it inevitably fails and freezes the entire app, which I have to kill via task manager and then manually restart, ad infinitum. 

I've done a bunch of tweaks in preferences, nothing worked, everything from the General tab to Transfers to Connection to Browser. I noticed there's a bunch of different Cyberducks running in task manager after awhile, all of which use no resources except one, when it finally freezes. I tried disabling hyperthreading and set affinity in task manager to cores 0 and 1 only, still testing that. 

On occasions the app wouldn't freeze, it would still fail the upload, with various error messages. I would then be able to resume immediately, but it again went through the whole checking process and calculating checksums etc., which wasted a ton of time. The log I found kept mentioning a "ch.cyberduck.core.LoginCallbackFactory" error. 

How do I stop this from happening?? Thanks.

**Comment by user2393** [comment]
Another question: just saw there were some "unfinished large files" in B2, even though those uploads had completed successfully and nothing seems to be missing (all done painstakingly via Cyberduck). But when I tried to use "upload" and "compare" cyberduck starts uploading some random folder with many "cyberducksegments" to both local and remote locations. I have no clue what that is. If I use "synchronize" and "mirror" cyberduck starts transferring 50 GB of data, no idea what or where to. I'm completely lost.

All I wanted was to upload shit from my hard drives to cloud, then check if everything got transferred properly.

**Comment by joootdooot** [comment]
I've had some similar issues before realizing that WinSCP supports S3
