### ISSUE TITLE
Registration license

### ISSUE THREAD

**Issue by akersha** [iterate-ch/cyberduck#12898]
**Describe the bug**
Double-clicking the license file once saved to the HDD does nothing. I've  confirmed that the file extension is correct once downloaded / saved. I've also tried using Open with >> in the context menu and selecting the Cyberduck app. When reopening Cyberduck, the app is still unlicensed.

**Expected behavior**
When I double-click the license file the Cyberduck app should reflect that it is licensed once opened.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by AliveDevil** [comment]
Please perform following steps:
* Open Cyberduck, enable Debug logging in Preferences/Connection tab.
* Double Click the license file
* In Cyberduck Preferences click "Show Log" and attach the file.

**Comment by akersha** [comment]
2022-02-22 13:36:31,376 [background-4] ERROR
ch.cyberduck.core.threading.BackgroundCallable - Exception
java.lang.ClassCastException: Specified cast is not valid. running cleanup
task
java.lang.ClassCastException: Specified cast is not valid.
at cli.Ch.Cyberduck.Ui.Controller.AsyncController.invoke(Unknown Source)
~[Cyberduck.exe:?]
at cli.Ch.Cyberduck.Ui.Controller.WindowController.invoke(Unknown Source)
~[Cyberduck.exe:?]
at
cli.Ch.Cyberduck.Ui.Controller.MainController.<InitializeSessions>b__55_3(Unknown
Source) ~[Cyberduck.exe:?]
at
ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:75)
~[Cyberduck.Core.DLL:0e46d6423ad19f50fd505a9ed04d161dad866faa]
at java.lang.Throwable.getLocalizedMessage(map.xml:1230) ~[?:1.8.0]
at
org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:136)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:115)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:97)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:384)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:241)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:226)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:60)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:198)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:313)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:136)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:90)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:541)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:485)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
~[Cyberduck.Core.DLL:2.17.1]
at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2018)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1985)
~[Cyberduck.Core.DLL:2.17.1]
at
org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:751)
~[Cyberduck.Core.DLL:2.17.1]
at cli.Ch.Cyberduck.Ui.Controller.AsyncController.invoke(Unknown Source)
~[Cyberduck.exe:?]
at cli.Ch.Cyberduck.Ui.Controller.WindowController.invoke(Unknown Source)
~[Cyberduck.exe:?]
at cli.Ch.Cyberduck.Ui.Controller.MainController.NewBrowser(Unknown Source)
~[Cyberduck.exe:?]
at
cli.Ch.Cyberduck.Ui.Controller.MainController$$$003C$$003Ec.<InitializeBookmarks>b__54_2(Unknown
Source) ~[Cyberduck.exe:?]
at cli.System.Delegate.DynamicInvokeImpl(Unknown Source) ~[mscorlib.dll:?]
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbackDo(Unknown
Source) ~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Unknown
Source) ~[System.Windows.Forms.dll:?]
at cli.System.Threading.ExecutionContext.RunInternal(Unknown Source)
~[mscorlib.dll:?]
at cli.System.Threading.ExecutionContext.Run(Unknown Source)
~[mscorlib.dll:?]
at cli.System.Threading.ExecutionContext.Run(Unknown Source)
~[mscorlib.dll:?]
at cli.System.Windows.Forms.Control.InvokeMarshaledCallback(Unknown Source)
~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbacks(Unknown
Source) ~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.Control.WndProc(Unknown Source)
~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.Form.WndProc(Unknown Source)
~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.NativeWindow.Callback(Unknown Source)
~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown
Source) ~[System.Windows.Forms.dll:?]
at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown
Source) ~[System.Windows.Forms.dll:?]
at
cli.System.Windows.Forms.Application$ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Unknown
Source) ~[System.Windows.Forms.dll:?]
at
cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoopInner(Unknown
Source) ~[System.Windows.Forms.dll:?]
at
cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoop(Unknown
Source) ~[System.Windows.Forms.dll:?]
at cli.Ch.Cyberduck.Ui.Program.Main(Unknown Source) ~[Cyberduck.exe:?]
2022-02-22 13:52:59,888 [Thread-0] INFO
 Ch.Cyberduck.Core.Preferences.AppConfigPreferences - setProperty:
ui.PreferencesForm.WindowState,PGludD4wPC9pbnQ+
2022-02-22 13:52:59,891 [Thread-0] INFO
 Ch.Cyberduck.Core.Preferences.AppConfigPreferences - setProperty:
ui.PreferencesForm.WindowBounds,PFJlY3RhbmdsZSB4bWxuczp4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIiB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIj48TG9jYXRpb24+PFg+NjEzPC9YPjxZPjIxMjwvWT48L0xvY2F0aW9uPjxTaXplPjxXaWR0aD44NzY8L1dpZHRoPjxIZWlnaHQ+NjMwPC9IZWlnaHQ+PC9TaXplPjxYPjYxMzwvWD48WT4yMTI8L1k+PFdpZHRoPjg3NjwvV2lkdGg+PEhlaWdodD42MzA8L0hlaWdodD48L1JlY3RhbmdsZT4=
2022-02-22 13:54:32,820 [Thread-0] DEBUG
Ch.Cyberduck.Ui.Controller.MainController - NewBrowser
2022-02-22 13:54:32,820 [Thread-0] ERROR AsyncController - Unhandled
exception during invoke
cli.System.TypeInitializationException: The type initializer for
'Ch.Cyberduck.Ui.Core.VirtualDesktop.Windows1809.DesktopManager' threw an
exception.
Caused by: cli.System.InvalidCastException: Specified cast is not valid.

**Comment by AliveDevil** [comment]
The log file pasted into an email is unfortunately truncated. Can you attach that as a file please?
