### ISSUE TITLE
Windows 10: Folder with 0 size, clear cache not help; 

### ISSUE THREAD

**Issue by dogonovm** [iterate-ch/cyberduck#12894]
We have problem with windows users. 
Some folders get status with out cloud icon. Look at file attached. 
Example folder with strart name 8. 
System tell 0 size. On nextcloud that folder has size 300Mb. 
That issue with folder have only one users.  

<img width="621" alt="Снимок экрана 2022-02-16 в 16 37 59" src="https://user-images.githubusercontent.com/84489925/154266655-69611e6c-cfd3-4e9f-80ae-6425e909a282.png">

I make clear cache on AppData user folder. After make restart full PC. That not helped. 
Can you help me. How to resync all folders with 0 size? 

Thank you!

**Comment by AliveDevil** [comment]
Please get in touch with support@mountainduck.io, and include debugging information as outlined in [our support documentation](https://docs.cyberduck.io/mountainduck/support/).

Regarding the missing icons: Windows has a limit of exactly, and no more than, 15 icons.
You can check `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers` in `RegEdit.exe` for the first 15 icons.
