### ISSUE TITLE
Sélection de répertoires

### ISSUE THREAD

**Issue by ylango** [iterate-ch/cyberduck#12913]
La sélection de répertoires s'ouvre et se referme instantanément lors du clic,

![jsuyqorMq7](https://user-images.githubusercontent.com/65193621/155173324-88bf7740-b10a-4117-bfab-8269514815a5.gif)

**Comment by AliveDevil** [comment]
Thanks for reporting.
I do see this here as well.

**Comment by AliveDevil** [comment]
Bisect result, Regression of https://github.com/iterate-ch/cyberduck/pull/12741
