### ISSUE TITLE
S3 config does not include Glacier Instant Retrieval storage class option

### ISSUE THREAD

**Issue by yousefamar** [iterate-ch/cyberduck#12915]
**Describe the bug**

The dropdown for default storage class for S3 does not include Glacier Instant Retrieval (I think because this might be a newer class?)

**To Reproduce**
1. Go to Preferences
2. Click on S3
3. Open the Storage Class dropdown
4. See that Glacier Instant Retrieval is missing

(I tried other ones to see if it might just be that they're labelled differently, but then when I check on the S3 console, it's none of them)

**Expected behavior**
That that option is there

**Screenshots**

![image](https://user-images.githubusercontent.com/999235/155312645-a173bff9-776b-4c5b-9ee5-a47788d77abc.png)

**Desktop (please complete the following information):**
 - OS: Win
 - Version 10
 
**Log Files**
N/A

**Additional context**
N/A

**Comment by AliveDevil** [comment]
Ref Implementation: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/StorageClass.java

**Comment by dkocher** [comment]
Identifier `GLACIER_IR`

>  Amazon S3 Glacier Instant Retrieval storage class is a new low cost storage class for customers with long-term, rarely accessed, data that is immediately accessible (less than a second for first byte latency). The target customers for this storage class are those who access an object less than once a quarter but require immediate access.

https://aws.amazon.com/s3/storage-classes/glacier/instant-retrieval/
