### ISSUE TITLE
Download from WebDav does not stop at the end of a csv file

### ISSUE THREAD

**Issue by JBRiehm** [iterate-ch/cyberduck#12921]
**Describe the bug**
When attempting to download a csv file for WebDav, the function continues well past 100% and creates many duplicate records.

**To Reproduce**
N/A 

**Expected behavior**
Stop at 100% of the file size.  Why are csv file downloads a problem. Uploads work fine, only downloads are a serious issue.

**Screenshots**
<img width="839" alt="Screen Shot 2022-02-25 at 12 38 27 PM" src="https://user-images.githubusercontent.com/83659603/155800908-bb437254-36dd-4325-b0b3-7ceda9252831.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.2.1

**Log Files**
N/A

**Additional context**
This is the only way we can get a content back-up of our website data.

**Comment by dkocher** [comment]
Apparently the server reports a different file size in response to `PROPFIND` than returned in the `Content-Length` header when accessing the file using `GET`.

**Comment by dkocher** [comment]
Please let us know the specifics about the server software in use to allow us to reproduce the problem and additionally report this bug to the server vendor if possible.
