### ISSUE TITLE
URLs generated structure issue

### ISSUE THREAD

**Issue by kmanan** [iterate-ch/cyberduck#12935]
Hi,

Previously Cyberduck would generate a URL that started with https://s3.amazonaws.com/<folderstructure and filename> In case of images, this would create a browser https friendly URL. Now all URLs created are https://<folder>.s3.amazonaws.com/<file> This URL is not browser https friendly. 

If I manually re-arrange the URL, then everything works. Here's an example:

Previously, Cyberduck would generate this URL: https://s3.amazonaws.com/images.beingmanan.com/wfh-gadgets/IMG_9775.JPG (works great!)

Now Cyberduck creates this: https://images.beingmanan.com.s3.amazonaws.com/g14/IMG_1391.JPG (this breaks in browsers) <-- same URL if I move the s3.amazonaws.com to beginning, everything works fine.

**Comment by AliveDevil** [comment]
You can mount your bucket directly via the Path-option in Cyberduck, then configure a custom Web URL in your connection to "https://s3.amazonaws.com/bucketname" which Cyberduck will fill in automatically using the path relative to your bucket.[^1]

[^1]: https://docs.cyberduck.io/cyberduck/bookmarks/#http-url

**Comment by kmanan** [comment]
Apologies, I did not understand what you asked me to do! In the open conx window, I use s3.amazonaws.com. And I am not a developer so don't really know what to look for in the URL you shared.

**Comment by AliveDevil** [comment]
You need to create a bookmark, instead of a quick connection.
Then configure it like this:
![image](https://user-images.githubusercontent.com/734738/189604515-5ef38385-5a12-4090-a658-1413fe8bc198.png)
