### ISSUE TITLE
 Unable to delete folders (Google Drive encrypted vault) 

### ISSUE THREAD

**Issue by nicollasricas** [iterate-ch/cyberduck#12936]
I'm unable to delete folders on my Google Drive encrypted vault.

Tested with Cyberduck and MountainDuck.

OS: Windows 11 Pro 21H2 (22000.527)
Cyber Duck: 8.2.3 (36880)
Mountain Duck: 4.10.3 (19145)
Cryptomator: 1.6.5 (FUSE)

[error.txt](https://github.com/iterate-ch/cyberduck/files/8182531/error.txt)
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8182530/cyberduck.log)

**Comment by dkocher** [comment]
Fix in 999065b.
