### ISSUE TITLE
Limitation on number of buckets?

### ISSUE THREAD

**Issue by ObjectMatrixCyberDuck** [iterate-ch/cyberduck#12949]
We use CyberDuck against an S3 compatible service.

We have hit a limit within Cyberduck it could be the number of buckets, or some sort of character limit in the list buckets response from the server. In this repeatable test, 77 buckets works, but 78 buckets fails, though these vaults have long name and this could be a issue with overall character length.

We have tested with an old version of Cyberduck and we get a popup error message (screenshot attached), but in later versions it fails with no error at all.

The server side logs show no errors.

Accessing the server with the same credentials, using another S3 compatible GUI program (not CyberDuck) is possible, but we would like to continue to use CyberDuck.

Can anyone assist with this? Is there any additional information you require
![cyberduck](https://user-images.githubusercontent.com/101195836/157299204-21127fa9-4d53-4985-932b-0af54db01b71.png)
?

**Comment by tatze96** [comment]
Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), reproduce the described behavior and send us the log file afterward? If you don't like to see sensitive data be shared publicly please send the log file with the ticket reference GH-12949 to support@cyberduck.io, otherwise attach it here.

**Comment by ObjectMatrixCyberDuck** [comment]
Thank you for the update - I will respond via email directly.

**Comment by dkocher** [comment]
Can you verify the server always responds a `Content-Type: application/xml` response HTTP header. The log output suggests it is missing in some cases.
