### ISSUE TITLE
Parsing Error ?

### ISSUE THREAD

**Issue by coulinator** [iterate-ch/cyberduck#12969]
Using duck.exe in a batch file to upload .PDF file in FTP shows an ERROR message (even if the upload works) :
12:41:19.552 [background-1] ERROR ch.cyberduck.core.ftp.list.FTPMlsdListResponseReader - Error parsing line 250-Begin
12:41:19.590 [background-1] ERROR ch.cyberduck.core.ftp.list.FTPMlsdListResponseReader - Error parsing line 250 End. 

Any idea why ?

(Using a older version of duck does nos shos this ERROR).

Tks.

**Comment by dkocher** [comment]
This indicates an invalid response from the server not formatted according to the RFC for FTP status replies. Previous versions might have not logged errors to the stdout. If you want to omit the warning, use the _Compatibility Mode_ profile from https://docs.cyberduck.io/protocols/ftp/#listing-directory-fails-or-shows-no-content 

With Cyberduck CLI you will have to change the URL in parameters to use the newly registered scheme `ftp-compat://` or `ftpssl-compat` respectively as shown in the output `duck --help`.
