### ISSUE TITLE
Impossible delete folder

### ISSUE THREAD

**Issue by StefanoFarina** [iterate-ch/cyberduck#12968]
Hi, creating a folder with "\\" in the name , the folder is created, but then is impossible to delete it.

**Comment by AliveDevil** [comment]
I fixed your comment, as GitHub uses \ to escape characters.

**Comment by AliveDevil** [comment]
On which protocol are you experiencing this issue?

**Comment by StefanoFarina** [comment]
Hi, using interface. The interface allows to add a folder name like "name\subname", but then is impossible to delete it.

**Comment by AliveDevil** [comment]
Sure, but which protocol (FTP, SFTP, WebDAV, etc.) are you connected to where you try to create such folder.

**Comment by StefanoFarina** [comment]
ah sorry, Amazon S3

**Comment by dkocher** [comment]
Test in 4d5286e3290fa2ec9871ac39b1ea0446af0038d0.

**Comment by dkocher** [comment]
Test in 4d5286e3290fa2ec9871ac39b1ea0446af0038d0.

**Comment by StefanoFarina** [comment]
![Img1](https://user-images.githubusercontent.com/22367762/158386683-a51f4034-8029-4234-a8d5-bb7ff65e4f75.JPG)
![err](https://user-images.githubusercontent.com/22367762/158386705-d8506a03-41a8-4d27-a0cb-5cccbf368abc.JPG)

**Comment by dkocher** [comment]
Possibly resolved with #14249.
