### ISSUE TITLE
%Errorlevel% is always 0 even in case of Error - Help wanted

### ISSUE THREAD

**Issue by coulinator** [iterate-ch/cyberduck#12971]
Hi, 

I need to use the %errorlevel% in a batch to delete of not a file uploaded by FTP. 

Seems to not work anymore ? (Work with older version).
%errorlevel% is always 0 even in case of error returned using duck like the following :

Connection failed. Connection timed out: connect. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

BATCH FILE :

for %%F in (".\*.pdf") do (
echo "%%F"
duck -q -y -v -e rename --username USER --password PASSWORD --upload ftps://xxxx "%%F"
if %ERRORLEVEL% equ 0 del "%%F"
)

Any other way to do this ?

Thks

**Comment by coulinator** [comment]
So, i reuse an old version (7.x.x) and %errorlevel% is correct.

**Comment by dkocher** [comment]
I cannot reproduce this on macOS with version 8.3.3.

```
silverbullet:~ dkocher$ duck --list ftps://iterate.ch/
Disconnecting iterate.ch…
Connection failed. Connect timed out. The connection attempt timed out. The server may be down, or your network may not be properly configured.
silverbullet:~ dkocher$ echo $?
1
```

**Comment by dkocher** [comment]
I cannot reproduce this on Windows with version 8.4.0

```
PS C:\Windows\system32> duck --list ftps://iterate.ch/
Disconnecting iterate.ch?
Connection failed. Connection timed out: connect. The connection attempt was rejected. The server may be down, or your network may not be properly configured.
PS C:\Windows\system32> $LASTEXITCODE
1
```
