### ISSUE TITLE
Remember sort order

### ISSUE THREAD

**Issue by alturic** [iterate-ch/cyberduck#12974]
I'm unsure if this is a bug or not, but is there any way to remember sort order? I always sort by Kind so folders are before files but I'm unsure if it's something on my end not remembering that or if that is expected behavior.

**Comment by dkocher** [comment]
I cannot reproduce this on macOS or Windows.

**Comment by alturic** [comment]
So you are saying on your end it remembers your sort order, if you sort by Kind?
