### ISSUE TITLE
Compose segments of download very slow after downloading is slow

### ISSUE THREAD

**Issue by yardik** [iterate-ch/cyberduck#12996]
After downloading a multi-segment download of large size (200GB etc.) the recompositing of the file is extremely slow, like hours, longer than the download. I see this was closed previously with a 'don't use segments' workaround, but doing so trashes your ability to 
- get maximum download speed
- effectively resume download, by resuming missing segments

I don't think the workaround solves the problem. 

I'd be happy to contribute a fix for this, if someone can point me towards the area of the codebase that functionally recreates the downloaded file from the multiple chunks.

Thanks!

**Comment by dkocher** [comment]
Duplicate for #10961.

**Comment by dkocher** [comment]
You can find the code in https://github.com/iterate-ch/cyberduck/blob/2b1b543e50b9f1f5b2490ccec24867bbd4c7cd2f/core/src/main/java/ch/cyberduck/core/transfer/download/AbstractDownloadFilter.java#L270-L300

If you can find a better performing implementation that would certainly be welcome.
