### ISSUE TITLE
Expired OAuth refresh token requiring re-authenticating with the browser

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/cyberduck#13003]
It seems contradictory to the [documentation](https://developer.box.com/guides/authentication/tokens/refresh/) the refresh token obtained from the OAuth authentication flow expires earlier than expected.

```
POST https://api.box.com/oauth2/token/
{
  "error": "invalid_grant",
  "error_description": "Refresh token has expired"
}
```

> A Refresh Token is valid for 60 days and can be used to obtain a new Access Token and Refresh Token only once. If the Access Token and Refresh Token are not refreshed within 60 days, the user will need to be re-authorized.
>
> Every time an application uses the Refresh Token to get a new Access Token the Refresh Token is invalidated and a new Refresh Token is returned with the new Access Token.
> 
> This new Refresh Token is then again only valid for 1 use within 60 days.

**Comment by Wrong-Code** [comment]
Are there any news on this issue? The problem persists and the token doesn't last more than 24-48 hours at most, and it's very annoying.

I see that at least the (unrelated?) issue of Cryptomator vaults on Box ( #13961) has been resolved. Thanks.
