### ISSUE TITLE
Encrypted upload progress bar is inaccurate

### ISSUE THREAD

**Issue by and-rew** [iterate-ch/cyberduck#13012]
**Describe the bug**
When uploading files to encrypted vault in cloud, the progress bar reflects the preparation/encryption stage of the process. The actual upload starts after 100% mark hit.

**To Reproduce**
Upload any big enough file to see how the progress bar stuck at 100%, while upload is still in progress.

**Expected behavior**
Include the upload time in progress bar total, or split it somehow - encryption + upload.

**Screenshots**
![Screenshot 2022-03-23 at 00 18 33](https://user-images.githubusercontent.com/7512348/160280853-2b988895-eb4e-4769-b43a-bc91bf6a36bb.png)

**Desktop (please complete the following information):**
- OS: MacOS 10.14.6 (18G9323)
- Version 8.2.3 (36880)

**Log Files**
-

**Comment by dkocher** [comment]
I cannot confirm this behaviour. We encrypt chunks on the fly using our [Cryptomator](https://docs.cyberduck.io/cryptomator/) implementation. This may be due to the server taking a long time to respond when finalizing the upload.

**Comment by dkocher** [comment]
Can you let me know what protocol you are using.

**Comment by dkocher** [comment]
> Webdav. To be exact, there's a mount point created by connecting to a cloud via Finder. Then, in Cyberduck I went to this folder (/Volumes/etc) and created a vault. Probably this is why it happens - the connection itself is maintained by MacOS/Finder, not Cyberduck. Thought about it just now. :|

Right, the connection is just to the local mount point. You might want to connect directly using WebDAV in Cyberduck.

**Comment by and-rew** [comment]
Will try. Thank you!
