### ISSUE TITLE
Cyberduck Version 8.2.3 - Crash copy files after 300 GB to S3 

### ISSUE THREAD

**Issue by mribeiro1990** [iterate-ch/cyberduck#13019]
Good morning,

After start a copy of 1.2 TB information to S3 Wasabi Cloud my cyberduck software crash (copy 300GB before).  Any someone with same problem?

Thanks a lot.

Best Regards,

**Comment by AliveDevil** [comment]
Which operating system and version are you on?

What type of crash are you referring to? Transfer incompletion, lock ups, or something different?

**Comment by mribeiro1990** [comment]
Windows Server 2019. last Update right now 8.3.0.

**Comment by mribeiro1990** [comment]
Version: 1809

**Comment by dkocher** [comment]
Please send us the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) for further investigation.
