### ISSUE TITLE
"Download" option doesn't work properly if downloading to iCloud Downloads folder 

### ISSUE THREAD

**Issue by yaroslav-pohil** [iterate-ch/cyberduck#13025]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
If I set the default downloading folder to be Donwloads folder from iCloud(`~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Downloads`), then Cyberduck(I'm using Version 8.2.3 (36880)) fails to download files. At the same time, if I download the same file to the same folder using option "Download To..." - it's downloaded without issues.

**To Reproduce**
1. Go to Cyberduck settings (Transfers -> General -> Download Folder and select Donwloads folder from iCloud
2. Download any file from SFTP server
3. See error "Access denied"

**Expected behavior**
File must be downloaded without any issues.

**Screenshots**
![CleanShot 2022-03-30 at 15 06 31@2x](https://user-images.githubusercontent.com/6236563/160830880-b21716e7-0e1a-4b24-b573-2f28a951a0f0.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.6.5

**Log Files**
```
2022-03-30 15:13:45,482 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for eject.pdf
2022-03-30 15:13:45,483 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - Return default size for eject.pdf
2022-03-30 15:13:45,485 [main] WARN  ch.cyberduck.core.local.AbstractPromptBookmarkResolver - Failure getting bookmark data for file Local{path='/Users/Yaroslav/Library/Mobile Documents/com~apple~CloudDocs/Downloads/phpunit.xml'}
2022-03-30 15:13:45,486 [main] WARN  ch.cyberduck.core.local.FinderLocal - Failure resolving bookmark for Local{path='/Users/Yaroslav/Library/Mobile Documents/com~apple~CloudDocs/Downloads/phpunit.xml'}. BackgroundException{class=class ch.cyberduck.core.exception.LocalAccessDeniedException, file=null, message='Access denied', detail='The file “phpunit.xml” couldn’t be opened because there is no such file.', cause='null'}
```

**Additional context**
I noticed that after I downloaded any file to the same folder using "Download To..." option, then "Download" option starts working properly.

**Comment by AliveDevil** [comment]
macOS Standalone (downloaded from website) or AppStore?

**Comment by yaroslav-pohil** [comment]
@AliveDevil I have AppStore version.

**Comment by tatze96** [comment]
I wasn't able to reproduce the behavior neither within the AppStore version nor within the Standalone version.

Can you attach the full logging output with debug logging enabled right after one of the mentioned errors occurs again so that we can investigate this further?

**Comment by yaroslav-pohil** [comment]
@tatze96 Hi, sure:
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8638666/cyberduck.log)
Also, I can say that it's important to open Cyberduck with "Download" folder already set, and do not download from any other servers beforehand. Because if you download first to a valid place, and then to `~/Library/Mobile\ Documents/com\~apple\~CloudDocs/Downloads` - file will be downloaded without any issues.

**Comment by dkocher** [comment]
Cannot be reproduced running in sandbox and having selected `/Users/dkocher/Library/Mobile Documents/com~apple~CloudDocs/Downloads` as the default download location.
