### ISSUE TITLE
cyberduck check for update error + search recursively error

### ISSUE THREAD

**Issue by jokermtb** [iterate-ch/cyberduck#13020]
Hi, 
When I click 'check for updates' I get an error message.  When I search recursively, the entire program stalls and locks up, causing me to ctrl+alt+delete close the program.   Version 7.10.2 (35432)

**Comment by AliveDevil** [comment]
What message do you get after checking for an update?

What remote storage/protocol are you connected to which produces this behavior?

**Comment by Johicov** [comment]
You're lucky you got an error message Before updating and not after, the newest update broke my application.
