### ISSUE TITLE
New problematic  issue with Cyberduck 

### ISSUE THREAD

**Issue by suchyczeslaw** [iterate-ch/cyberduck#13039]
Last weeks I noticed strange error using Cyberduck.I'm using this software from many years and I'm really glad  of it.
What I do wrong now, if I repeatedly see this warning? I didn't change anything in my configurations.  Attached screenshot.

Thanks
d
<img width="443" alt="Cyberduck attention" src="https://user-images.githubusercontent.com/102911053/161432506-97480447-a018-41c7-b44e-451f9fb08f7e.png">

**Comment by suchyczeslaw** [comment]
In fact, this is only annoying error message. I'm still able to upload and download files to/from ftp sites.
But to postpone it I have to Cancel, and disconnect and connect to the site again. Other way new files are not visible for me

**Comment by JLDo** [comment]
Same fom me, very anoying when you open/edit directly a file !!

**Comment by danihuge** [comment]
same here! waiting for a response...

**Comment by l1z0b** [comment]
I have the same problem! Also if you click "Try Again" multiple times there's a risk of being blacklisted depending on the settings of the server. I was hoping that this would be fixed with the next upgrade but right now the new upgrade made it only worse.
