### ISSUE TITLE
FTP/FTPs Connection or outbound has closed. 

### ISSUE THREAD

**Issue by jakubluny** [iterate-ch/cyberduck#13045]
When im using FTP or FPTs and then wait for like 10minutes and then try to save something or refresh folder, alert then shows:
Connection or outbound has closed. Pokus o spojení byl odmítnut. Server je pravděpodobně vypnut nebo vaše síť není správně nastavena.

Its really annoying and I need to close app and reconnect over and over again, please fix it.

**Comment by dkocher** [comment]
Duplicate for #13037.
