### ISSUE TITLE
List hidden files like `.env`

### ISSUE THREAD

**Issue by tom10271** [iterate-ch/cyberduck#13042]

**Comment by AliveDevil** [comment]
Click on "View" -> Show Hidden Files[^1]

[^1]: https://docs.cyberduck.io/cyberduck/browser/#browser-general-show-hidden-files

**Comment by lzambarda** [comment]
The above setting does not have any effect for me. Running Cyberduck 8.9.1

**Comment by AliveDevil** [comment]
Please, create a [new bug report](https://github.com/iterate-ch/cyberduck/issues/new?template=bug_report.md), adding as much details as possible (i.e. server software, protocol).
