### ISSUE TITLE
I am new to Cyberduck advice/comment needed

### ISSUE THREAD

**Issue by IanKMckenzie** [iterate-ch/cyberduck#13044]
Each time i try to upload a file (81.00MiB) it re-loads and uploads a number if times.  it appears not to have up loaded. But if i exit Cyberduck and then go to the upload folder it is there. The legend in Cyberduck often but not always says "Upload incomplete".

**Comment by tatze96** [comment]
Does this happen in combination with a specific protocol?

**Comment by IanKMckenzie** [comment]
I don’t understand what ‘protocol’ means in this context. 


Ian K. McKenzie
----------------------------------------------------------------------
Editor  Blues In The South a monthly ezine. All you need to know about blues in the south of England
Founder Member and Hon Sec of the  Independent Blues Broadcasters Association  ( IBBA )
Producer/host,  Wednesday's Even Worse , on Blues and Roots Radio ( www.bluesandrootsradio.com ) Wednesdays @ 5pm (UK Time/ 12 noon Eastern) Repeated Thursday @ 8am (UK time/ 3am Eastern)

Producer/host,  Acoustic Blues Club on Kansas City Online Radio, KCOR ( www.kconlineradio.com ) Every Wednesday @ 9pm (UK Time/ 3pm Central) on www.kconlineradio.com. Repeated Friday @ 1pm ( time /7am Central) and @ 11pm Central on Monday - 5am Tuesday

Podcasts of all shows including  Drive Time Blues a special commute friendly Podcast, may be found at at  http://ianm-blues-progammes.podomatic.com 
Creator/webmaster of tribute pages for Big Bill Broonzy at  www.broonzy.com
Reports to  Roots Music       Report


Thursday, 28 April 2022, 13:10 +0100 from ***@***.***  ***@***.***>:

**Comment by tatze96** [comment]
You've selected the protocol while you've either used the *Open Connection* functionality to open a temporary connection or while you've created a bookmark to connect to your server. Examples of protocols are SFTP, FTP, WebDAV, and S3.
