### ISSUE TITLE
Constant Kernel Panics

### ISSUE THREAD

**Issue by jkirkit** [iterate-ch/cyberduck#13056]
**Describe the bug**
CyberDuck causes macOS to kernel panic under load or at idle.

**To Reproduce**
I have been unable to reproduce the issue on other macOS devices I have access to. However the issue is consistent on the particular iMac. It has been serviced by Apple's Genius Bar twice already to no resolve. They indicated CyberDuck was causing a memory leak, leading to the kernel panics.

**Expected behavior**
The application to operate.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.0.1

**Log Files**
panic(cpu 2 caller 0xffffff8015f049ad): userspace watchdog timeout: no successful checkins from WindowServer in 120 seconds
service: logd, total successful checkins since wake (20490 seconds ago): 2050, last successful checkin: 0 seconds ago
service: WindowServer, total successful checkins since wake (20490 seconds ago): 2038, last successful checkin: 120 seconds ago
service: remoted, total successful checkins since wake (20490 seconds ago): 2050, last successful checkin: 0 seconds ago
service: opendirectoryd, total successful checkins since wake (20490 seconds ago): 2050, last successful checkin: 0 seconds ago

Panicked task 0xffffff905b8479c0: 3 threads: pid 115: watchdogd
Backtrace (CPU 2), panicked thread: 0xffffff905a8ee540, Frame : Return Address
0xffffffd04790b6c0 : 0xffffff8012a85ffd
0xffffffd04790b710 : 0xffffff8012be6035
0xffffffd04790b750 : 0xffffff8012bd5803
0xffffffd04790b7a0 : 0xffffff8012a25a60
0xffffffd04790b7c0 : 0xffffff8012a863cd
0xffffffd04790b8e0 : 0xffffff8012a85b86
0xffffffd04790b940 : 0xffffff80133164a6
0xffffffd04790b9b0 : 0xffffff8015f049ad
0xffffffd04790b9c0 : 0xffffff8015f04600
0xffffffd04790b9e0 : 0xffffff801328a33d
0xffffffd04790ba30 : 0xffffff8015f039bb
0xffffffd04790bb60 : 0xffffff801329460c
0xffffffd04790bcc0 : 0xffffff8012b8d0b4
0xffffffd04790bdd0 : 0xffffff8012a61048
0xffffffd04790be60 : 0xffffff8012a77a8d
0xffffffd04790bef0 : 0xffffff8012bb8f7e
0xffffffd04790bfa0 : 0xffffff8012a26246
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[0E41330C-797B-3F73-A333-04EFB1F20DAC]@0xffffff8015f02000->0xffffff8015f04fff

Process name corresponding to current thread (0xffffff905a8ee540): watchdogd
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21D62

Kernel version:
Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
Kernel UUID: 93729D02-FE6F-355B-BA76-BA930AA7103F
KernelCache slide: 0x0000000012800000
KernelCache base:  0xffffff8012a00000
Kernel slide:      0x0000000012810000
Kernel text base:  0xffffff8012a10000
__HIB  text base: 0xffffff8012900000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Hibernation exit count: 0

System uptime in nanoseconds: 119278763753626
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00006c7bc057c55f
  Sleep   : 0x000033afa48aafad 0x00000000a92c4e9a 0x000033a3de9582d9
  Wake    : 0x000033afad28ea8f 0x00000000a9596d56 0x000033afa9612b37
Zone info:
Foreign   : 0xffffff802a5e8000 - 0xffffff802a5f5000
Native    : 0xffffff805b8dc000 - 0xffffffa05b8dc000
Readonly  : 0xffffff85285a8000 - 0xffffff86c1f3c000
Metadata  : 0xffffffd6c1199000 - 0xffffffd6e14ac000
Bitmaps   : 0xffffffd6e14ac000 - 0xffffffd6ed4ac000
last started kext at 113051446609088: >usb.cdc.acm          5.0.0 (addr 0xffffff7fab884000, size 12288)
last stopped kext at 113128596740796: >usb.serial 6.0.0 (addr 0xffffff7fab901000, size 20480)
loaded kexts:
@filesystems.smbfs    4.0
>!ATopCaseHIDEventDriver    5020.1
>AGPM            127
>X86PlatformShim      1.0.0
>!APlatformEnabler    2.7.0d0
@filesystems.autofs   3.0
@fileutil          20.036.15
>!AHIDALSService       1
>!AUpstreamUserClient          3.6.8
@kext.AMDRadeonX6000      4.0.7
>!ABridgeAudio!C       200.8
@kext.AMDRadeonServiceManager  4.0.7
>!AGFXHDA     140.1
>!A!IKBLGraphics        18.0.4
>!AGraphicsDevicePolicy        6.4.12
@AGDCPluginDisplayMetrics 6.4.12
>pmtelemetry 1
|IOUserEthernet         1.0.1
>usb.!UUserHCI          1
>!AHV  1
>!ADiskImages2          126.60.3
>!AMCCSControl         1.14
>!A!IPCHPMC  2.0.1
>!AThunderboltIP       4.0.3
>!A!ICFLGraphicsFramebuffer            18.0.4
>!A!ISlowAdaptiveClocking    4.0.0
>BridgeAudioCommunication 200.8
>!AAVEBridge  6.1
>usb.!UHostBillboardDevice   1.0
|SCSITaskUserClient   452.60.2
>!UCardReader           532.40.7
>BCMWLANFirmware4387.Hashstore           1
>BCMWLANFirmware4378.Hashstore           1
>BCMWLANFirmware4377.Hashstore           1
>BCMWLANFirmware4364.Hashstore           1
>BCMWLANFirmware4355.Hashstore           1
>!AFileSystemDriver   3.0.1
@filesystems.tmpfs    1
@filesystems.lifs         1
@filesystems.hfs.kext 582.60.2
@BootCache   40
@!AFSCompression.!AFSCompressionTypeZlib         1.0.0
@!AFSCompression.!AFSCompressionTypeDataless 1.0.0d1
@filesystems.apfs       1933.80.3
|!ABCM5701Ethernet 11.0.0
>!ABCMWLANBusInterfacePCIeMac  1
@private.KextAudit    1.0
>!AACPIButtons          6.1
>!ASMBIOS      2.1
>!AACPIEC       6.1
>!AAPIC           1.7
@!ASystemPolicy        2.0.0
@nke.applicationfirewall       402
|IOKitRegistryCompatibility   1
|EndpointSecurity      1
@Dont_Steal_Mac_OS_X       7.0.0
@kec.!AEncryptedArchive      1
>driverkit.serial           6.0.0
@plugin.IOAVBDiscoveryPlugin         1010.2
>!AMultitouchDriver   5430.21
>!AInputDeviceSupport          5400.30
>!AHS!BDriver 5020.1
>IO!BHIDDriver           9.0.0
@kext.triggers 1.0
>!AHIDKeyboard         228
>!AAudioClockLibs      100.9.1
@kext.AMDRadeonX6200HWLibs      1.0
@kext.AMDRadeonX6000HWServices           4.0.7
|IOAudio!F      300.10
@vecLib.kext  1.2.0
>!ASMBusPCI  1.0.14d1
>!A!ILpssUARTv1        3.0.60
>!A!ILpssUARTCommon         3.0.60
>!AOnboardSerial       1.0
>!AGraphicsControl    6.4.12
|IO!BSerialManager    9.0.0
|IO!BPacketLogger     9.0.0
|IO!BHost!CUSBTransport      9.0.0
|IO!BHost!CUARTTransport   9.0.0
|IO!BHost!CTransport 9.0.0
>IO!BHost!CPCIeTransport     9.0.0
|IOAVB!F         1010.2
@plugin.IOgPTPPlugin            1000.11
|IOEthernetAVB!C      1.1.0
|CSR!BHost!CUSBTransport   9.0.0
@kext.AMDRadeonX6000Framebuffer          4.0.7
|Broadcom!BHost!CUSBTransport     9.0.0
|Broadcom!B20703USBTransport     9.0.0
>!AIPAppender           1.0
@kext.AMDSupport   4.0.7
>!UMergeNub 900.4.2
|IONDRVSupport        593
>!ASMBus!C    1.0.18d1
>!AThunderboltDPOutAdapter           8.5.1
|IOAccelerator!F2       462.4.1
@!AGPUWrangler       6.4.12
@!AGraphicsDeviceControl    6.4.12
|IOGraphics!F 593
|IOSlowAdaptiveClocking!F    1.0.0
>X86PlatformPlugin    1.0.0
>IOPlatformPlugin!F   6.0.0d8
>usb.IOUSBHostHIDDevice     1.2
>usb.!UHub     1.2
>usb.cdc.ecm  5.0.0
>usb.cdc.ncm  5.0.0
>usb.cdc          5.0.0
>usb.networking         5.0.0
>usb.!UHostCompositeDevice            1.2
>!AThunderboltPCIDownAdapter      4.1.1
>!AThunderboltDPInAdapter  8.5.1
>!AThunderboltDPAdapter!F 8.5.1
>!AHPM           3.4.4
>!A!ILpssI2C!C 3.0.60
>!A!ILpssI2C    3.0.60
>!A!ILpssDmac            3.0.60
>!ABSDKextStarter      3
|IOSurface      302.11.1
@filesystems.hfs.encodings.kext       1
>!AXsanScheme          3
>!AThunderboltNHI    7.2.8
|IOThunderbolt!F       9.3.3
>usb.!UVHCIBCE         1.2
>usb.!UVHCICommonBCE      1.0
>usb.!UVHCI    1.2
>usb.!UVHCICommon 1.0
>!AEffaceableNOR      1.0
|IOBufferCopy!C         1.1.0
|IOBufferCopyEngine!F          1
|IONVMe!F     2.1.0
>!ABCMWLANCoreMac          1.0.0
|IOSerial!F       11
|IO80211!F     1200.12.2b1
|IOSkywalk!F  1.0
>mDNSOffloadUserClient       1.0.1b8
>IOImageLoader         1.0.0
>!AOLYHALMac           1
>corecapture  1.0.4
>usb.!UHostPacketFilter         1.0
|IOUSB!F         900.4.2
>usb.!UXHCIPCI           1.2
>usb.!UXHCI    1.2
>!AEFINVRAM 2.1
>!AEFIRuntime            2.1
>!ASMCRTC     1.0
|IOSMBus!F    1.1
|IOHID!F         2.0.0
|IOTimeSync!F            1000.11
|IONetworking!F        3.4
>DiskImages    493.0.0
|IO!B!F            9.0.0
|IOReport!F    47
$quarantine    4
$sandbox        300.0
@kext.!AMatch           1.0.0d1
|CoreAnalytics!F         1
>!ASSE 1.0
>!AKeyStore    2
>!UTDM          532.40.7
|IOUSBMass!SDriver  209.40.6
|IOSCSIBlockCommandsDevice          452.60.2
|IO!S!F 2.1
|IOSCSIArchitectureModel!F  452.60.2
>!AMobileFileIntegrity            1.0.5
$!AImage4      4.2.0
@kext.CoreTrust         1
>!AFDEKeyStore          28.30
>!AEffaceable!S          1.0
>!ACredentialManager           1.0
>KernelRelayHost       1
|IOUSBHost!F 1.2
>!UHostMergeProperties       1.2
>usb.!UCommon         1.0
>!ABusPower!C           1.0
>!ASEPManager          1.0.1
>IOSlaveProcessor      1
>!AACPIPlatform         6.1
>!ASMC           3.1.9
|IOPCI!F          2.9
|IOACPI!F        1.4
>watchdog      1
@kec.pthread 1
@kec.Libm      1
@kec.corecrypto        12.0

**Comment by AliveDevil** [comment]
Nothing we can do here[^1]. The WindowServer (graphical user interface) locks up, due to unknown reasons.
More infos: [^2][^3][^4]

[^1]: https://forums.macrumors.com/threads/2222878/
[^2]: https://www.reddit.com/r/hackintosh/comments/q3kb4j
[^3]: https://discussions.apple.com/thread/252412856
[^4]: https://developer.apple.com/forums/thread/667376
