### ISSUE TITLE
peer socket write error

### ISSUE THREAD

**Issue by mrkleinfeld** [iterate-ch/cyberduck#13261]
Hello, I have a peer socket write error since two days. It appears with different hosts. The error always appears after about 10 - 20 minutes of inactivity. Maybe someone can help, I have no idea at all how to solve the problem. I have the latest version (purchased) of Cyberduck on the PC. 
Thanks a lot!

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/13037.
