### ISSUE TITLE
Recursive ProxyJump

### ISSUE THREAD

**Issue by 8uurg** [iterate-ch/cyberduck#13266]
**Is your feature request related to a problem? Please describe.**
Currently, Cyberduck (and MountainDuck) have support for connecting through a single ProxyJump. This is common, e.g., when using bastion servers. In my case there is another jump in between. This works fine with SSH itself, but fails in Cyberduck & MountainDuck.

**Describe the solution you'd like**
It would be nice if ProxyJump configuration was applied recursively: e.g. if a ProxyJump host itself has a ProxyJump declaration, use that as well. This is how it works when using ssh itself, and it would be nice to have parity with that.

**Describe alternatives you've considered**
I currently set up a SSH tunnel myself on localhost, and connect using Cyberduck using that. This works fine (albeit requires the extra step of connecting with a tunnel set-up). It is mostly annoying when using tools like MountainDuck: when a connection is opened automatically (e.g. on boot), this won't work as the tunnel has to be set up manually before a connection can be made.

**Additional context**
N/A

**Comment by dkocher** [comment]
Duplicate for #12672.
