### ISSUE TITLE
Problem with uploading maps used by WordPress software

### ISSUE THREAD

**Issue by sitbackLars** [iterate-ch/cyberduck#13272]
Today I could not upload maps from the software of WordPress itself. 
All kinds of error messages and no luck at all. Never had this problem before. I use Siteground as a hosting company. 

For now I made a new FTP account.
Restarted my mac two times and restarted all rooters. No effect. 
Still got errors or closing of the connection.

Also tried other hosting providers. There it works all fine.

Also used (just for now:) no worries) Filezilla. And guess what? It works ok then. Hmmm.
May be a conflict with Cyberduck and Siteground?

Yours Sincerely, 
Lars Eckardt

**Comment by AliveDevil** [comment]
Can you check whether the current released version 8.3.2 still has this issue?
There have been fixes for FTP since.

**Comment by sitbackLars** [comment]
Thank you . I just updated and checked. Still I'm not allowed to create a map via this software hmmm.

**Comment by dkocher** [comment]
Duplicate for #13322.
