### ISSUE TITLE
Duck hangs

### ISSUE THREAD

**Issue by geni2019** [iterate-ch/cyberduck#13278]
CyberDuck connects to provider,
can see the main folders, but can't get access to the content.
This happend after quick opening CyberDuck.
Mojave 10.14.6
Cyber Duck Version 8.3.1 (37445)

ernst.genser@aon.at

**Additional context**
[Cyberduck_2022-04-08-200808_ernst-gensers-imac.hang.zip](https://github.com/iterate-ch/cyberduck/files/8454440/Cyberduck_2022-04-08-200808_ernst-gensers-imac.hang.zip)

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/13273.
