### ISSUE TITLE
Cannot open folders after update to 8.3.1

### ISSUE THREAD

**Issue by sonezu** [iterate-ch/cyberduck#13276]
Hi! I've updated to 8.3.1 and right after was not able to open any folder anymore.
It's just loading forever and nothing happens.

I'm working on a M1 MacBook Air.
Nothing else has changed besides the upgrade and the trouble began just right away after the update.

Often the app is not responding and has to be closed manually.

**Comment by dkocher** [comment]
Duplicate for #13273.
