### ISSUE TITLE
Passwords not saved

### ISSUE THREAD

**Issue by aquorange** [iterate-ch/cyberduck#13284]
In Version 8.3.2 (37449) which I just updated Cyberduck doesn’t save the ftp passwords any more on macos 10.13. Is it an incompatibility or a bug? This worked before I updated.

**Comment by tatze96** [comment]
I can't reproduce the described behavior within the latest Snapshot version (8.3.4). Does this behavior persist on your side within the latest version?

**Comment by aquorange** [comment]
Hi Laura,

now using 8.3.3 (37544) it works fine.
Thanks for caring.

Carsten
***@***.***
