### ISSUE TITLE
Upload button greyed out -cyberduck (annoying problem)

### ISSUE THREAD

**Issue by mwfmcharlize** [iterate-ch/cyberduck#13298]
Hello, 
I have the latest install for cyber duck and the upload button is grayed out. this is very annoying and time losing issue.
how can be resolved?

tks

**Comment by AliveDevil** [comment]
Do you have an active connection to a server (via Quick Connect, a configured bookmark, or using the History)?
Do you have write permissions in the directory you are trying to upload to?
Which protocol are you using, on which operating system? Do you have screenshots showing the behavior?

**Comment by mwfmcharlize** [comment]
Tks for feedback ! I am able to access the directory using the credentials which were used before. I am using Windows.
![Capture](https://user-images.githubusercontent.com/103728605/164081739-5dc5822b-8c1b-46bf-87f4-5e694b61e7c6.JPG)
.

**Comment by AliveDevil** [comment]
Do you remember which protocol you were using, and which server software you connected to?
Is this issue fixed in the current release version?
