### ISSUE TITLE
"Cannot read container configuration" due to GET /?versioning HTTP/1.1 returns 404 on some s3 storage systems

### ISSUE THREAD

**Issue by alsarins** [iterate-ch/cyberduck#13301]
Hello

We have an minio server (s3 server) installation. It doesn't support versioning in FS mode (single disk/NAS) according to this thread: https://github.com/minio/mc/issues/3370

Cyberduck is failing to browse/listing bucket, because it receives 404 on GET /?versioning request. It's appeared from debug logfile and GUI shows exception while trying to browse bucket:

Cannot read container configuration.

Is it possible to ignore disabled/suspended versioning on server side? Because we cannot enable it on server side in current mode. s3cmd (console tool) for example doesn't take it into account and successfully read/list/upload files.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/77080750/163802777-53848a89-a262-4ba5-a76e-ebb7f443e297.png">

**Comment by dkocher** [comment]
We currently expect the server to respond with one of the following HTTP status code when the feature is not supported:
-  `501 Not Implemented `
-  `405 Method Not Allowed `
-  `400 Bad Request`
-  `403 Forbidden`

**Comment by alsarins** [comment]
Hope it would not be  a big work to handle 404 please for this particular s3 server? 
I can add debug logs (but need some work to strip some info due to NDA) if it helps.
