### ISSUE TITLE
Drag 'n drop files inside Cyberduck Filebrowser is crashing Cyberduck

### ISSUE THREAD

**Issue by Crefelder** [iterate-ch/cyberduck#13315]
Everytime i do drag' n drop files from inside of the file browser of loggedin SFTP Cyberduck the program is fully hanging. Only the close button of Cyberduck is working and Windows  then asks for waiting or closing Cyberduck.
Version: 8.3.2 (37449)

**Comment by AliveDevil** [comment]
Can you send us the latest crash reports file[^1]?

[^1]: https://docs.cyberduck.io/cyberduck/support/#crash-reports

**Comment by Crefelder** [comment]
There is no CrashReporter folder in my "C:\Users\am\AppData\Roaming\Cyberduck". but after the latest update 8.3.3 (37544) its working again.

I think Cyberduck was directly freezing before at starting dragn drop (mouse down and moving a file) without doing a crash report log file.

**Comment by dkocher** [comment]
Duplicate for #13322.
