### ISSUE TITLE
freeze when uploading multiple files

### ISSUE THREAD

**Issue by numbr007** [iterate-ch/cyberduck#13322]
Cyberduck for macOS seems to lock up when uploading multiple files via FTP to certain servers, particularly those hosted on Doteasy.  Attempting to transfer multiple files via drag-and-drop to the browser window results in an endless progress bar, requiring a FORCE QUIT of the Cyberduck app.  Using Cyberduck 8.3.2 on macOS 12.3.1.  Have attempted this process for numerous different clients whose sites are hosted on Doteasy; it happens every time.

**Comment by BrainScanMedia** [comment]
I get crashes and lockups as well. I'm a web designer and when I open a connection to Ubuntu Server I get massive issues. 1. Uploading ore then 4 files HTML, JS, PHP files at once crashes CyberDuck. I have to do one file at a time. Its horrible... If I try to download a few files I get the same results... I moved on to Fetch FTP Client, its like Cyber Duck but stable.

**Comment by numbr007** [comment]
I've since seen this behavior with other web hosts as well as Doteasy. Hostmonster, for example. You HAVE to upload one file at a time, or Cyberduck just locks up. Really frustrating.

**Comment by dkocher** [comment]
Regression from ced265dc.

**Comment by dkocher** [comment]
Additionally this could be caused by #13051.
