### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by CurtisBay** [iterate-ch/cyberduck#13324]
I am receiving an error code every time I enter my username and password.

The login information never changed.

Any help would be greatly appreciated!

Thank you,
![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/104375604/165119371-048b8940-6f08-4193-a23a-42b0c797a4dc.jpg)

**Comment by tatze96** [comment]
This error appears if Cyberduck has tried every possible authentication method but none of them worked in combination with the set credentials.

Please reach out to your server administrator to check if you are using the correct credentials and if you possibly need to use an SSH Private Key in addition to your credentials to access your server.

– Laura
