### ISSUE TITLE
Downloading beyond

### ISSUE THREAD

**Issue by ariespinoteau** [iterate-ch/cyberduck#13336]
Hi, this is not the first time this happens to me. Downloading is going beyond file size and eventually never stops. I am running Cyberduck 8.3.2, connecting to conntecting to a SFTP server. Most of the time I have no problem, but sometimes this happens. 

<img width="801" alt="Capture d’écran 2022-04-27 à 13 55 10" src="https://user-images.githubusercontent.com/9935503/165513179-384f845a-1fda-494d-a1bd-4ec5b9887a76.png">

**Comment by tatze96** [comment]
Hi,

This normally occurs if connectivity issues or other errors have occurred within the transfer process.
In regard to the transfers that "never stops" we would need more information:
- Which protocol is in use?
- Does this behavior occur in combination with specific file sizes?
- Can you please [enable debug logging](https://docs.cyberduck.io/cyberduck/support/#debug-logging-level), try to download a file, and send us the log file afterward if the download never stops? If you don't like to see sensitive data to be shared publicly please send the log file with the ticket reference GH-13336 to support@cyberduck.io, otherwise, attach it here.

– Laura

**Comment by ariespinoteau** [comment]
Here is the log again. My previous email was rejected because I forgot to
zip the log!

Ariès

48°43’ N, 003°58’ W
***@***.***,-3.9666667,563m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d48.7166667!4d-3.9666667>


Le 28 avr. 2022 à 14:56:31, Ariès Pinoteau ***@***.***> a
écrit :

> Hi Laura,
>
> Thank you for reaching back. The protocol for this transfer which is
> failing is SFTP. I am doing it from a server I do use a lot and most of the
> time it is working just fine. But sometimes it doesn’t and then I have to
> do it thru rsync.
>
> It failed again this this morning. Please find the log.
>
> Thanks
>
> Ariès
>
> 48°43’ N, 003°58’ W
> ***@***.***,-3.9666667,563m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d48.7166667!4d-3.9666667>
>
>

**Comment by AliveDevil** [comment]
Sorry to bother again with attaching the log file, but GitHub really doesn't like users to reply to notifications via e-mail and attach files to them[^1] - this, for whatever reason, is only possible on the Web-interface.

[^1]: https://github.blog/2011-03-10-reply-to-comments-from-email/

**Comment by ariespinoteau** [comment]
Here it is[cyberduck.log.zip](https://github.com/iterate-ch/cyberduck/files/8629535/cyberduck.log.zip)

**Comment by ariespinoteau** [comment]
Just an idea. The issue is maybe triggered by the filename. I was about to
transfer the file with rsync, and to make it easier I did first rename it.
This I though this might be the problem and I gave another try with
Cyberduck. This time, with a simpler file name the transfer went thru with
no problem.

Ariès

48°43’ N, 003°58’ W
***@***.***,-3.9666667,563m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d48.7166667!4d-3.9666667>


Le 28 avr. 2022 à 14:58:43, Ariès Pinoteau ***@***.***> a
écrit :

> Here is the log again. My previous email was rejected because I forgot to
> zip the log!
>
> Ariès
>
> 48°43’ N, 003°58’ W
> ***@***.***,-3.9666667,563m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d48.7166667!4d-3.9666667>
>
>
> Le 28 avr. 2022 à 14:56:31, Ariès Pinoteau ***@***.***> a
> écrit :
>
>> Hi Laura,
>>
>> Thank you for reaching back. The protocol for this transfer which is
>> failing is SFTP. I am doing it from a server I do use a lot and most of the
>> time it is working just fine. But sometimes it doesn’t and then I have to
>> do it thru rsync.
>>
>> It failed again this this morning. Please find the log.
>>
>> Thanks
>>
>> Ariès
>>
>> 48°43’ N, 003°58’ W
>> ***@***.***,-3.9666667,563m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d48.7166667!4d-3.9666667>
>>
>>

**Comment by dkocher** [comment]
Duplicate for #13374.
