### ISSUE TITLE
duck crashing on MacOS 12 M1

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#13347]
[duck-2022-05-02-132826.ips.zip](https://github.com/iterate-ch/cyberduck/files/8602496/duck-2022-05-02-132826.ips.zip)

duck 8.3.3 installed with .pkg.

**Comment by AliveDevil** [comment]
Error on MacOS 11 Intel amd64:
```
Error occurred during initialization of VM
Could not reserve enough space for code cache (245760K)
```

**Comment by Cassie205** [comment]
The latest working version seems to be duck-8.2.1.36773.pkg

**Comment by dkocher** [comment]
We fixed the build job to include the [entitlements](https://github.com/iterate-ch/cyberduck/blob/master/setup/app/default.entitlements) when signing the bundle which resolves this issue.

**Comment by dkocher** [comment]
The correct entitlements should look like

```
codesign -d --entitlements - /usr/local/duck.bundle/
Executable=/usr/local/duck.bundle/Contents/MacOS/duck
[Dict]
	[Key] com.apple.security.automation.apple-events
	[Value]
		[Bool] true
	[Key] com.apple.security.cs.allow-jit
	[Value]
		[Bool] true
	[Key] com.apple.security.cs.allow-unsigned-executable-memory
	[Value]
		[Bool] true
	[Key] com.apple.security.cs.disable-library-validation
	[Value]
		[Bool] true
```
