### ISSUE TITLE
Dragging to network shared drive results in incomplete download

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#13341]
**Describe the bug**
Unexplainable error message while downloading to a network shared drive.

**To Reproduce**
Drag file onto network shared drive of macOS 10.13 target.

**Expected behavior**
No errors thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/734738/165917671-cfa17e72-677e-49f3-962e-a85a06939911.png)

**Desktop (please complete the following information):**
macOS 12, Server macOS 10.13.6
Cyberduck 8.3.3

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8589708/cyberduck.log)

**Additional context**
With 8.3.2 there have been thousands of messages generated, in 8.3.3 this is reduced to one at the end.

**Comment by AliveDevil** [comment]
This does not occur on macOS 11.

**Comment by dkocher** [comment]
Underlying error locating download target

```
2022-04-29 11:15:20,757 [Thread-39] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.BackgroundException, file=null, message='Error', detail='No such file or directory.', cause='sun.nio.fs.UnixException: No such file or directory'}
```

**Comment by dkocher** [comment]
Cannot be reproduced downloading to WebDAV mount on macOS 12.6.

**Comment by dkocher** [comment]
Relates to #13482.
