### ISSUE TITLE
Cyberduck not parseing correctly .ssh/config file

### ISSUE THREAD

**Issue by elalitarek** [iterate-ch/cyberduck#13350]
When I add entries to directly to my config file like : 

Host newjump
    HostName x.x.x.x
    User opc
    IdentityFile ~/.ssh/id_rsa

Host tobejumped
    HostName x.x.x.x
    User opc
    ProxyJump newjump
    IdentityFile ~/.ssh/id_rsa
    
 It works like charm. 
 
 But when i use the include directive like 
 
 Include /Users/tarekelali/.ssh/privssh.config
it fails to resolve the host at all.

**Comment by AliveDevil** [comment]
Missing in https://github.com/iterate-ch/cyberduck/blob/master/ssh/src/main/java/ch/cyberduck/core/sftp/openssh/config/transport/OpenSshConfig.java.

**Comment by dkocher** [comment]
Duplicate for #10451.
