### ISSUE TITLE
Freezing when downloading/uploading

### ISSUE THREAD

**Issue by ralaya** [iterate-ch/cyberduck#13356]
Whenever I try to upload or download a file from Cyberduck, it freezes then crashes. Happens also when I click on the transfers button.
I use a Windows and have version 8.2.3 at the moment. Have confirmed with others that its working ok for them.

Have tried re-starting my computer, uninstalling and re-installing Cyberduck with the latest version and also tried with previous versions. (8.3.3 and 7.10). 

It was working last week, this is a recent issue. I use Cyberduck daily for downloading/uploading files.

**Comment by AliveDevil** [comment]
Can you check whether deleting the contents of the folder `%AppData%\Cyberduck\Transfers` resolves the crashes?

**Comment by ralaya** [comment]
> Can you check whether deleting the contents of the folder `%AppData%\Cyberduck\Transfers` resolves the crashes?

It worked! thanks so much for your suggestion
