### ISSUE TITLE
Issue with LinodeS3 connections

### ISSUE THREAD

**Issue by ndeblauw** [iterate-ch/cyberduck#13355]
I upgraded to the latest Cyberduck and now my Linode Object Storage buckets (S3 compatible) are no longer working.

Found this post on the linode community that summarizes things well. Exactly the same for me
https://www.linode.com/community/questions/22274/i-updated-to-cyberduck-v820-and-now-i-cant-connect-to-my-object-storage-buckets

Regards,

Nico

**Comment by AliveDevil** [comment]
Did you check for updates? Which version of Cyberduck are you running on?
I assume the regular „Amazon S3“ profile?

**Comment by ndeblauw** [comment]
I upgraded recently to 8.3.3. (from a 8.1 version, don't remember which) and it stopped working. 
I uninstalled 8.3.3 and went back to 8.1.1. (as recommended in the linked article) and it works again now.

It's indeed an Amazon S3 profile, but with the Linode server urls and keys

**Comment by AliveDevil** [comment]
We have connection profiles for each of the linode regions, which can be installed through Preferences->Profiles[^1]
Additionally 8.2.1 should have improved Linode-support, though I'm not sure we are testing against their service.
Can you send us the log file generated after receiving the failed login attempt?[^2] (Either attached to your answer here, or with the reference GH-13355 to support@cyberduck.io).

[^1]: https://docs.cyberduck.io/protocols/s3/linode/
[^2]: https://docs.cyberduck.io/cyberduck/support/#logging-output

**Comment by ndeblauw** [comment]
Hi there,

I'm sorry, but I removed the newest version, and I didn't make a copy of the directory before that, so I cannot upload logfiles from when the issue occurred.

And I'm not really willing to reinstall it, I've lost already enough time (+1.5 hour) with this issue. But it is something you can easily check yourself I guess. Linode offers free credits (100EUR/USD) for testing purposes.

Additionally: I was not aware of specific connection profiles for Linode. Maybe it is a good idea to append the error message on the amazon S3 profile with a reference to those linode profiles (when you detect a linode url), as a hint for a solution (after you checked it worked). I'm sure many users will benefit from this, and it will avoid a lot of potential helpdesk traffic.

So far my five cents,

Nico

PS. I really appreciate the thorough follow up on this issue from your side!

**Comment by dkocher** [comment]
- Cannot reproduce with Version 8.3.3 (37537) and the _Linode Object Storage (Frankfurt, Germany)_ connection profile.
- Can reproduce with _Amazon S3_ default connection profile which leads to error message
> Login failed. Forbidden. Service Error Message. SignatureDoesNotMatch.

This is caused because querying the region gives a 403 error because the signature uses the default us-east-1 region for this request

```
GET /?location= HTTP/1.1
Date: Thu, 05 May 2022 14:07:40 GMT
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Host: eu-central-1.linodeobjects.com
x-amz-date: 20220505T140740Z
Authorization: AWS4-HMAC-SHA256 Credential=x/20220505/us-east-1/s3/aws4_request,SignedHeaders=date;host;x-amz-content-sha256;x-amz-date,Signature=x
Connection: Keep-Alive
User-Agent: Cyberduck/8.3.3.37537 (Mac OS X/12.3.1) (aarch64)
Accept-Encoding: gzip,deflate

HTTP/1.1 403 Forbidden
Date: Thu, 05 May 2022 14:07:42 GMT
Content-Type: application/xml
Connection: keep-alive
Accept-Ranges: bytes
x-amz-request-id: tx00000d0f0f3833245d3ac-006273da2e-339a506-default
Content-length: 200

<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000d0f0f3833245d3ac-006273da2e-339a506-default</RequestId><HostId>339a506-default-default</HostId></Error>
```
