### ISSUE TITLE
MacOS Dock Mouse click intercepted

### ISSUE THREAD

**Issue by MorelloCherry** [iterate-ch/cyberduck#13369]
When Cyberduck is running I have seen the issue that it intercepts mouse clicks on the Application Dock. When this issue occurs I cannot quit Cyberduck using command-q and have to force quitting it.

I am running these versions:
MacOS: 12.3.1 on Mac Pro (Late 2013)
Cyberduck: V8.3.3 (37544)

Thank you for looking into this

**Comment by dkocher** [comment]
We cannot reproduce this.
