### ISSUE TITLE
Add support for Cloudflare R2

### ISSUE THREAD

**Issue by ahrenstein** [iterate-ch/cyberduck#13376]
**Is your feature request related to a problem? Please describe.**
Cloudflare is launching a new S3 compatible object storage service called [R2](https://blog.cloudflare.com/r2-open-beta/).
Cyberduck (and Mountain Duck) should definitely add support for this new service as it has a lot of benefits over AWS S3 in different cases. (One of which being zero cost on egress)

**Describe the solution you'd like**
I'd like to see support added for Cloudflare R2 (which is currently in open beta)

**Describe alternatives you've considered**
In the meantime, I'll see if I can create a custom profile to work with R2 but long term official support would be great.

**Additional context**
There is some [official documentation](https://developers.cloudflare.com/r2/) along with the most relevant doc being the [current API implementation status](https://developers.cloudflare.com/r2/platform/s3-compatibility/api/).  
Additionally the document about [using Wrangler to create and manage buckets](https://developers.cloudflare.com/r2/get-started/) might be important.

**Comment by juliancox** [comment]
Using S3 mode I can connect to R2 and list buckets but attempting to list objects in a bucket gives the following error:
Listing directory gc-public failed.
Internal Server Error. Request Error [InternalError]. Please contact your web hosting service provider for assistance.

**Comment by AliveDevil** [comment]
Can you check whether forcing path style requests works for R2? You can enable this profile in Cyberduck Preferences -> Profiles -> search for "S3 (Deprecated path style requests)"

There is a bunch of unsupported APIs which Cyberduck may depend on ([Unimplemented object-level operations](https://developers.cloudflare.com/r2/platform/s3-compatibility/api/#unimplemented-object-level-operations)) - specifically `ListObjects`. Chances are higher if there is a Java SDK or OpenAPI specification to be implemented, though.

Cloudflare isn't that great of making sure their blog posts are accurate, though.
![image](https://user-images.githubusercontent.com/734738/168018604-eb5770a1-e963-4af3-8e66-eb1f611a4668.png)
Referring in the text to "bucket.account.r2storage.com" while the anchor links to "account.r2.cloudflarestorage.com/bucket" isn't something I'd want to see.

**Comment by juliancox** [comment]
@AliveDevil I can confirm S3 (Deprecated path style requests) profile seems to allow R2 connections to work as expected I can list buckets, download and upload files without any problems.  

Cloudflare docs do leave a lot to be desired - sigh!

**Comment by deepybee** [comment]
Yep I've also managed to get R2 working as desired with path style access 👍

**Comment by AliveDevil** [comment]
Hint for the deprecated path style was this sample for the aws-sdk-js[^1], which explicitely forces the client to use path style.
```
  s3ForcePathStyle: true,
```
[^1]: https://developers.cloudflare.com/r2/examples/aws-sdk-js/

**Comment by AliveDevil** [comment]
@juliancox @deepybee 
Can one of you let me know what Cloudflare returns for a location request?
```
GET https://account.r2.cloudflarestorage.com/bucket/?location
```

**Comment by dkocher** [comment]
> @juliancox @deepybee Can one of you let me know what Cloudflare returns for a location request?
Querying the bucket location is not supported

```
<Error><Code>NotImplemented</Code><Message>GetBucketLocation not implemented</Message></Error>
```

**Comment by dkocher** [comment]
it is not clear how to make objects publicly available

- Pre-signed URLs do not work
- ACLs on buckets or files don't seem to be supported

**Comment by juliancox** [comment]
At this stage R2 buckets are private only.  The only way to make them public seems to be via a cloudflare worker.  There is a public access setting under the bucket's settings tab on the cloudflare dashboard but this says "Private - This bucket and its objects are only visible to users, Workers, or services that have been granted explicit access. It is not publicly visible on the Internet." with not option to make it public.  The learn more link just after leads to this page: https://developers.cloudflare.com/r2/get-started/#6-bucket-access-and-privacy
Which describes making a bucket public via workers but no details on how to make the bucket itself public.  It looks like this is a planned option but something available yet while R2 still has the 'beta' tag.

**Comment by raramuridesign** [comment]
Is there any documentation on how to setup R2 on Cyberduck?

**Comment by georgeboot** [comment]
So how is this supposed to work? When using the "Cloudflare R2 Storage (S3)" profile, I entered `{account-id}.r2.cloudflarestorage.com` as the server, and my access key and secret in the respective fields.

When opening the connection, I get the following error:

> The request signature we calculated does not match the signature you provided. Check your secret access key and signing method

What goes wrong?
