### ISSUE TITLE
Error: Maximum allowed connections exceeded. Waiting

### ISSUE THREAD

**Issue by birdbreath** [iterate-ch/cyberduck#13372]
What does this mean? I just appeared this morning. How do I remedy it?
<img width="560" alt="Screen Shot 2022-05-09 at 12 55 21 PM" src="https://user-images.githubusercontent.com/72421806/167513726-569c4d8d-a317-4248-95fb-7abd35396256.png">
.

**Comment by Cassie205** [comment]
It is possible that your server only allows a limited number of concurrent connections. Please change the setting within Cyberduck preferences Transfers from "Open multiple connections" to "Use browser connection" or "Open single connection" and retry to upload the file.
