### ISSUE TITLE
Hangs when listing directory

### ISSUE THREAD

**Issue by xzachx** [iterate-ch/cyberduck#13370]
I've been running into an issue since upgrading to 8.3.3 recently where Cyberduck starts chewing up all available CPU on my machine and seems to hang when trying to list a directory. I'm running MacOS Big Sur version 11.6.4 and this was working fine until recently. Any ideas what the issue might be?

**Comment by tatze96** [comment]
Does this behavior occur in combination with a specific protocol? Does the affected directory contain many (1000+) files?
