### ISSUE TITLE
Detect disabled ACLs for S3

### ISSUE THREAD

**Issue by ylangisc** [iterate-ch/cyberduck#13386]
> Amazon S3 Object Ownership can now [disable access control lists](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/) to simplify access management for data in S3

Cyberduck should be able to detect buckets with ACLs disabled to avoid sending any default ACL which would result in the following error otherwise:
```
The bucket does not allow ACLs.
```

It should not be necessary to set the default ACL to _None_ if there is no IAM policy preventing Cyberduck from reading the bucket ownership configuration.

Also refer to:
* https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketOwnershipControls.html
* https://github.com/iterate-ch/docs/issues/195

**Comment by dkocher** [comment]
Addendum in #13496.

**Comment by Fydon** [comment]
I'm still getting `The bucket does not allow ACLs` when moving files from one bucket to another. The destination bucket has disabled ACLs but the source does not.
