### ISSUE TITLE
Can't download a file with emoji (🚀) in its name from S3

### ISSUE THREAD

**Issue by gdubicki** [iterate-ch/cyberduck#13407]
**Describe the bug**

While trying to download a file with an emoji (🚀) in its name, I am getting the following error:

```
Download test-foobar-2022-05-17-BB:10204-🚀4.8.1-1e8ec65-10188.backup failed.

The specified version does not exist. Please contact your web hosting service provider for assistance.
```
**Screenshots**

<img width="257" alt="Screenshot 2022-05-22 at 21 56 12" src="https://user-images.githubusercontent.com/566632/169713512-01fbc58d-425d-47cd-9102-f36266eb84ca.png">

**Desktop (please complete the following information):**

 - OS: macOS Monterey 12.3.1 (21E258)
 - Version: Version 8.2.0 (36680) (**update**: for info about behaviour on 8.3.3 see below)

**Log Files**

I would prefer not to upload this log here as it contains some sensitive information that I can obfuscate but it would take me some time. I am hoping that this bug/missing feature is easy to reproduce and this step won't be needed.

**Additional context**

The same file downloads using the AWS web UI without any issues.

**Comment by gdubicki** [comment]
Sorry, I thought that I had an up to date version of Cyberduck but I had not. After an update to 8.3.3 I am getting a different error:

```
Error

Status code: 404, reason phrase: The specified version does not exist.
```

**Comment by dkocher** [comment]
Not sure if the emoji is the issue here as the error message `The specified version does not exist` suggests there is an error retrieving this particular version.

**Comment by gdubicki** [comment]
Thanks @dkocher! But I am not specifying any specific version to download and that file doesn’t have more than one version.

**Comment by ZeroCommits** [comment]
Also does not work with OneDrive (uploading and downloading files with emoji).

**Comment by dkocher** [comment]
> Also does not work with OneDrive (uploading and downloading files with emoji).
> 
> EDIT: I am using Mountain Duck. Not sure if it is okay to add it in this thread.

Cannot reproduce with a filename `Test-🚀.txt` on OneDrive accessed using Mountain Duck or Cyberduck.

**Comment by dkocher** [comment]
Cannot reproduce on S3 albeit the filename incorrectly displays as `Test-??.txt` instead.
