### ISSUE TITLE
Implement an option to enable s3 transfer accelaration.

### ISSUE THREAD

**Issue by networkneil** [iterate-ch/cyberduck#13403]
Running Version 8.3.3 (37544). Trying to upload a 130GB folder to an s3 bucket and the transfer speed gradually goes down to zero and eventually fails to complete.

The transfer even fails on the AWS web console and even in AWS CLI, after enabling s3 transfer acceleration, it worked great on the AWS web console and in the AWS CLI.

I think adding this feature to Cyberduck will improve the transfer speeds, also, if s3 transfer acceleration is also enabled on the bucket.

This is AWS doc on AWS SDK. [Enabling and using S3 Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration-examples.html)

Thank you! :)

**Comment by networkneil** [comment]
#13359 
#13339

**Comment by dkocher** [comment]
Refer to the [documentation](https://docs.cyberduck.io/protocols/s3/#transfer-acceleration).

**Comment by networkneil** [comment]
Hello @dkocher,

I'm unable to find the option on my side here.
![image](https://user-images.githubusercontent.com/64820853/169591007-57163fee-ec4d-4936-b335-c252dba831ec.png)

Please let me know if im missing anything.
The transfer acceleration is working when used with AWS CLI.

**Comment by dkocher** [comment]
You can toggle transfer acceleration for a bucket in the [Info](https://docs.cyberduck.io/cyberduck/info/#amazon-s3-panel) panel. Not that when enabled for a bucket, transfer acceleration will be used transparently when #13359 is resolved.

**Comment by networkneil** [comment]
Understood, thank you for your explanation and contribution.

**Comment by yellowtailfan** [comment]
The info panel only seems to be enabled after selecting a file in the bucket. Is there some way to enable transfer acceleration on an empty bucket?

A work around is to upload a dummy file, select the file, click Info, then enable Transfer Acceleration.
