### ISSUE TITLE
Problem using Cyberduck

### ISSUE THREAD

**Issue by LadyLincoln** [iterate-ch/cyberduck#13406]
I really don't have time or desire to continue having this problem.  I loved CyberDuck and this bug is just about ending my use of Cyberduck.

```
Failed to parse XML document with handler class org.jets3t.service.impl.rest.XmlResponsesSaxParser$ListBucketHandler.  Please contact your web hosting service provider for assistance
```

**Comment by dkocher** [comment]
Please try the connection profile _S3 (Deprecated path style requests)_ available from _Preferences → Profiles_.

**Comment by screencomuser** [comment]
Thank you, this helped me a lot.

Just tested this in Version 8.3.3 with CloudVPS Openstack (Dutch hosting, part of TransIP)

**Comment by elias-ik** [comment]
How would this profile work with HTTP (instead of HTTPS)?
