### ISSUE TITLE
Bonjour installation is not optional, can't be removed via normal means

### ISSUE THREAD

**Issue by savchenko** [iterate-ch/cyberduck#13416]
**Describe the bug**
Bonjour installation isn't optional anymore, it can't be removed manually from "Apps & Features" or a "classic" Control panel.

**To Reproduce**
1. Download `Cyberduck-Installer-8.3.3.37544.exe`
2. Try to install without Bonjour
3. Realise it's not optional, try to uninstall the Bonjour without wiping the Cyberduck

**Expected behavior**
Make Bonjour optional as per https://github.com/iterate-ch/cyberduck/commit/ee952d1d7a596b94a38ed0568c11f13564940dff and allow it to be uninstalled as per https://github.com/iterate-ch/cyberduck/issues/10850

**Screenshots**

#### Cyberduck installed
![image](https://user-images.githubusercontent.com/300146/170925557-f1c9db40-8497-4e25-af05-41ad9bdf72de.png)

#### Installer option~~s~~
![image](https://user-images.githubusercontent.com/300146/170925803-437d5967-b9b1-4b00-83d7-95c7db455832.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Version: 10.0.19044 Build 19044

**Log Files**
N/A

**Additional context**
See the linked issue & commit.

**Comment by leifcr** [comment]
This was originally fixed in #5563 back in 2010, but has sneak back it seems

**Comment by AliveDevil** [comment]
After merge Bonjour is removed automatically through auto-update. Installing Bonjour requires either running the installer again with the Bonjour checkbox selected (default), or installing Bonjour manually.

**Comment by AliveDevil** [comment]
Reviewed this, new behavior will be:
- Bonjour is opt-out (Options -> Bonjour checkbox)
- On Update, the installer checks for an existing Bonjour installation, and keeps the installation alive
- If Bonjour is removed after Cyberduck got installed, any future update won't install Bonjour again
- After merge the update should make Bonjour visible in Programs & Features
- For automated installations the property `Cyberduck-Installer.exe InstallBonjour=0` can be used.
