### ISSUE TITLE
Unable to choose anonymous login

### ISSUE THREAD

**Issue by saiprasanna06** [iterate-ch/cyberduck#13413]
1. I have downloaded the latest version of Cyberduck, I need to download data from Amazon S3. But I am unable to choose anonymous login

2. I downloaded version 5 of cyberduck, which allowed me to do anonymous login, But it says, the specified bucket is not valid, but i am sure the bucket exists and is valid. 

Please kelp me

**Comment by nk9** [comment]
I'm trying to connect to the anonymous [NARA 1940 census](https://registry.opendata.aws/nara-1940-census/) S3 server. 
The "Anonymous login" checkbox is always dimmed, however, just as described by OP here. I'm on Cyberduck 8.7.1 (40770) on macOS Sonoma 14.1.2.

I tried the solution suggested by @dkocher, but using credentials when connecting to the anonymous server failed.

I have ultimately been able to check the box by following these instructions from [2018](https://groups.google.com/g/cyberduck/c/ssqiLomy7Xg)(!!). I don't see how this issue could be classed is an enhancement, when the anonymous login feature is there but incorrectly disabled. The Google Groups poster says that this used to work but then stopped. It may be a longstanding bug, but it's still a bug. Hopefully this is straightforward to fix.

**Comment by nk9** [comment]
It seems like the solution is just to add this code (taken from [FTPProtocol.java](https://github.com/iterate-ch/cyberduck/blob/7f4450cea4827fb4ee052d5a9dcfe04ca3419cb6/ftp/src/main/java/ch/cyberduck/core/ftp/FTPProtocol.java#L27)):

```
    @Override
    public boolean isAnonymousConfigurable() {
        return true;
    }
```

To this [S3Protocol.java](https://github.com/iterate-ch/cyberduck/blob/7f4450cea4827fb4ee052d5a9dcfe04ca3419cb6/s3/src/main/java/ch/cyberduck/core/s3/S3Protocol.java#L46).

**Comment by dkocher** [comment]
To be resolved with [^1].

[^1]: iterate-ch/profiles#76

**Comment by nk9** [comment]
Thanks for the super-quick turnaround!
