### ISSUE TITLE
problem with cyberduck

### ISSUE THREAD

**Issue by canineprod** [iterate-ch/cyberduck#13410]
The application does not work properly anymore. It always asks me if I want to "clean the list" (in french) then gets stuck. I tried to uninstall then reinstall the program, it's always the same. 
What can I do? I need to take my files from Hubic.

**Comment by AliveDevil** [comment]
Can you check whether deleting all files in `%AppData%\Cyberduck\Transfers` resolves the issue?

**Comment by canineprod** [comment]
I tried to find the file you mention but, as you can see on the picture, it
does not seem to exist.
Philippe DORISON  / 06 86 88 79 17


Le mer. 25 mai 2022 à 09:18, Jöran Malek ***@***.***> a
écrit :

**Comment by AliveDevil** [comment]
Github unfortunately doesn't allow embedding images or attachments to emails, can you edit the message above in the Github web interface and embed your screenshot there?

**Comment by canineprod** [comment]
![cyberduck](https://user-images.githubusercontent.com/106063040/170220973-b4e8d45d-ddfc-4d8c-ba7d-f1b687978465.jpg)

**Comment by AliveDevil** [comment]
You can copy&paste everything (including `%AppData%`) into the address bar of the Windows file explorer.

**Comment by canineprod** [comment]
no such file nor folde
![cyberduck 2](https://user-images.githubusercontent.com/106063040/170224124-4cc3433f-2cc2-4d92-9533-f96ed7938cde.jpg)
r

**Comment by AliveDevil** [comment]
Please do not copy the path into the search-field of the file explorer, instead paste into the path-field:
![image](https://user-images.githubusercontent.com/734738/170224649-ce08dbe5-ec9a-42ba-b187-d6f955ffdbcc.png)

**Comment by canineprod** [comment]
Ok, I found the files and deleted them. 
I will make a mew try with cyberduck in a moment, can't do it right now.

**Comment by canineprod** [comment]
It seems to work, for the moment. But it is still a very slow transfer !

**Comment by AliveDevil** [comment]
Slow Transfers aren‘t on Cyberducks side of things.
The ToS of hubiC mention a bandwidth limit of 10 Mbits.[^1][^2] This roughly equates to 1 Mbyte/s of transfer speed excluding protocol overhead, so half that is realistically usable.

[^1]: https://hubic.com/de/contracts/Contrat_hubiC_2014.pdf
[^2]: https://www.reddit.com/r/DataHoarder/comments/4o9tm2/psa_hubic_is_now_limited_to_10mbps_transfer_speeds/

**Comment by AliveDevil** [comment]
And safer, than a service with unknown future.
