### ISSUE TITLE
Uploads don't populate in transfer window (newer versions)

### ISSUE THREAD

**Issue by tinkl014** [iterate-ch/cyberduck#13423]
In the newer versions, uploads only show in the bottom gray bar of the app window, rather than populating in the transfer window as they used to. I move a large number of files in parallel-running connections so I had to resort to downloading an older version of the software to see the separate jobs progress in the transfer window. It is working as it should in version 7.9.

**Comment by AliveDevil** [comment]
There is a setting in the Preferences connection tab "Transfer files". If that is set to "Use browser connection" then transfers won't be listed in the transfers window.
Setting that to either Single Connection or multiple connections will result in transfers being added to the transfers window.
