### ISSUE TITLE
Feature request: Customize "Copy URL" domain option for Backblaze B2

### ISSUE THREAD

**Issue by joethephish** [iterate-ch/cyberduck#13422]
**Is your feature request related to a problem? Please describe.**
We use Backblaze B2 for asset storage and frequently use it to share large files either with coworkers or publicly. However we have a custom subdomain mapped from `f000.backblaze.com` to `assets.ourdomain.com` so it looks like the files are stored directly on our server.

Cyberduck has a great way to right click -> Copy URL -> HTTPS URL, but unfortunately I always have to paste this into a plain text editor and edit the URL by hand every time so it points to our custom domain.

**Describe the solution you'd like**
I'd love to have a feature that lets you customise the custom domain URL of a server, perhaps in the "More Options" section of a bookmark?

**Describe alternatives you've considered**
- My current solution is to edit the URL in a text editor
- I've considered trying to find a tool that monitors the clipboard and find/replace automatically but (1) I haven't actually found a good way to do this and (2) it's not good for suggesting to coworkers!
- I've considered making a very simple app that when I click it on my computer it modifies the clipboard. Also not great.
- Yes, I could just use the `f000.backblaze.com` URL directly but 🤢

Thank you!

**Comment by tatze96** [comment]
You can achieve the custom URL by setting the URL prefix within the *Web URL* field of the bookmark configuration window.

Example:
You've set your Bookmark to:
- Path: Bucket that is published by `assets.ourdomain.com`

Then the *Web URL* you need to set within the corresponding field to achieve the mentioned URL would be:
- Web URL: `https://assets.ourdomain.com`
