### ISSUE TITLE
AUTO CLOSE DOWNLOAD WINDOW

### ISSUE THREAD

**Issue by xamonix** [iterate-ch/cyberduck#13439]
Hi

how about on option in preferences to **autoclose** the download/upload window. 
A button to clean the download history would also be great.

Thanks for the nice software...
Best regards, 
Sérgio Miranda

**Comment by AliveDevil** [comment]
Hi, there is an option in the Transfers-tab in the preferences called "Close window when transfer completes".
If you want to automatically remove those completes transfers tick "Remove when transfer completes".
You can select all transfers using Ctrl+A/Cmd+A then using the Remove-option in the toolbar to clear out all selected transfers.
