### ISSUE TITLE
Not connecting to SFTP 

### ISSUE THREAD

**Issue by jessicasimonson** [iterate-ch/cyberduck#13436]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
It spins at SFTP connection and then after awhile says "failure to connect" I have tried various wifi sources. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by wtw** [comment]
Guess, this is duplicated by #13442, which contains more info about the potential cause of this issue.
