### ISSUE TITLE
S3 or Digitalocean Spaces not connect due to wrong x-amz-date in header

### ISSUE THREAD

**Issue by supersuphot** [iterate-ch/cyberduck#13454]
My PC use Buddhist calendar (B.E.) year which current year is 2565.
When I connect to Digitalocean Spaces the error say Forbidden. RequestTimeTooSkewed

I see the error detail notice that `x-amz-date` in header use B.E. year instead of A.E.
I try change region format on my PC from B.E. to A.E. and re-install cyberduck but the year in `x-amz-date` doesn't change

![2022-06-10_223203](https://user-images.githubusercontent.com/3018710/173101381-74b03755-9fe3-4b80-8957-a50482866823.png)

**Comment by AliveDevil** [comment]
Thank's for reaching out. According to the screenshot only our s3-library is not converting to gregorian calendar correctly (as both the request date and response date are formatted correctly).

**Comment by supersuphot** [comment]
> Thanks for reaching out. According to the screenshot only our s3-library is not converting to gregorian calendar correctly (as both the request date and response date are formatted correctly).

Yes, only `x-amz-date` is not correct. I'm using version 8.3.3 (37544) on Windows 10 OS build 19044.1706

Thanks
