### ISSUE TITLE
Cache Limit and Expire Time

### ISSUE THREAD

**Issue by thespillmonkey** [iterate-ch/cyberduck#13456]
A few years ago, Cyberduck said cache limits/times were coming for version 4. 
Are these almost here? They are the last piece to the puzzle to put you fully ahead of other apps like RAIdrive (who has this feature)
At least give us a way to limit the time folders can be cached so that we can have a buffer, but if not used for several hours/days, they are deleted.

**Comment by dkocher** [comment]
Duplicate for #10739.

**Comment by dkocher** [comment]
This can be tested in the latest snapshot build of Mountain Duck 4.12.

**Comment by thespillmonkey** [comment]
Thank you. The options are very limiting though. Can we have the ability to set out own cache? I need a 1 or 2TB cache configured to expire every 2 days. The highest is only 10gb and the time jumps from 1 day to 7 days. That is rather small.  Thank you!

**Comment by dkocher** [comment]
> Thank you. The options are very limiting though. Can we have the ability to set our own cache and timeouts?
> 
> I need a 2TB cache configured to expire every 2-3 days. The highest is only 10gb and the time option jumps from 1 day to 7 days. That is rather small and a strict range. Thank you!

Thanks for the feedback. We will extend the available options.
