### ISSUE TITLE
Error message every time when downloading directly to mounted SMB volume

### ISSUE THREAD

**Issue by fripsen** [iterate-ch/cyberduck#13482]
Error message after downloading files from any FTP-Server directly to a NAS-folder (connected over smb).

The file-transfer runs up to 100% and then prompts every time with an error message like "No such file or directory." or "File exists." or some weird symbols (see screenshots attached). When downloading a single file it always prompts with error-message "Resource temporarily unavailable.".

Only happens when downloading directly to a NAS-folder. 
Downloading to local harddrive/ssd is no problem.
When NAS is connected over AFP-protocoll it is no problem/error message.
Problem occurs on all NAS-Systems connected over smb (QNAP TVS-871 / QNAP TS-1673 / QNAP TS-833).

Tested and reproduced on several iMacs (24", M1, 2021)
macOS Big Sur 11.6.4 and 11.6.7 - SMB v3.1.1
latest Cyberduck version 8.3.3 
Logfile attached

Strangely on a MacBook Pro 13.3'' 2020 i5  with macOS Sierra 10.12 the download directly to smb-NAS works flawless with no error.

![Bildschirmfoto 2022-06-16 um 15 29 21](https://user-images.githubusercontent.com/49317804/174084036-a7f77597-ac16-4a55-9bb9-313200736fb9.jpg)
![Bildschirmfoto 2022-06-16 um 15 30 37](https://user-images.githubusercontent.com/49317804/174084041-91e469dc-8fd5-4afa-8599-4f1c1335f362.jpg)
![Bildschirmfoto 2022-06-16 um 15 40 02](https://user-images.githubusercontent.com/49317804/174084042-528701fd-c77b-4ce5-b0df-aa506d494870.jpg)

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8925701/cyberduck.log)

**Comment by tatze96** [comment]
I can't reproduce the described behavior within the current *Snapshot* version 8.4.3.
Does the described download behavior persist within the latest *Snapshot* version on your side?

– Laura

**Comment by fripsen** [comment]
Hey Laura,

issue 

> I can't reproduce the described behavior within the current _Snapshot_ version 8.4.3. Does the described download behavior persist within the latest _Snapshot_ version on your side?
> 
> – Laura

Hey Laura,
thanks for testing and asking. The issue still exists. We will wait for 8.4.4 and test it again.

**Comment by dkocher** [comment]
@fripsen Can yo still reproduce with version _8.4.4_?

**Comment by fripsen** [comment]
@dkocher yes, just testet it with 8.4.4 it still prompts with an error message

**Comment by fripsen** [comment]
@dkocher  tested a download with v. 8.5.5 on a smb-drive and it seems to be working fine.
