### ISSUE TITLE
8.4.0 crash at launch on Catalina

### ISSUE THREAD

**Issue by jpmelko** [iterate-ch/cyberduck#13525]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

**Describe the bug**
See title

**To Reproduce**
Updated or installed by App Store
Launch it

**Expected behavior**
Launched

**Screenshots**

**Desktop (please complete the following information):**
 Catalina 10.15.7 updated

**Log Files**
Can't launch it
**Additional context**
[Cyberduck_2022-06-29-142800_Bacchus.crash.zip](https://github.com/iterate-ch/cyberduck/files/9010486/Cyberduck_2022-06-29-142800_Bacchus.crash.zip)

**Comment by dkocher** [comment]
Duplicate for #13521.
