### ISSUE TITLE
Open in Terminal does not work with actual Cyberduck Mac App Store Version

### ISSUE THREAD

**Issue by G0nz0666** [iterate-ch/cyberduck#13542]
See Screenshot.
<img width="409" alt="Bildschirmfoto 2022-07-05 um 12 22 15" src="https://user-images.githubusercontent.com/108730505/177307337-e8390229-c0cf-46c0-8ed3-2bca3184c10a.png">

**Comment by dkocher** [comment]
Duplicate for #7664. Unfortunately we are not aware of a workaround.
