### ISSUE TITLE
[Windows 10] Custom editor application selection not working

### ISSUE THREAD

**Issue by shayaknyc** [iterate-ch/cyberduck#13543]
Been using cyberduck on windows 10 for a few years now, and I used to have sublime text as the default editor and I had "Always use this application" checked ON.

Now, when I try to edit a file with sublime text, it doesn't appear at all on the list of applications to edit with, and the default was replaced by the default app for that file extension on my comp.

I tried manually adding sublime text, but it doesn't save the application in the list at all. I even tried loading Cyberduck as an Administrator and adding sublime text, and it doesn't add nor persist the setting. Any ideas?

**Comment by dkocher** [comment]
Duplicate for #13541.
