### ISSUE TITLE
Cannot choose a default editor in Windows

### ISSUE THREAD

**Issue by jasonwuwrf** [iterate-ch/cyberduck#13541]
**Describe the bug**
When choosing a default editor it does not set properly, it goes through the actions of allowing you to choose an editor but it is never used.

**To Reproduce**
1. Click on **Edit**
2. Click on **Preferences**
3. Click on **Editor** tab
4. Click on **Choose...**
5. Select new editor (i.e. **notepad++.exe**
6. Click **Open** button

**Expected behavior**
After choosing the default editor would expect it to be available in right click of files, downloads, etc.  The previous preference of editor was eliminated during the upgrade.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.4.1

**Additional context**
Problem appeared with the 8.4.1 version.

**Comment by jasonwuwrf** [comment]
Also attempted to set the default editor preference with "run as administrator" option and there was no difference.

**Comment by tonyzzz321** [comment]
This bug was introduced in 8.4.0. Might be related to #12802.

**Comment by AliveDevil** [comment]
As we are using Windows internal methods of resolving the default application to open/edit a file with, there is no way for us to use a default-application - that tab probably should've been deleted.

Would you be fine with using a solution like Right click -> Edit -> Open With, which then can be set as the default handler on your system?

**Comment by dkocher** [comment]
The expected behaviour is
 * Use the default editor set in _Preferences → Editor_ when no file association is set for the given file type unless
 * _ Always use this application_ is selected, then disregard any file type association in Windows or macOS but always use the selected editor.
