### ISSUE TITLE
Avoid retries for DelayedHttpEntity

### ISSUE THREAD

**Issue by ylangisc** [iterate-ch/cyberduck#13568]
In https://github.com/iterate-ch/cyberduck/blob/master/webdav/src/main/java/ch/cyberduck/core/dav/DAVWriteFeature.java#L118-L130 we resend the initial `PUT` with a removed header. As we are completely stream based that leads to an empty stream causing zero bytes files uploaded for transfer with an unknown length (-1).

In case of known length we set a `Content-Length` header >0 but have an empty output stream causing the upload to hang.

**Comment by dkocher** [comment]
Regression from bad8784b778b317a760a41ca641126629dd12288.
