### ISSUE TITLE
s3service.s3-endpoint-virtual-path property in the profile is ignored by the S3 client

### ISSUE THREAD

**Issue by osheinin** [iterate-ch/cyberduck#13561]
The 8.3.3 version of cyberduck is working fine with the property **s3service.s3-endpoint-virtual-path** enabling my service to work. But in 8.4.1 version this feature has broken and the listing has failed due to the lack the path in the HTTP request.

**To Reproduce**
Use Oracle S3 cyberduck profile and add the following properties to the configuration:
```
       <key>Properties</key>
        <array>
            <string>s3service.s3-endpoint-virtual-path=/your/endpont/at/the/server</string>
        </array>

```
Use this profile to create a connection, observe the error.
It is expected that the list of the buckets appeared, but the following error is happening:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/3050279/178439122-73cc8085-38af-46ba-a22a-79136ff7904a.png">

It is happening on MacOS 12.4

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9090820/cyberduck.log)

I have captured the messaging from the two different versions and it clearly shows that in the latest version it is not sending the right path to the server.

```
GET /odi/s3/s3/sss/buckets/?location= HTTP/1.1
Date: Tue, 12 Jul 2022 07:02:20 GMT
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Host: phoenix92207.dev3sub2phx.databasede3phx.oraclevcn.com
x-amz-date: 20220712T070220Z
Authorization: AWS4-HMAC-SHA256 Credential=adminb67fbedd40994a177ed1190f0bca598b/20220712/us-east-1/s3/aws4_request,SignedHeaders=date;host;x-amz-content-sha256;x-amz-date,Signature=665d85dbe7d0150798ab9b360ba8f6a6c58f2daa1c968f94f5060548d873b07b
Connection: Keep-Alive
User-Agent: Cyberduck/8.3.3.37544 (Mac OS X/12.4) (aarch64)
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Content-Type: application/xml
Content-Length: 71
```
and
```
GET /?location= HTTP/1.1
Date: Tue, 12 Jul 2022 07:06:55 GMT
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Host: phoenix92207.dev3sub2phx.databasede3phx.oraclevcn.com
x-amz-date: 20220712T070655Z
Authorization: AWS4-HMAC-SHA256 Credential=adminb67fbedd40994a177ed1190f0bca598b/20220712/us-east-1/s3/aws4_request,SignedHeaders=date;host;x-amz-content-sha256;x-amz-date,Signature=56e574206138cfacf49ac3ac10abcae2e547012a5153ddfa401847abfe812a11
Connection: Keep-Alive
User-Agent: Cyberduck/8.4.1.38006 (Mac OS X/12.4) (aarch64)
Accept-Encoding: gzip,deflate

HTTP/1.1 200 OK
Last-Modified: Thu, 17 Feb 2022 17:39:22 GMT
Content-Type: text/html
Accept-Ranges: bytes
Content-Length: 51

<html>
  <body>Server is running...
</body>

```

**Comment by dkocher** [comment]
Regresssion from c8c85d2c.

**Comment by dkocher** [comment]
Can you let me know where we have this property documented? With the latest version, you can use the `Context` property in the [connection profile](https://docs.cyberduck.io/protocols/profiles/#technical-file-format-specification) instead.

**Comment by osheinin** [comment]
I found this property by digging into the different S3 profiles and the source code of the application. Not sure if it is documented somewhere. 
I guess I can try to use the Context property as follows:
```
        <key>Context</key>
	<string>/odi/s3/s3/sss/buckets</string>
```
is it right?

**Comment by osheinin** [comment]
It works, thank you.
