### ISSUE TITLE
Cyberduck Issue After the Latest Update

### ISSUE THREAD

**Issue by gasoline3** [iterate-ch/cyberduck#13577]
Hi,

After installing the latest update to the Cyberduck FTP client software, an error message comes up: 

Connection failed

DNS lookup for XYZ failed. DNS is the network service that translates a server name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing access to the network.

Is there any solution to this? I might try using another brand of FTP client.

**Comment by AliveDevil** [comment]
Please check that there are no DNS invalid characters in the server-field (that is protocol (separated by `://`), username (parts before `@`), password information ( `username:password@`), no path).
The server-field should contain `name.tld.domain` only. If you verified that there is only a server name in the server field please send us the outlined [support files](https://docs.cyberduck.io/cyberduck/support/).
