### ISSUE TITLE
Download from local S3 Bucket is not working in the latest version

### ISSUE THREAD

**Issue by Bjoerntr** [iterate-ch/cyberduck#13572]
we have a local s3 bucket and with the latest version i cannot dowload files anymore.

with version
![image](https://user-images.githubusercontent.com/109284838/178970113-b1194702-450d-45e7-bbb5-60de4d2f9ac4.png)
the transfer is incomplete.

reverting to version 
![image](https://user-images.githubusercontent.com/109284838/178969846-5fc45f96-4566-42c9-be4c-41e730b5befa.png)

![image](https://user-images.githubusercontent.com/109284838/178970028-6b462f0f-388e-4347-8491-12806c6a49c4.png)
i can download

checked also version 8.4.0 
Download incomplete

**Comment by kirilyer** [comment]
I'm also experiencing a similar problem with S3.

Here, I have a suspicion that it is related to how S3 treats compressed files, in my case they were written using AWS Firehose.

I managed to reproduce the problem with simple AWS CLI commands:
I created a text file with random strings and created a copy of it which I compressed, then I uploaded it to S3 using the following commands:
```
# uploading the regular text file
aws s3 cp test.txt s3://some-bucket/path/

# uploading the compressed file without special flags
aws s3 cp test_compressed.txt.gz s3://some-bucket/path/

# uploading the compressed file and telling S3 it is a compressed file
aws s3 cp --content-type text/plain --content-encoding gzip test_compressed_with_content_encoding_gzip.txt.gz s3://some-bucket/path/
```

This is the transfers window from Cyberduck:
![Untitled](https://user-images.githubusercontent.com/16389302/183604998-69baa983-6bea-4a5d-bcdd-11a50e6fb907.png)

First two files downloaded without problems.
The third says it's failed although the file is downloaded and is complete and opens without problems.

Note the transfer size of the third file - it seems that either Cyberduck or, more probable, S3 itself uncompresses the file on retrieval and thus the _downloaded_ size is bigger than the size that S3 initially reports for the compressed file which makes Cyberduck think that the download is incomplete.

I know that S3 behaves like that when downloading compressed files from the web console but it didn't seem to be an issue until the latest versions of Cyberduck.

**Comment by dkocher** [comment]
This is related to #12767.

**Comment by dkocher** [comment]
Can you confirm the downloaded file will be the original uncompressed file.

**Comment by dkocher** [comment]
@Bjoerntr Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output) and reopen the issue. You can reach the logging output in Preferences → Connection.
