### ISSUE TITLE
Can't download individual files from S3 bucket

### ISSUE THREAD

**Issue by sg-chris** [iterate-ch/cyberduck#13586]
- Cyberduck version 8.4.2 (38090)
- OS - macOS 12.4

## Summary

I am able to download directories and multiple files from an S3 bucket but am **unable** to download **individual files** (from the same S3 bucket) using Cyberduck.

## Details

Steps

1. Connect to the S3 bucket
2. Select a directory/ folder
3. `Right click > Download`

Result - directory (and enclosed files) download successfully

1. Connect to the S3 bucket
2. Select a file
3. `Cmd + click` a second file
4. `Right click > Download`

Result - files download successfully

1. Connect to the S3 bucket
2. Select a file
3. `Right click > Download`

Result - **Error**

![Screenshot 2022-07-18 at 17 44 59](https://user-images.githubusercontent.com/59608498/179561296-11653fb2-22b3-46d1-9e04-2a10f3052b4d.png)

**Comment by sg-chris** [comment]
OK, turns out this was a permissions issue. Comment from a dev we're working with:

> Basically Cyberduck didn’t know which AWS region the S3 bucket was in. Whilst S3 buckets have to have globally unique names, they still physically reside in a region - for us that is eu-west-2. Adding the GetBucketLocation permission to your AWS user allowed Cyberduck to ask AWS what region it was in - so it was a permissions issue, but masked by the resulting error of the lack of permission. 

Maybe this is now a request for better error messages in this scenario.

**Comment by dkocher** [comment]
Make sure the IAM user has the permission `s3:GetBucketLocation` to read the bucket location. We should actually handle this with the `S3BucketRegionRedirectStrategy` [^1]

[^1]: https://github.com/iterate-ch/cyberduck/blob/master/s3/src/main/java/ch/cyberduck/core/s3/S3BucketRegionRedirectStrategy.java
