### ISSUE TITLE
connection fails using .pem that is in keychain?

### ISSUE THREAD

**Issue by rbelew** [iterate-ch/cyberduck#13597]
**Describe the bug**

connection to EC2 instance fails using .pem that is in keychain.  This despite:

- being able to make the same connection using cyberduck (v.8.4.1) on a different OSX (10.15.7) machine
- being able to make connection with a different EC2 instance using this same machine (8.4.2, 12.4)

i have also tried it after explictly adding the .pem file to my keychain via `security import *PEMFILE* -k ~/Library/Keychains/login.keychain`

i attach a log file showing all entries from when i try to connect, forward.

**To Reproduce**

1. Create new bookmark with IP and location of .pem 
2. Double-click bookmark
3. Get "connection fail" message

**Expected behavior**
i expect it to connect as it has on other machine connecting to same EC2 instance, and as it has with this machine to other EC2 instances.

**Desktop (please complete the following information):**
 - OS:  OSX 12.4
 - Version: 8.4.2

**Log Files**

[cyberduck-ec2fail-edit.log](https://github.com/iterate-ch/cyberduck/files/9169466/cyberduck-ec2fail-edit.log)

**Comment by dkocher** [comment]
The connection attempt fails with 

```
2022-07-21 18:50:00,194 [sshj-Reader-/*IP*:22] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (reason=PROTOCOL_ERROR, msg=Too many authentication failures)
2022-07-21 18:50:00,194 [sshj-Reader-/*IP*:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Too many authentication failures
```

This should be resolved with recent changes for authentication attempts with SSH connections.
