### ISSUE TITLE
Cyberduck cannot upload

### ISSUE THREAD

**Issue by Tikire** [iterate-ch/cyberduck#13598]
All I did was switch computers. Sold my old dual core intel Mac and replaced it with an M1 Mac mini. Downloaded the new version of Cyberduck, entered my FTP server data which is the same as always, now Cyberduck just hangs, gives up (time out), only lists the directory, buy cannot delete, upload, overwrite, nothing. My server IT guy told me to leave it as insecure FTP and still nothing.

**Comment by tatze96** [comment]
Please share the following information:
- Does the upload issue persist within the current Cyberduck release version (8.5.9)?
- Do you get error messages?
- Do you use the App Store version of Cyberduck or the standalone version from the website?
