### ISSUE TITLE
Sort directories/folders first

### ISSUE THREAD

**Issue by galbaras** [iterate-ch/cyberduck#13603]
I use Windows Explorer and FileZilla, and both of them display directories/folders first, and then files, which makes navigation down the file tree quicker and easier.

Cyberduck, on the other hand, lists files and directories mixed together, sorted by one of the columns, e.g. Filename.

Please (add the ability to) sort files by type (file or directory), and then by the sort column.

**Comment by alturic** [comment]
I _believe_ (on 8.2.4 anyway) if you sort by the Kind column, it does remember sorting. I had this issue a while ago with it not remembering the sorting by that but it was fixed. :P

**Comment by galbaras** [comment]
Confirmed. Thank you so much.

I did not have the Kind column in view, and didn't think of adding it, but now that I have, it's all good. Maybe this column should be added by default and used for sorting by default?
