### ISSUE TITLE
Unable to change fingerprint on windows

### ISSUE THREAD

**Issue by kurmachu** [iterate-ch/cyberduck#13605]
**Describe the bug**
I am on windows. My server has changed fingerprint due to a reinstall. I am unable through any means to get cyberduck to change or forget the old fingerprint, even through uninstalling and reinstalling it. (Checking "always" while allowing the change does not work) I cannot locate any information as to where the windows version of cyberduck stores keys (it certainly isn't known_hosts), so I am unable to attempt to clear said file. I have tried with cyberduck as admin, too.

**To Reproduce**
1. Change a server's fingerprint.
2. Reconnect to it
3. Attempt to update the fingerprint
4. Get prompted anyway 
5. Reinstall cyberduck
6. Get prompted anyway

**Expected behavior**
The allow prompt will work, or reinstalling cyberduck will clear known fingerprints, or at least some documentation somewhere to see what cyberduck is trying to load the fingerprint from.

**Screenshots**
![image](https://user-images.githubusercontent.com/31492625/180887831-86b0bad7-0c70-4704-8741-6ec70b9b201d.png)
Not really super helpful for debugging but here's an image.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 8.4.2

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9185252/cyberduck.log)

**Additional context**

**Comment by AliveDevil** [comment]
Please update to the latest Snapshot (Preferences -> Update, Channel "Nightly"), should be fixed there.
