### ISSUE TITLE
Windows version not saving SSH host key for SFTP connection

### ISSUE THREAD

**Issue by ciwghuntress** [iterate-ch/cyberduck#13614]
## **Bug Description**
One of my users reported that they are repeatedly receiving an "Unknown fingerprint" dialog with both Cyberduck 8.4.2 and Mountainduck 4.12.1 on Windows, despite checking the "Alway" checkbox when clicking "Allow" on the dialog.  I was able to reproduce this on our own Windows systems.  I was unable to reproduce the issue in the Mac version of Mountainduck 4.12.1.

![Screen Shot 2022-07-28 at 10 46 30 AM](https://user-images.githubusercontent.com/11759393/181606617-ccbec98c-7c0d-4fe9-ab80-fd59c248c788.png)

## **Expected Behavior**
SSH host key is saved after being allowed with the "Always" checkbox checked, and user is not queried on subsequent connections

## **Current Behavior**
User is queried on connections even after allowing the SSH host key with the "Always" checkbox checked

## **Steps to reproduce**
1. Connect to a new SFTP server
2. At dialog to allow SSH host key, click "Allow" with the "Always" checkbox checked
3. Disconnect from SFTP server
4. Re-connect to SFTP server

## **Environment**
- **Version:** Cyberduck 8.4.2 / Mountainduck 4.12.1
- **Platform:** Windows
- **Connection:** SFTP

## **Debug Logs**
[mountainduck.log.zip](https://github.com/iterate-ch/cyberduck/files/9213225/mountainduck.log.zip)

**Comment by AliveDevil** [comment]
Please update to the latest Snapshot (Preferences -> Update, Channel "Nightly"), should be fixed there.

**Comment by dkocher** [comment]
In b0316bfba622e8bd3943ededd08b61ee9b6749b3.
