### ISSUE TITLE
Doesn't remember "Always" on SFTP fingerprint.

### ISSUE THREAD

**Issue by alturic** [iterate-ch/cyberduck#13621]
~~On 8.4.2, clicking Always doesn't seem to remember accepting the server fingerprint. So every time (whether same instance or on fresh Cyberduck launches) you connect to a server it asks you to Allow/Deny the Unknown Fingerprint.~~

**Fixed in 8.4.3 build.**

**Comment by GrapeBacon** [comment]
I am using a 8.4.3 via beta channel and this still isn't fixed... at least on Windows. Constantly get unknown fingerprint popups while connected to an SFTP server. Typically while downloaded, but have had it while uploading and while just idle.

**Comment by dkocher** [comment]
Duplicate for #13605.
