### ISSUE TITLE
stop prompting for password at each upload

### ISSUE THREAD

**Issue by Danny-dK** [iterate-ch/cyberduck#13623]
I found a previous issue #12374 which describes that cyberduck continuously asks for a password to upload files when you have already signed in once. That issue indicates it was fixed in 2006, any reason why it is recurring? Would it be possible to have that feature activated again to not ask for a password at upload of a file (I have save passwords and use keychain disabled for the same reasons as mentioned in previous issue), to have the password saved only for the active session? I'm using WebDAV connection.  

Cyberduck version 8.4.2 (38090)
Windows 10 (20H2 build 19042.1826)

**Comment by AliveDevil** [comment]
Does updating to the Nightly-feed resolve the issue?
(Preferences -> Update, change Release to Snapshot, check for update)

**Comment by Danny-dK** [comment]
Unfortunately not. I connect to a webdav address, provide my username and password for that webdav address, after signing in I can see my folders and data, when I upload a file to a folder I am prompted for a password again.

**Comment by dkocher** [comment]
Make sure [General → Connection → Use Keychain](https://docs.cyberduck.io/cyberduck/connection/#id22)[](https://docs.cyberduck.io/cyberduck/connection/#general-connection-use-keychain) is enabled and you choose to save the password by checking _Add to Keychain_ in the login prompt. If you choose not to save passwords, you will have to use the browser connection for file transfers to workaround by choosing _Use browser connection_ in _ Bookmark → Edit Bookmark → Transfer Files_.
