### ISSUE TITLE
Clicking "Always" doesn't save SFTP fingerprint (#13621) 8.4.3

### ISSUE THREAD

**Issue by GrapeBacon** [iterate-ch/cyberduck#13638]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
This is stated to be fixed in 8.4.3 via a closed ticket #13621 but it's still an issue.

**To Reproduce**
Connect to an SFTP server, click always to save the fingerprint. Idle or take action (download for example). Eventually get reprompted that it's an unknown fingerprint. Click always and click allow. Sometime later get prompted again for unknown fingerprint.

**Expected behavior**
Get prompted once on an unknown fingerprint when the always box is checked

**Screenshots**
screenshot added

**Desktop (please complete the following information):**
Windows 10 21H2
Windows Server 2022
Windows 11 21H2
![Untitled](https://user-images.githubusercontent.com/91326615/183303184-94686693-4810-4661-8751-930ac65800c5.png)

**Comment by alturic** [comment]
I'm the guy who you mentioned my issue, but that's interesting. I'm on 8.4.3 (38188) and it's been working fine (remembering the fingerprint).

**Comment by dkocher** [comment]
Duplicate for #13605.

**Comment by dkocher** [comment]
I am pushing a new build to the _Beta_ update feed as well.
