### ISSUE TITLE
Are you stealing dns data?

### ISSUE THREAD

**Issue by f1-outsourcing** [iterate-ch/cyberduck#13640]
I have cyberduck complaining about a dns lookup, while everything else is working fine (behind a proxy). When I capture dns traffic, I don't even see the lookup being done. So that leads me to believe that you are not using the dns configuration of the configured desktop.
Which is a highly irregular approach, for sure not standard, and mostly done in data harvesting.

**Comment by AliveDevil** [comment]
Cyberduck uses operating system native methods of resolving DNS names - there is nothing special implemented.
What type of domain is not resolveable to you?

**Comment by f1-outsourcing** [comment]
Hmmm, ok weird, I use a custom domain in the aws s3 configuration. I will try again with an ip flushdns to see if I can get it to query the dns. nslookup resolves the exact same domain without issues.
