### ISSUE TITLE
Cyberduck crashing when trying to download files

### ISSUE THREAD

**Issue by dibelm** [iterate-ch/cyberduck#13647]
Windows 10 Cyberduck is crashing every time I try to download a file properly. Seems to be functioning perfectly well until I try to carry out a file transfer.

[cyberduck_crash.txt](https://github.com/iterate-ch/cyberduck/files/9303438/cyberduck_crash.txt)

**Comment by dkocher** [comment]
The attached crash report is from running Cyberduck 6.5.0 on macOS 10.13.4.

**Comment by dkocher** [comment]
Please try upgrading to the latest version available.
