### ISSUE TITLE
I added a new server at Cyberduck now I cant open my previous one. 

### ISSUE THREAD

**Issue by isabellelas** [iterate-ch/cyberduck#13654]
I opened a new Amazon S3 server it works fine but when I tried to open another server I got access denied.  I need to open both servers simultaneously.  

It says: Listing Directory/ Failed 
Access Denied Please Contact Your Web Hosting Service Provider for Assistance

What does that mean? 

I tried everything I unistalled and installed cyberduck several times already and I still get access denied at the Amazon S3 server that I need to open.

**Comment by dkocher** [comment]
The error indicates your access credentials do not have the required permissions to list the S3 buckets in the AWS account.

**Comment by isabellelas** [comment]
Is there anything I can do to have access credentials?
