### ISSUE TITLE
cyberduck transfer window freezes on large transfers dont complete cleanly on Windows laptop

### ISSUE THREAD

**Issue by markalanmiller** [iterate-ch/cyberduck#13660]
Recently I have been having issue whereby 0.5-1GB file downloads become almost complete, the transfer progress pane shows the yellow ball. The machine prompts me with a notification the transfer is complete. But the ball never turns green, and the window remains frozen. The only way out is to quit the cyberduck application altogether. I first observed this a few weeks ago. 
[cyberduck.pdf](https://github.com/iterate-ch/cyberduck/files/9339234/cyberduck.pdf)

I am using Windows 10 Pro Build 19044.1889; 64-bit operating system, x64-based processor

**Comment by dkocher** [comment]
Duplicate for #13610.
