### ISSUE TITLE
Versions 8.4.0 through 8.4.3 crashes on Windows if started by a standart user account

### ISSUE THREAD

**Issue by jekabsbalodis** [iterate-ch/cyberduck#13672]
Cyberduck versions 8.4.0 through 8.4.3 crashes on Windows 11, if the app is started by a standard user account. Recently I noticed that the standard user account is able to launch the app as administrator, however it is less convenient that just simply launching the app as a standard user and also saved bookmarks and license does not show up.
![image](https://user-images.githubusercontent.com/18625828/185409809-88fa7a9e-4831-4067-83eb-8a3c5b0c5d4e.png)

**Comment by AliveDevil** [comment]
Please attach the latest file from `%AppData%\Cyberduck\CrashReporter`.

**Comment by jekabsbalodis** [comment]
Of course, here it is.
[637964373383821693.txt](https://github.com/iterate-ch/cyberduck/files/9392624/637964373383821693.txt)

**Comment by AliveDevil** [comment]
Interesting, I need to investigate this further.
It looks like theapp crashes on startup due to some icon not being correct.
Unfortunately the crash report doesn't contain more information, as it is the last chance to catch an error.

Which application did you register for default web browsing (that is assigned to `http`-URL handler)?

**Comment by AliveDevil** [comment]
Crashes [here](https://github.com/iterate-ch/cyberduck/blob/master/core/native/refresh/src/main/csharp/Services/WinFormsIconProvider.cs#L136).
Relevant code path:
- Querying ProgId handler for `http`-protocol[^core-utils]
[^core-utils]: [core/Utils.cs:300](https://github.com/iterate-ch/cyberduck/blob/master/core/src/main/csharp/ch/cyberduck/core/Utils.cs#L300)
- Extracting Icon from that ProgId handler[^extract]
[^extract]: [refresh/WinFormsIconProvider.cs:51](https://github.com/iterate-ch/cyberduck/blob/80675fc997036cbc8e4b4a926b04d72a5895e598/core/native/refresh/src/main/csharp/Services/WinFormsIconProvider.cs#L51)
- Using the `largeIcon` handle to create an Icon
Possible issue here, that ExtractIconEx returns an error - which is ignored - or the icon returned is no icon.

Need to handle error return value.

**Comment by jekabsbalodis** [comment]
Thank You for Your reply. I use Firefox from windows store as my default web browser.
I tried to change the default app for HTTP and HTTPS to Edge browser and voila, the cyberduck version 8.4.3 opens normally and all my saved bookmarks are saved and license is applied.
If I change the default app for HTTP and HTTPS back to Firefox, the problem returns.

**Comment by AliveDevil** [comment]
Thank you, we'll check why the firefox appstore version brings Cyberduck down. Hopefully with the next release this should be fixed.

**Comment by AliveDevil** [comment]
Thank you for bringing this to our attention, this fix should be included in one of the next snapshot releases, or the next general release. In the meantime change the http-protocol handler to Edge, which doesn't break our implementation.
