### ISSUE TITLE
SSH connections added since last update have primary key trust issues

### ISSUE THREAD

**Issue by Insencel** [iterate-ch/cyberduck#13670]
This problem occured to me since the last update. I am running Windows 10. And it only effects new connections/bookmarks. The old ones still work perfectly fine.

Whenever i create a new bookmark the primary key won't ever be remembered. This means every time I connect to that address or on random occasions when i work with that connection cyberduck will prompt me with a pop up on whether or not I want to trust this ssh-rsa key (this persists even if I tick "remember this answer"). Depending on how long I wait before I select to trust this ssh-rsa key it is also possible that this pop up opens multiple times. After selecting to trust that key the pop up will still open every now and than (namely whenever I do an action I haven't done in a few minutes like renaming a file, saving something or moving files/directories)

**Comment by AliveDevil** [comment]
Duplicate for #13605.

Please update to latest Snapshot release.
