### ISSUE TITLE
Crash in -[NSApplication endSheet:returnCode:]

### ISSUE THREAD

**Issue by kohoward** [iterate-ch/cyberduck#13682]
**Describe the bug**
After restarting the application, some saved SFTP bookmarks would prompt for a .pem even though it is already configured. You can even edit the config the see that it is correctly configured.

Doing any action (clicking cancel, selecting the original correct .pem or even selecting a random .pem) would crash the application.

The work around I've found is to edit the config for my bookmark SSH private key to "none", then again going back to select the correct .pem.

As long as I do not close the application I can disconnect and open a new window to connect as many times without facing the issues.

This bookmark is not any way special or different from the other bookmarks I have. Recreating this bookmark with a different name does not help.

**To Reproduce**
1. Start application
2. Create SFTP bookmark with SSH private key
3. Connect successfully for testing the bookmark is valid
4. Disconnection and close the application
5. Start application again
6. Double click on the bookmark created in step 2
7. See that the application prompts for SSH private key
8. Do anything

**Expected behavior**
The application should not crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.5.1 (m1)

**Log Files**
No new error visible in log files. (Sorry will not be posting debug logs as it contains private information, including and not limited to some of my actual SSH keys)

**Additional context**
```
Process:               Cyberduck [26403]
Path:                  /Applications/Cyberduck.app/Contents/MacOS/Cyberduck
Identifier:            ch.sudo.cyberduck
Version:               8.4.3 (38269)
App Item ID:           409222199
App External ID:       851648099
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]

Date/Time:             2022-08-23 11:21:25.1403 +0800
OS Version:            macOS 12.5.1 (21G83)
Report Version:        12

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000000103124000
Exception Codes:       0x0000000000000002, 0x0000000103124000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by dkocher** [comment]
Can you post the full crash report in particular including the stacktrace for Crashed Thread 0.

**Comment by Subnero2001** [comment]
Is this Bug resolved as I notice the other thread on this has been closed out? Is there an update or new version out?

**Comment by dkocher** [comment]
As a workaround please move the private key to the {{.ssh}} folder in your home directory.
