### ISSUE TITLE
Prioritize identity set in bookmark before enumerating

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#13680]
There are servers disconnecting users after one failed authentication attempt.
Using SFTP Agent authentication can result in numerous failing attempts.

Is there a way where we can sort the list of identities found by priority (identity set in bookmark first, then all others)?

**Comment by dkocher** [comment]
See also #13442.

**Comment by dkocher** [comment]
Ordering was changed in a7cd0ba8.

**Comment by dkocher** [comment]
See also #13675.

**Comment by manuel-koch** [comment]
I updated to Version 8.4.5 (38423) and then issue still happens. I can still access my server via console with plain ssh command but Cyberduck keeps complaining about "Too many authentication failures." despite my attempt to give it the proper ssh-key-file.
