### ISSUE TITLE
Review singleton property for preferences controller

### ISSUE THREAD

**Issue by ylangisc** [iterate-ch/cyberduck#13687]
`PreferencesController` is *not* marked as singleton although it's instantiated as singleton in `PreferencesControllerFactory`. Controls are re-created every time the form is shown.

**Comment by dkocher** [comment]
This looks correct to me. The controller is invalidated when the window is closed[^1] but the same reference is returned on multiple invocations to open preferences[^2].

[^1]: https://github.com/iterate-ch/cyberduck/blob/master/binding/src/main/java/ch/cyberduck/binding/WindowController.java#L188
[^2]: https://github.com/iterate-ch/cyberduck/blob/master/osx/src/main/java/ch/cyberduck/ui/cocoa/controller/PreferencesControllerFactory.java#L30
