### ISSUE TITLE
suddenly cant get auth codes

### ISSUE THREAD

**Issue by alenskas** [iterate-ch/cyberduck#13688]
hi, Cyberduck has always worked for me but today when I select my google account to get a password, when I click continue it goes to a plain google.com frontpage. I don't get the code to copy-paste back into Cyberduck. 

please assist.

**Comment by dkocher** [comment]
As a workaround install Cyberduck from https://cyberduck.io/download/

**Comment by alenskas** [comment]
and thanks for the workaround :)
