### ISSUE TITLE
Retraité

### ISSUE THREAD

**Issue by maxjules** [iterate-ch/cyberduck#13699]
Bonsoir
Je n'arrive pas à utiliser le guide "comment récupérer les fichiers Hubic; j'ai installé le client FTP Cyberduck; j'ai même versé un don avec Paypal ; j'ai bien coché la case Hubic(OVH), fermé et relancé Cyberduck; mais je ne comprends ce que veut dire collez une connexion(traduction de l'anglais que je ne maitrise pas).
Donc je suis bloqué à ce stade.
Meri pour les informations.

**Comment by dkocher** [comment]
You will need to install the connection profile from _Preferences… → Profiles_. Refer to our [documentation](https://docs.cyberduck.io/protocols/openstack/hubic/).
