### ISSUE TITLE
S3 Multipart upload resume failing

### ISSUE THREAD

**Issue by AndySFreelance** [iterate-ch/cyberduck#13706]
Context, we're uploading files in excess of 1TB to S3, which takes significant amounts of time. Occasionally Cyberduck will hang, and when restarting the application and uploading again, progress restarts from 0% again. However testing with a much smaller 2.5GB file, I can artificially pause (at ~90% uploaded) and resume an upload and it will also return to 0% uploaded.
Cyberduck does have AMS permissions to list multipart uploads, and these are reflected in the logs as being queried successfully.

Comparing with S3Browser, multipart resumption of upload works correctly with the same permissions account, however S3Browser is at it's core an admin tool which is not suited to give to end-users, I would much rather be using Cyberduck for this use-case.

**Comment by dkocher** [comment]
Please reopen if this is still an issue in recent builds.
