### ISSUE TITLE
S3: Download of <file> failed. Request Error: Cannot invoke "String.toLowerCase()" because the return value of java.net.URI.getHost()" is null.

### ISSUE THREAD

**Issue by tchakabam** [iterate-ch/cyberduck#13708]
![Screenshot 2022-09-05 at 18 55 32](https://user-images.githubusercontent.com/1480052/188492428-d49587f5-c004-4dcc-9256-36abc24b0faf.png)

**Comment by tchakabam** [comment]
Happened repeatedly on an ongoing transfer queue with the *same* file.

**Comment by dkocher** [comment]
Duplicate for #13683.

**Comment by tchakabam** [comment]
Ok thanks will check

**Comment by tchakabam** [comment]
Hi @dkocher , can confirm it is fixed here 👍 Thanks again!! 💪
