### ISSUE TITLE
Review default prompt with message returned from server for challenge response authentication

### ISSUE THREAD

**Issue by slifty** [iterate-ch/cyberduck#13718]
**Describe the bug**
When connecting to an SFTP service that uses `keyboard-interactive` with a `name` field as defined in [RFC 4256](https://www.rfc-editor.org/rfc/rfc4256.html), CyberDuck's prompt uses both the server-provided title AND the default title when rendering to the user.  For example, if the server provided a name value of `title 1` CyberDuck renders:

```
title 1. Provide additional login credentials.
```

**To Reproduce**
1. Attempt to connect to a server that uses a `keyboard-interactive` prompt with a provided "name"
2. Look at the title of the resulting popup.

**Expected behavior**
I would expect CyberDuck to use the server-provided name exclusively if it exists, and only use the placeholder if a name is not provided.  In this case simply:

```
title 1.
```

**Screenshots**

<img width="328" alt="image" src="https://user-images.githubusercontent.com/208884/189233114-607f90da-2c7d-4225-9693-7645f1b1da02.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 8.4.3

**Log Files**
I can add log files but I don't know if PII is included so would prefer not to unless requested.

**Additional context**
I believe the solution is to modify [these lines](https://github.com/iterate-ch/cyberduck/blob/e212feb1e6ab543e8a14618a21ae0acfd568ce33/ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPChallengeResponseAuthentication.java#L123-L125) so the placeholder is only appended if name is not empty.

**Comment by dkocher** [comment]
This was last changed in 921333ad. Because some servers are configured to provide a non-explanatory message we opted to include the generic message to provide credentials.

**Comment by slifty** [comment]
Appreciated, this implementation limits what servers can do, however this does limit servers who do provide a working title.

For instance I am designing an MFA flow that does the following over three prompts:

1) Ask for password (name is "Provide a Password")
2) Ask the user to select a MFA technique from a list (name is "Select an MFA Method")
3) Ask for the user to provide the MFA code. (name is "Provide an MFA Code")

For other SFTP clients this is not a problem; for CyberDuck however this means the user is prompted as following:

1. "Provide a Password Provide additional login credentials."
2. "Select an MFA Method Provide additional login credentials."
3. "Provide an MFA Code Provide additional login credentials."

^ This means that CyberDuck's current implementation basically forces me (or other servers) to NOT follow the SFTP spec. Many clients do not have any sort of default name / title, which means I have to choose between providing no name / title or providing one that becomes redundant / confusing in CyberDuck.

Does this all make sense?

**Comment by dkocher** [comment]
> 1. "Provide a Password Provide additional login credentials."
> 2. "Select an MFA Method Provide additional login credentials."
> 3. "Provide an MFA Code Provide additional login credentials."

There should be a `.` suffix added to the message from the server if missing to make these two valid sentences.

**Comment by slifty** [comment]
Agreed! Maybe even better from a language POV would be to have the generic message first, followed by the more specific message.  For instance these might make more sense (in English anyway, I don't know about other localizations)

`Provide additional login credentials - Password`
`Provide additional login credentials (Password)`
`Provide additional login credentials: Password`
`Provide additional login credentials - Provide a Password`
`Provide additional login credentials (Provide a Password)`
`Provide additional login credentials: Provide a Password`
