### ISSUE TITLE
CSV Edit on Big Commerce through Cyber duck 

### ISSUE THREAD

**Issue by Stylenstride** [iterate-ch/cyberduck#13714]
Greetings, 

We have an ecommerce store on Big commerce platform and we are using cyberduck to show our size charts. Now we are trying to add few new columns but when we add the new columns in existing sheets it shows up on all the products we no heading. We would appreciate your help if you help us with this issue. 

Regards, 

Anuj     

This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Please contact Big Commerce support.
