### ISSUE TITLE
Access buckets with requester pays option enabled

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#13724]
![image](https://user-images.githubusercontent.com/734738/190115057-bad86acc-9c6e-493d-8462-e96108c00f48.png)

**Comment by dkocher** [comment]
> Normally, the project owner of the resource is billed for these charges; however, if the requester provides a billing project with their request, the requester's project is billed instead. With Requester Pays enabled on your bucket, you can require requesters to include a billing project in their requests, thus billing the requester's project. Enabling Requester Pays is useful, for example, if you have a lot of data you want to make available to users, but you don't want to be charged for their access to that data.

https://cloud.google.com/storage/docs/requester-pays
