### ISSUE TITLE
Conflicting with Win11 ?!

### ISSUE THREAD

**Issue by qwerty13** [iterate-ch/cyberduck#13721]
**Describe the bug**
It's very odd, but last night i installed cyberduck (and nothing before and after). after some normal working i turned off the machine, nothing happend and all usual.
today, i turned on machine and after a longer signing in, i see that windows 11 taskbar ribbon exists, system tray exists but not pinned icons nor time&system icons can be seen or works.
after some struggling, i realize that windows automatically makes a restore point when i install cyberduck; after restoring, taskbar problem fixed 😐.

Last version of cyberduck i had before was about 4-5 month ago (on previous windows installation), please check if something critical changed during last updates?

**Desktop:**
 - OS: Windows
 - Build 22000.918

**Comment by AliveDevil** [comment]
Interesting, Cyberduck shouldn't interfere with the taskbar - or anything with Windows, really.

Scenario is as follows?
- Windows 11 22000.918
- Install old Cyberduck version
- Update to latest release
- Windows taskbar is broken

**Comment by qwerty13** [comment]
No, it's as follows:

- Windows 11 22000.918
- Install old Cyberduck version
...
- Clean Installation of Windows 11 22000.918 (without deleting it's partition)
- Install latest release of Cyberduck
- Windows taskbar is broken
...
- System Restore to windows' created restore point before Cyberduck installation
- Windows taskbar is OK

**Comment by AliveDevil** [comment]
So I tried this, but didnt have any issue with the Taskbar or anything not working.
Installed Windows 11 22000.918 from ISO, installed Cyberduck 8.1.0 (Nov 2021), then went ahead and ran the installer again, with these options:
![Screenshot 2022-09-15 134650](https://user-images.githubusercontent.com/734738/190411444-fa6f7cc3-eaaa-40d5-94b5-2e97b5f5163e.png)
Installed Cyberduck 8.4.3, restarted. Windows works just fine. Do you have any other software installed that might interfere here?
