### ISSUE TITLE
Program crashes when trying to download/upload

### ISSUE THREAD

**Issue by WalidUplight** [iterate-ch/cyberduck#13746]
I have been using CyberDuck for about a year now, and a few days ago it started crashing every time I try to download/upload a file.  There does not seem to be an error report, the program just closes.  I have a registration key and did recently update to version 8.4.4. 
I use this for work on a PC.

**Comment by AliveDevil** [comment]
Please try to clear out `%AppData%\Cyberduck\Transfers`.

**Comment by dkocher** [comment]
Duplicate for #6550.
