### ISSUE TITLE
Upload fails with transfer incomplete but no error message

### ISSUE THREAD

**Issue by mdavisidsva** [iterate-ch/cyberduck#13744]
MAC OS 12.5.1

I am unable to get any files to upload to the SFTP. I have confirmed with META app that the details are correct, and that the issue is coming from my end.

![Screen Shot 2022-09-19 at 11 54 45 AM](https://user-images.githubusercontent.com/113925725/191060288-e9ec41c8-8ca3-430a-892b-3975cbed46bd.png)

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
