### ISSUE TITLE
Cloudflare R2 Storage (S3) profile enabled, not visible or usable

### ISSUE THREAD

**Issue by gellenburg** [iterate-ch/cyberduck#13765]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
I have enabled the profile for Cloudflare R2 (S3). It is not visible or usable when creating a new Bookmark or Connection.

**To Reproduce**
1. Enable Cloudflare R2 (S3) with the Connection Profile window.
2. Attempt to add a new Bookmark or Connection using the now enabled Profile.
3. You can't, because the option is not available.

**Expected behavior**
I would expect that the connection profile for Cloudflare R2 (S3) would appear once it's been enabled.

**Screenshots**
<img width="654" alt="image" src="https://user-images.githubusercontent.com/7026750/193332915-bdc74e87-7a55-4229-af3d-cdc0196bfa7e.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/7026750/193333103-d029715a-01a5-4b55-8881-5314a46e05d4.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22H2

**Log Files**
N/A

**Additional context**
N/A

**Comment by dkocher** [comment]
Duplicate for #13739.

**Comment by dkocher** [comment]
Please try the [snapshot build](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) 8.4.5.38394 or later.
