### ISSUE TITLE
Crashes when deleting folders

### ISSUE THREAD

**Issue by Tymorafarr** [iterate-ch/cyberduck#13769]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
When deleting folders (with or without items inside) in Google Drive with Cyberduck, there is a chance for Cyberduck to crash. The number of folder delete tries may take 2-10 times for me before it crashes.

**To Reproduce**
1. Start by creating several empty folders in Google Drive (~10)
2. Delete one folder
3. Delete another one if nothing happens
4. Repeat step 3
5. Observe a report crash prompt

**Expected behavior**
Deleting folders should not cause Cyberduck to crash

**Screenshots**
https://i.imgur.com/D0p46jK.mp4

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 22H2 (OS build 22621.525)

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9715907/cyberduck.log)

**Additional context**
N/A

**Comment by AliveDevil** [comment]
Thanks for reporting, though I don't know whether this can be fixed in the short term.

You have to love old software components. One more reason to drop the old interface.
```
[Exception Info 1]

Top-level Exception
Type:        System.NullReferenceException
Source:      ObjectListView
Stack Trace: bei BrightIdeasSoftware.TreeListView.TreeRenderer.HandleHitTest(Graphics g, OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   bei BrightIdeasSoftware.BaseRenderer.HitTest(OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   bei BrightIdeasSoftware.ObjectListView.OlvHitTest(Int32 x, Int32 y)
   bei BrightIdeasSoftware.ObjectListView.BuildCellEvent(CellEventArgs args, Point location)
   bei BrightIdeasSoftware.ObjectListView.OnMouseMove(MouseEventArgs e)
   bei System.Windows.Forms.Control.WmMouseMove(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
