### ISSUE TITLE
Constant (terrible) download problems

### ISSUE THREAD

**Issue by agithubber2** [iterate-ch/cyberduck#13767]
I usually download from google drive cloud,  usually whole folders (with about 20-50 files in it). 
But I almost NEVER can download in an automatic mode:  for some files your stupid (sorry) software warns about some (temporary!!) connection errors - but INSTEAD of just skipping the problem and trying downloading some later or so - your stupid (sorry) soft just says download error in the end! And when I try to redownload the folder it just redownloads EVERYTHING!  (this behavior I later fixed by unchecking the strange default overwrite checkbox in settings)
Instead of just trying to redownload the problem files ONLY!! Besides, there's NO info exactly which files it couldn't download , so that I could redownload them manually! I have to manually try to guess which files were not downloaded!

When at last I guess the problem files , I then try to download them manually with your soft - but for an unknown reason it often (not always) cannot download them, repeats its error message! Yet when I download those specific files with chrome browser , I have no problem at all!
I guess, the strange behavior of your soft might be caused by incorrect dealing with the google "cannot scan for viruses" message: the files I download are usually pretty large zip archives.

I use your latest 8.4.4 Cyberduck version, tried to use some older versions , but the problem is there too. 
Yet when some 1-2 years ago when I first started using your Cyberduck for dowloading folders with large zips, this bug didn't exist. I cannot guess from exactly which version the problem has started.

**Comment by dkocher** [comment]
Seems related to #10377.

**Comment by agithubber2** [comment]
I have just tested your latest 8.4.5 version from 11 Oct 2022 and the same problem exists!!
I have no clue why you cannot fix it! Manually I download those as if 'problem' files without any difficulty!! I I can download manually without errors , why can NOT your soft??
