### ISSUE TITLE
Bug with drag&drop to networkshare (Windows)

### ISSUE THREAD

**Issue by MartinHettich** [iterate-ch/cyberduck#13764]
Download works fine to local harddrive or to an network share by context function "download to...".
If a user drags&drops directly to a visible/open network share/network folder, cyberduck creates a 0 Byte file with random name.

(we noticed, that the 0 byte file gets as well created when downloading to local harddisk but gets replaced imediatly gets replaced with the correct downloaded file after download has finished)

**Comment by dkocher** [comment]
Duplicate for #5330.
