### ISSUE TITLE
Failure to read attributes of (file) Stream closed. The connection attempt was rejected.

### ISSUE THREAD

**Issue by notpoppy91** [iterate-ch/cyberduck#13776]
Right click and edit a file via SFTP. After 1-2 minutes of inactivity I get this bug. "Failure to read attributes of footer.php. Stream closed. The connection attempt was rejected. The server may be down, or your network may not be properly configured."

Mac OS Big Sur & Monterrey

It used to work perfectly, until an update.

Hosting: Cloudways/Vultr

**Comment by dkocher** [comment]
Duplicate for #13728.
