### ISSUE TITLE
forward slash folder name not showing

### ISSUE THREAD

**Issue by marcotielen** [iterate-ch/cyberduck#13779]
import boto3
from botocore.exceptions import ClientError

s3_client = boto3.client('s3')
try:
response = s3_client.upload_file("files.txt","bucket_name","/hello/files.txt")
except ClientError as e:
print(e)

If one executes something like the above, it doesn't show in cyberduck. What happens on AWS is that a "folder" named "/" is created. It is also visible in the AWS console:

![image](https://user-images.githubusercontent.com/5139616/194621523-a09c6a94-776f-4244-854f-bd27797d65ed.png)

![image](https://user-images.githubusercontent.com/5139616/194621014-eb1732cc-d2c2-4e74-a252-5a1e00172672.png)

**Comment by dkocher** [comment]
You will have to create a placeholder file for `/hello/` as we are listing buckets using the `/` delimiter.

**Comment by marcotielen** [comment]
Just to make sure you understand what I'm experiencing: In AWS the folder "/" exists, but in Cyberduck it doesn't show in the interface and as such all files in the folder "/" can't be seen at all, whilst they are there on s3. Apparently, it's possible to have a folder named "/". Logic would need to be: if starting with "/" or if more than 1 consecutive "/"  (hello//files.txt also seems to work) , it's a "folder".

**Comment by dkocher** [comment]
Duplicate for #10981.
