### ISSUE TITLE
Files not saving changes on DAV - bigcommerce 

### ISSUE THREAD

**Issue by bargaindealsexpress** [iterate-ch/cyberduck#13786]
Hi, I am using the newest version for connection with the Dav. The CSV files I am uploading are not editing anymore. I am unable to make changes to the CSV files on big commerce 

I tried uploading the new file to overwrite however getting 400 Bad response 

I have two issues ;

-My CSV files are not editing like chaos is not saving  - Transfer fails 
-400 Bad response messages popping up when I upload the file gain 
![Screen Shot 2022-10-12 at 4 27 08 pm](https://user-images.githubusercontent.com/100002272/195257438-1d0d2042-11bc-48db-ac7a-14246128f1fe.png)

**Comment by dkocher** [comment]
Please contact BigCommerce support for assistance.
