### ISSUE TITLE
Download to mounted SMB volume fails with Resource busy error

### ISSUE THREAD

**Issue by WolfgangFahl** [iterate-ch/cyberduck#13784]
**Describe the bug**
Transfer of a 1/2 GB file fails

**To Reproduce**
Drag & Drop the file to a network driver

**Expected behavior**
transfer should finish or be restartable

**Screenshots**
<img width="298" alt="grafik" src="https://user-images.githubusercontent.com/1336221/194722801-4afbc3d6-fbeb-438b-92bb-9fa066920ea5.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 8.4.3

**Comment by dkocher** [comment]
Can you elaborate what you refer to with _network driver_.

**Comment by WolfgangFahl** [comment]
@dkocher: the target was a volume mounted on an smbfs file system served by an unbutu machine. Mac OS is notoriously troublesome with such drives and it looks cyberduck has the same problem. A had to transfer the file to a local driver and than use the finder to move it to it's finaly destination. In general cyberduck is too unreliable to use to transfer to such smbfs drives with it's current version.

**Comment by dkocher** [comment]
I don't see there is much we can do as the error is reported from the underlying mounted SMB filesystem.

**Comment by dkocher** [comment]
> I don't see there is much we can do as the error is reported from the underlying mounted SMB filesystem.

As a workaround try to uncheck _Preferences → Transfers → Downloads → Segmented Downloads with multiple connections per file_.
