### ISSUE TITLE
Allowing generation of SSH keys in user interface

### ISSUE THREAD

**Issue by djt5019** [iterate-ch/cyberduck#13787]
**Is your feature request related to a problem? Please describe.**
Hey there!  Apologies if this has been requested before, I didn't see any direct references to it in the Github issue history.  

We have some folks who are using Cyberduck successfully for connecting to sFTP servers however the need to generate a SSH key externally to Cyberduck has become a sort of stumbling block, especially in a mixed environment where Windows and Mac are equally prevalent.  It's less a problem with Cyberduck itself but I believe there might be an opportunity to ease the learning curve for less technical users if they had the ability to generate a SSH keypair from the same tool they are accustomed to.

**Describe the solution you'd like**
I am far from an expert in UI/UX but I believe having an optional dialogue in the `sFTP` connection creation screen might be handy.  Either as a simple `+` symbol next to the `SSH Private Key` dropdown or in the `Additional Options` section.

Under the hood I believe shelling out to `ssh-keygen` or `PuttyGen` on Windows might be possible, though it would come with all the usual issues with subprocessing.

**Describe alternatives you've considered**
It may also be possible to use the [`java.security.KeyPairGenerator`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/KeyPairGenerator.html) class to do it ourselves, though that likely comes with additional baggage like managing which algorithms can be used to generate a key (though that may be putting the cart before the horse at this point).

**Additional context**
Thanks for reading this ticket and for building a great tool like Cyberduck!

**Comment by dkocher** [comment]
Sounds like a duplicate for #4405.
