### ISSUE TITLE
Crashes when uploading/downloading file from AWS S3

### ISSUE THREAD

**Issue by StevenLi-iHealth** [iterate-ch/cyberduck#13794]
Hi there,

We are using Cyberduck to upload files from local to our customer's AWS S3. The app keeps crashing when we upload/download the file. The current software version we are running is 8.4.5 (38423). Could you please advise? 

Thank you,
Steven Li

**Comment by dkocher** [comment]
Please attach the crash report [^1].

[^1]: https://docs.cyberduck.io/cyberduck/support/#crash-reports
