### ISSUE TITLE
please add auth_token authentication for  openstackswift.  

### ISSUE THREAD

**Issue by demoze** [iterate-ch/cyberduck#13796]
**Is your feature request related to a problem? Please describe.**
I would like to access openstack swift from an already provided auth_token.   Just like with rclone or the swift cli. 

@see https://docs.openstack.org/python-swiftclient/ocata/cli.html
_It is also possible that you need to use a completely separate auth system, in which case swiftclient cannot request a token for you. In this case you should make the authentication request separately and access your storage using the token and storage URL options shown below:_

Just by specifying OS_AUTH_TOKEN=my_token and OS_STORAGE_URL I can use swift cli.  I have a third party tool to generate the auth_token.  The rclone client implement the same feature.  keystone auth is bypass and the auth_token is use directly in the interaction with swift by inserting auth info in the header. 

 

**Describe the solution you'd like**

- Add a new field auth_token  , bypass keystone call and  use directly  auth_token insert "X-Auth-Token:  " in all interaction with swift as usual.
- 

**Describe alternatives you've considered**
A more generic way will be to be able to call an external script with project_name, storage_url as parameter (or all informations inside the connection profile)  and have this script return the value key/values pairs for cyberduck parameter.  In our case only auth_token and storage_url is needed.

**Additional context**

**Comment by dkocher** [comment]
Can you reference the relevant OpenStack documentation.

**Comment by demoze** [comment]
sorry  I'm going to rephrase, the request, the ticket

**Comment by dkocher** [comment]
Please reopen when the requirements are clearly defined.
