### ISSUE TITLE
Unknown Error for DRACOON share

### ISSUE THREAD

**Issue by your-highness** [iterate-ch/cyberduck#13803]
**Describe the bug**
We are routinely using duck in ubuntu terminal to upload files to a DRACOON share. Today we experienced the following error "Unknown":
```bash
>duck --username "<DRACOONUSER>" --list dracoon://<SHARE>
Picked up JAVA_TOOL_OPTIONS:  -Djava.net.useSystemProxies=true -Djava.net.useSystemProxies=true
DRACOON connection opened…
https://*****/oauth/authorize?client_id=dracoon_desktop&redirect_uri=https://*****/oauth/callback&response_type=code&state=2kfvpeGi&user_agent_info=cy1sYWJiLW5nczAxLmxhYm9yYmVybGluLmludGVybg%3
Disconnecting *****…
Unknown. Cannot invoke "ch.cyberduck.core.PathAttributes.getRegion()" because the return value of "ch.cyberduck.core.Path.attributes()" is null.
```

Using Duck 8.3.0 we can use duck to list and upload files.

**To Reproduce**
1. Install version ubuntu duck version 8.4.4 or 8.4.5
2. Remove duck config `rm -rf ~/.duck`
3. Run `duck --username "<DRACOONUSER>" --list dracoon://<SHARE>`
4. Authenticate via Link

**Expected behavior**
List files and folders of the share

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 20.04

**Log Files**
see above

**Additional context**
When updating to 8.4.5 from 8.3.0 **without removal of `~/.duck/`** (_i.e._ keeping the authentication token from version 8.3.0) the connection can be established. 

@selyasar

**Comment by dkocher** [comment]
Documentation is pending in iterate-ch/docs#272 for the new DRACOON CLI connection profile. Can you please try with the DRACOON (OAuth Password Flow) [connection profile](https://raw.githubusercontent.com/iterate-ch/cyberduck/master/dracoon/src/main/resources/DRACOON%20(CLI).cyberduckprofile) using `duck dracoon-cli:/`
