### ISSUE TITLE
Connection failed - Operation not supported for file storage type.

### ISSUE THREAD

**Issue by rynne94** [iterate-ch/cyberduck#13802]
Have downloaded hundreds of files using Cyberduck but for some reason it won't allow me currenty.
I have tried to download it to Mac, hard drive, online storage etc. 
It begins to attempt the download then says
Connection failed
Operation not supported for file storage type

Not sure what to do to fix this error?

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
