### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by TacticalTailorMWK** [iterate-ch/cyberduck#13809]
**Is your feature request related to a problem? Please describe.**
Uploading a PDF, get this error: Status code: 401

**Describe the solution you'd like**
I want the pdf to upload correctly

**Describe alternatives you've considered**
Reaching out to you
![401](https://user-images.githubusercontent.com/116292394/196989747-b6e3c314-9361-4f01-b451-8d2b7ee6bfce.jpg)

**Additional context**

**Comment by dkocher** [comment]
You should reach out to the support of BigCommerce.
