### ISSUE TITLE
did not receive registration key

### ISSUE THREAD

**Issue by Desert-West** [iterate-ch/cyberduck#13813]
I did not receive a registration key. I received the email and there is an attachment, but the attachment cannot be opened on a Mac. I tried to attach the file received, but your system does not support the file type. May I receive a valid registration key? Thank you. Regards, Desert West
[regisrration email recieved.pdf](https://github.com/iterate-ch/cyberduck/files/9844301/regisrration.email.recieved.pdf)

**Comment by dkocher** [comment]
Please write to support@cyberduck.io. You can always lookup your registration key at https://cyberduck.io/help#recover to receive it with the email address registered.
