### ISSUE TITLE
Cyberduck 8.4.5 crashes

### ISSUE THREAD

**Issue by EduardZorici** [iterate-ch/cyberduck#13820]
Hi

the latest version of Cyberduck (8.4.5) started to crash every time when i try to upload something. I tried to upload files on other servers too, repairing/uninstalling/reinstalling cyberduck. There is no crash error or message. For the first time when it crashed, it showed me the crash dialog window but i closed it by mistake. After this it only freezes and then close itself. I use Windows 11. Also on MacOS it has a long freeze until it uploads a file for the first time after open.

**Comment by AliveDevil** [comment]
Does it make it better if you remove past transfers in `%AppData%\Cyberduck\Transfers`?

**Comment by EduardZorici** [comment]
Hi, this fixed the issue on desktop and also the delay on mac. Thanks for the advice. Would be nice to have an autodelete function after some time.

**Comment by dkocher** [comment]
You should get a warning _Remove completed transfers from list._ when the number of transfers exceeds `20` with the option to _Clean Up_.
