### ISSUE TITLE
Failure to read attributes of. Error

### ISSUE THREAD

**Issue by Alan-lubnow** [iterate-ch/cyberduck#13839]
I'm attempting to connect via Amazon S3 and I keep getting the same error. All of my information is correct and I get a successful login, but I keep getting the error "Failure to read attributes of. Maximum redirects (5) exceeded." Does anyone have experience with this?

**Comment by Alan-lubnow** [comment]
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9923110/cyberduck.log)

**Comment by dkocher** [comment]
> cyberduck.log

The attached log file is empty.
