### ISSUE TITLE
Dropbox Login Giving Error (400)

### ISSUE THREAD

**Issue by akiramochi** [iterate-ch/cyberduck#13836]
When setting up Cyberduck and trying to log into Dropbox the login screen does not appear instead an error (400) appears. 
![IMG_0470](https://user-images.githubusercontent.com/117234771/199358748-f0a759e2-f969-41ea-a829-6e2a07d9d037.jpg)

**Comment by dkocher** [comment]
We have changed the app registration with Dropbox to allow the use of PKCE. Please try again.
