### ISSUE TITLE
Upload in "compare" mode to empty folder takes forever

### ISSUE THREAD

**Issue by guppyplopp** [iterate-ch/cyberduck#13843]
The first upload of a project into an empty folder on a server takes very long time if the "compare" mode is used. 
But if files/folder structures is already on the server, the "compare" works fine and quickly run through all folders and uploads the changed files.

**Comment by tatze96** [comment]
I can't reproduce the described behavior using the protocol WebDAV (HTTPS) on macOS and Windows. Given that there is the same amount of data within the transfer batch that isn't already located on the server, the transfer process needs the same time regardless of whether the target directory is empty or already has files located in it.

The transfer is expected to be shorter if the total data that isn't located on the server is smaller than within the initial transfer.

Which operating system and which protocol is in use on your side?

**Comment by guppyplopp** [comment]
Mac OS 12.6
Cyber Duck 8.5.0
ftp:// … :21 

Uploading a project with subfolders into empty folder. Each file/folder compare takes a 2-3 seconds. See attached video. 




Pål Walfridsson
Darktown Production AB
Högsbogatan 29
414 75  Göteborg
+46 708 701489
http://darktown.se <http://darktown.se/>

**Comment by guppyplopp** [comment]
Video: 
https://user-images.githubusercontent.com/20163876/201305938-da514570-e666-4634-b475-254514cbdcd2.mov

**Comment by guppyplopp** [comment]
Update: I saw now that it is working fine on another server i uploaded to. Looks like it is something on the server side then...

**Comment by guppyplopp** [comment]
The server were it works fine on has SFTP (SSH file transfer protocol) 
Using FTP or FTP-SSL it is slow.
