### ISSUE TITLE
File = 170GB but upload > 178+GB

### ISSUE THREAD

**Issue by AvdReis** [iterate-ch/cyberduck#13844]
Hi there

I have 'done' a ftp of 170GB tar.gz file. The file shows it has uploaded 100% on cyberduck, but the transfer status still shows uploading (for over an hour now). The file on the server shows it has uploaded, but it is actually still uploading as it has increased in size with timely checks. It's already 10GB over it's actual size. How can this be?

I did transfers of smaller files prior to this (all less than 1GB) and their sizes reflect their correct sizes. I had no issues with uploading.

Only difference with the upload between this and the other files was I had to pause the upload, but it resumed with no issues.

Cyberduck v8.5.0 (38556)

Cheers
Aimee

**Comment by AliveDevil** [comment]
Thanks for reaching out. We did try to upload a 180GB file onto a local OpenMediaVault NAS appliance, and succeeded.
Is there anything that could help us find the underlying issue?
What was the observed transfer speed? Our test used around 100 MiByte/s on Windows.
Is it a local or remote ftp server? Were there any error messages?
