### ISSUE TITLE
Capitalized File Names Overwritten as Lower Case

### ISSUE THREAD

**Issue by recproed** [iterate-ch/cyberduck#13852]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

Using BigCommerce as a provider.
Problem: Images on webDAV server being renamed or copied, resulting in embedded images breaking.

Synopsis:
1. We noticed some broken images on our website.
2. The embedded files were uploaded using a capital letter name scheme ex: First-Letter-Capitalized.jpg
3. We noticed that the broken images had been renamed from upper case to lower case, resulting in 404s and broken images.
4. I made duplicates of some of these image files in order to prevent from having to replace 100s of urls sitewide, using the same upper case naming. 
5. (BigCommerce) Ticket was closed, tech support unable to see when/why/who changed files. Ticket closed.
6. Week of 11/4, noticed another broken image in the same place previously, webDAV shows the capitalized files were again renamed with a prefix added to the files. 

**To Reproduce**
1. Upload a file to the directory using capitalized naming scheme.
2. After some time, file is renamed using all lowercase
3. Original file with capitalized naming re-uploaded to server
4. After some time, file is changed to lowercase again, however because the lowercase file already exists, a prefix is added to the file name.

Unable to reproduce this error, however it has happened numerous times. 

**Expected behavior**
Files are uploaded and retain the filenames assigned when uploaded.

**Screenshots**
![BigCommerce Broken Images 11-4](https://user-images.githubusercontent.com/117476787/200048183-40a3eed4-828b-492d-8538-a2edb7de1fc3.png)
*Note the 3 additional copies of installation-instruction-icon-for-website.jpg, as this file has been re-uploaded several times, with the same change in file name taking place. I would assume that the renaming is taking place at the same time the new file is created.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 21H2, Build 19044.2130

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/9941111/cyberduck.log)

**Additional context**

**Comment by dkocher** [comment]
Please contact BigCommerce support about the problem.
