### ISSUE TITLE
Implement cache size management

### ISSUE THREAD

**Issue by flypenguin** [iterate-ch/cyberduck#13865]
**Is your feature request related to a problem? Please describe.**
My hard drive seemed to be full. When I dug down in what's causing this, I saw that:
```
356G	H63SCF94XU.duck
```
I don't have kind words for this. Nothing should be able to creep up **more than three hundred gigabytes of cache** without having _some_ kind of indication or cache management.

[deleted some angry content and completely changed my mind]

So for some reason my mountain duck did not update, and i see you have implemented this SORELY NEEDED FEATURE.

Just when I realize (again 😁) I need it.

So thanks for that. In case you read it feel free to close this ticket, and be aware that you have made a customer happy here.

Thanks! 🎁

**Comment by dkocher** [comment]
Cache management has been introduced in version [4.12](https://mountainduck.io/changelog/).
