### ISSUE TITLE
Bug when renaming files / folders

### ISSUE THREAD

**Issue by davegiffney** [iterate-ch/cyberduck#13879]
![issue1](https://user-images.githubusercontent.com/26258811/202424177-c8c82156-2702-4a02-a3ba-88ae2723dd8e.png)

When trying to rename files or folder, it no longer highlights the whole text and is hard to see what you're editing if only editing part of name

**Comment by AliveDevil** [comment]
https://github.com/iterate-ch/cyberduck/pull/13774
