### ISSUE TITLE
Make it possible to provide the key name for SFTP connection

### ISSUE THREAD

**Issue by 8uurg** [iterate-ch/cyberduck#13888]
**Is your feature request related to a problem? Please describe.**
Currently Cyberduck allows for loading in a key from a file when connecting, allowing the user to pick specifically which key to use.
In contrast, when using an SSH agent to perform key-based authentication, it is not possible to provide the name of the key to use.
This could lead to cyberduck attempting to use all of the keys available in the SSH agent - causing the 'too many authentication attempts'-error to pop up.

**Describe the solution you'd like**
It would be nice if I could provide a string for the keyname to use when connecting.
Or alternatively, if it would be nice if Cyberduck used the keyname listed in my ssh configuration*.

**Describe alternatives you've considered**
I would need to convert the key to PEM format and provide it directly as a file.

**Additional context**
\* Cyberduck may already be using my ssh config, it certainly does for the jump hosts. But: connecting using ssh myself works fine, while with Cyberduck it does not. This makes me wonder what the other authentication attempts are.

**Comment by AliveDevil** [comment]
We implemented a feature, that tries to prioritize SSH keys from the agent if they are set as SSH key in the connection.
Can you confirm, that this works?
- Add SSH key to agent
- Select that same SSH key file in Cyberduck
- Connect, with active agent, to the SFTP capable server

Ideally this should prioritize the existing key and discard any non-matching keys from the agent.

**Comment by 8uurg** [comment]
Okay. That works if I use PuTTY to convert the key and load it in pageant - but does not work with the built-in OpenSSH agent.

**Comment by dkocher** [comment]
> We implemented a feature, that tries to prioritize SSH keys from the agent if they are set as SSH key in the connection. Can you confirm, that this works?

In #13698. As this is based on the comment field it is possibly not interoperable with PuTTY Pageant.

**Comment by dkocher** [comment]
Duplicate for #13935.
