### ISSUE TITLE
SFTP ProxyJump with password login doesn't work on version 8.5.0

### ISSUE THREAD

**Issue by petarbelokonski** [iterate-ch/cyberduck#13898]
~/.ssh/config looks like this:

```
Host jumperhost
HostName jumperhost.address
User root 
                                 
Host myhost
HostName myhost.address
ProxyJump jumperhost
User petar
```

**To Reproduce**

When I try to establish a connection to myhost@myhost.address I get 

<img width="362" alt="Screenshot 2022-11-24 at 18 26 23" src="https://user-images.githubusercontent.com/5446543/203830751-34e1a4ea-9457-4cbc-9c95-0589340fd9e9.png">

This is login using password. Seems like cyberduck wants to make a connection using an ssh key and since there is no key provided it fails

**Desktop**
 - OS: macOS 12.6
 - Version 8.5.0

**Additional context**

I have set this up before and it has worked fine. I spent hours to understand the problem and when I reverted to cyberduck 8.3.0 it all works fine.

**Comment by dkocher** [comment]
Please let me know if you still see this issue in version [8.5.4](https://trac.cyberduck.io/milestone/8.5.4).

**Comment by dkocher** [comment]
Make sure to set the _Server_ in the bookmark to your alias `myhost` in the OpenSSH configuration.
