### ISSUE TITLE
Customize toolbar not visible

### ISSUE THREAD

**Issue by rawneo** [iterate-ch/cyberduck#13908]
In MAC silicon m1 the customize toolbar is not visible.

**Comment by dkocher** [comment]
Choose _View → Customize Toolbar…_ or right click on the toolbar.

**Comment by rawneo** [comment]
<img width="781" alt="Screenshot 2022-11-28 at 2 09 56 PM" src="https://user-images.githubusercontent.com/528710/204232271-0f192806-d0bd-406a-bf91-682d4d95779b.png">
<img width="782" alt="Screenshot 2022-11-28 at 2 10 17 PM" src="https://user-images.githubusercontent.com/528710/204232324-4a30de4d-6065-47b2-b42b-817cc362aec2.png">
After Clicking to  View → Customize Toolbar only dancing icons are appearing on Menubar. 
No pop-up appearing as it appears before. I am used to customize it.
Cleared all cache, reinstalled many times with Homebrew or directly from website. 
Still  custom toolbar is not appearing.

**Comment by rawneo** [comment]
It was finally fixed by:
defaults delete ~/Library/Preferences/ch.sudo.cyberduck.plist logging
