### ISSUE TITLE
Using a Symlink to the Bookmarks folder on iCloud drive causes Cyberduck to hang upon starts

### ISSUE THREAD

**Issue by rkrug** [iterate-ch/cyberduck#13912]
Hi

I bought Cyberduck in the App Store a few days ago.

I was previously using thew home-brew installed version and I could follow https://docs.cyberduck.io/cyberduck/bookmarks/#sharing-bookmarks-between-different-computers and it worked. After switching to the Appstore version, Cyberduck hangs upon startup (at least the bookmark page). I even created an empty bookmarks folder and linked it in and the same problem.

I was using the iCloud folder to share settings between computers and between Cyberduck and Mountain Duck.

Cheers,

Rainer

**Comment by tatze96** [comment]
This is a limitation of the sandboxed version. The App Store (sandboxed) Cyberduck version can't list the existing bookmarks from the symbolic link.

After you've installed the App Store version of Cyberduck, the App Store will copy your purchase receipt to the application support folder, which acts as a license file for the standalone version. You can use the website version of Cyberduck to work around the issue if desired.
