### ISSUE TITLE
Problem synchronizing folder

### ISSUE THREAD

**Issue by rodllag** [iterate-ch/cyberduck#13911]
I hope I'm not doing anything wrong.

Attempting to sync a WP backups folder with a local folder. (host, etc. has been redacted for privacy).

`duck --username USERNAME --synchronize ftp://HOST.com/softaculous_backups/ /Volumes/Ext SSD/Site\ Backups/TEST/ --verbose`

After this choosing `download` option.

"Runs", then disconnects with no files transfered even though the destination folder is empty.

Verbose says this: (file names modified for privacy):

```
Prepare TEST (Download)…
> CWD /softaculous_backups
< 250 OK. Current directory is /softaculous_backups
> TYPE A
< 200 TYPE is now ASCII
> PRET MLSD null
< 200 Ready to proceed
> PASV
< 227 Entering Passive Mode (104,225,208,26,198,23)
> MLSD
< 150 Accepted data connection
< type=cdir;sizd=125;modify=20221129021015;UNIX.mode=0711;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g2407f8232; .
< type=pdir;sizd=4096;modify=20221128214211;UNIX.mode=0711;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g3000b6e29; ..
< type=dir;sizd=10;modify=20221128195300;UNIX.mode=0755;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g26280b071; tmp
< type=file;size=9121594260;modify=20221116163033;UNIX.mode=0600;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g2436f005b; wp.20_63017.2022-11-16_10-23-41.tar.gz
< type=file;size=9137184403;modify=20221128195300;UNIX.mode=0600;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g241323411; wp.20_63017.2022-11-28_13-45-58.tar.gz
< 226 5 matches total
> CWD /softaculous_backups
< 250 OK. Current directory is /softaculous_backups
> TYPE A
< 200 TYPE is now ASCII
> PRET MLSD null
< 200 Ready to proceed
> PASV
< 227 Entering Passive Mode (104,225,208,26,225,81)
> MLSD
< 150 Accepted data connection
< type=cdir;sizd=125;modify=20221129021015;UNIX.mode=0711;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g2407f8232; .
< type=pdir;sizd=4096;modify=20221128214211;UNIX.mode=0711;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g3000b6e29; ..
< type=dir;sizd=10;modify=20221128195300;UNIX.mode=0755;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g26280b071; tmp
< type=file;size=9121594260;modify=20221116163033;UNIX.mode=0600;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g2436f005b; wp.20_63017.2022-11-16_10-23-41.tar.gz
< type=file;size=9137184403;modify=20221128195300;UNIX.mode=0600;UNIX.uid=1944;UNIX.gid=1947;unique=fd00g241323411; wp.20_63017.2022-11-28_13-45-58.tar.gz
```

**Comment by btazus** [comment]
I am having the similar issue with synchronizing with Google Drive.  My first attempt works, but subsequent tries do not transfer.  I have tried changing my `--existing`  options with not affect.  {`mirror, upload, download`}.

Using Cyberduck on the same computer, with the same credentials works fine.
My command is
`duck --username myname@mycompany.com --synchronize googledrive:/My\ Drive/Subfolder/ file:/Volumes/ExtHD/Subfolder/ --existing mirror`

Where the subfolder names are the same.
I have tried on multiple Apple computers.  My duck installs are downloaded packages from the website as of today,
duck-8.5.9.39636.pkg.
Installed on Apple Silicon Macs, OS 13.3.1
