### ISSUE TITLE
Open in Terminal.app

### ISSUE THREAD

**Issue by ferben** [iterate-ch/cyberduck#13928]
Open in terminal generate bad command. for example:
` "ssh -t  root@comparator7042 -p 22 "cd \/vmfs\/volumes && exec \$SHELL -l"` → password based login
`"ssh -t -i "/Users/ferben/.ssh/id_rsa" ferben@rhel8 -p 22 "cd \/home\/ferben && exec \$SHELL -l"` → ssh key based login.
The problem is the very first double-quote `"` which cause not-closed command.

Tested on macOS 13.0.1 Ventura, but it should appear on all supported macOS versions.
Cyberduck 8.5.1 (38745)

**Comment by dkocher** [comment]
Regression from b4eaf7108b5e9d7076a2d747618257873e5dcc6a.

**Comment by ferben** [comment]
`terminal.command.ssh="ssh -t {0} {1}@{2} -p {3} \"cd {4} && exec \\$SHELL -l\"`→
`terminal.command.ssh=ssh -t {0} {1}@{2} -p {3} \"cd {4} && exec \\$SHELL -l\"`

**Comment by dkocher** [comment]
You should be able to put this in `~/Library/Group\ Containers/G69SCX94XU.duck/Library/Application\ Support/duck/default.properties` to override the default.
