### ISSUE TITLE
Downloading more than the size of the file and not stopping

### ISSUE THREAD

**Issue by gio888** [iterate-ch/cyberduck#13922]
**Describe the bug**
Cyberduck downloading more than the size of the Backblaze B2 zip and not stopping.

**To Reproduce**
1. Open connection to B2 Backblaze
2. Enter credentials
3. Click download
4. Download starts and running for days
5. Cyberduck seems to be downloading more than the size of the payload: 3.2TB of a 1.8TB zip file

**Expected behavior**
I would expect that it the payload size is the upper limit and cyberduck should only download up to that.

**Screenshots**
![Cyberduck Backblaze issue](https://user-images.githubusercontent.com/6746990/204936798-c927fb3a-340e-4ab0-8334-a565021ed867.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.0.1 (22A400)

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10128279/cyberduck.log)

**Comment by dkocher** [comment]
Please let us know if you can reproduce after unchecking _Preferences → Transfers → Segmented downloads with multiple connections per file_.

**Comment by dkocher** [comment]
Duplicate for #13374.
