### ISSUE TITLE
Timestamp not left unchanged

### ISSUE THREAD

**Issue by macwirbel** [iterate-ch/cyberduck#13924]
Desktop Version 8.5.1 (38745) running with macOS 12.6.1

The option "leave timestamp untouched" is activated for upload and download.
At least upload does not respect this.
Timestamp of file on the desktop was some hours old, but upload changed it to upload time.
<img width="712" alt="Bildschirmfoto 2022-12-01 um 22 07 43" src="https://user-images.githubusercontent.com/19307818/205160471-84ba3749-ab07-4328-8964-bf069a3cee16.png">

Connection was FTP to local device (shared folder on fritz!box)
<img width="522" alt="Bildschirmfoto 2022-12-01 um 22 17 26" src="https://user-images.githubusercontent.com/19307818/205161057-8134cd60-93d2-4ca5-aa0f-3d21ce7eda46.png">

Another example: source file was
![Bildschirmfoto 2022-12-01 um 22 20 33](https://user-images.githubusercontent.com/19307818/205162124-4c8e28cb-2dd1-4c56-bf09-097fa8710ea4.png)
After FTP-Upload file was
<img width="448" alt="Bildschirmfoto 2022-12-01 um 22 22 05" src="https://user-images.githubusercontent.com/19307818/205162213-6593cf28-f7ca-4a7d-8ca2-587f90caaa7a.png">

**Comment by dkocher** [comment]
Possibly related to #13685.

**Comment by dkocher** [comment]
Some FTP servers do not support setting the modification date on files thus this may not work as expected.
