### ISSUE TITLE
8.5.0 Not remebering History

### ISSUE THREAD

**Issue by 1jump2** [iterate-ch/cyberduck#13929]
Since updating to 8.5.0 on Ventura Cyberduck only stores 1 item in my History. 
Tres annoying. 

Adam

**Comment by dkocher** [comment]
I cannot reproduce in 8.5.5 (39213).

**Comment by 1jump2** [comment]
Still an issue. It's driving me insane. I have to keep manually typing the server details in because it picks and chooses which ones to remember.
