### ISSUE TITLE
Crash on Windows 11 Pro with IdentityAgent in ssh config

### ISSUE THREAD

**Issue by 3b0b** [iterate-ch/cyberduck#13933]
**Describe the bug**
Since version 8.3.0 in April, Cyberduck crashes on launch with my ssh config file. I originally thought my problem was #13672, but after realizing the fix for that was supposed to have been released already, I actually checked my crash reports and narrowed this down today. As of 8.4.5.38423 and 8.5.1.38745, the problem goes away if I comment out my IdentityAgent line. Fortunately, I don't think I actually need it - I don't use the SSH agent, so the following ProxyCommand line, which doesn't cause me any problems, is the important one.

**To Reproduce**
1. Have an ssh config with a line that starts with `IdentityAgent //` 
2. Try to launch Cyberduck

If the next character of the IdentityAgent is a period, the program crashes. If it is anything else, it seems to hang indefinitely with a process running but the UI never appears.

The reason I had the configuration in question was because Krypton Authenticator adds the following (path redacted):

```
# Added by Krypton
Host *
	IdentityAgent \\.\pipe\krd-agent
	ProxyCommand path\to\krssh.exe %h %p
```

but I had a _different_ tool - unfortunately I've forgotten what it was; it may have been a Visual Studio Code plugin - which worked if I changed the backslashes in the IdentityAgent line to forward slashes but not with the configuration as above.

Since I have a workaround, I've submitted this mostly in case it's a simple parsing issue that (A) is easy to fix and (2) might trip people up in a less obscure case. I may even come back later and try to whip up a pull request. My assumption is that the problem is in handling that kind of string in `LocalFactory.get()`, but I ran out of time to investigate this today before I figured out where LocalFactory lives in the codebase.

**Expected behavior**
Cyberduck working; if necessary, a convenient and documented way to tell Cyberduck not to try to parse my ssh config or to point it at a different one (which might already exist and I failed to find it...).

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro and Windows 11 Pro Insider Preview
 - Version: all attempts from at least 10.0.22593 through 10.0.25247

**Log Files**
[638055899217769141.txt](https://github.com/iterate-ch/cyberduck/files/10143983/638055899217769141.txt)

**Comment by AliveDevil** [comment]
Thanks for reporting, until now we only support the default built-in ssh-agent pipe (was quite the effort to get that working).
The ssh agent pipe is hardcoded[^WindowsSSH] to `\\.\pipe\openssh-ssh-agent`.
[^WindowsSSH]: https://github.com/iterate-ch/cyberduck/blob/master/ssh/src/main/java/ch/cyberduck/core/sftp/openssh/WindowsOpenSSHAgentAuthenticator.java#L30

@dkocher We need a `AgentAuthenticatorFactory`, where we can override e.g. UnixOpenSshAgentAuthenticator and WindowsOpenSshAgentAuthenticator in client-code.

**Comment by AliveDevil** [comment]
Root-issue for this lies in #5330, where our path sanitization just straight up bails out and fails hard.
