### ISSUE TITLE
Cyberduck crashes when I try to open the Preferences Dialog (v8.5.0)

### ISSUE THREAD

**Issue by weberhans** [iterate-ch/cyberduck#13943]
Paid for a license, but it's not much use if I can't even configure it. 
Windows 7 Pro x64

Log file: 
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10159278/cyberduck.log)

Crash report:
[638054335292899416.txt](https://github.com/iterate-ch/cyberduck/files/10159280/638054335292899416.txt)

![image](https://user-images.githubusercontent.com/42043895/205774725-aff354b4-8f57-41aa-8ad9-c9851364b100.png)

**Comment by ylangisc** [comment]
Per our download page Cyberduck requires Windows 10 (14393) or later. The latest installer should not allow you to install Cyberduck. A version [prior 8.4.0](https://cyberduck.io/changelog/) should work on Windows 7.

**Comment by weberhans** [comment]
Thank you! Sorry I did not see that!
