### ISSUE TITLE
Open Terminal adds wrong quotation mark to ssh-command

### ISSUE THREAD

**Issue by martinstoehr** [iterate-ch/cyberduck#13942]
M1 MBP
MacOS Ventura 13.0.1
Version 8.5.1 (38745)

With the update to 8.5.1 Cyberduck adds an additional quotation mark at the beginning of the ssh-command, when clicking the Terminal-Icon. 
Result is an incomplete terminal-command.

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/13928.
