### ISSUE TITLE
Crash when running network diagnostics

### ISSUE THREAD

**Issue by zmixnyc** [iterate-ch/cyberduck#13948]
I get the following error message:

Connection failed

> DNS lookup for [my ftp name] FTP failed. DNS is the network service that translates a server name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing access to the network.

It was working perfectly the day before and I changed nothing in my system. It's possible that it's specific to the 8.5.1 update? All other programs are working fine online.

Here is the crash report:

[Cyberduck Crashing.txt](https://github.com/iterate-ch/cyberduck/files/10166705/Cyberduck.Crashing.txt)

**Comment by dkocher** [comment]
```
Thread 33 Crashed::  Dispatch queue: NSOperationQueue 0x7f9dfa36bde0 (QOS: UNSPECIFIED)
0   libsystem_kernel.dylib        	    0x7ff8178ed00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8179231ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff81786ed24 abort + 123
3   libjvm.dylib                  	       0x11bd66181 os::abort(bool, void*, void const*) + 49
4   libjvm.dylib                  	       0x11bfca7d8 VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long) + 2968
5   libjvm.dylib                  	       0x11bfc9c0c VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*, char const*, ...) + 156
6   libjvm.dylib                  	       0x11bfca881 VMError::report_and_die(Thread*, unsigned int, unsigned char*, void*, void*) + 33
7   libjvm.dylib                  	       0x11be9264b JVM_handle_bsd_signal + 363
8   libsystem_platform.dylib      	    0x7ff817938dfd _sigtramp + 29
9   ???                           	               0x0 ???
10  CFNetwork                     	    0x7ff81c400f24 CFNetDiagnosticCreateWithURL + 24
11  libcore.dylib                 	       0x11904856b -[CDReachabilityMonitor diagnoseInteractively] + 29
```

**Comment by zmixnyc** [comment]
My main problem is that it's unable to connect.  The crash is of secondary importance here, can someone offer advice on how I can get back online with Cyberduck?

**Comment by dkocher** [comment]
> My main problem is that it's unable to connect. The crash is of secondary importance (to me!) I've re-filed my original issue individually.

In #13950.

**Comment by ekmixon** [comment]
> I get the following error message:
> 
> Connection failed
> 
> > DNS lookup for [my ftp name] FTP failed. DNS is the network service that translates a server name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing access to the network.
> 
> It was working perfectly the day before and I changed nothing in my system. It's possible that it's specific to the 8.5.1 update? All other programs are working fine online.
> 
> Here is the crash report:
> 
> [Cyberduck Crashing.txt](https://github.com/iterate-ch/cyberduck/files/10166705/Cyberduck.Crashing.txt)

this exact same behavior is also happening to me.

**Comment by dkocher** [comment]
The current implementation uses [deprecated API](https://developer.apple.com/documentation/cfnetwork/1426741-cfnetdiagnosticcreatewithurl?language=objc).

**Comment by dkocher** [comment]
Should possibly be reimplemented using [NWPathMonitor](https://developer.apple.com/documentation/network/nwpathmonitor).

**Comment by dkocher** [comment]
Testing on macOS 13.1 this has been disabled and prints in log

```
2023-01-19 13:44:02.004705+0100 0x12241d   Error       0x0                  42156  0    Cyberduck: (CFNetwork) CFNetDiagnosticDiagnoseProblemInteractively is no longer supported. Please stop using it.
```
