### ISSUE TITLE
Cyberduck 8.5.1 fails DNS lookup

### ISSUE THREAD

**Issue by zmixnyc** [iterate-ch/cyberduck#13950]
I get the following error message:

Connection failed

    DNS lookup for [my ftp name] FTP failed. DNS is the network service that translates a server name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing access to the network.

It was working perfectly the day before and I changed nothing in my system. It's possible that it's specific to the 8.5.1 update? All other programs are working fine online.

**Comment by dkocher** [comment]
The error indicates that the DNS server you are using to resolve hostnames most probably from your Internet hosting provider is unable to determine the address. Contact your hosting service provider for help with your setup.

**Comment by zmixnyc** [comment]
> The error indicates that the DNS server you are using to resolve hostnames most probably from your Internet hosting provider is unable to determine the address. Contact your hosting service provider for help with your setup.

That may be, but it all works fine on 2nd computer, using the same version of Cyberduck..

What should I look at to see where any differences might be?

**Comment by aleclevy** [comment]
Found the solution! Thanks for the help.
