### ISSUE TITLE
it show "cmdand dquote>" when Open in Terminal (Mac)

### ISSUE THREAD

**Issue by sonicwong** [iterate-ch/cyberduck#13954]
**Describe the bug**
it show "cmdand dquote>" when "Open in Terminal" (Mac)

**To Reproduce**
1. Go to 'menu bar'
2. Click on 'Open in Terminal'
3. it show "cmdand dquote>"

**Expected behavior**
it normal cli environment in v8.5.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 8.5.1

**Comment by map-g** [comment]
Having the same issue. Cyberduck seems to prepend the command with a double quote ("). Same command w/o the prepended double quote works fine.

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/13928.
