### ISSUE TITLE
hang on upload files

### ISSUE THREAD

**Issue by superlbr** [iterate-ch/cyberduck#13967]
It's Macos 13.0 with version 8.5.2 (38799).
When drag files in sftp, Transfer window display login success for a while, but no file or floder transfered.
Only work after drag a file or a single floder already, and overwrite file window popup.

**Comment by superlbr** [comment]
why not reuse sftp connection already or use a connection pool, instead of create a new connection to transfer files.
for little files such as webpack buildings, which could be detected before upload, use a compress and then decomporess as a fast upload channel.

**Comment by dkocher** [comment]
You can choose to use the connection from the browser for file transfers [^1].

[^1]: https://docs.cyberduck.io/cyberduck/transfer/#transfers-general-browser-connection-for-file-transfers
