### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by costacarsten** [iterate-ch/cyberduck#13964]
Hello folks,
For a few weeks now, the program has been crashing when trying to upload files. regardless of whether it's drag & drop or the upload button. Files are relatively small in kb, not huge volume. I use the last version as well as Windows 10 Version 22H2 x64.
I am a supporter(donator) of the Cyberduck program and hope for your help.
Thank you

**Comment by ylangisc** [comment]
Cleaning the entries in the transfer windows might help.

**Comment by costacarsten** [comment]
Thanks for the quick reply, Press this button or the File Transfer menu item triggers exactly the same thing, leads to freezing and a crash.

**Comment by ylangisc** [comment]
You can delete the old transfer entries through Explorer navigating to `%APPDATA%/Cyberduck/Transfers` and delete all files.

**Comment by costacarsten** [comment]
You guys are great, that helped right away. Will donate again today!
