### ISSUE TITLE
Missing scheme and hostname in Web URL

### ISSUE THREAD

**Issue by tangix** [iterate-ch/cyberduck#13978]
**Describe the bug**
The Web URL from a Bookmark does not show properly in Copy or Open URL context menu when right-clicking on an item.

**To Reproduce**
1. Configure Web URL on a Bookmark
2. Connect to the Bookmark
3. Right-click on an item and go to the Copy URL menu

**Expected behavior**
The Web URL should be added to the URL of the item, not `null`.

**Screenshots**
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/1013635/207431705-d18cc4a6-f058-48e2-b029-ba96a3939106.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.2
 - Version 8.5.1 (38745)

**Comment by dkocher** [comment]
I cannot seem to reproduce this running 8.5.5

<img width="1694" alt="Screenshot 2023-02-03 at 15 54 23" src="https://user-images.githubusercontent.com/71733/216634279-3da558dd-3712-4fbe-bff9-d3580c77ea33.png">

**Comment by tangix** [comment]
So, you must have fixed it ;-)
