### ISSUE TITLE
Username being added to server url

### ISSUE THREAD

**Issue by Arcadium21** [iterate-ch/cyberduck#13975]
So I'm trying to connect to a server but for some reason when I go into "Open Connection", type out the server name, and then start adding my username for the login info it adds my username to the server url which is preventing me from getting into the server. So instead of the server url appearing as "ftp://servername.com", the moment I start entering my username it appears as "ftp://username@gmail.com@servername.com"

Anyone encounter this before?

**Comment by AliveDevil** [comment]
This is just for informational/display purposes.
