### ISSUE TITLE
Rename file within OneDrive folder causes crash

### ISSUE THREAD

**Issue by subatomiq** [iterate-ch/cyberduck#13979]
Hello, Every single time i rename a file in a onedrive folder, cyberduck hard crashes
once re-launched, upon inspection, the file rename has always completed successfully

**Comment by subatomiq** [comment]
crash report here - [638066479210794895.txt](https://github.com/iterate-ch/cyberduck/files/10227026/638066479210794895.txt)

**Comment by AliveDevil** [comment]
I'll link #10785 here. Unsure if same origin.
Need more time to investigate here.
