### ISSUE TITLE
Architecture issue

### ISSUE THREAD

**Issue by Deepi05ka** [iterate-ch/cyberduck#13989]
Hi,

I installed the old version successfully for 32bit and 64bit .Now I am trying to update to the newer version  Cyberduck "8.5.2.38799"
64bit architecture. After installation, the 64 bit (8.5.2.38799) package saves in the registry file to a 32bit location.
x64 installer doesn't exist for this software??

**Comment by AliveDevil** [comment]
Cyberduck is a 64-bit application, and the installer refuses to install on 32-bit architecture.

The installer framework may write to some WOW6432-registry entries, due to it being a 32-bit process. Nothing wrong here.
