### ISSUE TITLE
Does not overwrite existing file on upload

### ISSUE THREAD

**Issue by ematvey** [iterate-ch/cyberduck#13980]
Version: 8.5.2 (38799)
Windows 11 Home 10.0.22621 Build 22621
Target: Google Cloud Storage bucket 

I have several issues:
1. Cyberduck does not overwrite files when uploading the file with the same name as existing
2. Editing files in-place similarly doesn't change file content
3. When I try to delete a file on remote, Cyberduck plainly crashes

**Comment by dkocher** [comment]
Please attach the [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) and the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
