### ISSUE TITLE
Copying file via sftp from remote to local by dragging would not complete

### ISSUE THREAD

**Issue by afelong** [iterate-ch/cyberduck#13984]
macOS Ventura 13.1, Cyberduck 8.5.2 - on local network dragged file from Raspberry Pi 4 to desktop.  File was 14MB but kept downloading past 42MB in size before I cancelled copy.  Tried several times.  I did a command line "scp" from Mac and file transferred OK.  Looked at partial file in Finder:

![Screenshot 2022-12-14 at 10 37 50 AM](https://user-images.githubusercontent.com/48457721/207684360-759baba6-c705-4955-997a-77c0763899d1.png)

Looking at other issues, this may be same or similar to: #13922

**Comment by dkocher** [comment]
Please reproduce and include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.

**Comment by dkocher** [comment]
Please let us know if you can reproduce after unchecking _Preferences → Transfers → Segmented downloads with multiple connections per file_.

**Comment by dkocher** [comment]
Duplicate for #13922.
