### ISSUE TITLE
transferencia de conexoes

### ISSUE THREAD

**Issue by pizzocaro** [iterate-ch/cyberduck#14003]
ola boa tarde !

Tudo bem ?
Meu nome é Jefferson, gostaria de saber se é possivel enviar as conexoes de um mac para outro mac , de forma que fique todas as conexoes compartilhadas em mais de um macOS, desde já agradeço obrigado !!!
skynet.pizzocaro@gmail.com

hey good afternoon !

All right ?
My name is Jefferson, I would like to know if it is possible to send connections from one mac to another mac, so that all connections are shared in more than one macOS, thank you in advance!
skynet.pizzocaro@gmail.com

**Comment by tatze96** [comment]
You can follow the steps on our [wiki page](https://docs.cyberduck.io/cyberduck/bookmarks/#sharing-bookmarks-between-different-computers) to share your created bookmarks between multiple computers. Note that this only works correctly while using the standalone version of Cyberduck.
