### ISSUE TITLE
Problema ftp-ssl

### ISSUE THREAD

**Issue by assicairo** [iterate-ch/cyberduck#14008]
Buon giorno,
abbiamo un problema con Cyberduck con macOS Big Sur che durante il trasferimento dei file si interrompe andando in errore generico (in allegato)
![Errore_Cyberduck](https://user-images.githubusercontent.com/121113084/208699532-bf4fd904-4e23-4e3c-918e-d43f65100429.png)
Abbiamo provato diverse versioni di Cyberduck con Big Sur esempio 8.0.0 ecc.. ma il problema persiste.
Usando altri macOS come 10.7.5 - 10.10.5 - 12.0 funziona correttamente
Potete verificare?
grazie

Assistenza

**Comment by dkocher** [comment]
try to resolve the issue with the assistance of your hosting service provider.
