### ISSUE TITLE
Can't open registration key document

### ISSUE THREAD

**Issue by GSmithCFFC** [iterate-ch/cyberduck#14006]
**Describe the bug**
I downloaded the Cyberduck license registration document but it will not open in Adobe acrobat

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/121043553/208460029-3b691d6c-0bc2-4244-ba70-096adbbe7d72.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Cassie205** [comment]
The registration key is not meant to be opened. After downloading simply double-click on the file to copy it to the application support folder. Alternatively, move the file to the application support folder manually. Refer to our [documentation](https://docs.cyberduck.io/cyberduck/support/#application-support-folder).
