### ISSUE TITLE
B2 download is greater than the file

### ISSUE THREAD

**Issue by ackerthehacker2** [iterate-ch/cyberduck#14025]
I am downloading a 1.7TB B2 snapshot.   Right now CD says it downloaded 2.3TB but on the disk, it's 1.77TB.   Something is not right here ,,,,,as how can something be bigger than it is:

![image](https://user-images.githubusercontent.com/38703791/209956315-49220041-984f-470b-9626-5d03cb0590c5.jpeg)

The above screen shot shows 135%

**Comment by ackerthehacker2** [comment]
After close to 400%, I finally got this:
![image](https://user-images.githubusercontent.com/38703791/210016728-441ddd39-e4ed-4d38-bf07-5e59c1d514ff.png)

I am now running it with debug turned on to see if I can capture any intersting information.

**Comment by ackerthehacker2** [comment]
I now how two connections from B2 over 100% .. is this a B2 issue or a CD issue?
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10322372/cyberduck.log)

**Comment by ackerthehacker2** [comment]
Is this #13374 that I am seeing?

**Comment by hthappy** [comment]
I also encountered this problem, have you solved it?

**Comment by dkocher** [comment]
Duplicate for #13374.
