### ISSUE TITLE
Duck CLI: Cannot invoke "ch.cyberduck.core.PathAttributes.getRegion()"

### ISSUE THREAD

**Issue by jasttw** [iterate-ch/cyberduck#14028]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
using CLI Cyberduck 8.5.3 (38959). I am not able to authenticate cloud services. When i type `duck --list onedrive:` I get this (removed client ID from links):

OneDrive connection opened…
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=(...)&code_challenge_method=S256&redirect_uri=https://cyberduck.io/oauth&response_type=code&scope=files.readwrite.all%20offline_access%20user.read&state=STqI
Disconnecting [graph.microsoft.com](http://graph.microsoft.com/)…
Unknown. Cannot invoke "ch.cyberduck.core.PathAttributes.getRegion()" because the return value of "ch.cyberduck.core.Path.attributes()" is null.

the same thing happens when i try `duck --list dropbox:/`

Dropbox connection opened…
https://www.dropbox.com/1/oauth2/authorize?client_id=(...)&code_challenge=(...)&code_challenge_method=S256&redir
Disconnecting [www.dropbox.com](http://www.dropbox.com/)…
Unknown. Cannot invoke "ch.cyberduck.core.PathAttributes.getRegion()" because the return value of "ch.cyberduck.core.Path.attributes()" is null.

**To Reproduce**
1.Enter the command `duck --list onedrive:` or `duck --list dropbox:/`

**Expected behavior**
Print a list of files in the cloud service or authenticate the account if it was not authenticated.

**Desktop (please complete the following information):**
 - Raspberry PI OS Debian Bullseye
 - Ubuntu Server 22.04

**Comment by AliveDevil** [comment]
Confirmed here, thanks for bringing this to our attention.

**Comment by AliveDevil** [comment]
We aren't waiting for oauth prompt, thus continuing and failing.
```
[background-1] WARN  ch.cyberduck.core.threading.AbstractRetryCallable - No retry for failure BackgroundException{class=class ch.cyberduck.core.exception.LoginCanceledException, file=null, message='null', detail='Access denied', cause='BackgroundException{class=class ch.cyberduck.core.exception.LocalAccessDeniedException, file=null, message='Access denied', detail='Failed to launch web browser for https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=f40bc18f-cd02-4212-b7f1-15243e4e2ad3&code_challenge=M-DHg0jIKSh7bqqQSBp_yqWwR-JrUpQxBN0Ob2w1DLE&code_challenge_method=S256&redirect_uri=https://cyberduck.io/oauth&response_type=code&scope=files.readwrite.all%20offline_access%20user.read&state=2DEFDpwe&prompt=select_account', cause='null'}'}
```

Something here: https://github.com/iterate-ch/cyberduck/commit/d684c5cb553cf56adec767fab1d20066e34335ba

Need to change TerminalPreferences to reflect changes in Preferences factories:
https://github.com/iterate-ch/cyberduck/commit/056a87d73615d8f20ffb71a95d520d33466315a1#diff-06a3023764b6e7863df7d32b2ced43a2beabe0fb97d5128927eb301bd5442449R1384
