### ISSUE TITLE
AWS SSO, A non-empty Access Key (AKID) must be provided in the credential.

### ISSUE THREAD

**Issue by charltonstanley** [iterate-ch/cyberduck#14027]
**Describe the bug**
aws sso cannot be used when attempting to access s3 buckets using the `duck` command. It seems that the duck command is looking in the `~/.aws/config` or `~/.aws/credentials` files for an access key id, however when using aws sso, no access key id is supposed to be configured in there. 

**To Reproduce**
1. create `~/.aws/credentials with the following contents:
```[default]
region = us-east-1
output = json
sso_start_url = https://REDACTED_SSO_DOMAIN.awsapps.com/start#/
sso_region = us-east-1
sso_account_id = REDACTED_AWS_ACCOUNT_NUMBER
sso_role_name = FullAdmins
```
2. login using `aws sso login` followed by `aws sts get-caller-identity`
3. download and save the `S3 (Credentials from AWS Command Line Interface)` profile to `~/.duck/profiles/
4. run duck --list s3-cli:/REDACTED_BUCKET_NAME/ 
5. command finishes with: `Listing directory REDACTED_BUCKET_NAME failed. The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential. Please contact your web hosting service provider for assistance.`

**Expected behavior**
```
Listing directory REDACTED_BUCKET_NAME...
file1.txt
file2.txt
file3.txt
```

**Screenshots**
n/a

**Desktop**
 ```
cat /etc/os-release                                                                                                                                                         
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

[cyberdug_sso_debug.log](https://github.com/iterate-ch/cyberduck/files/10326173/cyberdug_sso_debug.log)

**Additional context**
I'm happy to provide additional logs and to test any potential fixes if need be. Thank you!

This could be a duplicate of #13725 but it seems like it may be slightly different.

**Comment by electricsheep14** [comment]
I am facing a similar issue attempting to access a bucket using STS temporary credentials via an Assume Role. I suspect that Cyberduck seems to insist on getting the bucket's location before performing a listing, but such privilege hasn't been granted to the profile assigned to the role being used:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html

Cyberduck appears to give up after being rejected for the Location? call, and does not attempt to perform a listing on the provided bucket and path.

**Comment by dkocher** [comment]
> I am facing a similar issue attempting to access a bucket using STS temporary credentials via an Assume Role. I suspect that Cyberduck seems to insist on getting the bucket's location before performing a listing, but such privilege hasn't been granted to the profile assigned to the role being used:
> 
> https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLocation.html
> 
> Cyberduck appears to give up after being rejected for the Location? call, and does not attempt to perform a listing on the provided bucket and path.

We need to have permission to obtain the location of the bucket to defer the correct API endpoint to use.

**Comment by charltonstanley** [comment]
> We need to have permission to obtain the location of the bucket to defer the correct API endpoint to use.

In my case, the permission level I had for this attempt was full administrative permissions to the entire aws account, so I don't believe insufficient permissions is what is hindering me.

**Comment by dkocher** [comment]
Not sure why it does not work, but it should be supported with #554.

**Comment by dkocher** [comment]
The log output 

```
[background-1] DEBUG ch.cyberduck.core.sts.STSCredentialsConfigurator - Look for profile name  in Local{path='/home/myuser/.aws/config'} and Local{path='/home/myuser/.aws/credentials'}
[background-1] DEBUG ch.cyberduck.core.sts.STSCredentialsConfigurator - Reading AWS file Local{path='/home/myuser/.aws/credentials'}
```

suggests that no username is set. Please run `duck`  with the `--username` argument matching the name of the profile in `~/.aws/credentials`.
