### ISSUE TITLE
Saving file from Brackets editor does not upload changes

### ISSUE THREAD

**Issue by DJPVMA** [iterate-ch/cyberduck#14022]
When I save a file in Brackets on Mac, it won't upload to save changes sometimes, and recently, if I disconnect and reconnect, it will download and open the file, but saving the file does nothing to update my page.

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection and let us know the protocol in use after reproducing with version 8.5.5.

**Comment by DJPVMA** [comment]
I have no idea what you even just said to me, but I quit using that garbage
and switched back to filezilla. 🤷🏻‍♂️
