### ISSUE TITLE
Failed to launch web browser to prompt authorization for OneDrive

### ISSUE THREAD

**Issue by ErwonB** [iterate-ch/cyberduck#14035]
I have got the following error when trying to setup the connection with OneDrive :
```
WARN  ch.cyberduck.core.threading.AbstractRetryCallable - No retry for failure BackgroundException{class=class ch.cyberduck.core.exception.LoginCanceledException, file=null, message='null', detail='Access denied', cause='BackgroundException{class=class ch.cyberduck.core.exception.LocalAccessDeniedException, file=null, message='Access denied', detail='Failed to launch web browser for https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=...=select_account', cause='null'}'}
```
I used the following command : `duck --list onedrive:/ --debug`
I tried running with sudo, same issue.

Any idea on how to be able to authorize to launch the web browser ?

PS : I'm on Linux Mint 21 Cinnamon (5.4.12)

**Comment by dkocher** [comment]
Relates to #14028 and should be resolved with #14031 where we fail to open a desktop web browser but print the authorization URL to the command line instead.
