### ISSUE TITLE
Can't remember password in the latest build

### ISSUE THREAD

**Issue by h840027624** [iterate-ch/cyberduck#14063]
When I copy my Access Key ID, the password can't update and I can't connect directly with the Save Password checkbox opened. I need enter password by myself every time.

I install the old build version, when I copt the Access Key ID, the password will show directly, I dpn't need enter the password and I can connect directly.

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
