### ISSUE TITLE
Copy URL menu item stops working after hovering it at folder context menu

### ISSUE THREAD

**Issue by DmitriyYukhanov** [iterate-ch/cyberduck#14069]
**Describe the bug**
Copy URL menu item stops behaving properly if I hover it in folder context menu while being connected to the Backblaze B2.

**To Reproduce**
1. Connect to Backblaze B2 Cloud Storage.
2. Create a new folder "Folder 1" inside public directory.
3. Put any file "File 1" into the folder you just created.
4. Right-click "File 1" and hover "Copy URL >" context menu item to see it has the "HTTPS URL" inside.
5. Right-click "Folder 1" and hover "Copy URL >" context menu item.
6. See the ">" part of the menu item disappears (i.e. it now has no nested items).
7. Now right-click "File 1" and see Copy URL > doesn't expand into "Copy Url > HTTPS URL" anymore and clicking it doesn't produce any effect either.

**Expected behavior**
I expect Copy URL to be disabled for folders if it's not possible to share their URL and I expect it to keep working for sharable files after hovering in folders context menu.

**Screenshots**

https://user-images.githubusercontent.com/883587/211783119-c311abbf-7f43-4db3-90ce-173077965a37.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Version: 8.5.4

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10391407/cyberduck.log)

**Comment by AliveDevil** [comment]
Is this a workaround you'd be comfortable with?

https://user-images.githubusercontent.com/734738/212096540-dd9e613c-1b8c-4b7e-9c82-6332591b9d00.mp4

**Comment by DmitriyYukhanov** [comment]
Hi @AliveDevil, looking great to me, thanks!
