### ISSUE TITLE
ConcurrentModificationException while editing Bookmark nickname

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#14064]
```
Top-level Exception
Type:        java.util.ConcurrentModificationException
Message:     
Source:      Cyberduck
Stack Trace: bei Ch.Cyberduck.Ui.Controller.AsyncController.invoke(MainAction runnable, Boolean wait)
   bei Ch.Cyberduck.Ui.Controller.WindowController.invoke(MainAction mainAction, Boolean wait)
   bei Ch.Cyberduck.Ui.Controller.BrowserController.collectionItemChanged(Object obj)
   bei ch.cyberduck.core.Collection.collectionItemChanged(Object item)
   bei ch.cyberduck.core.AbstractFolderHostCollection.collectionItemChanged(Host bookmark)
   bei Ch.Cyberduck.Ui.Controller.BookmarkController`1.View_ChangedNicknameEvent()
   bei Ch.Cyberduck.Ui.Controller.VoidHandler.Invoke()
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   bei System.Windows.Forms.TextBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by AliveDevil** [comment]
Not reproducible with `bookmarks.folder.monitor=false`.

**Comment by AliveDevil** [comment]
What's been the reason to not just use `ArrayList.set()` instead of remove/add? @dkocher

**Comment by dkocher** [comment]
> What's been the reason to not just use `ArrayList.set()` instead of remove/add? @dkocher

I cannot remember a reason but it should not make any difference.

**Comment by AliveDevil** [comment]
Didn't find a commit for that either.
https://github.com/iterate-ch/cyberduck/commit/742ac9acba0e02efd01b7e87fd58bfb36e4cf039#diff-031f5eb11f191853eefae2fd605dc11681a92f120b035e14c2719158d5c9cb1fR132-R135

commit message and content don't reveal any reason for add/remove.

**Comment by AliveDevil** [comment]
> Basically:
> Nickname Change -> Item Changed (Save^) -> Populate Quick Connect (Async)
> Save^ -> Write to File
> Watcher -> Detect File Write -> Replace Host entry -> Invalidate all collection iterators
> PopulateQuickConnect crashes, due to invalidated collection iterator

https://github.com/iterate-ch/cyberduck/issues/14064#issuecomment-1477639812
