### ISSUE TITLE
Transfers no longer working with 8.5.4

### ISSUE THREAD

**Issue by Smiley006** [iterate-ch/cyberduck#14076]
8.5.4 not working with preset transfer which had been working fine for years. Results in 0 bytes transferred and transfer incomplete with all of the various transfers I have previously set up. They were working perfectly well yesterday. I reinstalled 8.5.3 , using time machine, and the transfers worked properly after that.
Using iMac, running Monterey 12.6.2. 
Thanks,
Harry

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
