### ISSUE TITLE
Cyberduck Freeze

### ISSUE THREAD

**Issue by Crefelder** [iterate-ch/cyberduck#14072]
Bei mir unter Windows 10 Pro friert Cyberduck direkt beim Start ein und wenn der Cursor darüber steht, wird nur der Wartecursor angezeigt. Es wird auch nicht mehr der Servermanager angezeigt bei Start sondern nur das Verbindungsfenster.

For me on Windows 10 Pro, Cyberduck freezes right at startup and when the cursor is over it, only the wait cursor is displayed. The server manager is also no longer displayed when starting, only the connection window.

Installer-Version: 8.5.3.38959

![image](https://user-images.githubusercontent.com/7198153/211820656-a8ec3d1c-e312-43fa-9538-466e4df4786c.png)

**Comment by AliveDevil** [comment]
Please update manually to [8.5.4](https://cyberduck.io/download/).

If the freezes on startup still occur, please perform these steps:
- Create file "default.properties" in `%AppData%\Cyberduck`, with contents:
```
logging=debug
```
- Remove the "cyberduck.log" file in the same directory
- Start Cyberduck, once you determined it froze attach the cyberduck.log file to your reply on Github.com (email attachments don't work).

You may try to clean the history (`%AppData%\Cyberduck\History`) and transfers-list (`%AppData%\Cyberduck\Transfers`).

Additionally you can check if a bookmark is creating these issues by moving all bookmarks (`%AppData%\Cyberduck\Bookmarks`) out of that directory, then populating that directory one-by-one with the previous bookmarks (restarting Cyberduck inbetween).

**Comment by Crefelder** [comment]
I can see a NullPointerException at ch.cyberduck.core.DeserializerFactory.create(DeserializerFactory.java:39) ~[Cyberduck.Core.DLL:20fb21293d329b033c46128924ec6f1d4c305dd2].

After clearing History and Transfers folders i got it start running again.

Many thanks!

Best, André
