### ISSUE TITLE
Multi Account Issue

### ISSUE THREAD

**Issue by 1621391916** [iterate-ch/cyberduck#14087]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Same as #14086 , When I choosed Microsoft OneDrive, all the input boxes are greyed. There's no problem if I have only one OneDrive account. When I clicked the bookmark, it will open a web page to start authorization. 
The problem is, I have multi OneDrive accounts, When I clicked a new bookmark, it will directly open the first account I added before. 

Same situation as #10562 descriped, but I just don't kown how to **_'enter a different username when creating another bookmark for the same provider that uses OAuth for authentication to trigger the authentication flow in the browser to obtain the authentication code using your other credentials to login._**' since all the input box are greyed out. [Official Docs](https://docs.cyberduck.io/protocols/onedrive/#multiple-accounts) also viewed

**To Reproduce**
1. Go to Bookmark->New Bookmark
2. Click on Microsoft OneDrive
4. All the input box are greyed out. See Screenshots

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/42343279/212594587-64058564-ae3f-48e8-816e-fb496eac853a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 22H2 22621.1105
 - Cyberduck Version 8.5.4 (39083)

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
In da03857e. This is a regression in the latest version as we are storing OAuth credentials in the keychain without user specific information. As a workaround, delete the entries in the login keychain that do not contain any username for the service you are connecting to. For example for Google Drive these entries will have a Account set to Google Drive OAuth2 Access Token. Open Keychain Access.app to edit.

Then update to the latest snapshot build available which will always store tokens including usernames in the format Service (Username) OAuth2 Access Token.

**Comment by 1621391916** [comment]
Still not working for me, maybe I didn't get your idea because I'm not a native English speaker. However, **I found another way to fix it.**

The problem is, when I already have a onedrive bookmark and create a new one, I can't change the username because the input box is grayed out and was written with the username of the previous bookmark. Therefore, modifying the new bookmark is all I need.

**So my solution is, go to %AppData%\Cyberduck\Bookmarks, find the new bookmark you create, and edit with notepad, change the username, then reconnect in Cyberduck. It will start a new authorization.**

**Comment by bgriffen** [comment]
Indeed, also greyed out for me and no way to change my authentication account/email (macosx) for my bookmarks. :(
