### ISSUE TITLE
Unable to create a Google Drive Bookmark

### ISSUE THREAD

**Issue by TonyTTTT** [iterate-ch/cyberduck#14086]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Unable to create a Google Drive Bookmark.  All Items are 'greyed out'

**To Reproduce**
1. Go to Bookmark->New Bookmark
2. Click on Google Drive
3. All input boxes are greyed out

**Expected behavior**

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.1
 -  Cyberduck Version 8.5.4 (39083)

**Additional context**

<img width="465" alt="Screenshot 2023-01-15 at 11 25 59 AM" src="https://user-images.githubusercontent.com/69021504/212553649-8a7acc5b-2e70-4ae1-b20e-be6cddf10364.png">

**Comment by Cassie205** [comment]
You don't have to enter any specific log in information. Once you connect to the bookmark, the OAuth will lead you to the google login page.

**Comment by TonyTTTT** [comment]
Ah!  I see now, thanks.
