### ISSUE TITLE
Connection failures with segmented downloads using multiple connections per file

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/cyberduck#14081]
When downloading a file while having the segmented downloads enabled, the download either hangs and resumes afterward or is stuck in a download cycle downloading the file until it has reached 100% multiple times and hangs afterward.

Log shows "Connection Failed" errors but with different causes depending on the server. Disabling segmented downloads resolves the download behavior.

**Comment by dkocher** [comment]
Relates to #13634.

**Comment by dkocher** [comment]
Duplicate for #13374.
