### ISSUE TITLE
"Open new browser window on startup" should be positioned more cleverly to not conflict/cover windows restored via "Save Workspace"

### ISSUE THREAD

**Issue by porg** [iterate-ch/cyberduck#14083]
## My Preferences
- General → ☑︎ Save Workspace
- Browser → ☑︎ Open new browser window on startup

## My screen/window setup
- I split the screen into 4 equal quarters: top-left, top-right, bottom-left, bottom-right, and position my windows in those quarters.

## Terminology in this report
- **browser-window:** refers to a window with an active connection (a concrete instance).
- **bookmark-window:**  refers to a blank browser window in its initial state when it shows the bookmarks and has no active connection yet, that you get with: File →  New Browser ( ⌘ N) or from the preference ☑︎ Open new browser window on startup.

## Reproduction
- Upper left: bookmark-window
- Upper right: browser-window at host1
- Bottom right: browser-window at host2
- Quit Cyberduck.
- Re-open Cyberduck.

## Actual
- All windows open at their last position.
  - ✅ That is the case for the browser-windows.
    - Mostly at least. Sometimes one fewer opens than when you quit. Maybe connected to the next symptom.
  - ❌ bookmark-window: Gets opened but often at uncomprehensible position.
    - Often covering active browser-windows.

## Expectation for: ☑︎ Open new browser window on startup
When you quit Cyberduck → Do this on startup:
1. Single bookmark-window open  → Restore with this size and position on startup.
2. No bookmark-window → Restore with size and position where the last blank bookmark was that was
    - a) closed in its initial state (never got active browser in its lifecycle).
    - b) opened in its initial state and got a browser window, and then closed.

That way you can specify a preferred position for the new bookmark window on startup, that does not cover restored browser-windows. Would be an assistance that naturally follows you (and your changing preferences) and not get into your way.

## Alternatives / Workaround
1. Use ☑︎ **Save Workspace** and ☐ **Open new browser window on startup** and create a new browser window when you need it with ⌘-N.
    - Pro users will choose this route most likely.
2. ☑︎ **Open new browser window on startup** gets nearby companion preference ☑︎ …if app starts with no other window being open(ed).
    - That's technically simple to implement and already improves the UX significantly: No bookmark-window will ever cover a browser-window (as currently the case which is disorienting/confusing)
3. My proposal above is the most adaptive solution, but possible harder to implement. Solution 2 would be just as fine.

**Comment by porg** [comment]
Note: Added "Alternatives / Workaround" to my initial post.

**Comment by porg** [comment]
Long time observation (3 weeks, used quite frequently):
- Once you know how this works, and are aware of the pitfalls, it is totally ok.
- But beginners may fall into the pitfalls, hence I documented the resulting usability issues and possible improvements.

**Comment by dkocher** [comment]
Relates to #13801.

**Comment by dkocher** [comment]
This has been revised with #14993.
