### ISSUE TITLE
FTPaccess

### ISSUE THREAD

**Issue by h-watanabe1222** [iterate-ch/cyberduck#14094]
Thank you for your time.
I'm using Cyberduck's FTP to access a Windows FTP server.
As a result of trying to download all files under an arbitrary directory as an event on the FTP client side,
Since the download does not proceed and the screen does not change, I have no choice but to forcibly terminate the tool.
I tried to connect again, but it timed out and I could not connect.
Looking at the log, the connection was successful, but it timed out to get the file list
Access may not be possible, resulting in an FTP 550 error.
Therefore, we are investigating all possible causes.
Do you use NLST command as Cyberduck FTP software?
https://support.microsoft.com/en-us/topic/fix-you-receive-an-error-message-when-no-file-is-found-on-an-ftp-7-5-server- 550-the-system-cannot-find-the-file-specified-c22e68cd-6200-97d8-535c-8625392714f6

please tell me who

**Comment by dkocher** [comment]
Error `550` implies a server failure.
