### ISSUE TITLE
Support ED25519 keys in new OpenSSH format

### ISSUE THREAD

**Issue by panda2134** [iterate-ch/cyberduck#14122]
**Is your feature request related to a problem? Please describe.**
The keys in new openssh format (mainly `id_ed25519` ones) are not supported by CyberDuck yet.

**Describe the solution you'd like**
Support the ED25519 keys in new openssh format

**Describe alternatives you've considered**
Seems to be irrelevant.

**Additional context**
This type of keys starts with:

```
-----BEGIN OPENSSH PRIVATE KEY-----
```

**Comment by dkocher** [comment]
Duplicate for #8548. Is expected to work.
