### ISSUE TITLE
Folder Uploads to Google Drive fail

### ISSUE THREAD

**Issue by truthsword** [iterate-ch/cyberduck#14139]
When I upload a folder containing files to Google Drive, by dragging it from Windows Desktop to the / of Google Drive, the upload fails leaving only an empty folder in Drive.

If I drag the files that were contained in the folder to the / of Google Drive, the file upload succeeds.

I've duplicated this with a second Google Drive account, and using different folders on the Windows Desktop. These same folders upload cleanly to other services (ex. B2).

This issue was first noticed in v8.5.4. Updating to v8.5.5 had no improvement

**Comment by AliveDevil** [comment]
Can reproduce it.

**Comment by AliveDevil** [comment]
Reproducible with duck CLI.

[duck.log](https://github.com/iterate-ch/cyberduck/files/10508592/duck.log)

**Comment by truthsword** [comment]
Still broken on 
![](https://i.imgur.com/nFrwnuz.png)

**Comment by dkocher** [comment]
> Still broken on ![](https://camo.githubusercontent.com/acb9b60fc28be3949ba09ffcc9043ad67ad0409f4011a7420b6dc679bc62cf53/68747470733a2f2f692e696d6775722e636f6d2f6e4672776e757a2e706e67)

I cannot reproduce. Please elaborate on the problem you are still having.

**Comment by truthsword** [comment]
The issue that I spoke of in the OP, I am still having. This was confirmed by subsequent posters in this thread. I'm not sure I understand your question.

Feb 3, 2023 7:01:00 AM David Kocher ***@***.***>:

> I cannot reproduce. Please elaborate on the problem you are still having.

**Comment by AliveDevil** [comment]
Uploads to "/" aren't supported, as that is a virtual directory, only to get you into the different views of Google Drive.

I've been able to upload a folder to e.g. "/My Drive" without any issue.

**Comment by AliveDevil** [comment]
Please enable debug logging in Preferences -> Connection, then click on Show. Quit Cyberduck and delete highlighted log file.
Start Cyberduck, upload a folder, after failure quit Cyberduck and attach the Cyberduck log to your reply on Github (through the Web UI, e-mail attachments don't work) or mention Github 14139 in an e-mail to support@cyberduck.io.

**Comment by truthsword** [comment]
This appears resolved moving from 8.5.5.39206.msi to 8.5.5.39213.msi

Thanks for your help. Issue closed.

**Comment by AliveDevil** [comment]
Glad to hear it worked out.
