### ISSUE TITLE
Deleting large folders with lots of subfolders and files keeps stalling

### ISSUE THREAD

**Issue by mikegull** [iterate-ch/cyberduck#14130]
deleting large folders with lots of subfolders and files (backup images) is problematic, keep stalling and/or not completing deletions.

**Comment by solsticesurfer** [comment]
Also having problems with this except it will crash while deleting files on B2.

**Comment by dkocher** [comment]
Please attach the [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports).

**Comment by solsticesurfer** [comment]
-----------------------------
[General Info]

Application: Cyberduck
Version:     8.5.4.39083
Region:      English (United States)
Date: 1/30/2023
Time: 4:35 PM

User Explanation:

User said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.NullReferenceException
Message:     Object reference not set to an instance of an object.
Source:      ObjectListView
Stack Trace: at BrightIdeasSoftware.TreeListView.TreeRenderer.HandleHitTest(Graphics g, OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.BaseRenderer.HitTest(OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.OlvHitTest(Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.BuildCellEvent(CellEventArgs args, Point location)
   at BrightIdeasSoftware.ObjectListView.HandleMouseMove(Point pt)
   at BrightIdeasSoftware.ObjectListView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
System.Windows.Forms, Version=4.0.0.0
System, Version=4.0.0.0
System.Drawing, Version=4.0.0.0
Cyberduck.Core.Native, Version=8.5.4.39083
System.Memory, Version=4.0.1.1
Cyberduck.Core.Refresh, Version=8.5.4.39083
System.Core, Version=4.0.0.0
System.ServiceModel, Version=4.0.0.0
StructureMap, Version=2.6.4.0
Splat, Version=14.1.0.0
Cyberduck.Core, Version=8.5.4.39083
ObjectListView, Version=2.9.1.1072
CustomOpenFileFolderDialog, Version=0.0.0.0
WindowsFormsIntegration, Version=4.0.0.0
IKVM.OpenJDK.Core, Version=8.0.312.7
System.Design, Version=4.0.0.0
System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0
Cyberduck.Bonjour.Native, Version=8.5.4.39083
System.Reactive, Version=5.0.0.0
System.Security, Version=4.0.0.0
Cyberduck.Protocols, Version=8.5.4.39083
ReactiveUI, Version=17.1.0.0
PresentationFramework, Version=4.0.0.0
Cyberduck.Importer, Version=8.5.4.39083
System.Xml, Version=4.0.0.0
Cyberduck.Bonjour, Version=8.5.4.39083
IKVM.Runtime, Version=8.0.312.7
PresentationCore, Version=4.0.0.0
ReactiveUI.Wpf, Version=17.1.0.0
Cyberduck.Cryptomator, Version=8.5.4.39083
IKVM.OpenJDK.Security, Version=8.0.312.7
IKVM.OpenJDK.Text, Version=8.0.312.7
System.Web, Version=4.0.0.0
Windows.Services.Store.StoreContract, Version=4.0.0.0

-----------------------------

[System Info]

Operating System
-Microsoft Windows 10 Home
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -360
--FreePhysicalMemory = 17508056
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19044

Machine
-MURGATROYD
--Manufacturer = To Be Filled By O.E.M.
--Model = Z690 Pro RS
--TotalPhysicalMemory = 34121383936

-----------------------------

**Comment by dkocher** [comment]
Duplicate for #10785.
