### ISSUE TITLE
drag drop folder for upload to google not working

### ISSUE THREAD

**Issue by alenskas** [iterate-ch/cyberduck#14142]
Hello

when i drag and drop a folder of contents to upload into a folder on google share dive it creates the folder structure, then stops and says transfer incomplete. I then have to double-click the transfer task in the transfer window and tell it to continue. then it works.

this is behavious i have not seen before. how can this be fixed please?

**Comment by AliveDevil** [comment]
Duplicate #14139

**Comment by alenskas** [comment]
@AliveDevil thank you, i see im not th eonly one :D is the issue resolved or are you working on it. apologies i am very new to github

**Comment by AliveDevil** [comment]
We are aware of it, could replicate it and need to investigate here. You can "Subscribe" to the Notifications of the mentioned issue above to get update notifications when we fix it.
