### ISSUE TITLE
Support Google Cloud uploads with service account credentials

### ISSUE THREAD

**Issue by sww314** [iterate-ch/cyberduck#14146]
**Is your feature request related to a problem? Please describe.**
I want to upload files to Google Cloud for non-Google users. Google provides ability to generate service account key (.json file) will limited access to specific buckets and permissions. 

**Describe the solution you'd like**
On the Google Bookmark page, provide a way to insert service account credentials.
Use those credentials instead of Oauth flow as currently setup.

**Describe alternatives you've considered**
Our user accounts have more permissions that we want to use for file uploads in the field.

**Additional context**
I can provide a test bucket and credentials. Or possibly a PR if that works. Although my java is rusty...

**Comment by dkocher** [comment]
Duplicate for #11611.
