### ISSUE TITLE
Inaccurate total transferred number with B2

### ISSUE THREAD

**Issue by glennbugreporting** [iterate-ch/cyberduck#14150]
Hello! I love CyberDuck! 

I was using the latest version to download a huge backup file from Backblaze via their B2 Cloud Service. The first 50 GB of the 900 GB+ file appeared to display correctly. I walked away from the computer for about 20 minutes. When I came back, the display showed over 2 TB download and 600 MB/s speed (I have a 100 MB/s Internet connection), so something went loopy. The temporary file on the local hard drive correctly shows expected download progress (about 90 GB of 900 GB given about 60 MB/s before I walked away).
![Screen Shot 2023-01-27 at 10 47 21 AM](https://user-images.githubusercontent.com/31303045/215170926-cc945eda-be3e-4dd4-8a52-b0dadecf8f5f.png)

**Comment by dkocher** [comment]
Duplicate for #13374.
