### ISSUE TITLE
Transfer incomplete downloading folders from Rasperry Pi

### ISSUE THREAD

**Issue by LastAtlantean** [iterate-ch/cyberduck#14161]
Currently running ver. 8.5.5 and for the last 2 updates am unable to download files to my computer. I have a raspberry pi 4 set up and use Cyberduck to download data as a backup solution. One of my two folders downloads fine with no issues, however the larger of the two gives me an error "transfer incomplete" after preparing approx. 2.2 GB of the data. Was working fine with no issues two updates ago, nothing on my end has changed.

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
