### ISSUE TITLE
Directly copy the path from the path line on Cyberduck window.

### ISSUE THREAD

**Issue by fengli787** [iterate-ch/cyberduck#14167]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
There is a path line in the window. I hope the path can be copied directly from this line to avoid typos in my script.

**Describe alternatives you've considered**
You may make the path line be editable. Then the text can be copied. 

**Additional context**
No.

**Comment by AliveDevil** [comment]
Is `Go To -> Go To Folder` a suitable workaround?

Duplicate for #13875.
