### ISSUE TITLE
Compare function not working

### ISSUE THREAD

**Issue by jmcarousel** [iterate-ch/cyberduck#14175]
The compare function has been broken since 8.5.3. After an upload completes, I copy the folder again and use the"Compare" function to confirm that all the data has been uploaded. Since 8.5.3, this no longer works and instead it re-uploads ALL files in their entirety, even the ones that already exist in that folder. I rolled the app back to 8.5.2 and "Compare" functions as expected.

**Comment by dkocher** [comment]
What protocol are you connecting with?

**Comment by jmcarousel** [comment]
Amazon S3

**Comment by dkocher** [comment]
Must be a regression from #13983 but was supposed to be fixed with 9b6bf431.

**Comment by dkocher** [comment]
I cannot seem to reproduce running version _8.5.5 (39213)_.
