### ISSUE TITLE
Glob pattern operators asterisk * and question mark ? do not work

### ISSUE THREAD

**Issue by porg** [iterate-ch/cyberduck#14179]
## Facts
- #13781 was added in [8.4.5](https://github.com/iterate-ch/cyberduck/milestone/204)
- The [documentation](https://docs.cyberduck.io/cyberduck/browser/#filter-and-search) says:
> Search is case-insensitive and does look for matching sequences in the filename supporting glob patterns * and ?.

## Environment
- Client: Cyberduck 8.5.5 (39213) on macOS 11.7.2 Big Sur
- Server: SFTP, on custom port (5-digits, assigned by my webhost), authentication with SSH key

## Bug
- Both glob pattern operators `*` and `?` do obviously not work, see screen recording (1 image every 3 secs):

https://user-images.githubusercontent.com/737143/216614723-71b2cb79-78c9-4cfe-a3bf-584e0211560c.mp4

**Comment by dkocher** [comment]
What protocol are you connected with?

**Comment by dkocher** [comment]
This currently only works when searching recursively by hitting ⏎ but this is not clearly stated in the [documentation](https://docs.mountainduck.io/cyberduck/browser/#filter-and-search) and there is no reason it should not be applied to the regular filter as well.

**Comment by dkocher** [comment]
It looks to me this is working as expected. Note that
 * Search and filtering is case-sensitive
 * Add a trailing `*` to match any ending

**Comment by porg** [comment]
> What protocol are you connected with?

- Sorry that I forgot this. Also edited this into the initial report:
- Server: SFTP, on custom port (5-digits, assigned by my webhost), authentication with SSH key


> ~This currently only works when searching recursively~ by hitting ⏎ but this is not clearly stated in the [documentation](https://docs.mountainduck.io/cyberduck/browser/#filter-and-search) and there is no reason it should not be applied to the regular filter as well.

Usability recommendation:
- Searching the current directory with globing operators should work like normal literal searches.
- Currently this happens with "on the fly"
  - I performance is an issue, a 2-3sec timeout is ok (show a premature spinner to indicate to the user this is intentional) and when the actual search beging (use a full spinner).
  - Or if that does not work out change the normal search to `⏎ ` and change the recursive search with a modifier, e.g. `⌘ ⏎ `.

> It looks to me this is working as expected.

As it is now is first felt inconsistent:
- 1a) A normal search without wildcards is case insensitive. Just tried:
  - E.g. query `axure` or `AXURE` all match all my `axure*` and `Axure*` files.
- 1b) Whereas as soon as you mix a wildcard in it becomes case sensitive. Just tried:
  - `axure*` matches only the lowercase ones, `Axure*` only the Word-capitalized ones, `AXURE*` matches nothing.
- 2a) A normal search matches the word everywhere in the filename. Just tried:
  -  `toc` matches in the middle of the filename.
  - 2b) As soon as you mix in wildcards, the whole query comes "positionally strict" as in "you must describe it from start to end entirely". `*toc` or `toc*` as usual in web search engines is not enough. If the word is in the middle of the name, you must sandwhich it into asterisk from both sides, so `*toc*`. It behaves exactly as globing in the Unix CLI Shell, just tried it there with `ls`.

But it is mostly a good UX after all:
- ✅ Normal search is "very forgiving": matches everywhere and is case insensitive.
- ✅ Using wildcards → By tendency you are advanced. So you need precession.
  - ✅ Positional strictness: Being able to say word at start middle or end is an advantage!
  - Case sensitivity
    - Can be an advantage (for some cases)
    - ❌ But mostly is a disadvantage
      - Even for advanced users can be a PITA in cases where you are not sure. Trying all permutations manually is cumbersome.
      - 👉 There should be an ad-hoc control for this, which applies to both normal and wildcard search.
- 👉 Documentation should be updated.
- 👉 Small inline help would be fine. `(?)` button which on click/hover shows tooltip how search works.

**Comment by dkocher** [comment]
Case sensitivity search is to be documented in iterate-ch/docs#320.
