### ISSUE TITLE
Error 229 extended passive mode entered

### ISSUE THREAD

**Issue by BrianSwager** [iterate-ch/cyberduck#14187]
Error message received when trying to upload a webpage.  I had uploaded two days ago with no problem.  I tried turning off my firewall.  Then I included CyberDuck in firewall exceptions.

Brian Swager  brian@allegrofuoco.com

<img width="468" alt="Screen Shot 2023-02-03 at 17 04 24" src="https://user-images.githubusercontent.com/124407880/216729326-7e2c652c-16e5-4e45-87e8-c68802861ae3.png">
<img width="595" alt="Screen Shot 2023-02-03 at 17 08 21" src="https://user-images.githubusercontent.com/124407880/216729328-62230df1-cf46-42c9-9ed9-d95ca9ba79b3.png">
<img width="581" alt="Screen Shot 2023-02-03 at 17 12 28" src="https://user-images.githubusercontent.com/124407880/216729329-99c0fc85-b197-46f6-9312-8fd841234192.png">

**Comment by AliveDevil** [comment]
Your ftp server responds to a PASV request with EPSV, which differs from the expected answer, thus fails.
Please use `defaults write ch.cyberduck ftp.datachannel.epsv true` to force Cyberduck to use EPSV if available.

**Comment by velanche** [comment]
Greets, @AliveDevil. Where do I enter that info? I'm assuming it's in a configuration file? I get that error when I attempt to upload a file to my web server from Cyberduck on my Mac. I'm running MacOS Ventura 13.2.1. Thanks!

**Comment by velanche** [comment]
Okay, I sorted it out. I got lucky, still persisting to find a solution. I read somewhere about additional options in Cyberduck for bookmarks, but wasn't sure how to get there. Realizing that I did not explicitly save a bookmark, I used the one cached in History to create anew. After verifying my configuration info, there's a "More Options" area at the bottom. Opening it up, one area called "Connection Mode" had it set to "Default." Clicking on it showed both Active and Passive, and I chose "Active" and exited the window. After reconnecting and then accessing the subdirectory where I wanted to upload my file, this time the process completed without a hitch. I think I'm set!

**Comment by AliveDevil** [comment]
That would've been entered in `Terminal.app`. Opening up `Terminal` through Spotlight, then pasting the above command into, and confirm with Enter.

Bear in mind that FTP Active mode has several limitations regarding NAT and port forwarding - passive is the "best-practice" way of connecting client devices to FTP servers, while I'd use active mode between two ftp servers. But if it works for you, don't change a setting.

**Comment by velanche** [comment]
Thanks for the clarification. When I get a chance, I shall add the line to the config file and disable “Active,’ in keeping with best practices.

Much appreciated!

From: Jöran Malek ***@***.***>
Date: Tuesday, February 28, 2023 at 1:29 AM
To: iterate-ch/cyberduck ***@***.***>
Cc: velanche ***@***.***>, Comment ***@***.***>
Subject: Re: [iterate-ch/cyberduck] Error 229 extended passive mode entered (Issue #14187)

That would've been entered in Terminal.app. Opening up Terminal through Spotlight, then pasting the above command into, and confirm with Enter.

Bear in mind that FTP Active mode has several limitations regarding NAT and port forwarding - passive is the "best-practice" way of connecting client devices to FTP servers, while I'd use active mode between two ftp servers. But if it works for you, don't change a setting.
