### ISSUE TITLE
Dropbox descarga de más

### ISSUE THREAD

**Issue by abarragane59** [iterate-ch/cyberduck#14189]
Cuando descargo grandes cantidades de archivos de vídeo -pesados, en 4k-, casi siempre alguno de ellos termina pesando más de lo que debería y la descarga termina lanzando un mensaje de error.

**Comment by tatze96** [comment]
Please add a screenshot of the error message and share the information below with us.
- Which operating system is in use?
- Which version of Cyberduck is in use?
- Do you download the files from a standard folder or a Cryptomator vault?
