### ISSUE TITLE
Uygulama Güzel Ancak Çok Yavaş Açılıyor.

### ISSUE THREAD

**Issue by nafizask** [iterate-ch/cyberduck#14191]
Merhaba,
Emekleriniz için teşekkür ederim. Uygulamayı severek kullanıyorum. Ancak bu uygulama çok yavaş ve geç açılıyor.
Teşekkürler.

Nafiz AŞIK
İstanbul/TÜRKİYE

**Comment by dkocher** [comment]
Duplicate for #12630.
