### ISSUE TITLE
unable to get an authentication code for `googledrive:/` on Linux with Duck CLI

### ISSUE THREAD

**Issue by tyson-swetnam** [iterate-ch/cyberduck#14193]
Hi Friends,

I've been a long time Duck, CyberDuck, and MountainDuck user. Thanks for all your hard work!

Lately, I've been unable to get an authentication code back for Duck CLI on Linux to my `googledrive:/` accounts -- 

```
[tswetnam@gpu07 ~]$ duck --username tswetnam@email.arizona.edu --list googledrive:/
Google Drive connection opened…
https://accounts.google.com/o/oauth2/auth?client_id=996125414232-s922bvdt21nceeh5dq1gb6av8plpj7hr.apps.googleusercontent.com&code_challenge=y3sMr4H1-oet-xWm6U4HudmIaaV7tvOgo2wodoo46bU&code_challenge_method=S256&redirect_uri=io.cyberduck:oauth&response_type=code&scope=https://www.googleapis.com/auth/drive&state=9OHURJER
Open web browser to authenticate and obtain an authorization code
```

Notice, there is no option to paste the `Authentication Code:`, as I can get with `onedrive:/`

```
[tswetnam@gpu07 ~]$ duck --username tswetnam@email.arizona.edu --list onedrive:/
OneDrive connection opened…
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=f40bc18f-cd02-4212-b7f1-15243e4e2ad3&code_challenge=7SDqjFlGOwi59WV9KUfelrJTIiaVraTlSZCN6Ow69w4&code_challenge_method=S256&redirect_uri=https://cyberduck.io/oauth&response_type=code&scope=files.readwrite.all%20offline_access%20user.read&state=4nXLUJxG&prompt=select_account
Login OneDrive. Paste the authentication code from your web browser.
Authentication Code: 

```

If I'm working remotely over SSH, the GoogleDrive URL will (a) open my local browser, resolve and open CyberDuck locally and the browser will refresh to Google without an authentication code, or (b) if I'm on a remote desktop or on a Linux desktop, resolve and go to Google homepage without an authentication code. 

I can connect the same email alias to `onedrive:/` without a problem. This only seems related to `googledrive:/`

Last, I am able to get the Authentication code for Google Drive from Duck CLI on MacOSX and use Duck CLI normally.

**Comment by dkocher** [comment]
Duplicate for #13587.
