### ISSUE TITLE
Transfer window no longer opens in 8.5.5

### ISSUE THREAD

**Issue by Rinakles** [iterate-ch/cyberduck#14190]
Windows 10. Updated to 8.5.5. Now, when transferring files (at least in Amazon S3), the transfer window no longer opens.
Files still get transferred, but being able to see the progress would be good.

This is all I see when I try to view the transfers:
![screen23](https://user-images.githubusercontent.com/86843995/216796881-b6d19e5c-cc9f-447a-8e76-36e19cafa0c7.png)

Already tried using Repair, doesn't fix the issue.

**Comment by AliveDevil** [comment]
Can you check what happens when you clear out `%AppData%\Cyberduck\Transfers`?

**Comment by AliveDevil** [comment]
Windows, being Windows, I guess.
