### ISSUE TITLE
Downloads freezes on encrypted vault – `Google Drive`

### ISSUE THREAD

**Issue by nicollasricas** [iterate-ch/cyberduck#14200]
Hi,

I'm having problems downloading files with Cyberduck on my encrypted vault/Google Drive. This issue is happening for a while, and the last time I needed a file I was able to download it using Mountain Duck, unfortunately my trial period expired, so I no longer can test it.

The download starts and freezes for hours. Maybe it's related to these issues?
#10990
#10849

It doesn't matter which version I'm using. I've tried with the latest stable (8.5.5) - Windows Store and MSI installer, the latest snapshot (8.5.6), the oldest available (8.4.0) still the same outcome.

I have also tried to create a new vault with a single file uploaded, the one I'm attaching to this issue. This time at least I was able to download the file after who knows how long… I left open and just forgot about it.

![Screenshot_20230205_042151](https://user-images.githubusercontent.com/7860985/217001062-77f5b471-c30e-4683-ae36-9e2ef25439d4.png)

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10664223/cyberduck.log)

**Comment by Cassie205** [comment]
I can reproduce the issue partially. One file constantly fails with a `Transfer incomplete` error while a similar file gets transferred correctly. In both cases, the transfer speed drops periodically and eventually rises again.

**Comment by Cassie205** [comment]
Rerunning the tests the issue can be avoided by disabling the `Segmented Downloads` option in the Cyberduck preferences _Transfers_ tab.
