### ISSUE TITLE
Mountain Duck: URLs doubled up when a path is used, one with, one without

### ISSUE THREAD

**Issue by minfrin** [iterate-ch/cyberduck#14209]
**Describe the bug**

When configuring a webdav server that has a path prefix, the “copy URL” and the “open URL” options show multiple URLs rather than one URL.

The first URL is the correct URL (/storage/home/), the second URL is the same URL without the /storage prefix (/home/) and is wrong.

When using “copy URL”, two URLs end up being copied, with a newline between.

When using “open URL”, the second URL is opened. This second URL is the broken URL without the prefix, and end user is sent to a page that does not exist.

**To Reproduce**
1. Configure and connect to a WebDAV server,.
2. Right click to get mountain duck -> copy url
3. Two URLs are copied, one with the prefix, one without.

**Expected behavior**
Exactly one URL copied, matching the actual server URL.

**Screenshots**
Screenshot in support ticket.

**Desktop (please complete the following information):**
 - OS: Windows / Mac
 - Version 4.13.4 (20921)

**Comment by dkocher** [comment]
As a workaround you can set a [property](https://docs.mountainduck.io/mountainduck/preferences/#hidden-configuration-options) to disable the default URL that does not take the default path

```
nativity.contextmenu.url.filter=provider
```

On macOS, open _Terminal.app_ and type 

```
defaults write io.mountainduck nativity.contextmenu.url.filter provider
```
