### ISSUE TITLE
"Enable Finder Extension" appears when finder extension is enabled

### ISSUE THREAD

**Issue by minfrin** [iterate-ch/cyberduck#14210]
**Describe the bug**
When an attempt is made to mount a drive, a popup requests to enable a finder extension. This finder extension is already enabled.

**To Reproduce**
1. Connect to a WebDAV server
2. See "Enable Finder Extension".
3. Click "Open system preferences".
4. See finder extension is already enabled.

**Expected behavior**
Invitation to enable finder extension should not appear when already enabled.

**Screenshots**
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1331788/217587371-ae0de1b2-adb4-4a43-848f-0506cbd7465b.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1331788/217587477-31bfdc43-47a6-4572-9a0c-ea0fa40dc780.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 4.13.4 (20921)

**Comment by dkocher** [comment]
We are aware of this problem occasionally showing on some systems and track this in an internal ticket.

**Comment by dkocher** [comment]
Also discussed in #15584.
