### ISSUE TITLE
S3 connection error: Cannot read container configuration. Maximum redirects (50) exceeded.

### ISSUE THREAD

**Issue by mkieser** [iterate-ch/cyberduck#14230]
this error is not consistent, it makes the connection, then starts "Listing directory ..."

**Comment by dkocher** [comment]
Please confirm you are running version [8.5.5](https://trac.cyberduck.io/milestone/8.5.5) and include the debug log [^1] if you can reproduce.

[^1]: https://docs.cyberduck.io/cyberduck/support/#logging-output

**Comment by dkocher** [comment]
I am unable to reproduce using bucket `test-us-west-2-cyberduck` either set in _Path_ or in _Server_ as `test-us-west-2-cyberduck.s3.amazonaws.com` [^1].

[^1]: https://docs.cyberduck.io/protocols/s3/#access-single-bucket

**Comment by mkieser** [comment]
Apologies, looks like it was something on the terraform side.

**Comment by flymg** [comment]
For us it was a SCP / missing IAM that was required and must be allowed
s3:GetBucketLocation
