### ISSUE TITLE
Custom S3 region not used for downloads

### ISSUE THREAD

**Issue by jpds** [iterate-ch/cyberduck#14232]
**Describe the bug**

My users use cyberduck with my S3-compatible storage service which uses a region name that isn't one of the AWS S3 regions. I have set the region name string in the `.cyberduckprofile` file I provided to the user, as follows:

```
...
        <key>Region</key>
        <string>garage</string>
        <key>Regions</key>
        <array>
            <string>garage</string>
        </array>
...
```

The whole file can be found [here](https://github.com/jpds/cyberduck/blob/garage-profile/profiles/default/Garage.cyberduckprofile) - I was planning to contribute it in once I had confirmed that everything is working with no errors.

However, when they do certain operations against the endpoint - the program appears to instead use the default `us-east-1` region, for some of the operations, but not all of them, based on the server backend logs:

```
client-ip (via [::1]:22668) GET /
client-ip (via [::1]:22668) GET /
client-ip (via [::1]:22668) GET /?versioning
Response: error 400 Bad Request, Authorization header malformed, unexpected scope: 20230214/us-east-1/s3/aws4_request
client-ip (via [::1]:22668) GET /?versioning
client-ip (via [::1]:22668) GET /?encoding-type=url&max-keys=1000&prefix=&delimiter=%2F
client-ip (via [::1]:22668) GET /?delimiter=%2F&uploads=
client-ip (via [::1]:22668) GET /?encoding-type=url&max-keys=1000&prefix=test%2F&delimiter=%2F
client-ip (via [::1]:22668) GET /?prefix=test%2F&delimiter=%2F&uploads=
client-ip (via [::1]:22668) GET /?location=
Response: error 400 Bad Request, Authorization header malformed, unexpected scope: 20230214/us-east-1/s3/aws4_request
client-ip (via [::1]:22668) GET /?location=
client-ip (via [::1]:22668) HEAD /test/test-file.jpg
Response: error 400 Bad Request, Authorization header malformed, unexpected scope: 20230214/us-east-1/s3/aws4_request
```

They tell me that they appear to be able to browse the buckets, but an error occurs only when they attempt to download a file (the "Quick View" option works however).

**Desktop (please complete the following information):**
 - OS: macOS X 10.15.7
 - Version: Cyberduck/8.5.5.39213

**Comment by jpds** [comment]
Curiously, it seems that removing from the profile:

```
        <key>Bundled</key>
        <true/>
```

...may have fixed this? Going to see if the user hits any more errors in the coming days.

**Comment by dkocher** [comment]
The `Bundled` key is reserved for connection profiles that are bundled with Cyberduck by default.

**Comment by dkocher** [comment]
Refer to [^1] for contributing connection profiles.

[^1]: https://github.com/iterate-ch/profiles/issues/new/choose
