### ISSUE TITLE
Webdav File download replacing filename special characters

### ISSUE THREAD

**Issue by onindus** [iterate-ch/cyberduck#14241]
Trying to download files using secure webdav protocol using Cyberduck and it replaces the special characters in file names like spaces, @, #, $ to UTF-8. character set like %20 etc

for e.g. Sample File Name.pdf is downloaded as Sample%20File%20Name.pdf

and we want to have original file names without any modifications.

**Comment by onindus** [comment]
It does it only to file names and not to folder names.

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output) with the _Debug_ option enabled. You can reach the logging output in _Preferences → Connection_.

**Comment by onindus** [comment]
Hi David

Please find attached the requested log file and screenshot of downloaded
files where space was in file name was converted to %20

Thanks

Vikas

[image: -]
<http://www.onindus.com/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>

Vikas Handa
Chief Operating Officer

*Cell:* 704-904-3673
*Email:* ***@***.***
*Address:* 7050 W. Palmetto Park Road, Suite 15700 Boca Raton, FL 33433
*www.onindus.com
<https://www.onindus.com/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>
    *                                                         [image:
facebook icon]
<https://pxl.onindus.com/links/5ec9ed0d9c305e0015986b4f/618d91bea889d10743d6d477/618d937aa889d10743d6d47b?target=https%253A%252F%252Fwww.facebook.com%252FOnIndusServices%252F&utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>
  [image: linkedin icon]
<https://pxl.onindus.com/links/5ec9ed0d9c305e0015986b4f/618d91bea889d10743d6d477/618d937aa889d10743d6d47a?target=https%253A%252F%252Fwww.linkedin.com%252Fcompany%252Fonindus%252F%253FviewAsMember%253Dtrue&utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>

[image: Events]
<https://www.onindus.com/news-events/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>

**Comment by dkocher** [comment]
> Hi David Please find attached the requested log file and screenshot of downloaded files where space was in file name was converted 

No screenshot is required. We require a log file which will probably show the server double URI encoding filenames. Please add as a comment as attachments do not appear when replying by email.

**Comment by onindus** [comment]
[cyberduck.log.zip](https://github.com/iterate-ch/cyberduck/files/10758064/cyberduck.log.zip)

**Comment by onindus** [comment]
Please confirm that you have the log file .. Thanks

**Comment by onindus** [comment]
David

Any update on this? Not sure why the issue has been marked closed in Github

Thanks

Vikas
<http://www.onindus.com/?utm_source=signaturesatori&utm_medium=email&utm_campaign=general_signature>

**Comment by AliveDevil** [comment]
The files you are trying to download with the percent-encoding are already URI decoded paths - that is they exist with this name on your server.

Request from Cyberduck:
```
PVH%2520Admin%2520Training%2520Session%2520211-16-2021.mp4
```
For `PVH%20Admin%20Training%20Session%20211-16-2021.mp4`.

Please check that these files are not double-URI encoded.

**Comment by onindus** [comment]
Hello Joran

They don't exist in the source with the URI encoding, they do have special
characters like spaces, #, @ etc ..

see attached in Cyberduck, the files from the source

Thanks

Vikas

**Comment by onindus** [comment]
<img width="1117" alt="Screen Shot 2023-02-17 at 7 06 53 AM" src="https://user-images.githubusercontent.com/46682152/219662387-2782ef26-ae66-4f71-aba2-43d2bc143515.png">

**Comment by onindus** [comment]
Can you pls help fix this issue?

Regards
