### ISSUE TITLE
OpenSSH agent based authentication broken on Windows

### ISSUE THREAD

**Issue by sferrazzi** [iterate-ch/cyberduck#14257]
OS: Windows 11
SSH Agent: 1Password

File .ssh/config with only:

```
Host nuci5
  User ste

```
Connection with 8.5.5: OK

[cyberduck-8.5.5-OK.log](https://github.com/iterate-ch/cyberduck/files/10774492/cyberduck-8.5.5-OK.log)

Connection with 8.5.6: KO

[cyberduck-8.5.6-KO.log](https://github.com/iterate-ch/cyberduck/files/10774495/cyberduck-8.5.6-KO.log)

Ref. previous issue:

#14196

**Comment by shyim** [comment]
Can reproduce it too with OpenSSH Agent together with 1Password SSH

**Comment by blaineam** [comment]
confirmed this issue bubbled its way over the Mountain duck so had to roll back to the previous version. Best I could guess from the linked issue it has to do with the newly added logic for checking if the "proxy.isRunning()" which I think is incompatible with how 1password interfaces with the OpenSSH client for windows. I think the part that fixed that referenced ticket had nothing do do with the proxy.isRunning() code that was added to that landed PR. I think the null check would be sufficient

**Comment by Aidan-Chey** [comment]
For those coming across this like I, downgrading the application gets around the issue. 
- In Windows uninstall the application using the add / remove application tool. 
- Download the previous version (8.5.5) from the change log page here https://cyberduck.io/changelog/
- Install and launch and everything should be as it was but with working SSH

**Comment by ylangisc** [comment]
Regression from f5a537a9fb608ccc299896300f66670b755adea3. The check if the agent is running does not work on Windows.

**Comment by ylangisc** [comment]
Workaround is to define an env variable `SSH_AUTH_SOCK` in Windows with any value.
