### ISSUE TITLE
Cannot duplicate file on version 8.5.6 

### ISSUE THREAD

**Issue by 1sttati** [iterate-ch/cyberduck#14262]
When I updated to 8.5.6, the duplicate button is not working

**Comment by AliveDevil** [comment]
Same as #14263.

The duplicate file contains a `.`-character thus fails.

**Comment by AliveDevil** [comment]
In the meantime, set
```
browser.filter.regex=^[\\.]{1,2}$ [:/\\\\]
```
in a (new) file called "default.properties" (enable Show File Extension in Explorer) in `%AppData%\Cyberduck`.
