### ISSUE TITLE
OpenSSH agent based authentication with pubkey broken on Windows

### ISSUE THREAD

**Issue by sferrazzi** [iterate-ch/cyberduck#14267]
OS: Windows 11
SSH Agent: 1Password or OpenSSH

File .ssh/config with only:

```
Host nuci5
  User ste

```
Tried with `SSH_AUTH_SOCK ` workaround,  connection with 8.5.6:   OK 

Modified config file (ref. #14196):

```
Host nuci5
  User ste
  IdentityFile ~/.ssh/nuci5-key.pub
  IdentitiesOnly yes
```
Connection with 8.5.6:   KO

[cyberduck-pubkey-8.5.6.log](https://github.com/iterate-ch/cyberduck/files/10797100/cyberduck-pubkey-8.5.6.log)

**Comment by dkocher** [comment]
Duplicate for #14257.
