### ISSUE TITLE
Can not create or duplicate files with any suffix on SFTP (SHH) - Windows 10

### ISSUE THREAD

**Issue by Insencel** [iterate-ch/cyberduck#14263]
When trying create a file with any suffix over SFTP on Windows 10 i only get a "error" sound and nothing happens. I can however create a file without suffix (so no .html, .css, etc) and remame it to have a suffix after. The same issue however arrises when using "Duplicate" instead of new.

I have tested this on multiple servers with the same result.

Specs:
Cyber Duck Versions I have tested this on: 8.5.6 and current Beta-Build for 8.5.7 (39395)
Windows 10
Intel(R) Core(TM) i5-4690k CPU @ 3.50 GHz
24 GB Ram
64 bit

**Comment by AliveDevil** [comment]
Thanks for reporting.

Will be fixed in an upcoming version.

**Comment by AliveDevil** [comment]
Regression from #14236

**Comment by AliveDevil** [comment]
In the meantime, set
```
browser.filter.regex=^[\\.]{1,2}$ [:/\\\\]
```
in a (new) file called "default.properties" (enable Show File Extension in Explorer) in `%AppData%\Cyberduck`.

**Comment by Insencel** [comment]
alright thanks, works!
i'll leave the ticket open, since i don't know if you want it closed or not. but feel free to close it :)
