### ISSUE TITLE
8.5.5 and 8.5.6 seems to crash when connecting to server from existing bookmarks (mac osx 10.13)

### ISSUE THREAD

**Issue by sbgraphic** [iterate-ch/cyberduck#14274]
Hello, I've just upgraded to 8.5.6 and I had the following issue. I've deleted some caches / preferences and revert back to 8.5.4 which is fine.

**Describe the bug**
Cyberduck 8.5.5 or 8.5.6 crash as soon as I click connect to a server with an existing bookmark

**To Reproduce**
1. Open to 'browser' window
2. Click on 'first existing bookmark'
3. => Quit unexpectedly
4. reinstall 8.5.6 or 8.5.5 from .pkg => same crash 
5. clean some caches files in 'application support' (manually) 
6. reinstall 8.5.4 from .pkg = > working

**Expected behavior**
Connect to the server as usual

**Desktop**
Process:               Cyberduck [907]
Path:                  /Applications/Cyberduck.app/Contents/MacOS/Cyberduck
Identifier:            ch.sudo.cyberduck
Version:               8.5.5 (39213)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Cyberduck [907]
User ID:               501

Date/Time:             2023-02-22 20:14:53.641 +0100
OS Version:            Mac OS X 10.13.6 (17G14042)

**Log Files**
Sorry there is nothing there about the crash..., only some previous lines (see attached from latest use)
[cyberduck-crash_22-2-2023.log](https://github.com/iterate-ch/cyberduck/files/10807753/cyberduck-crash_22-2-2023.log)

**Additional context**
I cann't be sure that 8.5.5 was fine before update, but I'm not sure (I'm not a daily user) but 8.5.6 trigger the crash… I will try to update later again...

Thx anyway !

**Comment by tatze96** [comment]
Please attach the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) for further investigation.

**Comment by sbgraphic** [comment]
Sorry I often miss those notifications, is the crash report above not visible for you ?

**Comment by sbgraphic** [comment]
Hello, **version 8.5.7** has fixed this issue for me !, Thank you.

**Comment by sbgraphic** [comment]
Hello, I've just updated to 8.5.9 and the app crashed again opening some bookmarks… I revert back to 8.5.4 and it's fine again. Previous updaded 8.5.7 crashed also… So it is somehow very eratic…
