### ISSUE TITLE
Overwrite prompt does not allow to expand folder

### ISSUE THREAD

**Issue by truthsword** [iterate-ch/cyberduck#14287]
I transfer a folder to Google Drive that periodically contains changed files. When I select Overwrite from the dropdown (or any other choice), I do not see the "twisty" or "dropdown" that allows me to see the existing folder choices. For example:
![](https://i.imgur.com/5IDyjWA.png)
Instead, I see:
![](https://i.imgur.com/CyB7rlz.png)

Is this a bug, as I recall some time ago I could expand the folder.

Version:
![](https://i.imgur.com/MCa3er8.png)

**Comment by AliveDevil** [comment]
Tree view is there … but selectors are missing. May be cursed renderer.

![image](https://user-images.githubusercontent.com/734738/226598571-86b82df9-f94c-4ead-9449-7a38e76b811f.png)

In the meantime you can expand lines by selecting them, then hitting "arrow right".
