### ISSUE TITLE
"New bookmark" save button

### ISSUE THREAD

**Issue by jpds** [iterate-ch/cyberduck#14283]
**Describe the bug**

I've had various users ask me what to do after they add their credentials to the "new bookmark" window:

<img width="366" alt="Capture" src="https://user-images.githubusercontent.com/29158971/221422778-dd04c549-2d2a-4d1b-9960-9822dd97d20a.PNG">

There's no save button, and they don't realize that pressing the close window button will save their changes.

**Comment by dkocher** [comment]
We think changes made in the user interface should apply immediately without having to confirm with _Apply_ or similar.
