### ISSUE TITLE
Dropbox callback does not work via CLI

### ISSUE THREAD

**Issue by JoepdeJong** [iterate-ch/cyberduck#14282]
**Describe the bug**
It seems not possible to retrieve an OAuth2 token on a Linux machine that has only CLI installed. The redirect uri is of course not able to open the program, but the prompt also does not allow to manually type a code.

**To Reproduce**
1. run `duck --list dropbox:/` in terminal, this outputs something like:
 ```sh
https://www.dropbox.com/1/oauth2/authorize?client_id=XXXX&code_challenge=XXXX&code_challenge_method=S256&redirect_uri=x-cyberduck-action:oauth&response_type=code&state=XXXX
Open web browser to authenticate and obtain an authorization code
```
3. go on my main machine to the url
4. Accept the terms and copy the redirect-uri: `x-cyberduck-action:oauth?code=XXXXX&state=XXXXX`
5. There is no way to paste the code in the terminal shell directly, and the `x-cyberduck-action:oauth` also does not work when only a CLI is installed.

**Expected behavior**
After `Open web browser to authenticate and obtain an authorization code` an input prompt should start which allows typing the code manually

**Desktop (please complete the following information):**
 - OS: ubuntu
 -  - Version 22.04

**Comment by AliveDevil** [comment]
@dkocher Add OAuth prompt handle so that pasting the `x-cyberduck-action` automatically retrieves all required information?

Joep, copying the redirect URI and only using the `X` part after `code=` should work, though isn't elegant and requires opening up some text editing application.

**Comment by dkocher** [comment]
Duplicate for #13587.
