### ISSUE TITLE
Setting CyberDuck

### ISSUE THREAD

**Issue by JACweb44** [iterate-ch/cyberduck#14297]
Hello,
I have an issue with a client who hasn't ftp sub-domain. Then I can't use CyberDuck to access is ftp zone. Instead, with FileZilla, I can set the hoster with www.domain.com, the user, the port and password, and it works.

How can I do the same with CyberDuck ? I only have the choice with ftp or sftp for setting the hoster?

**Comment by dkocher** [comment]
Set the hostname in _Server_ when editing the [bookmark](https://docs.cyberduck.io/cyberduck/connection/#toolbar-button).
