### ISSUE TITLE
Excessive Caching by Mountainduck

### ISSUE THREAD

**Issue by lhangart** [iterate-ch/cyberduck#14305]
I am using Mountainduck (default preferences) to connect to a server directory and an individual node on our high-performance cluster via SFTP. I noticed that the cache accumulated excessive amount of data. The folders I connect to are <100Mb in size and the cache in Group Containers accumulated >4Mio files worth over 1TB of data. 

I had to manually delete the cache as my HD ended up full. 

Could this be a bug? Also, could you add a feature to manually purge the local cache?

Thanks, Lars

![Screenshot 2023-03-03 at 7 28 11 AM](https://user-images.githubusercontent.com/66847983/222763371-ee2d460d-7575-42d3-a8bd-8edd3cfe6665.png)

**Comment by dkocher** [comment]
- You can set in _Preferences → Sync → Cache_  to periodically sweep the cache [^1]. 
- Manually choose to delete files or folders in cache [^2] by choosing _Delete on Local Disk_.
- You may want to disable _Sync → Enable Buffering_ [^3]  if you don't want files opened to be added to the persistent cache automatically.

[^1]: https://docs.mountainduck.io/mountainduck/preferences/#cache-limitations
[^2]: https://docs.mountainduck.io/mountainduck/sync/#delete-on-local-disk 
[^3]: https://docs.mountainduck.io/mountainduck/preferences/#enable-buffering
