### ISSUE TITLE
downloading a large (2gb) file reports a much larger file and doesn't calculate ETA correctly

### ISSUE THREAD

**Issue by yfarjoun** [iterate-ch/cyberduck#14302]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/2745554/222497467-ffbb2ab5-39f6-4c4b-9a92-2caf0e320b14.png">

I'm not sure how to recreate this, but this is what I'm seeing...

**Comment by yfarjoun** [comment]
when I `du` the cyberducksegment directory I get a much smaller number:

```
MCF7_25M_R1_2.hicup.bam.cyberducksegment % du -h .
1.2G	.
```

**Comment by yfarjoun** [comment]
It looks like an off by 10x error somehow:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/2745554/222498579-91bf7dd6-3033-4082-9991-4d44da0301c9.png">

**Comment by yfarjoun** [comment]
Could there be an off-by-10x error?
![Uploading image.png…]()

**Comment by yfarjoun** [comment]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/2745554/222498930-8e0ab14a-6b82-4ea8-ac35-a6a717c0483d.png">

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Comment by dkocher** [comment]
Please let us know if you can reproduce after unchecking _Preferences → Transfers → Segmented downloads with multiple connections per file_.

**Comment by dkocher** [comment]
Duplicate for #13374.
