### ISSUE TITLE
On Windows IdentitiesOnly with public identity file through SSH agent not authenticating

### ISSUE THREAD

**Issue by sferrazzi** [iterate-ch/cyberduck#14308]
OS:                
**Windows 10**

SSH-Agent:
**OpenSSH**

### Cyberduck BETA

Tested with: Cyberduck beta: 8.5.7.39395 and Cyberduck snapshot: 8.5.7.39418

File ~/.ssh/config with only:

```
Host hhh-instance
  HostName hhh-instance.cloudapp.azure.com
  User hhh
  IdentityFile ~/.ssh/hhh-key.pub
  IdentitiesOnly yes
```

Connection KO... :-(

I've tried Cyberduck SFTP on OSX and it works.

I already open the issues:  #14196 (Cyberduck 8.5.5) and #14257 (Cyberduck 8.5.6) fixed by #14259 merged on master.

Sorry but where am I doing wrong?

Thank you.

[cyberduck-8.5.7-beta.log](https://github.com/iterate-ch/cyberduck/files/10883954/cyberduck-8.5.7-beta.log)

**Comment by dkocher** [comment]
Duplicate of #14267.

**Comment by dkocher** [comment]
This is supposed to be fixed with #14259.

**Comment by AliveDevil** [comment]
Cyberduck Beta 8.5.7.39395 is the same as Cyberduck Release 8.5.6.39394.
Please try the nightly update.

**Comment by sferrazzi** [comment]
> 

Ok, no problem. Tested with Cyberdick 8.5.7.39422, same result.

**Comment by AliveDevil** [comment]
So, with an absolute path `C:\Users\user\.ssh\id_ed25519.pub` it works without any issue (on current Snapshot).

Using `~` (as we don't resolve that) isn't supported.

**Comment by sferrazzi** [comment]
> So, with an absolute path `IdentityFile C:\Users\user\.ssh\id_ed25519.pub` it works without any issue (on current Snapshot).
> 
> Using `~` (as we don't resolve that) isn't supported.

Thank you.
