### ISSUE TITLE
Overwriting file deletes segments after transfer is complete

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/cyberduck#14326]
Discussed in https://github.com/iterate-ch/cyberduck/discussions/14311

**Comment by dkocher** [comment]
This is caused by #7682 which is not implemented properly in f225f1f5.

**Comment by dkocher** [comment]
> @dkocher I see that you already fixed the issue in master 🕺 Do you know when this also be part of Cyberduck update?

Fixes on the master branch are available in the nightly [snapshot builds](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds).

**Comment by OdedRaiches** [comment]
@dkocher meaning as an official "Release" - will it be in 8.5.7? and when will this Release be?

**Comment by dkocher** [comment]
> @dkocher meaning as an official "Release" - will it be in 8.5.7? and when will this Release be?

Have a look at our [changelog page](https://cyberduck.io/changelog/) for an estimate when the next release may arrive.
