### ISSUE TITLE
gcp bucket listing no longer works

### ISSUE THREAD

**Issue by pvggp** [iterate-ch/cyberduck#14328]
When opening a google cloud platform bucket, the top level id shows (the name of the project/bucket) with an arrow next to it. When expanding that arrow, nothing expands and cyberduck only shows the project/bucket name.

There was an existing shortcut in my config however, directly to a folder and this works with no issues.

ps: all our folders are encrypted with cryptomator.

**Comment by dkocher** [comment]
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
