### ISSUE TITLE
Ftp MLST used despite compatibility protocol (FTP)

### ISSUE THREAD

**Issue by Schaefers** [iterate-ch/cyberduck#14333]
**Describe the bug**
I'm trying to upload the folder containing other folders and files via FTP. According to the logs there's an issue with the `250-Status` response, maybe it's wrongly sent by the server. Testing with a different FTP client worked, though.

**Screenshots**
Attached screenshots of the ftpd server.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.2.1

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10930743/cyberduck.log)

**Additional context**
![IMG_B948C8971E7B-1](https://user-images.githubusercontent.com/9284160/224006176-16e12467-c6ee-4786-bb51-7c8d78e44100.jpeg)

**Comment by AliveDevil** [comment]
Unfortunately that isn't an error in itself - just noise.

We'd need the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) to check further here.
Please provide the log as attachment here (use the web ui, e-mail attachments don't work) or as separate e-mail to support@cyberduck.io mention "Github 14333".

To summarize:
You upload a folder with files to a FTP server, after completing the transfers shows incomplete?

**Comment by Schaefers** [comment]
> Unfortunately that isn't an error in itself - just noise.
> 
> We'd need the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) to check further here. Please provide the log as attachment here (use the web ui, e-mail attachments don't work) or as separate e-mail to [support@cyberduck.io](mailto:support@cyberduck.io) mention "Github 14333".
> 
> To summarize: You upload a folder with files to a FTP server, after completing the transfers shows incomplete?

I'm trying to copy the attached folder (just zipped it to upload here) and Cyberduck is just creating the empty folder on the ftp. Screenshot of Transfers attached.

![image](https://user-images.githubusercontent.com/9284160/224034754-64149ad7-c1a7-4b7f-8a23-e67188534129.png)

[010012F017576000.zip](https://github.com/iterate-ch/cyberduck/files/10931967/010012F017576000.zip)

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10931988/cyberduck.log)

**Comment by AliveDevil** [comment]
```
2023-03-09 14:16:45,469 [Thread-45] INFO  ch.cyberduck.transcript.request - MLST /010012F017576000
2023-03-09 14:16:45,472 [Thread-45] INFO  ch.cyberduck.transcript.response - 250-Status
 /010012F017576000
250 End
```

Your FTP server isn't standards[^rfc-3659-7.7.2] compliant.
[^rfc-3659-7.7.2]: https://www.rfc-editor.org/rfc/rfc3659#section-7.7.2

Please report this issue to your ftp server vendor.
In the meantime use the "FTP Compatibility"-protocol, which can be installed in the preferences[^profiles], to workaround this.
[^profiles]: https://docs.cyberduck.io/protocols/#preferences-profiles

**Comment by Schaefers** [comment]
Thank you! I'll raise an issue in their issue tracker.

Sadly the "FTP Compatibility"-protocol didn't fix it, I'm still getting "Transfer incomplete" and it's still using `MLST` command.

I deleted the log and tried transferring again:

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10932337/cyberduck.log)

**Comment by AliveDevil** [comment]
We are, despite disabling MLS*, still trying to use MLST if the server announces it.

https://github.com/iterate-ch/cyberduck/blob/c52332e90ffa9c819c29fa1e69e7c1e78388d29f/ftp/src/main/java/ch/cyberduck/core/ftp/FTPAttributesFinderFeature.java#L59

Unfortunately, there is nothing you can do to workaround this now.

**Comment by Schaefers** [comment]
> Unfortunately, there is nothing you can do to workaround this now.

I can still create it folder by folder 😊 Thanks for tracking the issue down!

**Comment by AliveDevil** [comment]
@dkocher Failing test for you. #14336
