### ISSUE TITLE
Impossible de créer un fichier

### ISSUE THREAD

**Issue by skytylon** [iterate-ch/cyberduck#14342]
Lorsque le fichier est nommé à l'appui sur le bouton "Créer" rien ne se passe

![image](https://user-images.githubusercontent.com/38259402/224300112-16e57737-937d-4a72-a1bb-3c209e6a53ff.png)

Aucune erreur n'est affiché

**Comment by AliveDevil** [comment]
Please update to latest snapshot (fixed with #14263).
