### ISSUE TITLE
profiles.cyberduck.io TLS

### ISSUE THREAD

**Issue by jpds** [iterate-ch/cyberduck#14379]
**Is your feature request related to a problem? Please describe.**

`profiles.cyberduck.io` should be served over TLS with the same Cloudfront configuration `docs.cyberduck.io` has - the profile links within the docs should then be updated to point to the new `https://` links.

Currently, this is what happens if you force TLS:

```
$ curl -v https://profiles.cyberduck.io.s3.amazonaws.com/
...
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=*.s3.amazonaws.com
*  start date: Sep 21 00:00:00 2022 GMT
*  expire date: Aug 26 23:59:59 2023 GMT
*  subjectAltName does not match profiles.cyberduck.io.s3.amazonaws.com
* SSL: no alternative certificate subject name matches target host name 'profiles.cyberduck.io.s3.amazonaws.com'
```

**Comment by dkocher** [comment]
The bucket is reachable over TLS but because of hostname verification fails because of the `.` in the bucket name. We will see if we can create an alias.
