### ISSUE TITLE
SFTP keyboard-interactive prompt not displayed under Microsoft Windows

### ISSUE THREAD

**Issue by markmont** [iterate-ch/cyberduck#14381]
Long SFTP keyboard-interactive prompts are not displayed under Microsoft Windows 10 and 11.  These prompts are used for Duo multi-factor authentication, among other things:

![image](https://user-images.githubusercontent.com/141380/226331524-df96c045-593d-4182-b0de-d9ec51f04832.png)

The prompt **_is_** displayed correctly under macOS:

![image](https://user-images.githubusercontent.com/141380/226331797-e8063901-0857-42cf-8e8b-baa2f2cf9bbe.png)

**Comment by AliveDevil** [comment]
Well … either got lost somewhere along the way, or never really worked.
Thanks for bringing this to our attention.

**Comment by AliveDevil** [comment]
It is just missing autosizing, indeed.

Which somehow either never worked, or was patched away …
