### ISSUE TITLE
Can't duplicate file since  Version 8.5.7 (39535) on MacOS

### ISSUE THREAD

**Issue by daimaire** [iterate-ch/cyberduck#14413]
Since Version 8.5.7 (39535) on MacOS,  when we try to duplicate a file, it gives as usual a name xxx (yyyy-mm-dd hh:ii:ss).ext . Can't valid it.

It seems that ":" is not accepted anymore in filename.

**Comment by connerat** [comment]
+1

**Comment by dkocher** [comment]
Regression from #14264.
