### ISSUE TITLE
File Transfer - drag and drop - non-responsive app

### ISSUE THREAD

**Issue by davegiffney** [iterate-ch/cyberduck#14450]
If I try and drag a file from Cyberduck onto the desktop there is very good change it will make the application non-responsive.  This can either be for approx 30/60 seconds then the file is copied or the app stays non-responsive 

You can tell when it is going to happen, when dragging file if the cursor stays as arrow, it will go non-responsive, if the cursor is arrow with small box, then it will work.

Currently on latest version and Win11 full updated.

**Comment by tatze96** [comment]
This is likely a duplicate for #15885. If you still encounter this issue, please follow the workaround in the mentioned ticket.
