### ISSUE TITLE
Activity download stuck

### ISSUE THREAD

**Issue by rarelli** [iterate-ch/cyberduck#14463]
Hi,

After updating to version 8.5.7 on mac, i encounter some bugs in SMTP connection, when double click file on my server, i choose to automatically open it with my chosen editor, but in this version, sometime the "activity download" stuck and cannot finish (I check it on activity window), i can still open other file that not stuck on "activity download", but i need to disconnect and re-connect to able open file that stuck in that activity. This never happen in previous version.

**Comment by redsector72** [comment]
#14412 Seems like the same problem
