### ISSUE TITLE
SharePoint folders appear empty

### ISSUE THREAD

**Issue by suilujjulius** [iterate-ch/cyberduck#14483]
Dear all, 
I'm happily using MountainDuck since a while but now I can't access the files of some of the libraries of a specific site anymore.  Some libraries behave normal but in others I do see the folders but they're all empty. It was working in the past.

I tried three different versions of MountainDuck
4.12.4
4.13.6 (stable)
4.13.7 (beta)

I also checked for the differences between the SharePoint libraries, I'm owner of both libraries and have full rights. The only apparent difference I could find between the libraries is the amount of files. At least some of the "inaccessible" libraries have many files and I see this warning. 

<img width="537" alt="image" src="https://user-images.githubusercontent.com/61146290/230014607-4efb6ab6-ff51-4a2a-b5c0-5a7b7a5107f2.png">

Do you have other ideas to fix this issue?

Thanks for your help!

Regards, Julius

**Comment by AliveDevil** [comment]
> It was working in the past
You are referring to the tested 4.12.x?

If that doesn't work now, but worked in the past, then there have been API changes we were unaware of, that we'd need to investigate further.

Do you see this with Cyberduck installed and connected to the same SharePoint library as well?

**Comment by suilujjulius** [comment]
Thanks for the fast answer. My post was a bit confusing, none of the mentioned/tested versions work now. I tried now also 4.13.2 but also without success.
I'm quite sure that it worked in the past but I don't recall the version. Sorry for being of limited help.

**Comment by AliveDevil** [comment]
The only thing I can think of is that the 12000 items need to fit in 200 item pages (that is 60 pages/API requests).
Depending on what you and other users are doing, there are a bunch of limits, that could interfere here - this should usually resolve itself after running out of the throttling time (sometimes as high as a day).

https://learn.microsoft.com/en-us/graph/throttling-limits
https://learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online

You could send us the log output to verify that the issue really is throttling by sending us the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) of Cyberduck while navigating into a folder that doesn't load in Mountain Duck. Either as an attachment here or as an e-mail to support@mountainduck.io, referring to "Github 14483".
If it works in Cyberduck, we'd need the [debug log](https://docs.cyberduck.io/mountainduck/support/#logging-output) of Mountain Duck.

**Comment by AliveDevil** [comment]
Please enable debug logging in Cyberduck Preferences -> Connection. Do you typed anything into the search-field in Cyberduck?

**Comment by suilujjulius** [comment]
The log was already enabled but now I restarted Cyberduck, navigated through the folders and searched for one file ("Test plan") that definitely exists in the folder. See the attached log.

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/11157581/cyberduck.log)

Thanks for your help!

**Comment by AliveDevil** [comment]
Got it.
Search works fine here, but there are issues, that I didn't get around to fix yet, underlying issue (for now): https://github.com/iterate-ch/cyberduck/issues/13895

**Comment by AliveDevil** [comment]
@suilujjulius Can you confirm, that this is resolved with [Cyberduck 8.5.8](https://cyberduck.io/changelog/) just released?

**Comment by suilujjulius** [comment]
Hi @AliveDevil,
the update solved the issue, I can now see the full folder content in Cyberduck. Thanks for the good work! Do I assume correctly that this bugfix will also find its way into Mountainduck in the next release?
Cheers, Julius

**Comment by AliveDevil** [comment]
This update will be included in the next release, scheduled later today (CEST).

**Comment by suilujjulius** [comment]
wohoo, this is fast. Thanks for fixing this!

**Comment by AliveDevil** [comment]
Thanks for confirming.
