### ISSUE TITLE
Authorization for duck opens cyberduck

### ISSUE THREAD

**Issue by btazus** [iterate-ch/cyberduck#14495]
When I run the command
duck --list googledrive:/
I get an authorization screen for Cyberduck and after I acknowledge permission, Cyberduck opens up.
When I return to terminal, on Mac OS, my screen is still waiting on the acknowledgment.
I have Mountain Duck, Cyberduck and duck(via Brew) all loaded on my computer
Mac OS 13.3, Apple Silicon.  Browser that opens up is Chrome.
[duck-log.txt](https://github.com/iterate-ch/cyberduck/files/11173052/duck-log.txt)

I have uploaded my log file.

**Comment by btazus** [comment]
I did do the basic steps of clearing out my browser cache and restarting my computer.  The result was the same after doing these steps.

**Comment by btazus** [comment]
If I enter my username, my authorization get retrieved.
But then I get an enormously long list of commands, but no result
[duck-log-2.txt.zip](https://github.com/iterate-ch/cyberduck/files/11173417/duck-log-2.txt.zip)

**Comment by dkocher** [comment]
Duplicate for #13587.
