### ISSUE TITLE
SmartCard Authentication

### ISSUE THREAD

**Issue by kmmertes** [iterate-ch/cyberduck#14549]
**Is your feature request related to a problem? Please describe.**
I can't use CyberDuck when connecting to a server that requires smartcard (PKCS11Provider) authentication

**Describe the solution you'd like**
I would like to be able specify an option in the bookmark settings to specify the PKCS11Provider or for cyberduck to honor the .ssh/config settings for the server.

**Describe alternatives you've considered**
I can ssh and use cli to copy files

**Additional context**

**Comment by ylangisc** [comment]
Can you post the snippet from your `.ssh/config` for your smart card configuration?

**Comment by dkocher** [comment]
Duplicate for #8401.
