### ISSUE TITLE
 8.5.9 crashes again when opening some bookmarks

### ISSUE THREAD

**Issue by sbgraphic** [iterate-ch/cyberduck#14551]
Hello, I've just updated to 8.5.9 and the app crashes again when opening some bookmarks… I revert back to 8.5.4 and it's fine again. Previous updaded 8.5.7 crashes also now… So it is somehow very erratic for me…

_Originally posted by @sbgraphic in https://github.com/iterate-ch/cyberduck/issues/14274#issuecomment-1515139177_

**Comment by tatze96** [comment]
Please attach the [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports) right after the issue occurs again for further investigation. Make sure to attach it through the GitHub web interface, as it wouldn't be visible to us otherwise.
