### ISSUE TITLE
Missing digest header in POST request when commiting large file upload

### ISSUE THREAD

**Issue by chowderhead** [iterate-ch/cyberduck#14564]
greetings,
i own a registered copy of cyberduck and have encountered a error that i cant figure out.  please analyze my error log and advise what i should do.

the error occus only using the api.box.com.  FTP uploading to ftp.box.com works fine to box.  downloading from api.box.com works fine, uploading does not.  I can find no workaround.  uploading one file or multiple makes no difference.  same error.

my debug log is attached.

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/11300920/cyberduck.log)

**Comment by chowderhead** [comment]
BTW im using version 8.5.9.(39636) on windows 10 Enterprise LTSC build 17763rs5 release 180914-1434 on a comcast business internet 200Mbit DL/30Mbit UL connection.  I also am able to successfully UL to api.box.com with filezilla so i know its possible with my PC just NOT with cyberduck.  filezilla has other things i find annoying not related to uploading which is why im looking for alternative applications currently and subsequently tried cyberduck.
thanks
Randy

**Comment by dkocher** [comment]
This affects uploads >= `20MB`.
