### ISSUE TITLE
ssh tunnel through multiple bastion servers not working

### ISSUE THREAD

**Issue by phaupt** [iterate-ch/cyberduck#14592]
I have this sshd_config:
```
Host pj-mobileid
  Hostname real.host1
  Port 5000
  User alice
  IdentitiesOnly yes
  ForwardAgent yes
  PreferredAuthentications publickey
  IdentityFile keyfile

Host pj-jhost
  HostName real.host2
  Port 7000
  User bob
  IdentitiesOnly yes
  ForwardAgent yes
  PreferredAuthentications publickey
  ProxyJump pj-mobileid
  IdentityFile keyfile

Host pj-midlab
  Hostname real.host3
  Port 22
  User bob
  IdentitiesOnly yes
  ForwardAgent yes
  PreferredAuthentications publickey
  ProxyJump pj-jhost
  IdentityFile keyfile
```
Using the terminal, I can successfully connect via ssh:
```
$ ssh pj-midlab
```

Using the terminal, I can successfully transfer files using SCP:
```
$ scp testfile pj-midlab:/tmp
```

However, in Cyberduck it doesn't work. According to https://docs.cyberduck.io/protocols/sftp/#connect-via-ssh-tunnel-through-bastion-server If I set the SFTP server to "pj-midlab", it seems to attempt to connect to real.host2 instead of real.host1, so it'll time out (because real.host2 can only be reached from real.host1).

It seems like Cyberduck SFTP doesn't consider more than 2 hops? So the use of more than one bastion server, such as  macbook->host1->host2->host3 isn't working?

**Comment by AliveDevil** [comment]
Currently only the first jump is used for connection[^1].
[^1]: https://github.com/iterate-ch/cyberduck/blob/c67459cc71c5d6bf56709f1d8ad06c95a7b9ed8b/ssh/src/main/java/ch/cyberduck/core/sftp/SFTPSession.java#LL149C98-L149C98

Need to make this an iteration, until no proxy jump is found.

**Comment by dkocher** [comment]
Duplicate for #12672.
