### ISSUE TITLE
Sync and directory access issue with SFTP mount

### ISSUE THREAD

**Issue by milyenpabo** [iterate-ch/cyberduck#14646]
I'm trying out MountainDuck as a replacement for SSHFS on my Mac client. My use case is to SFTP-mount remote folders from Linux servers as local volumes on my Mac, and then edit the files via an editor running on the client.

From my first tests, it seems I can achieve this with MountainDuck, however, I see two issues so far:

1. When I use the terminal to `cd` into the mount folder on my Mac, the terminal session typically freezes. (Sometimes the `cd` command succeeds, but it is very very slow). Seems like MountainDuck does not support visiting the mount folder from a terminal?

2. When I edit a file on the client, the changes are reflected on the sever pretty quickly (within 1 second). However, when I edit a file on the server, the changes are reflected on the client with varying latency, but it is usually slow (takes 10s of seconds). Is this a known issue, or can I configure the app to handle 2-way sync better? (I tried various config options from the MountainDuck GUI, but it did not help.)

I appreciate any help or feedback.

**Comment by dkocher** [comment]
Duplicate for #14643.

**Comment by milyenpabo** [comment]
@dkocher Right, I was not sure how to categorize my questions. Do you think I'll get some feedback on https://github.com/iterate-ch/cyberduck/discussions/14643 ?
