### ISSUE TITLE
Editing same path on subsequent connections uploads to wrong connection

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#14666]
Connect server A
Edit file / Save
Connect server B
Edit file / Save

On open-file the correct file is downloaded (TextEdit shows correct content)
On save-file the edited file is uploaded to previous connection, instead of to the correct connection.

**Comment by dkocher** [comment]
Possible regression from c5822c6e. Editors should be cleared when closing connection in browser.
