### ISSUE TITLE
Problem downloading from S3 server

### ISSUE THREAD

**Issue by david-navigator** [iterate-ch/cyberduck#14668]
I have some files that won't download from my S3 server. Cyberduck attempts the transfer, transfers too many bytes and then displays Transfer incomplete 1.5 GiB of 512.0 MiB.

If I use the server's web file management portal then the files download successfully (indicating that the files are OK).

Interestingly Cyberduck claims the file is 512 MB but actually creates a downloaded file of 550,292,684 bytes, whereas the web server claims the file is 512 MB and creates a downloaded file of 536,870,912 bytes.

Not sure how to debug further, but can supply download credentials to file if required.

**Comment by dkocher** [comment]
Can you reproduce when you disable [segmented downloads](https://docs.cyberduck.io/cyberduck/download/#segmented-downloads) by unchecking _Preferences → Transfers → General → Downloads → Segmented download with multiple connections for file_?

**Comment by dkocher** [comment]
Relates to #13610.
