### ISSUE TITLE
CredRead sometimes fails inexplicably

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#14728]
Can someone shed some light on why these would fail this way?

```
Cannot get credential for "duck:ftp:user@a.some.server?user=": Class not registered

Class not registered
```

```
duck:ftp:some.server?user=user@a.some.server": Class not registered

Class not registered
```

There have been hints about Windows Defender Credential Guard interfering here - but I didn't have any chance of success in running a nested virt Windows 11 Enterprise VM with TPM and UEFI lock to block access to credentials obtained through Windows Credential Manager.

Sometimes this works correctly, then a login works fine:
```
331 User user@a.some.server OK. Password required
PASS *****************
```
But then all of a sudden, this same login fetched from credential manager is reduced to a single symbol.
```
331 User user@a.some.server OK. Password required
PASS *
```

Call stack:
[WinCredentialManager.GetCredentials](https://github.com/iterate-ch/cyberduck/blob/1aa6d79fc6ab347885ad2bc74a3e649e1576b6c5/core/src/main/csharp/ch/cyberduck/core/credentialmanager/WinCredentialManager.cs#L59)
[CredentialManagerPasswordStore.findLoginPassword](https://github.com/iterate-ch/cyberduck/blob/1aa6d79fc6ab347885ad2bc74a3e649e1576b6c5/core/src/main/csharp/ch/cyberduck/core/CredentialManagerPasswordStore.cs#L87-L96)
[PasswordStoreFace.HostPasswordStore.findLoginPassword](https://github.com/iterate-ch/cyberduck/blob/1aa6d79fc6ab347885ad2bc74a3e649e1576b6c5/core/src/main/csharp/ch/cyberduck/core/PasswordStoreFacade.cs#L58-L61)

Message above is logged in [WinCredentialManager](https://github.com/iterate-ch/cyberduck/blob/1aa6d79fc6ab347885ad2bc74a3e649e1576b6c5/core/src/main/csharp/ch/cyberduck/core/credentialmanager/WinCredentialManager.cs#LL67C16-L67C16)

**Comment by dkocher** [comment]
Fix in 067ab444.
