### ISSUE TITLE
Editing file in multiple connections uploads file to wrong connection

### ISSUE THREAD

**Issue by andandrej** [iterate-ch/cyberduck#14730]
**Describe the bug**
I have docker-compose.yml file in multiple servers. When I open one with right click -> edit it saves tmp file on host machine in /private/var/folders/.../ch.sudo.cyberduck/editor-UUID/path/on/server/filename

The problem is because i have same filename on multiple servers and each file edit opens file in same tmp location. After changing file and saving, it gets uploaded to firstly opened connection and not on right one.

Can you add some UUID for each connection to put files in right connection folder to prevent rewriting files with same filename and filepath on different servers?

**To Reproduce**
1. Connect to server number 1
2. Right click on file docker-compose.yml in /home/user directory, edit file and save
4. Open new connection to server number 2
5. Right click on file docker-compose.yml in /home/user directory, edit file and save
6. File gets uploaded to server number 1 instead of upload to server number 2.

Please note that file names must be identical and file paths too.

**Expected behavior**
It should upload file to right server and not on firstly opened one.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 8.5.9 (39636)

**Comment by dkocher** [comment]
Duplicate for #14666.
