### ISSUE TITLE
Fall back to alternative IPs resolved for Backblaze B2 API hostname

### ISSUE THREAD

**Issue by PatTheMav** [iterate-ch/cyberduck#14761]
**Is your feature request related to a problem? Please describe.**
As of right now (Monday, 2023.06.05, 20:49 UTC) Backblaze is recovering from an outage, which seems to have knocked off one of their IP ranges.

`api.backblazeb2.com` currently resolves to 3 IPv4 addresses:

```
api.backblazeb2.com.	300	IN	A	104.153.233.180
api.backblazeb2.com.	300	IN	A	149.137.142.15
api.backblazeb2.com.	300	IN	A	104.153.233.176
```

The IP `149.137.142.15` is currently unreachable (`ping` yields `Destination Net Unreachable`), but `104.153.233.180` is reachable.

Using `curl` to check the URL will expectedly fail at first, but then fall back to a different IP and connect successfully.

Cyberduck however will only try to connect with the failing IP and not fall back to the alternatives:

```
2023-06-05 22:15:02,010 [Thread-146] DEBUG org.apache.http.impl.conn.DefaultHttpClientConnectionOperator - Connecting to api.backblazeb2.com/149.137.142.15:443
[...]
2023-06-05 22:15:06,026 [Thread-146] INFO  org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.backblazeb2.com:443: Network is unreachable
```

**Describe the solution you'd like**
Cyberduck should attempt to use other resolved IP addresses to connect to an endpoint specified by a hostname, if alternatives are available.

**Describe alternatives you've considered**
Alternatively it should be possible to override the predefined hostname used for a bookmark using a built-in service implementation. This would allow me in the current situation to enter the IP address that is actually reachable from the network right now.

**Comment by dkocher** [comment]
Refactored our resolver to return all addresses in #14766.
