### ISSUE TITLE
Not possible to copy or move files between Azure containers

### ISSUE THREAD

**Issue by ion-dev** [iterate-ch/cyberduck#14826]
It's no longer possible to move files between Azure containers in the last couple of releases.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click and drag a file from one folder to another... works.
2. Click and drag a file from one location to another container... does not work.

**Expected behavior**
The container should highlight and allow the file to be moved.

Tested on macOS.

Works fine in 8.5.5.

Broken in all later version.

**Comment by ion-dev** [comment]
Hi @dkocher thanks for your quick response! Is there a workaround?

**Comment by dkocher** [comment]
> Hi @dkocher thanks for your quick response! Is there a workaround?

Looks like copying files between containers is supported and we can remove the restriction.

**Comment by ion-dev** [comment]
@dkocher oh that's great. So will that be lifted in the next release? Much appreciated
