### ISSUE TITLE
8.6.0 Backblaze B2 not all files listing

### ISSUE THREAD

**Issue by rlevene** [iterate-ch/cyberduck#14820]
With 8.6.0 when i connect to my B2 storage it fails to list all my folders. Only 1 out of the 105 i have.

Initially i thought i had somehow lost all my files with maybe a dodgy sync but Backburner website/dashboard shows all my files.

My previous version was 8.5.5 and redownloading that and connecting it lists and i can see all my folders.

**Comment by dkocher** [comment]
Duplicate for #14768. Previously discussed in #14759.
