### ISSUE TITLE
Backblaze B2 slow to list files and not all files show

### ISSUE THREAD

**Issue by EMplIFil** [iterate-ch/cyberduck#14895]
As of the past few months or so, I've noticed that when connecting to Backblaze B2, Cyberduck has been very slow to list files in directories.

I just found out today that in addition to that, not all files/folders appear. It seems that only the most recent files appear. But when I go to the B2 web interface, I see them all.

Cyberduck version: Version 8.6.0 (39818) / MacOS Big Sur (also happened on El Capitan)

**Comment by dkocher** [comment]
Duplicates #14768 and #14775.
