### ISSUE TITLE
Sharepoint: please limit # connections for "preparing" file list, but not the file transfers

### ISSUE THREAD

**Issue by cloneman** [iterate-ch/cyberduck#14905]
**Is your feature request related to a problem? Please describe.**
When downloading large folders with many sub-folders and files in sharepoint, Cyberduck first goes through a "preparing" step where it discovers all the files it needs to transfer.

The problem is, this operation goes through too quickly if not limited to 1 single connection, microsoft throttles you, and the operation fails.

if you choose to limit yourself to 1 connection, the "preparing" step succeeds, but then the file transfer itself will be slow because it needs multiple connections.

Changing the # of connections allowed "on the fly" doesn't seem to have any effect... it might be be set on stone once the transfer is initiated.

**Describe the solution you'd like**
For Sharepoint, automatically limit the number of connections (or api calls, whatever it is) for the discovery process of files & folders, so as to not trigger Microsoft's throttling. Then, allow the transfer to proceed with the number of threads the user wants.

**Describe alternatives you've considered**
Tried to change # of connections on the fly. 

**Additional context**
The throttling problem cannot be reproduced unless there is a large enough folder structure to trigger this, perhaps is needs 5,000+ items or so

**Comment by dkocher** [comment]
Can you confirm you have enabled _Connection → Timeouts → Retry failed networking tasks_ and can reproduce with the current [snapshot build](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds).

**Comment by dkocher** [comment]
Duplicate for #13963.
