### ISSUE TITLE
Version 8.6.0 (39818) Absturz/Crash

### ISSUE THREAD

**Issue by DirkEwert** [iterate-ch/cyberduck#14958]
System macOS Monterey v 12.6.8
Programm stürzt sofort beim Kopieren von Daten auf unterschiedliche FTP-Server ab und muss beendet werden.
Mit freundlichen Grüßen
Dirk
Program crashes immediately when copying data to different FTP servers and must be closed.
Best regards
Dirk

**Comment by dkocher** [comment]
Please attach the crash report [^1].

[^1]: https://docs.cyberduck.io/cyberduck/support/#crash-reports
