### ISSUE TITLE
Empty transfers when cPanel Cookie IP validation" set to "strict".

### ISSUE THREAD

**Issue by chrispink** [iterate-ch/cyberduck#14950]
Although I can't see any evidence of IP address change this is the main difference between two hosting servers where the behaviour is absolutely repeatable on one but never happens on the other. 

When transferring (any type of) files, after a time Cyberduck will report successful transfer but the Browser shows 0 B. Once happened with one file, all subsequent transfers to that server result in an empty file.

The only way of resolving this behaviour is to relaunch Cyberduck.

**Comment by dkocher** [comment]
Discussed in #14902.
