### ISSUE TITLE
Failure configuring credentials from AWS CLI setup

### ISSUE THREAD

**Issue by Xarno** [iterate-ch/cyberduck#14970]
**Describe the bug**
The version 8.6.2 fails to connect to S3 when using SSO credentials. The error message is „Cannot read bucket location.“
Version 8.6.0 is not affected and works correctly.
From the logfiles it looks like the x-amz-security-token header is not send.

**To Reproduce**
Setup an AWS SSO connection (new or old format does not matter)
Try to connect

**Expected behavior**
Working sso ;)

**Desktop (please complete the following information):**
 - OS: MacOs 13.5

**Log Files**
[cyberduck_8.6.0.log](https://github.com/iterate-ch/cyberduck/files/12274899/cyberduck_8.6.0.log)
[cyberduck_8.6.2.log](https://github.com/iterate-ch/cyberduck/files/12274900/cyberduck_8.6.2.log)

**Comment by jasonbrd** [comment]
+1 Issue does not happen on rollback to 8.6.0.

**Comment by jbarnhill-vk** [comment]
+1 8.6.2 also doesn't seem to like profile/assume role in .aws/credentials file

**Comment by dkocher** [comment]
Regression from #14799 and affects connections using the S3 (Credentials from AWS Command Line Interface) connection profile [^1].

[^1]: https://github.com/iterate-ch/profiles/blob/main/S3%20(Credentials%20from%20AWS%20Command%20Line%20Interface).cyberduckprofile

**Comment by Kuzma79** [comment]
> added a commit that referenced this issue

**Comment by dkocher** [comment]
Version _[8.6.3](https://trac.cyberduck.io/milestone/8.6.3)_ with a fix has now been released.

**Comment by jasonbrd** [comment]
Issues resolved in Cyberduck, but still present in MountainDuck. Where can that issue be tracked?

**Comment by dkocher** [comment]
> Issues resolved in Cyberduck, but still present in MountainDuck. Where can that issue be tracked?

Please upgrade to Mountain Duck _4.14.3_

**Comment by srober22utm** [comment]
The MacOS links on both the main Mountain Duck page and the changelog page say "Not found: the resource cannot be found."

**Comment by dkocher** [comment]
> The MacOS links on both the main Mountain Duck page and the changelog page say "Not found: the resource cannot be found."

The links have been fixed, thanks for notifying us about the problem.
