### ISSUE TITLE
Transfer (using Synchronize)[sftp] - actual transfer is not detected properly and ends up as "Transfer Incomplete"

### ISSUE THREAD

**Issue by AcidSlide** [iterate-ch/cyberduck#14974]
OS: MacOS Monterey (12.6.8)
CyberDuck: Version 8.6.2 (40032)
Transfer via SFTP (using "Synchronize")

NOTE: target folder in the SFTP has been previously cleared of all files and directory

**First Issue:** Super long time to for preparation (this used to be fast in about 2 years ago), first time to report this
![image](https://github.com/iterate-ch/cyberduck/assets/6833047/d93f98a0-ec36-4bcd-9ed4-e8e9e36fc685)

**Second Issue:** Although the transfer was successful (all files and directories was transfered/synced), it ends up in the UI as failed with 0 bytes transferred.
![image](https://github.com/iterate-ch/cyberduck/assets/6833047/64cc60af-fc36-49d6-9652-974ca2cc75ca)
![image](https://github.com/iterate-ch/cyberduck/assets/6833047/a14df27f-0420-45f7-9a63-5598d3e8fceb)

**Comment by AcidSlide** [comment]
Uploading a partial screen recording of what is happening for devs to understand better the issue.

https://github.com/iterate-ch/cyberduck/assets/6833047/1c916972-6ebf-421a-8c52-7102889635fb

**Comment by AcidSlide** [comment]
I've retested with both with target having existing files/folders and empty, and both ended up with "Transfer Incomplete" although with manual checking all files and folders has been uploaded (synchronized).

**Comment by AcidSlide** [comment]
Rollback to version: 8.6.0 (39818)
Confirmed Working in that version.
![image](https://github.com/iterate-ch/cyberduck/assets/6833047/cf776ad4-871d-4327-ba9c-97179024a5d0)


Tried also 8.6.3 but same issue with 8.6.2.

**Comment by AcidSlide** [comment]
@MerzGH @dkocher @tatze96 linking this with #15389

**Comment by dkocher** [comment]
Regression from 6750569974a2fd80cc1521791ee50c545cc4a70f.
