### ISSUE TITLE
SFTP connection failure after upgrading ProFTPd on server

### ISSUE THREAD

**Issue by jlecour** [iterate-ch/cyberduck#14999]
Hi,

After upgrading from ProFTPd 1.3.7 (Debian 11) to ProFTPd 1.3.8 (Debian 12) my SFTP setting in Cyberduck stopped working.
I've verified that other SFTP clients on the same Mac as Cyberduck (and other computers) work.

I've opened an issue in the ProFTPd tracker : https://github.com/proftpd/proftpd/issues/1694
It seems that it an issue with host and/or client keys. 

I was relunctant to open an issue here because the problem appeared when something changed on the server side, while nothing changed on the client side. I work in hosting and I hate when clients open tickets for something that changed on their side and not mine.
But, on many different computer (including those where the problem with Cyberduck is reproductible) I've managed to connect using other SFTP clients (builtin "sftp" command, FileZilla…).

I don't know how to verify what Cyberduck does when connecting. I've attached a log file, but I could get any meaningful information from it myself.

If you have any idea how I can help debug this, I'd be happy to.

Context :
* macos 12.6.8 (21G725)
* Cyberduck 8.6.3 (40040)

Logs (I've changed my username, domain name and IP address) :
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/12343253/cyberduck.log)

**Comment by ylangisc** [comment]
Closing this as the bug is confirmed on the ProFTPd side.
