### ISSUE TITLE
files downloaded over and over

### ISSUE THREAD

**Issue by jreiter1975** [iterate-ch/cyberduck#15011]
Cyberduck with Wasabi S3.

Large files never finish correctly in downloading.  Shows finished, but download speed continues to reduce over the next 10-15 minutes til program hangs.
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/12381337/cyberduck.log)
![Cyberduck](https://github.com/iterate-ch/cyberduck/assets/30632774/9147fd40-58eb-44b6-b803-0ba1f7a5498f)

**Comment by jreiter1975** [comment]
Hi David, 

That setting seems to have done the trick. The downloads complete properly now. 

Thank you! 

Jeff 




From: "David Kocher" ***@***.***> 
To: "iterate-ch/cyberduck" ***@***.***> 
Cc: "Jeff Reiter" ***@***.***>, "Author" ***@***.***> 
Sent: Wednesday, September 6, 2023 1:44:07 AM 
Subject: [EXTERNAL] Re: [iterate-ch/cyberduck] files downloaded over and over (Issue #15011) 

Can you try disabling segmented downloads 
͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ ͏‌ 
Caution: External email from: ' [ https://telluride.longmont.cloud/public/launchNewWindow.jsp?skin=carbon&localeId=en&full=1&childId=0# | ***@***.*** ] ' 
Use caution before clicking on links or opening attachments. 	
Protection by [ https://mxguardian.net/ | MXGuardian ] 




Can you try disabling [ https://docs.cyberduck.io/cyberduck/download/#segmented-downloads | segmented downloads ] .

**Comment by dkocher** [comment]
Relates to #13610.
