### ISSUE TITLE
Crash after private key selection

### ISSUE THREAD

**Issue by YannSterckx** [iterate-ch/cyberduck#15024]
Dear,

I recently updated CyberDuck (v8.6.2) and am working on a Macbook Pro (macos v12.6).
After the update, the program crashes everytime I try to select a private key to connect to my academic work server.

Everything was working fine prior to the update. Please find the crash report attached to this message.

Any help would be appreciated.

Best wishes,

Yann
[CyberDuck_crash_report.txt](https://github.com/iterate-ch/cyberduck/files/12419469/CyberDuck_crash_report.txt)

**Comment by Subnero2001** [comment]
I am having exactly the same issue after the upgrade  on OS X 13.5.1 the only way to make it work is to delete the entire app, reinstall it and then it will only work once before the same error happens. Has anyone found a work around for this at the moment as it is very annoying for a paid app? Thanks

**Comment by dkocher** [comment]
Crash in AppKit duplicate for #13682.

```

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	    0x7ff8182cc00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8183021ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff81824dd24 abort + 123
3   libc++abi.dylib               	    0x7ff8182be082 abort_message + 241
4   libc++abi.dylib               	    0x7ff8182af1bd demangling_terminate_handler() + 266
5   libobjc.A.dylib               	    0x7ff8181abe11 _objc_terminate() + 96
6   libc++abi.dylib               	    0x7ff8182bd4a7 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	    0x7ff8182bfd05 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	    0x7ff8182bfccc __cxa_throw + 116
9   libobjc.A.dylib               	    0x7ff8181a4cc1 objc_exception_throw + 302
10  Foundation                    	    0x7ff8192f0d03 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 267
11  AppKit                        	    0x7ff81b13469e -[NSApplication endSheet:returnCode:] + 121
```

**Comment by huubvv** [comment]
I am using 8.6.3 and still have this issue
