### ISSUE TITLE
Allow suppression of prompt when fetching authorization code from browser

### ISSUE THREAD

**Issue by chenkins** [iterate-ch/cyberduck#15054]
**Is your feature request related to a problem? Please describe.**
The modal window can hide the browser in some situations. 

**Describe the solution you'd like**
Use the `"oauth.browser.open.warn` property to skip showing `prompt.await` in `CustomSchemeHandlerOAuth2AuthorizationCodeProvider`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by dkocher** [comment]
If implemented there must be an alternative to the prompt for cancelling the connection attempt.
