### ISSUE TITLE
Transfer Incomplete on Upload Sync into Cryptomator Vault

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/cyberduck#15161]
**Describe the bug**
Cyberduck indicates that the transfer is incomplete despite having all items transferred successfully into the vault.

**To Reproduce**
1. Setup Upload sync of a local folder to a remote Cryptomator vault.
2. Let the sync process run through.
3. Cyberduck indicates that the transfer is incomplete at the end of the process.

**Expected behavior**
Show the correct state of the transfer after it has finished

**Notes:**
 - OS: Windows, macOS
 - Cyberduck Version 8.6.3

**Comment by dkocher** [comment]
Please reopen if you can reproduce with the current release.
