### ISSUE TITLE
CyberDuck & MountainDuck don't see into S3 objects with multiple slashes

### ISSUE THREAD

**Issue by John-D-B** [iterate-ch/cyberduck#15173]
Follow up from [^1]. After the workflow below, the 'Ducks cannot see  `folder-2//kitten.jpg`

```
$ aws s3 cp kitten.jpg s3://slasher-test/folder-1/kitten.jpg
    upload: ./kitten.jpg to s3://slasher-test/folder-1/kitten.jpg

$ aws s3 cp kitten.jpg s3://slasher-test/folder-2//kitten.jpg
    upload: ./kitten.jpg to s3://slasher-test/folder-2//kitten.jpg   

$ aws s3 ls s3://slasher-test --recursive
    2023-10-05 09:24:55      96444 folder-1/kitten.jpg
    2023-10-05 09:25:03      96444 folder-2//kitten.jpg
```

[^1]: [StackOverflow](https://stackoverflow.com/questions/77235258/aws-s3-collapsing-multiple-slashes-into-just-one)

**Comment by dkocher** [comment]
Duplicate for #10981.

**Comment by John-D-B** [comment]
Duplicate yes, but this way there's a publicly visible description of the problem - to benefit others.

i have the impression that you haven't solved the problem in the 'Duck products, but rather, you just referenced docs that say "don't do this".

The ongoing issue here is that there's no "**you**" doing bad behavior, but rather, existing workflow and software with Linux-based file access paradigms that need still support.

May I kindly ask you to re-open this issue, and implement a fix in the 'Ducks, instead of giving reasons why not?

Thanks much, this would be well appreciated and definitely more useful as a **bug-fix** than a **bug-won't-fix**.

**Comment by dkocher** [comment]
> Thanks much, this would be well appreciated and definitely more useful as a **bug-fix** than a **bug-won't-fix**.

We acknowledge this is an open issue in #10981.

**Comment by John-D-B** [comment]
Yeah, but that topic is 3 years old. **Bug-as-Tech-Debt-and-Forgotten-About**.

Could this fix be expedited? It seems like a small amount of work, about the same refactoring effort that every other Unixy "double slash" use-cases need to do.

Maybe you could first roll this out in your "**premium paid-for**" edition to get revenue funding, as there's definitely a cost-factor to deal with this S3 situation on the customer side.

Thanks

**Comment by dkocher** [comment]
> Yeah, but that topic is 3 years old. **Bug-as-Tech-Debt-and-Forgotten-About**.
> 
> Could this fix be expedited? It seems like a small amount of work, about the same refactoring effort that every other Unixy "double slash" use-cases need to do.
> 
> Maybe you could first roll this out in your "**premium paid-for**" edition to get revenue funding, as there's definitely a cost-factor to deal with this S3 situation on the customer side.
> 
> Thanks

Unfortunately this has many implications for prefix handling in our S3 protocol implementation but pull requests are always welcome.

**Comment by John-D-B** [comment]
In other words - you want **me** to fix it for you?
