### ISSUE TITLE
Support OpenSSH with certificate user authentication

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#15183]
Feature 8.0 [mentions](https://github.com/iterate-ch/cyberduck/blob/release-8-0-0/Changelog.txt#L11) support for SSH certificates due to support in SSHJ (v0.32.0), but requires setup to work properly.
In 8.0 Public Key Authentication is used as

https://github.com/iterate-ch/cyberduck/blob/65849932163b5b30b6db028f3d482cc07bc8e639/ssh/src/main/java/ch/cyberduck/core/sftp/auth/SFTPPublicKeyAuthentication.java#L96

We'd need to forward the absolute file path to SSHJ in order to get SSH certificates to work properly, like:

    public static File getPublicKeyFile(File privateKeyFile) {
        File pubKey = new File(privateKeyFile + "-cert.pub");
        if (!pubKey.exists()) {
            pubKey = new File(privateKeyFile + ".pub");
        }
        if (pubKey.exists()) {
            return pubKey;
        }
        return null;
    }

https://github.com/hierynomus/sshj/blob/ff4a4774bd1e3d45e9e796c2b17ef835e7e6d67f/src/main/java/com/hierynomus/sshj/userauth/keyprovider/OpenSSHKeyFileUtil.java#L32-L41

or, based on contract, call `initPublicKey` after `init`:

https://github.com/hierynomus/sshj/blob/ff4a4774bd1e3d45e9e796c2b17ef835e7e6d67f/src/main/java/net/schmizz/sshj/userauth/keyprovider/OpenSSHKeyFile.java#L88-L92

**Comment by dkocher** [comment]
Reverted in 59e1843d.
