### ISSUE TITLE
Immediate crash creating/viewing a bookmark for FTP-SSL connections

### ISSUE THREAD

**Issue by sensibleish** [iterate-ch/cyberduck#15196]
1. Start creating a new bookmark.
2. Change the connection type to `FTP-SSL`.

Immediate crash. Version 8.6.3 on macOS 13.6. Reproduced on 2 computers.

**Comment by dkocher** [comment]
Please attach the [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports).
