### ISSUE TITLE
Crashed when I use history SFTP to reconnect

### ISSUE THREAD

**Issue by cryptoadu** [iterate-ch/cyberduck#15229]
Steps:
Add a new connect, select SFTP, choose ssh key option, finish other config, connect success. 

Command+Q, quit program.

Reopen Cyberduck, in the bookmark or history tab, select the SFTP record to connect, it open a window let to select ssh-key, choose the key-file, then Crashed.

**Comment by cryptoadu** [comment]
Solved: move the key file to .ssh/ directory

**Comment by dkocher** [comment]
Please add the latest [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports).

**Comment by Misakaou** [comment]
Same situation, here is my crash report.
[Cyberduck-2023-10-23-140941.zip](https://github.com/iterate-ch/cyberduck/files/13066664/Cyberduck-2023-10-23-140941.zip)

**Comment by dkocher** [comment]
> Same situation, here is my crash report. [Cyberduck-2023-10-23-140941.zip](https://github.com/iterate-ch/cyberduck/files/13066664/Cyberduck-2023-10-23-140941.zip)

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1906a711c __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1906decc0 pthread_kill + 288
2   libsystem_c.dylib             	       0x1905eea50 abort + 180
3   libc++abi.dylib               	       0x1906966d8 abort_message + 132
4   libc++abi.dylib               	       0x1906867c8 demangling_terminate_handler() + 348
5   libobjc.A.dylib               	       0x190333894 _objc_terminate() + 144
6   libc++abi.dylib               	       0x190695a9c std::__terminate(void (*)()) + 16
7   libc++abi.dylib               	       0x190698a48 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 36
8   libc++abi.dylib               	       0x1906989f4 __cxa_throw + 140
9   libobjc.A.dylib               	       0x19032a01c objc_exception_throw + 420
10  Foundation                    	       0x19197718c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 188
11  AppKit                        	       0x1942325d4 -[NSApplication endSheet:returnCode:] + 112
12  libjnidispatch.dylib          	       0x10491004c 0x104900000 + 65612
13  libjnidispatch.dylib          	       0x10490ea18 0x104900000 + 59928
14  libjnidispatch.dylib          	       0x104906814 0x104900000 + 26644
15  libjnidispatch.dylib          	       0x104906be8 Java_com_sun_jna_Native_invokeVoid + 44
16  ???                           	       0x1101bd704 ???
17  ???                           	       0x110403830 ???
18  ???                           	          0x190438 ???
```

Duplicate for #13682.

@Misakaou Can you let me know 
* If the private key is password protected and you have saved the passphrase in the keychain or not.
* Running Cyberduck from the Mac App Store

**Comment by Misakaou** [comment]
@dkocher Thank you for your prompt reply!

> If the private key is password protected and you have saved the passphrase in the keychain or not.
- the private key doesn't have a password.
> Running Cyberduck from the Mac App Store
- Yes, It's Mac App Store version. Version 8.7.0 (40629)

**Comment by dkocher** [comment]
We can reproduce the crash. Follow up in #13682.
