### ISSUE TITLE
SMB Time Capsule - Underflow error on connect

### ISSUE THREAD

**Issue by hoydas** [iterate-ch/cyberduck#15226]
Background:
Apple Time Capsule router
USB drive attached and setup as network disk sharing (secured with option for device password)
Able to connect using SMB on other clients or apps including Finder and Infuse

The bug/error:
When I try to connect to the SMB share using Cyberduck, I get the following error:

Connection failed (Infuse)
Java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: com.hierynomus.protocol.commons.buffer.Buffer$BufferException: Underflow.

![screenshot_0702](https://github.com/iterate-ch/cyberduck/assets/148478797/9da5e10a-3348-4ca7-840b-cd606eca6bb6)

**Comment by dkocher** [comment]
Upstream issue in [^1].

[^1]: hierynomus/smbj#501

**Comment by dkocher** [comment]
@hoydas Can you please test with [snapshot build](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) 8.7.1.40638 and let me know if that makes any difference.

**Comment by hoydas** [comment]
@dkocher  That error is gone, but now I get a new one:
Java.util.concurrent.ExeutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.mssmb.SMB1NotSupportedException: SMBv1 is not supported by SMBJ.

I don't think I can update the SMB version on the Time Capsule, so I'm not sure if anything else can be done?

**Comment by dkocher** [comment]
> I don't think I can update the SMB version on the Time Capsule, so I'm not sure if anything else can be done?

We only aim to be [compatible](https://docs.cyberduck.io/protocols/smb/#interoperability) with SMBv3.

**Comment by hoydas** [comment]
@dkocher Ok. Thats fair and I have read that to be the philosophy of smbj as well due to security reasons. I wonder if SMBv3 support could be the default, but is there a way to let the user allow SMBv1 as an option. 

Other apps use the highest version of SMB available but do from back down if needed. Infuse for example allows Auto, SMB3, SMB2, SMB1, Legacy. Auto seems to figure it out most of the time but sometimes Legacy is needed for older hardware. 

Thanks for considering. Once you released SMB support, I saw the potential once there is Mountain Duck support.  It would be great if it worked but understand if it's not possible based on choices for your app. 

Thanks again!

**Comment by dkocher** [comment]
> @dkocher Ok. Thats fair and I have read that to be the philosophy of smbj as well due to security reasons. I wonder if SMBv3 support could be the default, but is there a way to let the user allow SMBv1 as an option.

SMBv1 is not supported in the upstream library and therefore we cannot provide support.

**Comment by hoydas** [comment]
@dkocher Thanks again for your responses.  I know it won't be a high priority (if at all!),  but it looks like there is an older Java package, jCIFS, and some newer forks, that do support older SMB devices.  (I totally understand that this may be wishful thinking on my part!  Haha!)

**Comment by dkocher** [comment]
> @dkocher Thanks again for your responses. I know it won't be a high priority (if at all!), but it looks like there is an older Java package, jCIFS, and some newer forks, that do support older SMB devices. (I totally understand that this may be wishful thinking on my part! Haha!)

We are reluctant to invest time in integrating yet another third party library to bring support for SMBv1.
