### ISSUE TITLE
S3 Pre-signed URLS for non AWS service incorrect

### ISSUE THREAD

**Issue by sfarrowGR** [iterate-ch/cyberduck#15231]
**Describe the bug**
After updating to 8.7.0 if I generate a pre-signed URL on a non-amazon S3 object store, the link generated points to amazon was, not my custom server.  I can connect, upload, download etc, but the pre-signed URLs are incorrect.

**To Reproduce**
1. Login to a non-amazon s3 service in Cyber Duck.
2. Right click on a file and copy a pre-signed URL.

**Expected behavior**
A URL like this is generated: https://bucketname.myserver.com/key-here

**Actual behaviour**
https://bucket.s3.amazonaws.com/key-here (note the s3.amazonaws.com

**Comment by ldjb** [comment]
I am experiencing the same issue when trying to generate signed URLs for Wasabi buckets.

The hostnames of the signed URLs are `{bucketName}.s3.amazonaws.com`, whereas I would expect them to be (for example) `{bucketName}.s3.eu-central-1.wasabisys.com`.

**Comment by dkocher** [comment]
> I am experiencing the same issue when trying to generate signed URLs for Wasabi buckets.

For Wasabi, make sure to use a connection profile provided [^1].

[^1]: https://docs.cyberduck.io/protocols/s3/wasabi/

**Comment by dkocher** [comment]
Regression from efdbc706.
