### ISSUE TITLE
Cannot longer connect to S3 after Version 8.7.0 update

### ISSUE THREAD

**Issue by javide** [iterate-ch/cyberduck#15240]
After updating to Version 8.7.0 on my Apple M1 Max Sonoma 14.0 I am no longer able to connect to a series of bookmarked AWS S3 buckets.

I enter the correct access key id and secret acces key when prompted 

<img width="476" alt="Screenshot 2023-10-23 at 4 31 31 pm" src="https://github.com/iterate-ch/cyberduck/assets/4940103/38a89dd6-eeb2-405b-abf3-2ee6183208ea">

and instead of seen the list of objects in my bucket, I get this message:

<img width="404" alt="Screenshot 2023-10-23 at 4 31 45 pm" src="https://github.com/iterate-ch/cyberduck/assets/4940103/fc4129c1-c468-44b3-8c2d-21a3939c4ad7">

**Comment by przemyslawpluta** [comment]
Same issue on Ventura with this version.

**Comment by przemyslawpluta** [comment]
Works without issues on **8.6.3**

**Comment by dkocher** [comment]
> Same issue on Ventura with this version also while using profiles in ~/.aws/credentials

Duplicate for #15222.

**Comment by aracg** [comment]
I see the same issue on Windows 11.

**Comment by dkocher** [comment]
> I see the same issue on Windows 11.

What connection profile are you using? @aracg Please attach a debug log from Preferences → Connection.

**Comment by aracg** [comment]
On second thought, maybe issue I see is not the same. I'm using profile S3 (Credentials from AWS CLI), using SSO (with periodical  `aws sts get-caller-identity --profile xxxx`) which worked in previous version. I'll see if I can get the log.

**Comment by dkocher** [comment]
> On second thought, maybe issue I see is not the same. I'm using profile S3 (Credentials from AWS CLI), using SSO (with periodical `aws sts get-caller-identity --profile xxxx`) which worked in previous version. I'll see if I can get the log.

This is fixed in the current snapshot build. Duplicate for #15222.
