### ISSUE TITLE
Keeps putting copy of bookmarks in trash when launched.

### ISSUE THREAD

**Issue by metril** [iterate-ch/cyberduck#15255]
**Describe the bug**
Mountain Duck keeps putting bookmarks in the trash upon launch if a connection was previously open prior to close.

**To Reproduce**
1. Enable "Save Workspace".
2. Setup and connect to any service. Save the bookmark.
3. With the connection "connected", quit Mountain Duck.
4. Relaunch Mountain Duck and within a few seconds, a copy of the stored bookmarks will be put in the trash.

**Expected behavior**
Mountain Duck should not be putting any bookmarks in the trash unless the user has chosen to delete the bookmark(s).

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Version 13.3.1

**Log Files**
Search log file for "DELETE" and you will see that Mountain Duck seems to think a filesystem DELETE event is emitted.

**Additional context**
Can reproduce problem on both a physical Macbook Pro install as well as in a fresh MacOS VM. Using direct download version of Mountain Duck.
[mountainduck.log](https://github.com/iterate-ch/cyberduck/files/13109308/mountainduck.log)

**Comment by dkocher** [comment]
Regresion from f3480a82. Should not apply to `Sessions`.
