### ISSUE TITLE
AWS connection using CLI session tokens broken on v8.7.0

### ISSUE THREAD

**Issue by flypenguin** [iterate-ch/cyberduck#15297]
**Describe the bug**
The "S3 (Credentials from AWS Command Line Interface)" profile no longer works

**To Reproduce**
1. Use an AWS bucket with AWS STS tokens
2. Upgrade to v8.7.0
3. Try to connect

**Expected behavior**
A connection is established

**Screenshots**
- The configuration that works is attached below as a screenshot

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.0 (23A344)

**Log Files**
- Log file is attached

**Additional context**
I did nothing else but upgrade, and it stopped working.

## Logfile

[cyberduck.log.zip](https://github.com/iterate-ch/cyberduck/files/13206376/cyberduck.log.zip)

## Screenshot

![cyberduck-working-and-non-working-config](https://github.com/iterate-ch/cyberduck/assets/5030694/97bf0e69-93c2-493a-a2b9-51e587f9fd03)

**Comment by flypenguin** [comment]
Ups. Missed that. Sorry. :)

**Comment by dkocher** [comment]
> Ups. Missed that. Sorry. :)

No problem. The fix is available in the current snapshot build and will be pushed to _Release_ later this week.
