### ISSUE TITLE
8.7.0 Update Breaks Keychain Access - Mac OS Sonoma

### ISSUE THREAD

**Issue by kittonian** [iterate-ch/cyberduck#15300]
Just opened Cyberduck and it asked to update to 8.7.0 so I did. Unfortunately after doing so, my bookmark can no longer find my client certificate stored in Apple Keychain. I tried removing the certificate and importing it again, no change. Both my root cert and my client cert are marked as Always Trust, and they work perfectly via Firefox.

When I go into my bookmark, the drop down that displays my certificate selections is blank. This means I cannot connect to my WebDav server.

Can confirm that downgrading to 8.6.3 shows my certificate and I can select it and login.

**Comment by dkocher** [comment]
Duplicate for #15223.
