### ISSUE TITLE
S3 Bookmark using profile for AWS IAM Identity Center no longer work in 8.7.0

### ISSUE THREAD

**Issue by richerdavid** [iterate-ch/cyberduck#15328]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

I created a S3 bookmark created following the instructions here: https://docs.cyberduck.io/protocols/s3/#aws-iam-identity-center

It was working fine with 8.6.3 but stop working after I upgrade to 8.7.0.

https://docs.cyberduck.io/protocols/s3/#aws-iam-identity-center

**To Reproduce**
1. Create an S3 profile following https://docs.cyberduck.io/protocols/s3/#aws-iam-identity-center
2. Create an cyberduck S3 bookmark
3. try to connect

**Expected behavior**

**Screenshots**

<img width="310" alt="Screenshot 2023-11-03 at 9 25 33 PM" src="https://github.com/iterate-ch/cyberduck/assets/104082608/b89459de-c24c-427b-a39b-159c21d9afb9">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.1

**Comment by dkocher** [comment]
Duplicate for #15222.

**Comment by richerdavid** [comment]
Thanks! Just tested 8.7.1 and it's working file!
