### ISSUE TITLE
Renaming Folder Deletes All Files

### ISSUE THREAD

**Issue by Jeff-Enriquez** [iterate-ch/cyberduck#15358]
**Describe the bug**
When connected to S3. If you rename a folder, all of the contents in that folder get deleted. 

**To Reproduce**
1. Create a folder
2. Create a file in that folder
3. Rename the folder

**Expected behavior**
The content of the folder should be copied to the newly named folder.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Sonoma 14.1.1

**Comment by dkocher** [comment]
Do the folder contents show after you choose _Go → Refresh_?
