### ISSUE TITLE
S3 Bucket Download slow on Windows version of CyberDuck (Macs version seems unaffected)

### ISSUE THREAD

**Issue by MarekBabala** [iterate-ch/cyberduck#15367]
Hello, 
I just wanted to point out something, and would be interested if someone using CyberDuck to interface with Downloading / Uploading files to S3 bucket.  

We are seeing pretty strange speed bottleneck on the CyberDuck (latest version 8.7.1, same on beta 8.7.2) (also have seen this slowdown for a while now) 

Downloading large (or small files) with multipart download turned on , and no throttling at all.   All workstations are on very robust 1 GBps network drop.    We can get consistent download rates of 30MB/sec - 35MB/sec from S3 Bucket in Virginia region, or Ohio, or California (tested all the regions in US) .    

On the flip side, i have couple of test Macs (new Silicon and older Intel boxes) and all are downloading in the near 110MB/sec or 90MB/sec if an older CPU is stressed (which is understandable )   

Can you run some speed tests on recent version of CyberDuck if you can duplicate this situation?  Thank You

**Comment by tatze96** [comment]
This is currently expected behavior, given that you're using an encrypted (HTTPS) connection to connect to your S3 server. We're already working on a solution but can't provide a timeframe for when this will be fixed.

I'll close this ticket as a duplicate for #14909. We'll post any updates regarding the solution there.

**Comment by MarekBabala** [comment]
Thank you that is understandable, I am doing some comparison between CyberDuck's copy speed and a copy of just using aws cli, simply using: "aws s3 cp SOURCE DESTINATION --recursive"  and I am getting much better speeds, also tried with some of the different settings that CyberDuck offers for "concurrent connections" and and I can't figure out how to make CyberDuck use just a straight AWS S3 CP command underneath w/o any additional flags/options.      Also , as you stated the https copy does put a strain on using an older computer vs using a very powerful workstation.   Thank you for your response! and pointing out the 14909!
