### ISSUE TITLE
[DE] Transfer incomplete (SFTP Sync)

### ISSUE THREAD

**Issue by MerzGH** [iterate-ch/cyberduck#15389]
![SC 2023-11-22 um 15 32 43](https://github.com/iterate-ch/cyberduck/assets/21160501/3007a267-c721-4156-9666-a7b9d0013e89)

Cyberduck: Version 8.7.1 (40770)
macOS: 14.1.1 (23B81)

Seit dem letzten Update funktioniert die Meldung nicht richtig. Nach der Synchronisation erscheint "Transfer unvollständig". Wenn wir die Daten auf dem Server prüfen, scheint alles geklappt zu haben.

**Comment by tatze96** [comment]
Ich kann das Verhalten hier reproduzieren. Beim ersten Sync Prozess zeigt das Transfer Fenster "Transfer unvollständig", die Dateiliste zeigt allerdings nach dem aktualisieren, dass alles korrekt übertragen wurde. Ein Reload des gleichen Sync-Prozesses zeigt im Anschluss in den meisten Fällen, dass der Transfer erfolgreich war. Das Verhalten tritt nicht nur für SFTP auf, ich konnte es beispielsweise auch für S3 reproduzieren.

---

I can reproduce the described synchronization behavior on my side. The first synchronization process finishes with "Transfer incomplete" and "0B of xB". Still, the file listing shows that all files were correctly transferred after a file listing refresh. If you Reload the synchronization process, it indicates a successful transfer process in most cases. The display issue isn't limited to SFTP; I can also reproduce it for S3, for instance.

**Comment by AcidSlide** [comment]
I have been waiting for this fix since mid-2023.. #14974

**Comment by dkocher** [comment]
Closing as duplicate for #14974.
