### ISSUE TITLE
Upload error seen screenshot 

### ISSUE THREAD

**Issue by blumorrell** [iterate-ch/cyberduck#15396]
<img width="230" alt="Upload IMG_9869 CR2 failed" src="https://github.com/iterate-ch/cyberduck/assets/139998605/6c1d8c5b-92ad-4c02-8aeb-214c7d8c7bc7">

**Comment by tatze96** [comment]
Please add more information about the present issue:
* Which protocol is in use?
* Did you try to upload the file into a standard folder or a Cryptomator vault?
* Which operating system is in use?
* Which version of Cyberduck is in use?

**Comment by blumorrell** [comment]
What do you mean by protocol?
Uploading to standard folder
Mac OS Sonoma 14.1.1
Cyberduck Version 8.7.1 (40770)

Kind regards,

Byron Lu Morrell
***@***.***

**Comment by dkocher** [comment]
We are working to better handle B2 and its unreliable by design error responses in #15601.
