### ISSUE TITLE
How to protect my connections?

### ISSUE THREAD

**Issue by stefano-p** [iterate-ch/cyberduck#15404]
### Discussed in https://github.com/iterate-ch/cyberduck/discussions/15369

<div type='discussions-op-text'>

<sup>Originally posted by **stefano-p** November 18, 2023</sup>
In my view, cyberduck looks really nice, but it seems an important security feature is totally missing. After I have configured my connections and set my favorite ones, how shall I prevent unauthorized users from launching this tool and access all my data? I would expect at least a kind of a master password or something, so that my configurations are not visible to anyone. If there were a portable version of cyberduck, this would solve this problem. So, my question is: am I missing something? How can I protect my configured connection?</div>

**Comment by stefano-p** [comment]
I would suggest to implement the possibility to add a master password, in a similar way as in S3 Browser.

**Comment by dkocher** [comment]
The master password is the login to your computer and optionally a different password to access credentials in your login keychain.
