### ISSUE TITLE
Application Crash When Deleting Multiple Items in Backblaze B2 Bucket

### ISSUE THREAD

**Issue by itswzyss** [iterate-ch/cyberduck#15416]
**Describe the bug**
Application crashes after selecting multiple items and right-clicking > Delete OR pressing the Delete key. Selected items appear to get deleted from remote. Crash may be happening when refreshing file tree?

**To Reproduce**
Not always re-producible!

1. Log into B2 bucket
2. Browse into a folder with multiple files
3. Select multiple files (at least 3+)
4. Right-click -> Delete
5. Items will disappear and then the application immediately crashes

**Expected behavior**
Application should delete the selected items and automatically refresh, displaying the newly updated file tree / list.

**Screenshots**
After two application crashes, I haven't been able to repro -- so unfortunately no screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 11 (22H2, 22621.2715)

**Log Files**
* [cyberduck.log](https://github.com/iterate-ch/cyberduck/files/13520625/cyberduck.log)

**Additional context**
* File names don't contain any special characters. An example of file name being referenced is `authentik_backup_2023-10-08_00-00-12.zip`
* Files being deleted are ZIP files

**Comment by AliveDevil** [comment]
Duplicates #10785

Basically: Some external library is causing these issues, which has long been abandoned by their authors, and we don't have the capacity to fork and fix this.
