### ISSUE TITLE
Transfer incomplete message

### ISSUE THREAD

**Issue by 4RBull** [iterate-ch/cyberduck#15431]
A few versions back I started getting transfer incomplete messages following a sync download.  This had previously worked fine until an update.  I waited for it to be fixed after the last few updates but nothing yet.

It does appear to be downloadiing the files but I can not trust them now.

I have attached a screenshot.
<img width="503" alt="Screenshot 2023-12-04 at 10 26 47 PM" src="https://github.com/iterate-ch/cyberduck/assets/152949603/21f4d296-619a-4ca7-ae17-0d9745daeab5">

I have also attached log files.
[cyberduck-2023-12-04T223312.log.zip](https://github.com/iterate-ch/cyberduck/files/13555653/cyberduck-2023-12-04T223312.log.zip)

Current version is Version 8.7.1 (40770)
MacOS Sonoma 14.1.2 (23B92)
The problem predated both the current CyberDuck version and the MacOS version.

**Comment by 4RBull** [comment]
No response in over a month.  Log files deleted.

**Comment by dkocher** [comment]
Duplicate for #14974.
