### ISSUE TITLE
Cyberduck crashing when I try to download files or does not want to disconnect

### ISSUE THREAD

**Issue by jamest1206** [iterate-ch/cyberduck#15439]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
I am trying to download and upload files but Cyberduck shuts down and closes.  
![Screenshot (139)](https://github.com/iterate-ch/cyberduck/assets/143458387/04258f40-f0b0-4184-ab9e-a1a215879885)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #15794.
