### ISSUE TITLE
Memory Exhaustion Error - SMB Connections

### ISSUE THREAD

**Issue by filimentation** [iterate-ch/cyberduck#15488]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Memory exhaustion error when downloading large amounts of files over SMB 

**To Reproduce**
1. Start Cyberduck 
2. Connect to SMB server via Cyberduck
3. Download several thousand small files (<2mb)
4. Watch memory utilization 

**Expected behavior**
I'd expect a memory "limit" where SMB connection downloads don't take up 50gb of memory, but possibly at most 2gb. 

**Screenshots**
Screenshot 1:  Showing the highest value I was able to capture
Screenshot 2: Showing that its not an isolate incident.

**Desktop (please complete the following information):**
 - MacOS:
 -    Version: 14.2.1 (23C71)
 - CyberDuck 
 -    Version: 8.7.1 (40770)
 - SMB Server
 -    Ubuntu Server 22.04 
 
**Log Files**
I have log files which I could upload to a secure area.  I don't have time to redact a 10mb text file with regex.
<img width="641" alt="screenshot 1" src="https://github.com/iterate-ch/cyberduck/assets/63804268/95ea2b2b-0135-4551-9365-c3ac605bf221">
<img width="959" alt="screenshot 2" src="https://github.com/iterate-ch/cyberduck/assets/63804268/4b8195a5-d6f9-447c-adbe-346fdaa78861">

**Additional context**
It seems to happen everytime even with larger files.  It usually ends up with the MacBook pro M1 giving the spinning wheel and I then have to kill it (CyberDuck) in Activity Monitor.

**Comment by ylangisc** [comment]
I have tried to reproduce the issue with the same setup but couldn't see any memory leaking at all. The memory never went beyond 1.5GB. As we integrate with native code from our JVM I suspect unreleased native resources which are not visible inspecting the Java heap.

As you are able to reproduce the issue it would great if you could confirm my suspicion by using [Visual VM](https://visualvm.github.io/) to inspect the JVM heap. 

Steps:
* reproduce the exhausting memory situation
* start VisualVM and connect to `ch.iterate.mountainduck.application.StatusBarApplication`
* switch to _Monitor_ tab, take a screenshot of the _Heap_ graph and post it

**Comment by tristanmcguire** [comment]
My comment from what is possibly a duplicate report of this error - https://github.com/iterate-ch/cyberduck/issues/15510#issuecomment-2055598351  

I have not followed the Visual VM instructions above.
