### ISSUE TITLE
Support upload to S3 buckets with Object Lock enabled

### ISSUE THREAD

**Issue by yoni-yad2** [iterate-ch/cyberduck#15557]
**Is your feature request related to a problem? Please describe.**
Currently when trying to upload a file into an S3 bucket which has Object Lock enabled, this error shows:

```
InvalidRequest: Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters
```

**Describe the solution you'd like**
Calculate MD5 hash for the file and upload it in the request header along with the file.

**Describe alternatives you've considered**
Disabling Object Lock on the S3 bucket temporarily to be able to upload the file.

**Additional context**
[Discussion about workarounds for this issue](https://github.com/aws/aws-sdk-php/issues/1694)

**Comment by dkocher** [comment]
This would need to be set conditionally depending on the object lock configuration [^1] of the bucket.

[^1]: https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLockConfiguration.html

**Comment by dkocher** [comment]
> This would need to be set conditionally depending on the object lock configuration [1](#user-content-fn-1-b40a791b5dc1b08b09dbc9f907b9cedf) of the bucket.
> 
> ## Footnotes
> 1. https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectLockConfiguration.html [↩](#user-content-fnref-1-b40a791b5dc1b08b09dbc9f907b9cedf)

It would probably be easier to just set the `Content-MD5` unconditionally for al uploads.

**Comment by dkocher** [comment]
Looks like instead we can use one of 

```
x-amz-checksum-crc32: ChecksumCRC32
x-amz-checksum-crc32c: ChecksumCRC32C
x-amz-checksum-sha1: ChecksumSHA1
x-amz-checksum-sha256: ChecksumSHA256
```

**Comment by dkocher** [comment]
Fix does not apply for multipart uploads.

**Comment by dkocher** [comment]
> Fix does not apply for multipart uploads.

We previously came to the conclusion in f7977d0f that the `x-amz-checksum-sha256` must be omitted for parts.
