### ISSUE TITLE
Choosing AWS2 profile causes signature mismatch errors with AWS S3

### ISSUE THREAD

**Issue by jamshid** [iterate-ch/cyberduck#15556]
**Describe the bug**
Your S3 AWS2 V2 Signature profiles (HTTP and HTTPS) in Version 8.7.2 (40975) does not work even with AWS S3. The list of buckets show fine but lots of 403 errors like for GET /bucket?versioning below.

I think one problem is that you send x-amz-date with an ISO-8601 date but V2 requires one of the old HTTP date formats:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html

**To Reproduce**
1. Create a connection S3 AWS2 Signature Version.
2. Open it, see the list of buckets.
3. Double click on a bucket, see 
Cannot read container configuration. (Amazon S3)
The request signature we calculated does not match the signature you provided. Check your key and signing method. Please contact your web hosting service provider for assistance.

**Expected behavior**
It works fine if I switch to defaultt Amazon S3 profile, same access and secret key.

**Screenshots**
<img width="904" alt="Screenshot 2024-01-17 at 3 53 53 PM" src="https://github.com/iterate-ch/cyberduck/assets/8549/f239a2d2-24fb-4bb0-a14a-a2150d066e10">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.1.2

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/13969147/cyberduck.log)

**Additional context**
David said he couldn't reproduce but I'm only using an access key for the account owner so it's not a permission issue. Log shows it's a signature mismatch.

> I cannot seem to reproduce the authentication failure using the S3 AWS2 Signature Version (HTTPS) connection profile connecting to AWS. The problem is probably just that have not granted s3:GetBucketVersioning for the user. Refer to https://docs.cyberduck.io/protocols/s3/#versions

**Comment by dkocher** [comment]
Some regions do no longer support AWS2 signatures but the error will be different.

> The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

**Comment by dkocher** [comment]
@jamshid Can you let me know the reasoning to use AWS2 authentication with AWS S3?

**Comment by jamshid** [comment]
It's fine I don't really need AWSV2 sigs. 
I was just testing it because Cyberduck failed same way against an S3-compatible system and I thought there was a V2
bug in that server.
