### ISSUE TITLE
remote file transfer always ends with "transfer" incomplete likely becasue the bytes are counted double

### ISSUE THREAD

**Issue by altmvogi** [iterate-ch/cyberduck#15583]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**
- host OS Mac 14.3
- set up two sftp file transfers with Linux host in my case two RHEL servers.
- open two browser windows and drag a file from source to destination.
- the issue is whatever you do the transfer reports incomplete 
- I notice that the app reports twice as much as the file transfer is. Transfer incomplete 1.8k of 907B 
- however, the file gets transferred properly.
- this has been working in the previous version properly. please fix this.

**Expected behavior**
I expect the remote to remote transfer to complete without reporting an error/

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Version 14.3

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by altmvogi** [comment]
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/14057779/cyberduck.log)

**Comment by altmvogi** [comment]
![Screenshot at Jan 25 22-10-11](https://github.com/iterate-ch/cyberduck/assets/18576195/428260ad-54ee-4f81-883e-0be7f1a77557)

**Comment by dkocher** [comment]
Regression from 6c0604dd.

**Comment by kbuc** [comment]
Still the same behaviour (S3, encrypted vault). Cyberduck 9.0.3 (42112) for Windows. 
![image](https://github.com/user-attachments/assets/233ba661-6079-440f-b737-d5fa735f61e2)
