### ISSUE TITLE
Incomplete transfers in latest version

### ISSUE THREAD

**Issue by sbartelski** [iterate-ch/cyberduck#15598]
**Describe the bug**
Since installing the latest update, it seems that server to server transfers, which used to work perfectly, are now showing 'Transfer incomplete'. When I check the target location I see the expected files. Note also that the data volume lisetd is two times what was determined as the size of the selected file (2xN of N). 
Also, the progress section where I could see how much of the files have been copied does not show, it seems to get stuck on 'Preparing' of 'Login successful' until 'Transfer incomplete' appears.
**To Reproduce**
1. Open two browsers, one for each server
2. Select files to be copied in sending directory
3. Drag to target directory

**Expected behavior**
In the previous version, it would show 'Transfer complete' and the correct data volume, e.g. 'N of N' Also once the prepare stage was complete, the progress was shown, e.g. file being copied and % complete of the selection

**Screenshots**
![image](https://github.com/iterate-ch/cyberduck/assets/17244265/95f0a678-8d81-4191-8972-7f433f1b4a4f)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/14114897/cyberduck.log)

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #15583.
