### ISSUE TITLE
duck CLI v8.7.1 hangs on permissions request page with dropbox instead of file allowing uploads 

### ISSUE THREAD

**Issue by jmicklos** [iterate-ch/cyberduck#15593]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Since upgrading to duck cli 8.7.1, I can no longer upload files to dropbox via command line. When I run the duck cli for dropbox, instead of being presented with a duck webpage with an authentication code to use, I am presented an API Authorization Request page on dropbox. When I click the authorize button, it seems to hang. Eventually this times out. I have attempted to remove the existing permissions to duck on dropbox and this has not helped. I have been able to replicate this behavior across multiple machines. 

**To Reproduce**
1. Install duck cli v8.7.1
2. Run a dropbox upload command such as `duck -e compare --upload "dropbox:/$remote_path" "$local_path";`
3. The dropbox API Authorization Request page appears in the browser
4. Attempt to authorize to no avail 

**Expected behavior**
1. Install duck cli v8.7.1
2. Run a dropbox upload command such as `duck -e compare --upload "dropbox:/$remote_path" "$local_path";`
3. [optional] If you need to authorize access in dropbox, the dropbox API Authorization Request page appears in the browser
4. The duck ui supplies an authentication code
5. You can use the authentication code on the command line to continue the upload. 

**Screenshots**
<img width="1031" alt="Screenshot 2024-01-29 at 10 35 48 AM" src="https://github.com/iterate-ch/cyberduck/assets/14788723/7c9d88e8-e1db-4278-9972-46e394048cc8">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.6.3 and 14.3

**Log Files**
I can't seem to find these. They are neither in `~/Library/Logs/Cyberduck` (this directory does not exist) nor in console.app. I am using the homebrew version of the duck cli. I was following instructions in https://docs.cyberduck.io/cyberduck/support/

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #13587. Please try the profile [^1].

[^1]: https://github.com/iterate-ch/cyberduck/issues/13587#issuecomment-1822842151
