### ISSUE TITLE
Application does not open

### ISSUE THREAD

**Issue by BillComplex** [iterate-ch/cyberduck#15609]
Downloaded and unzipped CyberDuck 8.7.2.40975, move to Application folder. Icon appears in dock, bounces, does not open.

<img width="401" alt="Screenshot 2024-02-05 at 2 03 02 PM" src="https://github.com/iterate-ch/cyberduck/assets/159075722/f5296029-647d-4a36-a92d-04011f9f0671">

 - Mac Studio
 - Apple M2 Max
 - MacOS Sonoma Version 14.0

**Comment by dkocher** [comment]
Please reopen with a [crash report](https://docs.cyberduck.io/cyberduck/support/#crash-reports).

**Comment by BillComplex** [comment]
David,

Thank you for the reply and sorry for the delayed response.

I tried to go to the library folders you linked in the crash report, and I
don't receive a response from either.

Attached is a screen recording of me opening the ZIP, adding to my
applications, and attempting to search for those folders.

Thank You,

-
 2024-03-18 09-53-37.mp4
<https://drive.google.com/file/d/1y4E9Jfc2XCO69-wFaC4x1zTwgOYy6vBk/view?usp=drive_web>
Bill

**Comment by BillComplex** [comment]
Hi there David,

Just following up on this and wondering if you saw my recent email. Hope
you had a good weekend.
