### ISSUE TITLE
Overwrite on upload is ignored

### ISSUE THREAD

**Issue by nlour** [iterate-ch/cyberduck#15615]
**Describe the bug**
File overwriting is not occurring upon uploading or synchronizing a local directory of the same name as remote.

**To Reproduce**
1. Drag and drop or synchronize local folder into parent directory containing remote folder of same name
2. On Overwrite dialogue click Continue (note 0 B file size)
3. Transfer of files appears to occur
4. No change (Modified date/time does not change)

**Expected behavior**
- Overwrite dialogue should note total file size of directory intended for upload
- Transfer of files should actually occur
- Modified date/time should update

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1 (23C71)
 - Version 8.7.2 (40975)

**Comment by dkocher** [comment]
I cannot reproduce the problem dragging a folder to upload that exists already on the server. You can choose _Overwrite_ in the prompt that will result in all files to be uploaded again regardless if they already exist on the server.
![Screenshot 2024-03-07 at 10 50 54](https://github.com/iterate-ch/cyberduck/assets/71733/43f12c9c-966c-4909-b4d7-5e63b3e2989a)
