### ISSUE TITLE
NextCloud/OwnCloud Append Connection Path to Default Path

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#15621]
When configuring a NextCloud/OwnCloud connection, users can easily get tripped by how the path is configured in these profiles.

With an empty path the `Home` feature is used, defaulting to `remote.php/dav/files/username`. When a path is set the `Home` feature isn't used, thus Cyberduck tries to mount `/Path/To/Some/Folder`, which should really be `remote.php/dav/files/username/Path/To/some/Folder`.

Proposal:
Unconditionally prepend "remote.php/dav/files/username" to all paths coming _from_ a connection.
Additionally: Make prefix configurable - as in 
```
<key>Properties</key>
<array>
    <string>connection.url.base=remote.php/dav/files/${username}</string>
</array>
```
Where Username-token is replaced in HostPreferences to host configured username.

**Comment by AliveDevil** [comment]
> Häufig ist da noch ein reverse proxy vorne dran, so dass der default pfad nicht mehr stimmt.

Quote @dkocher 

> Often there is a reverse proxy in front, changing the default path.

**Comment by dkocher** [comment]
Unfortunately the OCS capabilities seem to return an invalid value 

```
…
 <capabilities>
   <core>
    <pollinterval>60</pollinterval>
    <webdav-root>remote.php/webdav</webdav-root>
…

advertising `remote.php/webdav` instead of `/remote.php/dav`.

**Comment by ylangisc** [comment]
> Unfortunately the OCS capabilities seem to return an invalid value
> 
> ```
> …
>  <capabilities>
>    <core>
>     <pollinterval>60</pollinterval>
>     <webdav-root>remote.php/webdav</webdav-root>
> …
> ```
> 
> advertising `remote.php/webdav` instead of `remote.php/dav`.

Per the [documentation](https://owncloud.dev/apis/http/webdav/#request-uri) the only non-legacy endpoint is `dav/spaces/`.

**Comment by dkocher** [comment]
> Per the [documentation](https://owncloud.dev/apis/http/webdav/#request-uri) the only non-legacy endpoint is `dav/spaces/`.

We will only change that as part of much larger effort switching to Libre Graph API with #14166.

**Comment by dkocher** [comment]
I want to revisit this to make sure we support more configurations in bookmarks and deployments

- [ ]  Deployments with prefix to default Nextcloud URIs (`example.net/nextcloud`) or root (`example.net/`)
- [ ] Bookmarks configured with custom path using `/remote.php/webdav/path`
- [ ] Bookmarks configured with custom path using `/remote.php/dav/username/path`

**Comment by dkocher** [comment]
- [ ] Ensure no regression for #15855.
