### ISSUE TITLE
"Transfer incomplete" after successful transfer.

### ISSUE THREAD

**Issue by jclounge** [iterate-ch/cyberduck#15632]
**Describe the bug**
Transfer shown as "Transfer incomplete" even after successfully transferring files between two servers over SFTP. Also then does not show the new files until refreshing the view on the destination server.

**To Reproduce**
1. Connect to one server via SFTP in one window.
2. Connect to another server via SFTP in another window.
3. Drag a file from one server file browser window to the other server file browser window.
4. See "Transfer incomplete" with red circle icon even though the file has been transferred successfully.
5. See the complete file is actually now on the destination server by refreshing its file browser window.

**Expected behavior**
Expect it to say "Transfer complete" with green icon, and for the transferred file(s)/folder(s) to appear in the destination server file browser window.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15.7

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/15583.
