### ISSUE TITLE
tab name needs to reflect the current subdirectory that is opened, not the connection directory

### ISSUE THREAD

**Issue by Dahn-YoungDong** [iterate-ch/cyberduck#15649]
**Describe the bug**
When I open multiple tabs -- different subdirectories of the same connection directory, the tab window shows the name only the name of the connection directory. But what is necessary is the name of the current subdirectory that I am currently viewing.

**Comment by dkocher** [comment]
This would imply we will need to update the window title while the user is navigating the folder hierarchy. This is not something we would want.
