### ISSUE TITLE
 Introduce Path Option in Open Connection Box for S3  

### ISSUE THREAD

**Issue by sufiyanpk7** [iterate-ch/cyberduck#15646]
**Is your feature request related to a problem? Please describe.**

In the present situation, if the 'ListAllMyBuckets' permission is not utilized, an error occurs during the login process, After logging in, you can access the option to edit the connection, allowing you to specify the desired bucket. Subsequently, the functionality operates smoothly for the specified bucket

**Describe the solution you'd like**

Adding a path option on the connection page is especially helpful when setting permissions for specific buckets. It makes it easier to manage permissions for individual buckets, It helps prevent complications related to S3 connection issues 

<img width="323" alt="Screenshot 2024-02-19 at 8 54 27 PM" src="https://github.com/iterate-ch/cyberduck/assets/45423403/2669965d-ea3b-4b2a-aa9a-16833614937d">

**Comment by dkocher** [comment]
Duplicate for #12891.
