### ISSUE TITLE
Transfer from FTP to S3 shows as double in size in Transfer Window, and ends as 'Transfer incomplete'.

### ISSUE THREAD

**Issue by gilesncwilliams** [iterate-ch/cyberduck#15688]
I am transferring 71 files from an FTP server to an S3 bucket.
The files are mainly .wav files, on average 40MB in size, plus some .txt files and a .csv. The total file size of the transfer is 1.9 gb

Steps:
- To start the transfer I dragged and dropped the folder from the FTP Cyberduck browser to the S3's browser.
- After transferring, the Transfer Window showed 3.9 gb of 1.9 gb was transferred and that 'transfer incomplete' was shown when it finished (see attached screenshot)
- I checked the files in the S3 and they are all there at 1.9gb, and the few I checked were not corrupt, so it looks like it completed ok.
- I have tried transferring both the whole folder, and then just the files to a new folder in the S3, and the same thing happened both times.

I am about to transfer 2750 .wav files in the same way, so want to be sure there are no issues before starting the larger transfer.

I am using a M1 MacBook Pro running macOS Big Sur 
Cyberduck verison: 8.7.2

Debug log was enabled and logfile attached

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/14511075/cyberduck.log)

<img width="720" alt="Screenshot 2024-03-06 at 13 58 58" src="https://github.com/iterate-ch/cyberduck/assets/150936411/da3069a5-7b22-407f-8cc2-a9184f690860">

**Comment by dkocher** [comment]
Duplicate for https://github.com/iterate-ch/cyberduck/issues/15583.
