### ISSUE TITLE
Cyberduck crashes everytime I go to upload a file

### ISSUE THREAD

**Issue by cls295** [iterate-ch/cyberduck#15682]
When I go to upload a file into Cyberduck the app crashes. The screen will go black after about 10 seconds and then the app crashes. I recently updated cyberduck and it is still showing that it is up to date. I also have unistalled and reinstalled Cyberduck from my desktop. I updated my computer and have the latest version of windows 11 on it.

After updating my desktop and the cyberduck app I am unsure of what else I can do to avoid the app from crashing. I was wondering if  there is possibly a 5000 file limit and if that might be the reason for the crashes? I was also wondering if I purchased Cyberduck in the windows store would I have a higher file limit? I am open to any suggestions to fix this problem.

**Comment by dkocher** [comment]
Duplicate for #6550. Try to remove all items from the transfer window. If you cannot open the *Transfers* window, remove the directory `Transfers` in the [application support directory](https://trac.cyberduck.io/wiki/help/en/faq#Preferencesandapplicationsupportfileslocation) and restart Cyberduck.
