### ISSUE TITLE
Sorting by Date Modified doesn't work well

### ISSUE THREAD

**Issue by kstella** [iterate-ch/cyberduck#15684]
**Describe the bug**
The folders sort order is oK when date is shown, but Today & Yesterday are mixed into the middle.
**To Reproduce**
Just look at a full directory with recent files and folders
**Expected behavior**
Today & Yesterday (macOS silliness) should be overridden by real date, or at least treated correctly. I'd prefer an ISO date structure: 2024-03-04

**Screenshots**
<img width="505" alt="SS 2024-03-03 at 3 55 41 PM" src="https://github.com/iterate-ch/cyberduck/assets/6173205/0810ec2f-a370-456c-aeb8-7e1891a8422b">

**Comment by dkocher** [comment]
The sort order is correct regardless of the date formatter style using relative names.
