### ISSUE TITLE
No thumbnail preview in Finder

### ISSUE THREAD

**Issue by websnowtea** [iterate-ch/cyberduck#15744]
### Discussed in https://github.com/iterate-ch/cyberduck/discussions/15454

<div type='discussions-op-text'>

<sup>Originally posted by **s-zh** December 12, 2023</sup>
I updated my Mac to Sonoma 14.2, but webdav no longer displays thumbnails in Finder. Has anyone encountered the same problem?</div>

Issue still occurs in macOS Sonoma 14.4. Mountain Duck 4.15.6 (21921).

Thank you!

**Comment by dkocher** [comment]
We will keep this as a discussion and follow up when we have an update from Apple as we are not aware of any possibility to implement a workaround for this issue caused by macOS.

**Comment by dkocher** [comment]
> @dkocher I find OneDrive can show thumbnail previews normally

Please refer to the discussion in #15454.
