### ISSUE TITLE
Resolve Include directive in ~/.ssh/config

### ISSUE THREAD

**Issue by ioanalytica** [iterate-ch/cyberduck#15745]
**Is your feature request related to a problem? Please describe.**
Cyberduck is using ~/.ssh/config to allow connections via jump hosts. Larger ssh configuration files are often broken down into several files that are included in  ~/.ssh/config, e.g.

'''
Include ~/.ssh/config.d/*.cfg
'''

The include directive is ignored. Cyberduck can only connect to hosts via aliases and/or jump hosts that are defined directly in ~/.ssh/config.

**Describe the solution you'd like**
Cyberduck should resolve includes in ~/.ssh/config

**Describe alternatives you've considered**
An alternative solution could be to delegate sftp connections to the local ssh setup. This may also remove the need to specify keys since ssh-agent could take care of selecting the appropriate private key.

**Comment by dkocher** [comment]
Duplicate for #10451.
