### ISSUE TITLE
File Info Metadata Not Displaying / Amazon S3

### ISSUE THREAD

**Issue by dmripley** [iterate-ch/cyberduck#15767]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

When connecting to an Amazon S3 bucket, the File/Info options allow the Metadata to be set for files.  The window no longer displays the metadata for the files.  This used to work.

**To Reproduce**
Connect to an Amazon S3 bucket.
Select an existing file by clicking on it
Select [File][Info]
This will bring up the Info-Metadata window
The Metadata for the file should be displayed.  Instead, the window is blank.
Try adding Metadata to the file.
Use the Dropdown in the lower left corner of the scree.
Select Content Disposition / Attachment
The new attribute is not shown on the file.

**Expected behavior**
The metadata for each file should be shown.
Previous versions of Cyberduck have shown the metadata.  As of Version 8.8.1 (41263) it does not.

**Screenshots**

![image](https://github.com/iterate-ch/cyberduck/assets/164699840/2e0a194c-46da-4721-b076-c68f8475e081)

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.7
 - Version 8.8.1 (41263)

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #15742.
