### ISSUE TITLE
Crash with ArgumentNullException in System.Windows.Forms.CurrencyManager when loading Preferences

### ISSUE THREAD

**Issue by Fydon** [iterate-ch/cyberduck#15795]
**Describe the bug**
When attempting to adjust preferences by going to the Preferences menu item, the app crashes. Therefore I can't access the latest snapshot builds. I've tried reverting to 8.8.0 and 8.7.3 and repairing the install of 8.8.1.41263, but it still crashes.

**To Reproduce**
1. Go to Preferences

**Expected behavior**
Preferences load

**Screenshots**
![Cyberduck](https://github.com/iterate-ch/cyberduck/assets/3404761/54346c5f-d84e-408d-a444-da5fe1843bd9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 build 22631.3296

**Log Files**
The following is the crash report [638477617558948223.txt](https://github.com/iterate-ch/cyberduck/files/14855373/638477617558948223.txt)

**Comment by Fydon** [comment]
I've tried opening Preferences with 8.8.2 and it also crashes. I'll try repairing the install with 8.8.2 once the download link on the website are working.

**Comment by AliveDevil** [comment]
Thanks for both crash reports, not quite sure why it's crashing on your end.

If it continuous to crash even when downgrading to a version that previously worked, can you check whether resetting Cyberduck makes a difference (Bookmarks, Profiles, History will be kept).
For this rename the file "Cyberduck.user.config" in `%AppData%\Cyberduck` to Cyberduck.user.config.bak, if you want to be on the safe side you can move all folders in `%AppData%\iterate_GmbH\` that start with Cyberduck.

Your configured locale is en-GB, and you don't have other culture/region changes applies?

**Comment by AliveDevil** [comment]
Tested this, and found this behavior:
- In Profiles-tab enable a profile
- Restart Cyberduck
- In Connection-tab set profile to downloaded profile
- Disable/Remove profile from Profiles-tab (or delete file)
- Restart Cyberduck
- Open Preferences
- Observe crash

If you don't want to reset all settings, you can delete the line starting with `<setting name="connection.protocol.default"`.

**Comment by AliveDevil** [comment]
@dkocher 
Whats the plan here?
On null return of ProfilesFactory try again with `Preferences.getDefault("connection.protocol.default")` or add a "Unknown"-entry for fallback (unselectable)?

**Comment by Fydon** [comment]
Thank you so much. Commenting out `<setting name="connection.protocol.default"` solved the issue.

**Comment by dkocher** [comment]
> @dkocher Whats the plan here? On null return of ProfilesFactory try again with `Preferences.getDefault("connection.protocol.default")` or add a "Unknown"-entry for fallback (unselectable)?

Yes, we should have a generic fallback to `getDefault("connection.protocol.default")`.

**Comment by Fydon** [comment]
Was this related to the profile `S3 (Credentials from AWS Security Token Service)` being removed?

I see it is no longer available in the profile list and [the link on the website](https://cyberduck.io/s3/) doesn't work. The secition should probably be replaced with https://profiles.cyberduck.io/S3%20(Credentials%20from%20AWS%20Command%20Line%20Interface).cyberduckprofile, which can be used to obtain temporary credentials from the AWS Security Token Service (STS).

When selecting one of the profiles to download, I instead see the contents of the file rather than it downloading. [Mozilla have some suggestions](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#download), although most people probably using the interface inside Cyberduck to add profiles.
