### ISSUE TITLE
When I try to open the transfers it freezes and the app closes

### ISSUE THREAD

**Issue by CrazyPear7** [iterate-ch/cyberduck#15794]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by AliveDevil** [comment]
Please navigate to `%AppData%\Cyberduck` and rename the folder "Transfers" to "Transfers.bak". Then start Cyberduck and the Transfers-window should start to work again.
If you are certain that you don't need any file in Transfers.bak (this is the history of all transfers), i.e. you don't regularly rerun a transfer, you can delete the Transfers or Transfers.bak folder safely.

**Comment by tatze96** [comment]
duplicates #15885
