### ISSUE TITLE
dragging a bookmark to first or last entry often deletes it

### ISSUE THREAD

**Issue by joernhees** [iterate-ch/cyberduck#15801]
**To Reproduce**
1. duplicate a bookmark, it should appear as last
2. go edit the dup's name so you can distinguish it
3. close the edit window
4. drag the edited bookmark to first entry (i have many bookmarks, maybe scrolling is involved)
5. poof, it's gone

same happened, when i dragged another bookmark to the last entry 🤷‍♂️ 

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 8.8.1 (41263)

**Comment by tatze96** [comment]
duplicates #12897
