### ISSUE TITLE
Windows High DPI support

### ISSUE THREAD

**Issue by lemonicy** [iterate-ch/cyberduck#15803]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The software looks blurry in high DPI devices. Please add the High DPI support.

**Describe alternatives you've considered**
You can refer to ![https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows](Microsoft Official Website)

**Additional context**
No.

**Comment by dkocher** [comment]
Duplicate for #8961.
