### ISSUE TITLE
bump jna to 5.14.0

### ISSUE THREAD

**Issue by chenrui333** [iterate-ch/cyberduck#15813]
While upgrading duck to the latest release, there was some issue of building/running with jna 5.14.0. I noticed that the one used in the project is 5.12.1. Maybe bump to [5.14.0](https://github.com/java-native-access/jna/releases/tag/5.14.0)?

https://github.com/iterate-ch/cyberduck/blob/0a161fe6f1881764ead00a97472cb669a97fc941/pom.xml#L82

- https://github.com/Homebrew/homebrew-core/pull/166120
- https://github.com/Homebrew/homebrew-core/pull/168360

This was the test failure I ran into

```
    BuildError: Failed executing: /opt/homebrew/Cellar/duck/8.8.1.41263/bin/duck --download https://ftp.gnu.org/gnu/wget/wget-1.19.4.tar.gz /private/tmp/duck-test-20240314-10268-dihqso/test
```

**Comment by dkocher** [comment]
Blocked by #14090.
