### ISSUE TITLE
Download links (Win and Mac) are broken on the web site for 8 April 2024 release

### ISSUE THREAD

**Issue by minimondo** [iterate-ch/cyberduck#15814]
Download links (Win and Mac) are broken on the web site for 8 April 2024 release v8.8.2

[UPDATE]: Thanks to the MacUpdater app I found the issue with the macOS download - the download link refers to an apparently non-existent version:

web link:      https://update.cyberduck.io/Cyberduck-8.8.2.41263.zip
working link:      https://update.cyberduck.io//Cyberduck-8.8.2.41344.zip

I cannot find a Windows download using the same version/release though.

**Comment by dropmann** [comment]
+1

**Comment by dkocher** [comment]
Thanks for letting us know, the links have been fixed.

**Comment by dropmann** [comment]
I still can't get the links to work from the downloads page

**Comment by dkocher** [comment]
> I still can't get the links to work from the downloads page

Please reload the page. The correct links are 

- https://update.cyberduck.io/windows/Cyberduck-Installer-8.8.2.41344.exe
- https://update.cyberduck.io/Cyberduck-8.8.2.41344.zip

**Comment by dropmann** [comment]
I have multiple times. It must be a propagation delay. Thanks for the links
