### ISSUE TITLE
Does not display shortcuts created in Google Drive

### ISSUE THREAD

**Issue by ARTveli** [iterate-ch/cyberduck#15821]
**Describe the bug**
When I add a shortcut to my Google Drive it doesn't show up in my Cyberduck, even though it was visible before. 

For example, someone shared a link to a folder in Google Drive. 

I make a shortcut and put this shortcut in my Google Drive, and if before it was displayed in my Cyberduck and I could download all the files at once, now it is not displayed.

I checked and in third party programs like Transmit everything works as it did before in Cyberduck.

**To Reproduce**
1. Click on a link created by someone in Google Drive and shared and shared with you.
2. Create a shortcut and tag it to your Google Drive
3. Go to Cyberduck and see that this shortcut did not appear in our program (Cyberduck).

**Expected behavior**
I need to see the shortcut I created and transferred to my Google Drive in Cyberduck so I can download the files.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  macOS
 - Sonoma 14.4.1 (23E224)

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/14943097/cyberduck.log)

**Additional context**

**Comment by dkocher** [comment]
Shortcuts in Google Drive are documented [here](https://developers.google.com/drive/api/guides/shortcuts).

> Shortcuts are files that link to other files or folders on Google Drive

**Comment by dkocher** [comment]
I am unable to reproduce with both files and folder shortcuts created from _Shared with me_.
