### ISSUE TITLE
Name of File not updating when selecting Info of another file

### ISSUE THREAD

**Issue by hamadimoustapha** [iterate-ch/cyberduck#15820]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
When requesting Info for a file for the first time with Cyberduck, the file name on the top of the window is OK. When selecting another file and getting infos, data is correct but the file name is still the first one you ask infos for.

**To Reproduce**
1. Select a file and click on "Get Info", or Right Click on the file and Select "Info"
2. On the first time the file name on the top of the window is OK
3. Close the window
4. Select another file and do the same thing.
5. File Info is OK but file name on the top of the window is still the first one you requested Info for.
6. Same behaviour for any future files you will ask Info for
7. Need to close and reopen Cyberduck for each Info request to get the name updated.

**Expected behavior**
File name in the Info window to reflect the good one.

**Screenshots**
![image](https://github.com/iterate-ch/cyberduck/assets/72764429/440b17b6-c78d-49b7-94bf-6b38906b1fad)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Version : Latest version of Cyberduck

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by AliveDevil** [comment]
Thanks for reporting, we'll take a look and update the window title on selection change.
