### ISSUE TITLE
Unsupported header x-amz-checksum-sha256 error for uploads

### ISSUE THREAD

**Issue by jeffstreann** [iterate-ch/cyberduck#15841]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
On Cyberduck version 8.8.2 Not able to create folders, or upload files. When trying to create a folder or upload a file this message pop up 
![image](https://github.com/iterate-ch/cyberduck/assets/167233794/13b20c31-92e5-4be5-8258-bf0ad73db9af)

**To Reproduce**

**Expected behavior**
Should be able to create a folder, upload a file and a done.txt file to upload files to our platform.

**Screenshots**
![image](https://github.com/iterate-ch/cyberduck/assets/167233794/0b69ae17-66a7-4025-848f-242df91def76)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home Single Language
 - Version 22H2
 - OS Build 22621.3447

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by technotherion** [comment]
I  hope that it is OK to piggyback off of this issue, this issue is the only other place I've seen this error.

My bookmark settings are as follows. 
![image](https://github.com/iterate-ch/cyberduck/assets/13829537/91cf320e-937d-4130-b56e-ae5b0b0e0479)


Experiencing the same issue on Windows 10 + Cyberduck 8.8.2.
Attempting to upload files to Backblaze B2 via Amazon S3. 
I am able to delete files but not upload them.
I am also able to create new b2 buckets and do not experience any errors doing so. Said buckets show up correclty on the Backblaze website. 

[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/15053302/cyberduck.log)

**Comment by dkocher** [comment]
This seems to be caused by the changes implemented for #15557. Please open a bug with Backblaze about this issue with their S3 implementation not being interoperable.

**Comment by dkocher** [comment]
@jeffstreann Do you also see this issue when uploading to B2 using S3?

**Comment by dkocher** [comment]
The incompatibility is documented [^1].

[^1]: https://www.backblaze.com/docs/cloud-storage-s3-compatible-api

> Requests that include the following checksum HTTP headers are rejected with a 400 Bad Requestresponse:
> x-amz-checksum-crc32
> x-amz-checksum-crc32c
> x-amz-checksum-sha1
> x-amz-checksum-sha256
> x-amz-checksum-algorithm
>  x-amz-checksum-mode

**Comment by jeffstreann** [comment]
> @jeffstreann Do you also see this issue when uploading to B2 using S3?

correct. I am using version 8.7.3 (40979) temporarily, as any newer version gives me an error when trying to create folders or upload files.

**Comment by blented** [comment]
middleware to remove the bad headers. insert this right after your s3client creation
```js
const badHeaders = [
  'x-amz-sdk-checksum-algorithm',
  'x-amz-checksum-crc32',
]
s3Client.middlewareStack.addRelativeTo(
  (next, _context) => async (args) => {
    if (args.request.headers) {
      for (const header of badHeaders) {
        delete args.request.headers[header]
      }
    }
    console.log('headers removed:', args.request.headers)
    return next(args)
  },
  {
    relation: 'before',
    toMiddleware: 'awsAuthMiddleware' // Ensure it runs before auth signing
  }
)
```
you should remove the logging for production but it's good to know it's running first :)
