### ISSUE TITLE
Folders/Groups and filtering

### ISSUE THREAD

**Issue by RobertHana** [iterate-ch/cyberduck#15853]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to group or to filter my bookmarks.

**Describe the solution you'd like**
I want to have actions somewhere in the bookmarks list to group and a filterbar to filter.

**Describe alternatives you've considered**
Scroll to find?  Manual sort to just order near each other.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #12233.
