### ISSUE TITLE
Support custom URI scheme for opening Cyberduck and defaulting the connection and remote folder automatically

### ISSUE THREAD

**Issue by bdw429s** [iterate-ch/cyberduck#15901]
**Describe the solution you'd like**
My wife's company is looking to move to S3 as a storage location for large amounts of photos.  This would require photographers and editors to use some app like Cyberduck to handle uploading and downloading the images into a folder structure on S3 that follows a special format for each session.  As their employees work with dozens of different sessions a day and deal with many thousands of folders, it would make the workflow much simpler and less error-prone to support a custom URI scheme that could be presented as a hyperlink on their internal website so a user can simply click the link in the browser, and Cyberduck would be associated with that scheme and would handle the link, opening the connection and remote folders to the appropriate location in the app.  This would allow a user to jump directly to the folder needed without the manual steps of navigating there. 

This would require the installer for Cyberduck's installer to register the schema with the operating system opon installation.

**Describe alternatives you've considered**
I requested the same features from the developers of S3 Browser, and they actually added it right away and it worked amazing.  Their URI schema looked like this:

s3b://some-bucket/folder/location

Unfortunately, S3 Browser is a Windows only application, and with many Mac users, it just wasn't a feasible option.

**Comment by bdw429s** [comment]
Wow, awesome!  Thanks for working on this.  Where/how would I go to test this?

**Comment by dkocher** [comment]
The [URI syntax](https://docs.duck.sh/cli/#uri) documented for Cyberduck CLI applies. The `s3` scheme is registered by default which should allow to open URLs in Cyberduck from your web browser like `s3:/bucketname` or `s3://mys3endpoint/bucketname`.

To register other schemes you will have to create a [custom connection profile](https://docs.cyberduck.io/protocols/profiles/#technical-file-format-specification) with additional `Schemes`.

Documentation [^1] is pending.

[^1]: https://github.com/iterate-ch/docs/issues/526

**Comment by bdw429s** [comment]
Thanks for that.  I was more asking what build/download I would need to use to test this out.  I'm new to Cyberduck and not sure you have nightly builds, or if I need to wait for a release candidate, etc.
