### ISSUE TITLE
"Your system has run out of application memory." During large sftp transfer.

### ISSUE THREAD

**Issue by ianianianianian** [iterate-ch/cyberduck#15900]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

**Describe the bug**
During a transfer of a large folder (300+ GB) from a NAS RAID backup I got a popup window to **Force Quit Applications** due to using all system memory.

Cyberduck was at the top of the list to force quit using 69.33GB of memory.

**To Reproduce**
1. Transfer large folder via SFTP
2. Wait

**Expected behavior**
MacOS will product a **Force Quit Applications** menu due to running out of system memory.

**Screenshots**
[https://imgur.com/a/G6vHdwY](https://imgur.com/a/G6vHdwY)

![J5hACBP](https://github.com/iterate-ch/cyberduck/assets/71733/c9c5aa9b-05e3-44ff-b5d0-0eb47f743cdf)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.4.1 (23E224)

**Log Files**

There was nothing in the log related to this.

**Comment by dkocher** [comment]
Duplicate for #15510.
