### ISSUE TITLE
Memory leak when downloading from S3

### ISSUE THREAD

**Issue by alaz** [iterate-ch/cyberduck#15927]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

Hi, I was downloading a 30GB sparsebundle from S3 and Cyberduck consumed 75GB of memory, please see a screenshot below.

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="495" alt="Screenshot 2024-05-12 at 21 29 10" src="https://github.com/iterate-ch/cyberduck/assets/12065/5134172a-dc57-45d5-87a8-58caac6f7ce2">

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1
 - Version 8.8.2

**Log Files**

Sorry, no log file, I have disabled them.

**Additional context**

**Comment by alaz** [comment]
Possibly duplicate of #15510 and #15900

**Comment by kdambiec** [comment]
I've had the same issue multiple times over the last year with Cyberduck on Mac. It also occurs with SFTP.
