### ISSUE TITLE
No large file download via FTP

### ISSUE THREAD

**Issue by master-kw** [iterate-ch/cyberduck#15965]
Hi,

the following recent problem:

This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

**Describe the bug**
I am currently no longer able to download larger files (10MB or more) via FTP. The upload, on the other hand, works perfectly, regardless of size. This applies to existing data as well as directly uploaded files. PS: Access and upload/download via the provider's (netcup.de) web terminal works to the desired extent, as does FileZilla.

I have tested this with various files (regardless of format) and, for example, a PDF test file with 11.5MB (and larger) causes an error message when downloading with Cyberduck (see attachment). 

**To Reproduce**
1. e.g. successful upload of a 3MB and an 11MB file
2. Immediately afterwards download of exactly these files. 
3. 3MB successful
4. 11MB see error message.
5. got an *.cyberducksegment file on my Mac

**Screenshots**
![connection-error](https://github.com/iterate-ch/cyberduck/assets/104136223/8438c74d-6ec6-459f-8866-9cfcd904c128)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Cyberduck: 8.9.0 (41543)

Regards,
Oliver

**Comment by tatze96** [comment]
Based on your description, I would assume that your server doesn't allow the use of multiple connections for the download. Please deactivate the segmented downloads within the Cyberduck preferences *Transfers* tab and try again to download the affected file.
