### ISSUE TITLE
macOS Memory leak when transferring large amount of data from WebDAV server

### ISSUE THREAD

**Issue by andtechgroup** [iterate-ch/cyberduck#15977]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
When transferring over 100GB of data from the cloud service Sharefile via WebDAV, Cyberduck uses a significant amount of RAM and swap disk. This issue has been observed on multiple Macs, including the Mac mini M2 Pro with 16GB of RAM and the Mac Studio M1 Max with 32GB of RAM. 

**To Reproduce**
1. Connect to Webdav server
2. Select files to transfer more than 100 GB. Monitor transfer processes as RAM usage increases exponentially during transfer until the system has no available memory, causing Cyberduck to become unresponsive and require a force quit.

**Expected behavior**
I don't expect the cache data to be stored in RAM before being downloaded to the destination folder on the disk. (I assume that is what is occurring (?))

**Screenshots**
I've been limiting my transfers to less than 100GB in order to complete the task of transferring. I've attached a screenshot of a current transfer of 65.7GB of data. The transfer is only 22% complete (14.9GB), but Cyberduck is already using 8.85GB of RAM and over 15GB of swap.

<img width="1192" alt="Screenshot 2024-05-30 at 4 39 21 PM" src="https://github.com/iterate-ch/cyberduck/assets/6607885/8c76e701-6403-4ea2-bbf8-e439b0c2ce84">

**Desktop (please complete the following information):**
macOS Sonoma 14.5

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

[cyberduck.log.zip](https://github.com/iterate-ch/cyberduck/files/15505575/cyberduck.log.zip)

**Additional context**
Using Cyberduck also triggers perpetual indexing for Spotlight on my hard drive, which may be unrelated.

**Comment by dkocher** [comment]
Possible duplicate for #15510.
