### ISSUE TITLE
selection is 'sticky' in macos

### ISSUE THREAD

**Issue by COMInterop** [iterate-ch/cyberduck#15980]
Hello,

I have a persistent problem where Cyberduck retains memory of my previous selection even after selecting a new file. That is to say, if I select file 1 in the GUI, and then select file 2 (and only file 2), and then drag file 2 to a new folder, it seeks to move both file 1 and file 2. 

Is this known and how may I avoid it. Thank you!

**Comment by dkocher** [comment]
I am not able to reproduce the problem. Please describe the exact steps required.
