### ISSUE TITLE
Connection failed (Amazon S3) when try to open S3 url with Cyberduck

### ISSUE THREAD

**Issue by DanSega1** [iterate-ch/cyberduck#16010]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

**Describe the bug**
When trying to open S3 URL with Cyberduck I get "connection failed (Amazon S3)" message

**To Reproduce**
1. connect to S3 bucket and copy s3 URL from file or folder
2. try to open it with Cyberduck

**Expected behavior**
The expectation is to open the directory of the folder or the file

**Screenshots**
![image](https://github.com/iterate-ch/cyberduck/assets/108394291/b92b1dfa-2158-4d1a-881d-eed7b906ae61)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.5 (23F79)
 - Cyberduck Version: Cyberduck 8.9.0

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/15751403/cyberduck.log)

**Additional context**
I can access programmatic and from AWS console to the bucket and the data, from Cyberduck I can access manually to the data but not with S3 URL.

**Comment by tatze96** [comment]
DNS lookup failures are issues within your local network that usually resolve themselves after some time. Please verify that your network connection and DNS server (if you have a custom one) work as they should.

**Comment by tatze96** [comment]
DNS lookup failures can also occur if a bad or non-existent hostname is used.

For further information regarding the configuration of S3 bookmarks, refer to our [wikipage](https://docs.cyberduck.io/protocols/s3/).

**Comment by DanSega1** [comment]
I can access the files and directory manually, but not through links.

**Comment by farhatkevin** [comment]
<img width="458" height="154" alt="Image" src="https://github.com/user-attachments/assets/ff77a3d0-b54b-4858-aaa2-5766a8046a74" />

Having the same issue here. if i click into the bookmark i can browse files fine, but when clicking on an S3 URI like "s3://path/to/folder" I get "Connection Failed (Amazon S3), DNS lookup for BUCKET_NAME failed"

Do things look right in the screenshot?

**Comment by dkocher** [comment]
The URL displayed is for informational purpose only. You should instead attempt to connect by double clicking the configured bookmark.

**Comment by farhatkevin** [comment]
Apologies for not being clear, double clicking the configured bookmark works properly. The issue is when clicking an s3 link (on Slack for example), then I get the DNS lookup issue, even though I can manually click into the path that is sent. I sent the screenshot above in case the URL or server name were incorrect. I think this is the same issue as @DanSega1.
