### ISSUE TITLE
Uploading Error "Cannot retry request with non-repeatable request entity."

### ISSUE THREAD

**Issue by unitop322** [iterate-ch/cyberduck#16037]
Hello.
Currently, I am trying to upload our website sitemap files on CyberDuck(/dav/content/sitemap).
Tried again today and it pops up with same error message, but also says my file uploaded and then failed to upload. (Files haven't uploaded).
![image](https://github.com/iterate-ch/cyberduck/assets/151155288/081a7f02-eda6-4bde-897b-626c5a1cf5f6)
[cyberduck.log](https://github.com/user-attachments/files/15872764/cyberduck.log)
Could you please let me know the reason of this error?
Thank you.

**Comment by tatze96** [comment]
The logging output doesn't include the error. However, we already had multiple tickets this week with the same error message for BigCommerce servers. In those tickets, the server answered with "401 Unauthorized", which may also be the case on your side. You can verify if this is also the case on your side by clicking on the "See details" button within the error message and looking for a line that includes the mentioned server answer.

401 Unauthorized typically either indicates missing permissions or a credential issue. So, if the server answer is also the case on your side, verify that you have the needed writing permissions for the folder and reach out to the BigCommerce support to check why the server answers with "401 Unauthorized" on the attempt to upload the file if necessary.

**Comment by unitop322** [comment]
Thank you.

**Comment by dkocher** [comment]
Duplicate for #16024.
