### ISSUE TITLE
uploading file causes cyberduck to crash

### ISSUE THREAD

**Issue by RIZZOAGUILAR03** [iterate-ch/cyberduck#16051]
[638544017860456838.txt](https://github.com/user-attachments/files/15905825/638544017860456838.txt)
[638544019322600398.txt](https://github.com/user-attachments/files/15905826/638544019322600398.txt)
[638544019323616875.txt](https://github.com/user-attachments/files/15905827/638544019323616875.txt)

**Describe the bug**
When trying to upload a document to a server folder I open file then upload and select the pdf file I choose to upload. I select upload then the cyberduck screen goes black says its not responding then crashes 

**To Reproduce**
1. Go to 'file' then "upload"
2. Click on 'desired file i want to upload'
3. select upload 
4. See error cyber duck crashes

**Expected behavior**
file is supposed to be uploaded in the folder then when i reopen cyber duck and connection the file should be accessible 

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Version 8.9.0 (41543)

**Comment by RIZZOAGUILAR03** [comment]
![cyber duck](https://github.com/iterate-ch/cyberduck/assets/173308887/f858131d-9bde-4c0c-9960-73e7a13baed2)
![cyber duck 2](https://github.com/iterate-ch/cyberduck/assets/173308887/42b5caeb-5101-4011-b8e9-fd0d6051b671)
These are the images of what happens when trying to upload the file 
Below is the changes I've made to increase the UserProcessHandleQuota however still get the same crash
![cyber duck 3](https://github.com/iterate-ch/cyberduck/assets/173308887/41df23f7-8ac5-41e0-b772-1d663b7aa67f)

**Comment by AliveDevil** [comment]
Does this happen as well when you unset `Preferences/Transfers/"Bring window to front when transfer starts"`?
You may try to update to the latest snapshot, which has a rewritten Transfers-window to combat the increased control count of Cyberduck - which may help reduce the overall number of handles requested.

1.3 GiB of free memory out of 8 GiB shouldn't be an issue.
Windows 10 (18363, 2019)
