### ISSUE TITLE
Support for Implicit FTP over TLS

### ISSUE THREAD

**Issue by SoCuul** [iterate-ch/cyberduck#16066]
**Is your feature request related to a problem? Please describe.**
With the Bambu Lab line of 3d printers, ftp is implemented to be able to access the SD card over the network. However, the authentication requires use of implicit TLS to connect.

**Describe the solution you'd like**
It would be nice if we could have a toggle for implicit tls in cyberduck, like what is done in FileZilla.

**Describe alternatives you've considered**
The only solution at the moment is to use another ftp client, which is inconvenient and not as nice to work with as Cyberduck.

**Additional context**
Some more information on the connection information is provided on the Bambu Lab forums: https://forum.bambulab.com/t/we-can-now-connect-to-ftp-on-the-p1-and-a1-series/6464/108

**Comment by dkocher** [comment]
Duplicate for #12158.

**Comment by SoCuul** [comment]
Could it potentially be reconsidered, as the last time it was happened over 19 years ago?
