### ISSUE TITLE
File selected to edit does not open in Visual Studio

### ISSUE THREAD

**Issue by Jo-gonzalezu** [iterate-ch/cyberduck#16086]
Hi, I recently updated the application, later, after it was installed I connected to my server and when I wanted to edit a file, Cyberduck shows the "Download Complete" message, however, it does not open the file with the editor selected in preferences.

Steps:
- I connected to my server
- I tryied to edit an php file
- Right click in the file
- Edit with "Visual Studio"

And the system shows the message "Download Complete".
Finally, if i click the button "Edit" that contains the Visual Studio's Logo, the Download Complete message appears again, but the file does not open.

![image](https://github.com/iterate-ch/cyberduck/assets/90359419/d35cb8fc-4d29-4bc0-a829-d454fd230598)

**Comment by AliveDevil** [comment]
Just tried this here, with both Visual Studio and Visual Studio Code.
In both cases the target application launched without issue and showed the file content.
Please
- [Enable debugging logging](https://docs.cyberduck.io/cyberduck/support/#logging-output), 
- Click on Show, close Cyberduck, delete the highlighted file
- Restart Cyberduck,
- Connect
- Start editing a file,
- Close Cyberduck after you've determined that the edit-application isn't launching

You can attach the log file either here on GitHub using the web interface (don't reply by e-mail), or send it to support@cyberduck.io.
