### ISSUE TITLE
Cyberduck can not be opened on the Mac OS.

### ISSUE THREAD

**Issue by ainmor** [iterate-ch/cyberduck#16090]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
The app is not launching and is damaged.

**To Reproduce**
1. Go to 'App Store'
2. Click on 'Cyberduck'
3. Purchase the app
4. Then download the app on the Mac Book Pro M1 chip
5. Try to click on the app that has been downloaded
6. The app does not launch. It says the app is damaged and can not be opened.

**Expected behavior**
The App should have launched without any error. 

**Screenshots**
<img width="1920" alt="Screenshot 2024-06-30 at 09 02 49" src="https://github.com/iterate-ch/cyberduck/assets/31561907/c85cbc4c-5da2-4f82-b6d6-534f4f5b548b">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 15 Beta version]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**
I uninstall and installed it couple of times but its the same problem. Need to support ASAP to fix the problem.

**Comment by dkocher** [comment]
Duplicate for #16031.
