### ISSUE TITLE
the imported file doesn't appear on server

### ISSUE THREAD

**Issue by Autotal-mx** [iterate-ch/cyberduck#16091]
![Screenshot 2024-06-30 033626](https://github.com/iterate-ch/cyberduck/assets/170778819/d3dda355-b441-42fd-85d9-99781d82692f)
![Screenshot 2024-06-30 033647](https://github.com/iterate-ch/cyberduck/assets/170778819/8652016d-2828-42ba-a2ce-09e1a7a8ec49)
The "transfers" shows that import of file is complete, but it doesn't appear on server.

**Comment by Autotal-mx** [comment]
The "transfers" shows that import of file is complete, but it doesn't appear on server.

**Comment by dkocher** [comment]
Duplicate for #16088.
