### ISSUE TITLE
Erro on S3 buckets with dot in the name

### ISSUE THREAD

**Issue by FrancoTampieri** [iterate-ch/cyberduck#16102]
**Describe the bug**
When I create a bucket on a S3 compatible platform I got many errors and is impossible to browse the data. If I remove the dot in the name of the bucket the problem is fixed. I tried with S3Browser or AWS-cli and didn't get the problem.

**To Reproduce**
1. Create a bucket with a dot inside, like i4.0-backups
2. Put alla the configuration in Cyberduck, like the right endpoint the keys for access the storage object
3. Click to connect and get this message:
![Screenshot 2024-07-01 alle 12 07 54](https://github.com/iterate-ch/cyberduck/assets/4396444/a3462c03-7789-4e54-9f91-57e78a3a4e49)

and if I press continue I got this:
![Screenshot 2024-07-01 alle 12 12 32](https://github.com/iterate-ch/cyberduck/assets/4396444/e931b454-cca6-4833-a87e-2e0cd76868b5)

**Expected behavior**
Well if I remove the dot in the name of bucket, All going good, no certificate request paper and no message error and all the system working as aspected

**Desktop (please complete the following information):**
 - OS: Sonoma 14.4 arch M1
 - Version: Cyberduck 9.0.0 (41777)

**Comment by tatze96** [comment]
I can't reproduce the described behavior with a local S3-compatible server.

I noticed within the screenshot of the error message that you are using Cubbit.
There are currently compatibility issues between the S3 implementation on the Cubbit server and the Amazon S3 API, which likely also caused the described errors.

We have already notified Cubbit about the ongoing issues, including technical details about their interoperability failure with S3 protocol support.

Please reach out to the Cubbit support for further troubleshooting.

**Comment by FrancoTampieri** [comment]
Hi!

I warned the support about that problem too.
Hope they will fixit

Kind Regards

Franco
