### ISSUE TITLE
Doesn't auto detect Cryptomator Vaults

### ISSUE THREAD

**Issue by roeIant** [iterate-ch/cyberduck#16105]
**Describe the bug**
If I approach a cryptomator vault that's either on a Google Drive or a Microsoft Onedrive, it doesn't recognise the vault. It doesn't auto unlock as per the setting, and the right click context menu to unlock vault is greyed out. On Dropbox it does still work properly as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to a vault hosted on Google Drive
2. Navigate to the vault folder
3. Face the encrypted files, even if autodetect/-unlock vault is enabled
4. See that you also cannot unlock it with right click menu or Cmd-L.

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.5 (23F79)
 - CyberDuck 9.0.0 (41777)

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/16116906/cyberduck.log)

**Comment by dkocher** [comment]
In #16098.
