### ISSUE TITLE
Application blocked by Google for OAuth Flow

### ISSUE THREAD

**Issue by giannhsg** [iterate-ch/cyberduck#16178]
Windows 10 

Good morning, I downloaded the program and tried to connect via google driver, unfortunately it shows me this message

> this application has been blocked Google

**Comment by kaizenjinco** [comment]
I faced to the same issue. It could be came from the policy of Google to protect this app from collecting sensititive data of users.

**Comment by dkocher** [comment]
I cannot reproduce the problem opening a connection to _Google Drive_ and granting permissions for Cyberduck to access.

**Comment by n1ghthouse** [comment]
Facing the same issue right now as well.

> This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.

**Comment by jerapiblaze** [comment]
This issue happened when I clean reinstall my OS and have a new installation of Mountain Duck.

I tried with all of my G-accounts, and all have same issue.
 
![image](https://github.com/user-attachments/assets/06040577-0fdd-4c90-9c6f-d1bd32ebbf3c)

**Comment by Spaex** [comment]
Same Issue here.

**Comment by dkocher** [comment]
This may be caused by missing CASA assessment [^1] for `api-project-996125414232`. 

[^1]: #16192

**Comment by dkocher** [comment]
As a workaround you will need to create a [Custom OAuth 2.0 Client ID for Google Cloud Storage and Google Drive](https://docs.cyberduck.io/protocols/profiles/google_client_id/) and create a custom connection profile.

**Comment by sojohnnysaid** [comment]
having the same issue I can't access any of my google drives anymore 😭

**Comment by sojohnnysaid** [comment]
Please let us know when you are compliant again.

**Comment by TechnicolorGUO** [comment]
same issue here

**Comment by lweismantel** [comment]
> As a workaround you will need to create a [Custom OAuth 2.0 Client ID for Google Cloud Storage and Google Drive](https://docs.cyberduck.io/protocols/profiles/google_client_id/) and create a custom connection profile.

Thanks for the links. I was able to use these with a bit of extra research to get access to my google drive again.

**Comment by ladysun1969** [comment]
Hi, does anybody know the status of this issue? Are they working on it? Will it be fixed soon? Thanks.

**Comment by PublicBenemy** [comment]
Ran into this issue now, too

**Comment by lweismantel** [comment]
What dkocher linked above does work. I'm a new Cyberduck user and was able to follow that to get things working. It did take a few hours though, so it's not ideal for most.

**Comment by ladysun1969** [comment]
@lweismantel -- I've used cyberduck for years, but I'm not a dev* & while I have read through @dkocher's instructions, I have no idea how to do them. I also haven't had the time to sit with them and sort it out. Maybe I'll have some time next week. 

*I was trained as a COBOL/CICS/JCL programmer

**Comment by n1ghthouse** [comment]
Turns out cryptomator's android app's drive oauth has also gotten blocked just as Mountain Duck oauth did.

**Comment by lweismantel** [comment]
@ladysun1969 I'm stubborn and great at following directions, and I still almost gave up a few times due to some missing information between all the resources.

**Comment by dchakro** [comment]
Ran into the same issue right now with Mountain duck

**Comment by GittyU** [comment]
Same issue, app is blocked for "tried to access sensitive data".

**Comment by lxne** [comment]
Same here. MacOS.

**Comment by tysnaden** [comment]
Any updates as to when we can expect a bug fix to roll out for this? It's been over a week now of not being able to access G drive through mountain duck, and I'm not about to go through the faff of creating a custom OAuth token for this...

**Comment by jerapiblaze** [comment]
This is the step-by-step [workaround](https://jerapiblaze.github.io/posts/workaround-for-mountain-duck-google-drive/#create-google-drive-oauth-client).

Fow now, all we can do is wait, as the CASA assessment takes a long time to be done.

**Comment by ladysun1969** [comment]
@jerapiblaze Thank you! I will try that this weekend.

**Comment by ericgs92** [comment]
I have tried the workaround but I'm facing the same issue: Access bloqued Error 400: redirect_uri_mismatch

**Comment by jerapiblaze** [comment]
> I have tried the workaround but I'm facing the same issue: Access bloqued Error 400: redirect_uri_mismatch

Perhaps you mis-edit somewhere. The final `.cyberduckprofile` should look like this (values that need to edit are colored):

![image](https://github.com/user-attachments/assets/40043950-740b-4bd1-ba20-54f7a5c9eca7)

Also, remember to delete the old bookmarks and remove the old profile in `%appdata%/cyberduck/profiles` before opening the new file.

**Comment by ericgs92** [comment]
thanks! there was a typo on the file. 
anyway, i can't log in, I don't know if it's the URL, i can't change mine and it is slightly different

<img width="594" alt="image" src="https://github.com/user-attachments/assets/d1cbeb4f-52f2-4e59-956b-38dd52f17e53">

**Comment by ericgs92** [comment]
forget it, I've already solve it! 
I had to add to the Test Users my own gmail account.
Many thanks :)

**Comment by ladysun1969** [comment]
Quick question to all: do I need to make a separate profile for each gmail ID? (I have 6 gmail IDs that I use to access drives via Cyberduck.) Thanks!

**Comment by dkocher** [comment]
> Quick question to all: do I need to make a separate profile for each gmail ID? (I have 6 gmail IDs that I use to access drives via Cyberduck.) Thanks!

You should be able to use a single client id registration for all acsounts.

**Comment by appletree12345** [comment]
I exactly followed the workaround, but when I double-click the newly created .cyberduckprofile file, nothing appears. Still cannot get connected to Google. How do you delete the old bookmarks on Mac? I cannot find %appdata%/cyberduck/profiles

**Comment by dkocher** [comment]
After revalidation of our consent screen we are again requested to complete a paid CASA assessment [^1].

[^1]: #16192

**Comment by dkocher** [comment]
Referencing other open source projects affected by the requirement for a CASA assessment:
- Cryptomator cryptomator/android#546
- Rclone https://forum.rclone.org/t/google-drive-rclone-authentication-error-400/46747

**Comment by dkocher** [comment]
We have made available a tutorial [^1] with step-by-step instructions inspired by @jerapiblaze to workaround using a custom registration with Google.

[^1]: [Setup a Custom OAuth Client ID for Google Drive & Google Cloud Storage](https://docs.cyberduck.io/tutorials/custom_oauth_client_id/)

**Comment by MaximillianFoe** [comment]
Let's hope for a swift resolution!

**Comment by dkocher** [comment]
The OAuth Client ID that is used in the default connection profiles for Google Drive and Google Cloud Storage do now have again _Verified_ status.

> Thank you for your patience while we reviewed your submission. We've approved your OAuth App Verification request.
