### ISSUE TITLE
Allow AWS Session Token to be passed along with Access Key ID and Secret Access Key.

### ISSUE THREAD

**Issue by phillipsj** [iterate-ch/cyberduck#16202]
**Is your feature request related to a problem? Please describe.**
I have tried to do this with a custom profile, but it doesn't seem to work. I would like to take the temporary credentials provided by IAM Identity center to connect to an S3 bucket using CyberDuck.

**Describe the solution you'd like**
 If I copy and paste the credentials which are Access Key ID, Secret Access Key, and Session token into the AWS credentials file, I can use the profile to access it. This is fine for a technical person, but for end users I would like to have it just something they can enter in the UI just like they do for a IAM user credential.

**Comment by dkocher** [comment]
Duplicate for #13377.
