### ISSUE TITLE
`--assumeyes` not working to skip certificate verification

### ISSUE THREAD

**Issue by Secarius** [iterate-ch/cyberduck#16200]
I am using the cyberduck duck cli with option --assumeyes but i still have to answer the question with yes:
`The certificate for this server is invalid. You might be connecting to a server that is pretending to be xxx.xxx.xxx.xxx which could put your confidential information at risk. Would you like to connect to the server anyway? (y/n): y`
I am aware of that self signed certificate and want to skip all the questions about it.

**Expected behavior**
shoud automaticaly answer with yes

**Desktop (please complete the following information):**
 - OS: ubuntu server
 - Version 22.04

**Comment by dkocher** [comment]
I am unable to reproduce running Cyberduck CLI _9.0.2 (42108)_ on Linux.
