### ISSUE TITLE
Google refuse a new connection

### ISSUE THREAD

**Issue by Marcounet** [iterate-ch/cyberduck#16211]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Google refuse all CyberDuck connection.

**To Reproduce**
1. Go to 'Open a connection'
2. Choose 'Google drive'
3. On the Internet browser choose your google account
4. Then enter your password
5. Enter your Second-Step Password (optional)
6. See error

**Expected behavior**
Google seems refusing all third party connection.

**Screenshots**
<img width="659" alt="Capture d’écran 2024-08-06 à 17 55 15" src="https://github.com/user-attachments/assets/b2eacd08-da84-4397-9691-436c183fe0a1">

**Desktop (please complete the following information):**
 - OS: macOS Ventura (13.6.8)
 - CyberDuck: 9.0.1 (41941)

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/16512828/cyberduck.log)

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #16178.
