### ISSUE TITLE
When I start Cyberduck I am prompted to Modify Setup

### ISSUE THREAD

**Issue by VenetaMatova** [iterate-ch/cyberduck#16212]
**Describe the bug**
When I start Cyberduck I am prompted to Modify Setup. The options I am provided with are: Repair & Uninstall. 
![image](https://github.com/user-attachments/assets/93fe2c27-1d17-44d1-a84e-79ecfe678cb3)
When I click repair and restart after the action is performed, I receive the same message when I open Cybeduck.
When I click Unisntall, delete Cyberdcuk and then download it again,  I receive the same message when I open Cybeduck.             How can I fix it? Thanks in advance!

**Comment by tatze96** [comment]
The "Modify Setup" window only appears if you run the Cyberduck installer again instead of opening the installed application, for example, through the Windows _Start_ menu.

Please open Cyberduck from the _Start_ menu of your Windows system.
