### ISSUE TITLE
Add support for ca-west-1 (Calgary) to the S3 defaults

### ISSUE THREAD

**Issue by Joshuah143** [iterate-ch/cyberduck#16215]
**Describe the bug**
Add support for ca-west-1 (Calgary) to the default bucket location.

**To Reproduce**
1. Go to settings
2. Click S3
3. See the options in the default bucket location

**Screenshots**

Current default S3 locations:
<img width="249" alt="Screenshot 2024-08-07 at 10 01 35 PM" src="https://github.com/user-attachments/assets/de694079-0fd8-4a54-8ab0-febd43b1c8bd">

**Desktop (please complete the following information):**
 - OS: MacOS 14.6
 - Version 4.16.2 (Mountain Duck)
 - Version 9.0.1 (Cyber Duck)

**Additional context**
[Amazon recently introduced a new region.](https://aws.amazon.com/blogs/aws/the-aws-canada-west-calgary-region-is-now-available/)

Can I have a go at fixing? Should be super simple.

**Comment by Joshuah143** [comment]
Should be simple addition above this line:

https://github.com/iterate-ch/cyberduck/blob/4fff0bbd1d02b1f9b3ff8459a78dd5c94f232f17/profiles/default/S3%20(HTTPS).cyberduckprofile#L46

**Comment by tatze96** [comment]
Thanks for letting us know about the new S3 region.
> Can I have a go at fixing? Should be super simple.

Contributions are always welcome. You can open a pull request with your changes.

> Should be simple addition above this line:
> 
> https://github.com/iterate-ch/cyberduck/blob/4fff0bbd1d02b1f9b3ff8459a78dd5c94f232f17/profiles/default/S3%20(HTTPS).cyberduckprofile#L46

Correct, but the addition should be below the line because of the alphabetical ordering.
