### ISSUE TITLE
Changing install directory in Cyberduck CLI (Windows) is ignored

### ISSUE THREAD

**Issue by KKMEFM** [iterate-ch/cyberduck#16221]
Changing the install directory when running the Windows CLI exe installer is ignored and the program is installed in "C:\Program Files\Cyberduck CLI" anyway.

**To Reproduce**
Run the installer.
Click on Options.
Change the install location.  I used "C:\CyberduckCLI"
Click OK.
Click Install.
The files are installed to the default directory instead of the user supplied one.

**Expected behavior**
The files are installed to the user supplied one.

**Desktop (please complete the following information):**
 - OS: Win 10 22H2

**Comment by AliveDevil** [comment]
Thanks for noticing. Will be fixed in an upcoming release.
