### ISSUE TITLE
S3 default ACL setting not persisted on Windows and prevents some uploads

### ISSUE THREAD

**Issue by jahs** [iterate-ch/cyberduck#16237]
Steps to reproduce the behaviour:
1. Fresh install of Cyberduck 9.0.1 on Windows (also reproduced on 8.7.1).
2. Run; Edit -> Preferences -> S3, change Default ACL from "private" to "None"
4. Quit; Reopen; Edit -> Preferences -> S3 -> Default ACL shows "private", when "None" is expected.

This prevents uploads from windows to buckets without ACLs. The same S3 credentials and test bucket however do work from macos 14.3.

**Comment by AliveDevil** [comment]
Regression from #14571.
