### ISSUE TITLE
allow using Transfer Acceleration without changing the bucket properties

### ISSUE THREAD

**Issue by yellowtailfan** [iterate-ch/cyberduck#16232]
**Is your feature request related to a problem? Please describe.**
As I understand it, toggling Transfer Acceleration in Cyberduck currently toggles the bucket properties on S3 as well as changing the endpoints in Cyberduck. This means that if a user uses another tool to access the bucket, their speeds can be reduced if Cyberduck has been used with Transfer Acceleration off. It also means that the Cyberduck user needs both `s3:GetAccelerateConfiguration` and `s3:PutAccelerateConfiguration` permissions, when they should only need `s3:GetAccelerateConfiguration` permissions.

**Describe the solution you'd like**
Here's a suggestion for an overall approach that I think might be easier to use:
1. Add a "Transfer Acceleration" toggle to the bookmark editor for S3 bookmarks
2. This toggle only controls whether Cyberduck uses the Transfer Acceleration endpoints. It only needs `s3:GetAccelerateConfiguration` permissions. It does not affect the properties on the bucket on S3.
3. Add a separate toggle to the bookmark editor "Transfer Acceleration for All Users". This changes the properties on the bucket on S3 and requires both `s3:GetAccelerateConfiguration` and `s3:PutAccelerateConfiguration` permissions.

**Describe alternatives you've considered**
A work around is for our AWS admin to disable the `s3:PutAccelerateConfiguration` permission for the user. They can still switch on Transfer Acceleration in Cyberduck but they get an error message which could be confusing.

**Comment by dkocher** [comment]
The bucket is queried with `GET /?accelerate=` for the configuration once for every upload regardless of any previous setting in _File → Info → S3_. Thus it should suffice to add the `s3:GetAccelerateConfiguration` permission for the user.
