### ISSUE TITLE
add Transfer Acceleration to Edit Bookmark dialog for S3 bookmarks

### ISSUE THREAD

**Issue by yellowtailfan** [iterate-ch/cyberduck#16231]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to explain to our users how to set up Cyberduck to connect to a bucket we are providing with Transfer Acceleration enabled. At the moment the user has to click on a file in the bucket and press Info to switch on Transfer Acceleration. I was expecting to see the Transfer Acceleration toggle in the bookmark editor instead as it applies to the whole bucket, not just a file.

**Describe the solution you'd like**
Add a Transfer Acceleration toggle to the bookmark editor for S3 bookmarks.

**Describe alternatives you've considered**
A work around is to ask the user to upload a dummy file, select it, click Info, then switch on Transfer Acceleration.

**Additional context**
See also: #13403.

**Comment by dkocher** [comment]
You should be able to configure transfer acceleration when selecting a bucket and choosing _File → Info → S3_. As mentioned in #16232 you do not need to enable the user of transfer acceleration on every installation but the status is queried for every upload.

**Comment by dkocher** [comment]
> > You should be able to configure transfer acceleration when selecting a bucket and choosing _File → Info → S3_.
> 
> Thanks for your quick response. FYI I tried this but the File > Info menu item is disabled.
> 
You will  have to connect and switch to the _List|Outline_ view in the browser window.
