### ISSUE TITLE
Cyberduck crashes due to "illegal characters in path" when a ftp folder is opened

### ISSUE THREAD

**Issue by PaulMccoySr** [iterate-ch/cyberduck#16280]
Copied a FTP file to website, and Cyberduck crashed after trying to open the web site folder containing the file for editing. Uninstalled Cyberduck and manually removed appdata folders, reinstalled and crash continues.

Cyberduck Log
[cyberduck.log](https://github.com/user-attachments/files/16840244/cyberduck.log)

Crash reporter
[638608788969277335.txt](https://github.com/user-attachments/files/16840246/638608788969277335.txt)

**Comment by dkocher** [comment]
Duplicate for #16174.
