### ISSUE TITLE
SSH non-default port setting not being read from .ssh/config file

### ISSUE THREAD

**Issue by mbac** [iterate-ch/cyberduck#16281]
Hi,

At least on my system, Cyberduck isn't reading the `Port` parameter from `~/.ssh/config`. While it does read the host's IP, `IdentityFile` etc…, the port is always 22 after updating other data in the config file.

Steps to reproduce:
- Create bookmark using a host alias from SSH's config file.
- Update said config file, changing both IP and Port (e.g. when using cloud GPUs)
- Edit bookmark: you'll see that the displayed IP is the new one, but Port: has the same value it had before changing the config file.

Thanks!

**Comment by mbac** [comment]
Hi,

I'm now running Version 9.0.4 (42128) and I still can't see the fix. How can I check if I'm doing everything right?

**Comment by dkocher** [comment]
> Hi,
> 
> I'm now running Version 9.0.4 (42128) and I still can't see the fix. How can I check if I'm doing everything right?

Please attach a [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output).

**Comment by mbac** [comment]
Here it is:

[cyberduck.log](https://github.com/user-attachments/files/17155662/cyberduck.log)

Thanks

**Comment by mbac** [comment]
Update: it's now working for me [Version 9.0.4 (42193)], but I have a small feature request: it seems to me I need to slightly change the host name or port number in order for the port number itself to update from `.ss/config`. Although way better than nothing, it still requires user intervention for Cyberduck to pick up changes from the config file. Would it be possible to have it refresh the data at startup and/or every time a connection is started or edited? Thanks!

**Comment by dkocher** [comment]
> Update: it's now working for me [Version 9.0.4 (42193)], but I have a small feature request: it seems to me I need to slightly change the host name or port number in order for the port number itself to update from `.ssh/config`. Although way better than nothing, it still requires user intervention for Cyberduck to pick up changes from the config file. Would it be possible to have it refresh the data at startup and/or every time a connection is started or edited? Thanks!

It should pick up the latest setting from your OpenSSH configuration file `~/.ssh/config` when attempting to open a connection.
