### ISSUE TITLE
Review Lock Vault Button Availability

### ISSUE THREAD

**Issue by tatze96** [iterate-ch/cyberduck#16317]
On macOS, the lock vault option is deactivated as soon as the automatic vault detection is activated. On Windows, the option is always active regardless of whether the automatic vault detection is activated or not.

**Comment by dkocher** [comment]
It should be disabled as the lock will be immediately unlocked again with _Auto detect…_ enabled the next time the directory listing is refreshed. Supposed to be fixed with bc3b1dcb.

**Comment by AliveDevil** [comment]
> immediately unlocked again with Auto detect
Only if Keychain is used.

**Comment by dkocher** [comment]
Relates to #16171.
