### ISSUE TITLE
9.0.2 on Windows displays red "Get a registration key!" message with .cyberducklicense file in Application Support folder

### ISSUE THREAD

**Issue by SSLbits** [iterate-ch/cyberduck#16329]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Valid donator .cyberducklicense file is in Application Support folder. Under Help drop-down, "Registered to %name%" is greyed out, but red "Get a registration key!" message still appears after upgrading to 9.0.2. Double-clicking on the .cyberducklicense file will remove the red message, but it reappears after relaunching the application. 

**To Reproduce**
1. Upgrade to 9.0.2 with valid donator .cyberducklicense file in Application Support folder.
2. Launch the application.
3. See error

**Expected behavior**
The red "Get a registration key!" message should not appear. 

**Screenshots**
![capture_oxptaAIKDh](https://github.com/user-attachments/assets/e817e688-7b49-4592-9a6e-e281b02280f7)

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11
 - Version 9.0.2

**Log Files**
[cyberduck.log](https://github.com/user-attachments/files/16984834/cyberduck.log)

**Additional context**
9.0.1 does not have this issue.

**Comment by dkocher** [comment]
Duplicate for #16326.
