### ISSUE TITLE
Get a Registration Key displaying when registered

### ISSUE THREAD

**Issue by davegiffney** [iterate-ch/cyberduck#16326]
**Describe the bug**
After the update today (to 9.0.2 (42108) there is a red notice top right stating "Get a registration key!"  but the app is registered and shows as such in the About Cyberduck.

**Comment by dkocher** [comment]
Regression from bba30c739533e872b4920fe81132741aeb8dfa2c

**Comment by dkocher** [comment]
Please update to the latest _9.0.3_ snapshot or beta build from _Preferences → Update_.

**Comment by davegiffney** [comment]
Thanks, all good now
