### ISSUE TITLE
Failure to Recognize Registration Key on New Sign-in

### ISSUE THREAD

**Issue by halh28437** [iterate-ch/cyberduck#16333]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _third party_.

**Describe the bug**
I downloaded and registered Cyberduck Ver 9.0.2 (42108) on a new HP Envy laptop running Windows 11 on September 12, and promptly received a registration key that I copied as instructed into my Application Support Folder. That action removed the red "Get a registration key!" box from the upper right corner of the Cyberduck window as expected. However, the software doesn't continue to recognize that I have already registered it when I reopen the software to start a new session. Whenever I sign back in to the computer, the red box returns. Asan aside, I had already downloaded, registered and successfully used an earlier version of Cyberduck on an older laptop running an earlier version of Windows on August 31, 2022, but that registration didn't carry over to the new machine.

  
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #16326.

**Comment by halh28437** [comment]
Thank you. That worked.
