### ISSUE TITLE
9.0.2 showing "Get a registration key" on Microsoft Store version

### ISSUE THREAD

**Issue by cprivitere** [iterate-ch/cyberduck#16343]
Updated to 9.0.2 via the Microsoft store yesterday and now I get a big "Get a registration key" box on the program. I'm figuring this isn't intentional.

![image](https://github.com/user-attachments/assets/b3bf9d45-a218-4382-8b8e-4eb939304979)

**Comment by dkocher** [comment]
Duplicate for #16326.
