### ISSUE TITLE
sftp: I enter a username and it is not reflected in the url

### ISSUE THREAD

**Issue by vincentluciani** [iterate-ch/cyberduck#16366]
**Describe the bug**
I am using Cyberduck for Mac. I am opening a new connection for sftp. When I enter the Server ip, it gets reflected in the URL, but when I enter the username, it is not appended to the server IP in the URL field.

**To Reproduce**
1. In the menu "File", choose "Open connection"
2. Choose option SFTP (SSH Transfer Protocol)
3. Enter the server IP in the Server edit field. For example 120.10.10.10. The url field becomes sftp://120.10.10.10
4. Enter the username in the Username edit field. For example root
5. See error: The url field is still sftp://120.10.10.10, not sftp://root@120.10.10.10
6. The problem is still the same when I choose the private key 

**Expected behavior**
The url should become sftp://root@120.10.10.10
<img width="1463" alt="Screenshot 2024-09-22 at 12 54 06" src="https://github.com/user-attachments/assets/c5d27704-36a2-4541-9332-0a11e9bb87e9">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 15.0

**Comment by vincentluciani** [comment]
Note that I am able to connect with the same credentials on the same Mac to this server using the Mac termina

**Comment by AliveDevil** [comment]
The displayed url is just for informational purposes - the real connection is perfomed using the properties, as defined in the connection window.
Nonetheless, the displayed url should represent the expected format of `protocol://identity@host`.

Please attach the [debug log](https://docs.cyberduck.io/cyberduck/support/#logging-output) or send it to support@cyberduck.ch, with subject "GH-16366".

**Comment by dkocher** [comment]
This is intended as of 6295e0023dae0a00adff6b3bea76cf67deb63cc1 as many protocols do not allow representing the username credentials in the URL.
