### ISSUE TITLE
License key not recognized after update to 9.0.3

### ISSUE THREAD

**Issue by jettro77** [iterate-ch/cyberduck#16372]
After updating to version 9.0.3 my license key is not recognized. 

After starting cyberduck application the red icon get a registration key is displayed within the program. 
I verified that my license key is in the same file as the application and it is correctly labeled.

While making sure my license key was correctly labeled I right clicked on the license number and then clicked on "open with" cyberduck.

Problem resolved.

**Comment by dkocher** [comment]
Duplicate for #16329.
