### ISSUE TITLE
Using DNS Name to connect to S3 Protocol on NetApp Storage Array

### ISSUE THREAD

**Issue by jcabrero-sd** [iterate-ch/cyberduck#16380]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Unable to open S3 buckets when connecting to S3 using a DNS name. On windows machine I can nslookup and ping the S3 Server (Netapp SVM) But when I access the bucket I get the following error.
"DNS lookup for S3Server.domain.com Failed, DNS is the network service that translates a server to its Internet address........."
1. "Open New Connection --> Select S3 'Https' --> Server = 's3servername.local.domain' 
2. Click on 'Access Key' - Secret Key ' --> Select 'Save Password'
3. Scroll down to 'Connect'
4. See error 'Cannot Read container configuration'

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/a853bcda-e73a-45c0-ad13-162cd5cb9af2)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2019 STD edition]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**To Reproduce**
1. Go to 'Open Connection --> Select S3 Https --> Server 's3server.domain.com' --> Port

**Comment by AliveDevil** [comment]
Please enable the `S3 (HTTPS, Deprecated Path Style)`-profile in Preferences/Profiles, or make sure that your NetApp Storage Array supports [virtual host style](https://docs.cyberduck.io/protocols/s3/#connecting-using-deprecated-path-style-requests) requests (i.e. bucket.s3.domain.com)
