### ISSUE TITLE
Maximum redirects exceeded error connecting to bucket

### ISSUE THREAD

**Issue by OanaLef** [iterate-ch/cyberduck#16427]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

I already tried to find the solution online.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

I had our IT department have a look and they said they don't know what the issue could be and they suggested i contact you.

**Describe the bug**

I have Tried to connect CyberDuck and it' didn't work, i have sent an email with the image of the error i have received to [support@cyberduck.io] 

The error kept saying Error Failure to read attributes of assets (Maximum redirect 50 exceeded)

**To Reproduce**

1  Open Connection 
2 Select Amazon S3 from the dropdown 
3 Enter Access Key ID......
4 Enter Secret Access Key:............ 
5 Expand More Options and enter this into Path: 
6 Connect
7 See the Error message appear 
![Cyber Duck Error 2](https://github.com/user-attachments/assets/68e8cdfd-8510-4365-a815-6e2be0747f31)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Cyberduck-Installer-9.0.3.42112

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Please revoke your AWS access key exposed in this ticket.

**Comment by dkocher** [comment]
I cannot reproduce the issue connecting to a path i a bucket in region `us-west-2`. Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in Preferences → Connection.
