### ISSUE TITLE
Webdav failure -- catch 22

### ISSUE THREAD

**Issue by LaurelMurphy** [iterate-ch/cyberduck#16456]
### Discussed in https://github.com/iterate-ch/cyberduck/discussions/16455

<div type='discussions-op-text'>

<sup>Originally posted by **LaurelMurphy** October 28, 2024</sup>
I am trying to upload to Big Commerce on windows 11.   From Cyberduck I get error message "unexpected response 501, not implemented.  contact hosting service."  I have also tried to uninstall CyberDuck  and the control panel says the installer is broken and it cannot be removed.  At this point I just want to wipe it all off my computer and start over.  Could someone help me with this?  Thank you.</div>

**Comment by LaurelMurphy** [comment]
Mr. Kocher,

I am astounded.  I know several native Swiss, including the owner of one of Switzerland's largest manufacturers, and none of them would be so rude.

You couldn't even say "I won't help you, so go away"?   So I guess you mean for Cyberduck to be only used by computer geeks?  Someone like me who actually participates in the economy doesn't deserve an answer? 

Well, thank you very much.  I will return the favor by letting the people at Big Commerce know all about your customer service.

L. Murphy

**Herr Kocher,

 Ich bin verblüfft. Ich kenne mehrere gebürtige Schweizer, darunter den Besitzer eines der größten Schweizer Hersteller, und keiner von ihnen wäre so unhöflich. 

Sie könnten nicht einmal sagen: „Ich werde Ihnen nicht helfen, also gehen Sie weg“? Sie meinen also, dass Cyberduck nur von Computerfreaks verwendet werden darf? Jemand wie ich, der tatsächlich an der Wirtschaft teilnimmt, verdient keine Antwort?

Nun, vielen Dank. Ich werde mich revanchieren, indem ich den Leuten bei Big Commerce alles über Ihren Kundendienst erzähle.**

**Comment by dkocher** [comment]
> Mr. Kocher,

You may have noticed we are providing support here with no service level agreement free of charge. We have closed this as a duplicate of the discussion you opened previously as long as the cause is not determined to be a bug.
