### ISSUE TITLE
Deleting a S3 delete marker creates a new delete marker

### ISSUE THREAD

**Issue by Fydon** [iterate-ch/cyberduck#16472]
**Describe the bug**
I enabled preserving modification date and then uploaded a new file to a S3 bucket. I deleted it, which created a delete marker. I deleted the previous version, i.e. the file itself, which completed successfully. I then deleted the delete marker, but it just creates a new delete marker.

**To Reproduce**
1. Download [S3 (Credentials from AWS Command Line Interface).cyberduckprofile](https://svn.cyberduck.io/trunk/profiles/S3%20(Credentials%20from%20AWS%20Security%20Token%20Service).cyberduckprofile)
2. Edit it to add the following, as [mentioned here](https://github.com/iterate-ch/cyberduck/issues/15381#issuecomment-1859201488).
```
    <key>Properties</key>
    <array>
      <string>s3.listing.metadata.enable=true</string>
    </array>
```
3. Change a S3 connection to use profile and connect
4. Upload a file to S3
5. Delete file
6. Delete previous version of file
7. Try to delete the delete marker

**Expected behavior**
Before enabling the preservation of the modification date, I was able to delete a delete marker. I'm still able to on another installation of Cyberduck using the same profile but without the above changes to enable preserving modification date.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Cyberduck Version: 9.0.4 (42232)

**Log Files**
Delete and list was over 2000 lines long, so just extracted delete.
[cyberduck.log](https://github.com/user-attachments/files/17590333/cyberduck.log)

**Additional context**

**Comment by dkocher** [comment]
As indicated by @Fydon this cannot be reproduced with the default AWS S3 connection profile but with the _S3 (Timestamps)_ profile that has set `s3.listing.metadata.enable=true`. In this case file attributes are retrieved for every file using `HEAD` [^1] which is not supported for delete markers and causes us to dismiss the version ID.

[^1]: https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html

**Comment by Fydon** [comment]
Thank you. The latest snapshot resolved this.

I first installed the snapshot version just before and waited for the next release. When I checked for update, the window immediately disappeared even when there was a new release found to update to. Closing the app and openning it again prompted for the update, allowing me to update.
