### ISSUE TITLE
Regression in Connection configuration

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#16489]
Regression: #16421

https://github.com/user-attachments/assets/4cb86263-7c7c-46a3-ad81-b8541717132f

When using the "S3 (HTTP)"-protocol, the URL-field doesn't represent the configured hostname.
When changing the hostname, the port is wrongly set to 443, instead of 80.

**Comment by dkocher** [comment]
Regression from a6f3150f.
