### ISSUE TITLE
Bad b2_list_parts API call fails when Resuming large file fails due to api paramater being "null" 

### ISSUE THREAD

**Issue by pwfulghum** [iterate-ch/cyberduck#16570]
Windows 11 
Cyberduck 9.0.3 (42112)

Repo Steps:

1. Start a large file upload.
2. Stop Upload
3. Resume Upload.

It seems that Cyberduck is making this request...

```
GET /b2api/v2/b2_list_parts?maxPartCount=null&startPartNumber=101&fileId=4_zbd04e47494f741f29339041e_f2051e532bb2c6666_d20241122_m151<truncated for security>
```

See the `maxPartCount` is set to "null"  it should be a number...

This API call fails... and cyberduck doesn't know what to do...

The prior call to 
```
GET /b2api/v2/b2_list_parts?fileId=4_zbd04e47494f741f2933<deleted>
```

returned `nextPartNumber=101`  and info about the 100 parts that did succeed.

**Comment by dkocher** [comment]
Fix in upstream [^1].

[^1]: https://github.com/iterate-ch/backblaze-b2-java-api/commit/9691ba9261dd94e438879b60fe68ace7a24ad39c

**Comment by pwfulghum** [comment]
Will check fix on next release....
