### ISSUE TITLE
SFTP "Provide additional login credentials" window inaccessible

### ISSUE THREAD

**Issue by socameron** [iterate-ch/cyberduck#16676]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

**Describe the bug**
With the newest Cyberduck update, I cannot access the second pop-up that requests additional login credentials for access to a cluster. My cluster uses 'Duo' as a two-factor authentication. Previously, I was able to click on the window, specifically the typing box to enter my passcode or the other option (application authentication), but I can't even click on the second pop up window.

**To Reproduce**
1. Go to 'SFTP'
2. Login to a computer cluster with addition login credentials
3. Attempt to login with the two-factor

**Expected behavior**
You should be able to click and access the second window. However, the second pop-up window just appears but is inaccessible. I cannot click on any of the buttons (e.g Continue, Skip, Cancel, or enter my Passcode)

**Screenshots**
See screenshot for more context [Screenshot_cyberduck](https://github.com/user-attachments/assets/8f39b1ad-d609-4aeb-a32d-0bcdcf741207)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Cyberduck Version: 9.1.0

**Log Files**
See log file:
[log file (.txt file)](https://github.com/user-attachments/files/18160675/638699923468179727.txt)

**Additional context**

**Comment by dkocher** [comment]
Relates to #16645.

**Comment by dkocher** [comment]
Fixed with #16490.
