### ISSUE TITLE
Clean install of v9.1.0.42520: Nothing happens. No error. No logs.

### ISSUE THREAD

**Issue by fdcastel** [iterate-ch/cyberduck#16683]
**Describe the bug**
Nothing happens on duck cli. Not even `duck --help` works.

**To Reproduce**
1. Install with `choco install duck -y`
2. Close the command prompt and start a new one to refresh the PATH
3. Run `duck --help`. Nothing happens. `$LASTEXITCODE` returns 1.
4. Run `duck --upload ...`. Nothing happens. `$LASTEXITCODE` returns 1.
5. Run `duck --upload ... --verbose`. Nothing happens. `$LASTEXITCODE` returns 1.
6. Run `duck --upload ... --debug`. Nothing happens. `$LASTEXITCODE` returns 1.

**Expected behavior**
Program should at least display SOME error information about what is going wrong. 

**Desktop (please complete the following information):**
 - OS: Windows Server 2022 Standard (very new install, almost clean. Updates applied)
 - Version  v9.1.0.42520

**Log Files**
There is no `%AppData%\cyberduck` folder (!)

**Additional context**
Tried to reboot the computer. Still doesn't work.

However, I did notice that running just `duck` without parameters produces some output:

```powershell
PS C:\> duck
Missing required option: [--upload Upload file or folder recursively, -d Download file or folder. Denote a folder with a trailing '/', --copy Copy from origin server to target server, --move Move or rename file on server, -l List files in remote folder, -L Long list format with modification date and permission mask, -D Delete, -c Make directory, --synchronize Synchronize folders, --edit Edit file in external editor, --purge Invalidate file in CDN, -V Show version number and quit., -h Print this help]
Try 'duck --help' for more options.
PS C:\> $LASTEXITCODE
1
PS C:\> duck --help
PS C:\> $LASTEXITCODE
1
```

I also created the `%AppData%\cyberduck` folder manually. Problem still persists. 

Nothing is logged on Windows Event Viewer / Administrative Events.

**At least some error message should be produced whenever the last exit code is non-zero.**

**Comment by dkocher** [comment]
Regression of #16566.

**Comment by fdcastel** [comment]
Thanks @dkocher for the prompt response (and fix). 

Newbie here. Is there some kind of nightly build available for testing this? Or when can we expect a 9.1.1 release?

Just asking because I'm in the middle of a process wanting to adopt duck cli.

**Comment by fdcastel** [comment]
Thank you guys. It is working now! 👍🏻
