### ISSUE TITLE
Rename function of files and folders disappeared

### ISSUE THREAD

**Issue by Killua99x** [iterate-ch/cyberduck#16695]
Hi, I'm a MacOS 15.2 User

I was using CyberDuck version 9.0.2, after updating it to version 9.1.1, the Rename function of files and folders disappeared

I connect in SSH to a FreeBSD 14.1 server

**Comment by pzdunek** [comment]
I have the same error

**Comment by smart7324** [comment]
Same problem for me on 2 different Macs with the latest version.

**Comment by CemeaPaolo** [comment]
Restored to previous version, problem solved. Hope the update will come soon. thank you

**Comment by Verkhovskyi** [comment]
Same

**Comment by sgrenzh** [comment]
I have the exact same issue on 9.1.1. Cannot rename, permissions are all present and correct.

**Comment by gabersyd** [comment]
I have the same problem. It is quite a annoying as I have to rename quite a few files.

**Comment by dkocher** [comment]
You can update to the current [snapshot build](https://docs.cyberduck.io/cyberduck/preferences/#snapshot-builds) until the _Release_ build is out which contains the fix.
