### ISSUE TITLE
Rename greyed out when connected but SFTP (by FTP Rename is available)

### ISSUE THREAD

**Issue by stona1** [iterate-ch/cyberduck#16700]
**Describe the bug**
Connect to server by SFTP. Right click in folder or file name. Option "Rename" is greyed out. 
When connecting to this server by FTP "Rename" is available. 

**To Reproduce**
1. Connect to the server by SFTP
2. Right click in folder or file name.
3. Try to choose "Rename"
4. It os grayed out.

**Expected behavior**
Should be possible to rename file. I have administrator privileges on this server on this credentials. 

**Screenshots**
![image](https://github.com/user-attachments/assets/9e0d5e24-c80c-4c54-bc87-a674ce0f7bf2)

**Desktop (please complete the following information):**
 - OS: macOS 15.2
 - Version 9.1.1 (42639)

**Comment by dkocher** [comment]
Duplicate for #16695
