### ISSUE TITLE
Modifica nome file

### ISSUE THREAD

**Issue by CemeaPaolo** [iterate-ch/cyberduck#16705]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
**clicking on the filename doesn't allow me to change its name**
cliccando sul nome file non mi permette di cambiarne il nome
**To Reproduce**

1 click on a file
2 press enter
3 nothing happens

**Expected behavior**
after highlighting the file and clicking enter I expected to be able to change the file name
dopo aver evidenziato il file e cliccato su enter mi aspettavo di poter cambiare il nome del file
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - MacOs 
15.2
[cyberduck.log](https://github.com/user-attachments/files/18230846/cyberduck.log)

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #16695.
