### ISSUE TITLE
Rename not available

### ISSUE THREAD

**Issue by ShoreFryer** [iterate-ch/cyberduck#16708]
Hi, I've noticed that recently the rename option has dissapeared (greyd out) when connected via SFTP. I've tested multiple servers and the same issue persists. However this only applies to Cyberduck since other FTP clients work fine
<img width="241" alt="Screenshot 2024-12-24 at 00 06 39" src="https://github.com/user-attachments/assets/34006601-755c-43b7-80b1-c1c3f67d51d5" />

**Comment by dkocher** [comment]
Duplicate for #16695.
