### ISSUE TITLE
Impossible to change file names…

### ISSUE THREAD

**Issue by Hymenorebutia** [iterate-ch/cyberduck#16710]
**Describe the bug**
I want to change a file name in a browser window; I select the corresponding line, but it is then, impossible to select the filename.
It seems to happen since the last update of December 19th (date of my cyberduck 9.1.1 application in the "Application" folder).
SEEMS to be the same as #16708    ("Rename" in the file menu is also grey)

**Expected behavior**
I expect to be able to select the filename and to modify it…

**Desktop (please complete the following information):**
 - OS: Mac OSX Sequoia 15.1.1

**Additional context**
PLEASE UPDATE QUICKLY because it is extremely bothering: I have to download the file, rename it, then re-upload the file!!!
(Or using an older version of Cyberduck…)

**Comment by ylangisc** [comment]
Duplicate for #16695.
