### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by XRumer** [iterate-ch/cyberduck#16727]
Hi, after the Cyberduck update, I can't rename folders and files. The "Rename" option is inactive on all my servers (SFTP). I'm using a MacBook Pro with Apple Silicon (Version 9.1.1 (42639))
<img width="672" alt="3432423" src="https://github.com/user-attachments/assets/094849d8-1b1b-4148-aa16-6890e3d40707" />

**Comment by dkocher** [comment]
Duplicate for #16695.
