### ISSUE TITLE
can't rename files 

### ISSUE THREAD

**Issue by marcodiversi** [iterate-ch/cyberduck#16721]
Dear Cyberduck Support Team,

Since the last Cyberduck update, I’ve been unable to rename files. Interestingly, I have an older version installed on another computer (with the same setup), and it works perfectly fine there.

I’m currently using the latest macOS version. Could you please help me resolve this issue?

Thank you for your assistance!

Best regards,

**Comment by ylangisc** [comment]
Duplicate for #16695.
