### ISSUE TITLE
unable to rename files or directories

### ISSUE THREAD

**Issue by Mwanafunzi** [iterate-ch/cyberduck#16732]
the rename option is greyed out and not working either via right click or file>rename

mac os Version 15.2 (24C101)

Cyberduck Version 9.1.1 (42639)

This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Log Files**
Please include the [log file](https://docs.cyberduck.io/cyberduck/support/#logging-output). You can reach the logging output in _Preferences → Connection_.

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #16695.
