### ISSUE TITLE
Support for Samba (SMB) protocol

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#5368]
> **841fd6e** created the issue

Is there a possibility to add ability to access SMB (Samba) servers to CyberDuck?

The Finder implementation is spotty.

**Comment by hjkcai** [comment]
+1. The Finder implementation does not support non-standard SMB port.

**Comment by dkocher** [comment]
Add an implementation using [smbj - SMB2/SMB3 client library for Java
](https://github.com/hierynomus/smbj) should be quit straight forward.

**Comment by AlanATL** [comment]
This would be very useful to me as well.

**Comment by StraightfaceStudios** [comment]
Windows' explorer copy mechanism works very well.  But implementing this as a file service would enable offline files in mountain duck.

**Comment by AlanATL** [comment]
> Windows' explorer copy mechanism works very well. But implementing this as a file service would enable offline files in mountain duck.

My use case is for offline files in Mountain Duck on Mac OS. On Windows, it is already possible to use the built-in Sync Center functionality for offline files, which works quite well. But there has never been a similar option on the Mac to access offline files for an SMB share (Windows file server). I know several people, myself included, who would benefit from this feature.

**Comment by AlanATL** [comment]
> Windows' explorer copy mechanism works very well. But implementing this as a file service would enable offline files in mountain duck.

My use case is for offline files in Mountain Duck on Mac OS. On Windows, it is already possible to use the built-in Sync Center functionality for offline files, which works quite well. But there has never been a similar option on the Mac to access offline files for an SMB share (Windows file server). I know several people, myself included, who would benefit from this feature.

**Comment by AlanATL** [comment]
> Windows' explorer copy mechanism works very well. But implementing this as a file service would enable offline files in mountain duck.

My use case is for offline files in Mountain Duck on Mac OS. On Windows, it is already possible to use the built-in Sync Center functionality for offline files, which works quite well. But there has never been a similar option on the Mac to access offline files for an SMB share (Windows file server). I know several people, myself included, who would benefit from this feature.

**Comment by kaylynn234** [comment]
I'd definitely appreciate SMB support, and would be willing to help implement it if necessary. My experience with what Windows provides in Explorer has been pretty poor; it seems to handle credentials weirdly and will often fail to connect to my Synology NAS after a restart.

**Comment by TheNighthawk99** [comment]
I'd really like the SMB support as well, it is a missing feature which would turn this app into a complete powerful suite.
I had contacted the Company support some weeks ago and they replied me that this feature should be available in the second half of this year. It would be awesome!
Finger crossed.

Bye.

**Comment by TheNighthawk99** [comment]
> > Windows' explorer copy mechanism works very well. But implementing this as a file service would enable offline files in mountain duck.
> 
> My use case is for offline files in Mountain Duck on Mac OS. On Windows, it is already possible to use the built-in Sync Center functionality for offline files, which works quite well. But there has never been a similar option on the Mac to access offline files for an SMB share (Windows file server). I know several people, myself included, who would benefit from this feature.

After switching from Windows 10 to MacOS, one of the most useful features I really miss is the Offline Files along with Sync Center.
Hope we are going to get this feature really soon (SMB shared folders).

**Comment by arroos** [comment]
Just to add to the enthusiasm for SMB, I too would like to use MD to automagically synchronise files between an SMB share, which is available via a VPN, and local storage that can be accessed when offline. Ideally, synchronisation should be auomatic when the VPN is connected, making the share available, and the "fail-over" to locally cached files when the VPN is disconnected should be transparent to the user.

**Comment by ajbaab** [comment]
I figured rather than keep checking back on here, I should post that the main reason I purchased Cyber Duck was because I was trying to find something similar to SyncToys on the PC side for the Mac that worked with SMB.

Highly looking forward to this feature being implemented!

**Comment by ajbaab** [comment]
Hi,I see the ticket was closed, however I can’t figure out how to use SMB on Mountain Duck.Is it closed because it’s slated for release?Respectfully,Andrew BaabOn Sep 20, 2023, at 10:37 AM, David Kocher ***@***.***> wrote:﻿
Closed #5368 as completed via #15020.

**Comment by dkocher** [comment]
> Hi,I see the ticket was closed, however I can’t figure out how to use SMB on Mountain Duck.Is it closed because it’s slated for release?Respectfully,Andrew BaabOn

SMB support will be available in Mountain Duck 5 and can be tested in current snapshot builds of Cyberduck.

**Comment by ajbaab** [comment]
Good afternoon David, I changed my updates to the snapshot builds. It has me updated to 4.15.0, I checked both profiles and the default drop-down for connections, and I cannot find and option. This was my use case for getting mountain duck in the beginning, so I'm looking forwards to getting it up and running. Thank you!

**Comment by dkocher** [comment]
> Good afternoon David, I changed my updates to the snapshot builds. It has me updated to 4.15.0, I checked both profiles and the default drop-down for connections, and I cannot find and option. This was my use case for getting mountain duck in the beginning, so I'm looking forwards to getting it up and running. Thank you!

We do not have a snapshot build of Mountain Duck with support for SMB available yet.

**Comment by Savjee** [comment]
Any update on Mount Duck with support for SMB?

**Comment by ajbaab** [comment]
Checking back in on this, I haven't used Cyberduck in a while due to it constantly glitching with the file system when I'm trying to use it for SMB. 

But I would really like to see this implemented because this is what I thought I was purchasing with Cyberduck. Any news on V5

**Comment by IanJSaul** [comment]
I couldn't get a trial key to work for some reason, so I went ahead and purchased Mountain Duck.

My use case is for an SMB mount of local TrueNAS... Any ideas how far out a beta build with SMB is that I could test? Or the final release date of V5?

Thanks...

**Comment by StraightfaceStudios** [comment]
Will/does this support SMB over Quic? 

https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-over-quic

We are seeing massive speed-ups from QUIC support over WAN.   SMB QUIC + MountainDuck would be a match made in heaven.
