### ISSUE TITLE
Download failure when filename or directory contains # character

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#9760]
> **42b76c3** created the issue

Unable to export via WebDAV HTTP/SSL if content contains hashtag (#) - repeated attempts to export/Download files from a server fail if any of the target files contain a hashtag in the filename, sometimes it's just a few files & I can find and change the file name manually then re-try the export/download & it works fine, but other times there may be hundreds of "#" in the collection of filenames, it's too time consuming to find & change them all to re-try the export/download.  Both Win7 & Win10 OS on both 32-bit & 64-bit machines.
___
Attachments

* [`Error when a file has a hashtag in its name.jpg`](https://github-cyberduck-assets.s3.amazonaws.com/9760/Error%20when%20a%20file%20has%20a%20hashtag%20in%20its%20name.jpg) (120.8 KiB)

**Comment by Cassie205** [comment]
Tested with v8.5.8.39550, Win11: Downloading different files from WebDAV (HTTP) server with # in their name works just fine
